USE [BuhDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[PRICE_TYPE_UPDATETR]', 'TR') IS NULL EXEC('CREATE TRIGGER [dbo].[PRICE_TYPE_UPDATETR]  ON [dbo].[PriceType] AFTER INSERT,UPDATE,DELETE  AS SELECT 1')
GO
ALTER TRIGGER [dbo].[PRICE_TYPE_UPDATETR]
   ON  [dbo].[PriceType]
   AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;

    EXEC [dbo].[REFERENCES_RELOAD]
END
GO
