USE [BuhDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DISTR_TYPE_UPDATE_TR]', 'TR') IS NULL EXEC('CREATE TRIGGER [dbo].[DISTR_TYPE_UPDATE_TR]  ON [dbo].[DistrTypeTable] AFTER INSERT,UPDATE,DELETE  AS SELECT 1')
GO
ALTER TRIGGER [dbo].[DISTR_TYPE_UPDATE_TR]
   ON  [dbo].[DistrTypeTable]
   AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON;

    EXEC [dbo].[REFERENCES_RELOAD]
END
GO
