USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[StringDelimiterPartInt]', 'FN') IS NULL EXEC('CREATE FUNCTION [Common].[StringDelimiterPartInt] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Common].[StringDelimiterPartInt]
(
	@STRING		NVARCHAR(MAX),
	@DELIMITER	NVARCHAR(10),
	@PART		INT
)
RETURNS INT
AS
BEGIN
	DECLARE @RES INT

	DECLARE @I INT

	SET @I = 1

	WHILE CHARINDEX(@DELIMITER, @STRING) > 0 AND @PART > @I
	BEGIN
		SET @STRING = RIGHT(@STRING, LEN(@STRING) - CHARINDEX(@DELIMITER, @STRING))

		SET @I = @I + 1
	END

	IF @PART <> @I
		SET @RES = NULL
	ELSE
	BEGIN
		IF CHARINDEX(@DELIMITER, @STRING) > 0
			SET @RES = CONVERT(INT, LEFT(@STRING, CHARINDEX(@DELIMITER, @STRING) - 1))
		ELSE
			SET @RES = CONVERT(INT, @STRING)
	END

	RETURN @RES
END
GO
