USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[BitToStr]', 'FN') IS NULL EXEC('CREATE FUNCTION [Common].[BitToStr] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Common].[BitToStr]
(
    @Value      Bit
)
RETURNS NVarChar(50)
AS
BEGIN
    RETURN CASE @Value WHEN 1 THEN 'Да' WHEN 0 THEN 'Нет' ELSE 'Неизв.' END
END
GO
