USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[DateOf]', 'FN') IS NULL EXEC('CREATE FUNCTION [Common].[DateOf] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Common].[DateOf]
(
	@DT	DATETIME
)
RETURNS DATETIME
WITH SCHEMABINDING
AS
BEGIN
	RETURN CONVERT(DATETIME, CONVERT(VARCHAR(20), @DT, 112), 112)
END
GO
