USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ACTION_ADD]
	@NAME	VARCHAR(50),
	@TYPE	SMALLINT,
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@PERIOD	VARCHAR(MAX),
	@ACTIVE	BIT = 1,
	@RETURN	BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ID	SMALLINT

	IF @PERIOD IS NULL
	BEGIN
		INSERT INTO dbo.Action(ACTN_NAME, ACTN_ID_TYPE, ACTN_BEGIN, ACTN_END, ACTN_ACTIVE)
			VALUES(@NAME, @TYPE, @BEGIN, @END, @ACTIVE)

		SET @ID = SCOPE_IDENTITY()
	END
	ELSE
	BEGIN
		INSERT INTO dbo.Action(ACTN_NAME, ACTN_ID_TYPE, ACTN_ACTIVE)
			VALUES(@NAME, @TYPE, @ACTIVE)

		SET @ID = SCOPE_IDENTITY()

		INSERT INTO dbo.ActionPeriod(AP_ID_AC, AP_ID_PERIOD)
			SELECT @ID, Item
			FROM dbo.GET_TABLE_FROM_LIST(@PERIOD, ',')
	END

	IF @RETURN = 1
		SELECT @ID AS NEW_IDEN
END
