USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_POLKA_SET]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@POLKA	DECIMAL(8, 4)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SubhostPolka
	SET POLKA = @POLKA
	WHERE ID_PERIOD = @PR_ID
		--AND ID_SUBHOST = @SH_ID
		
	--IF @@ROWCOUNT = 0
	INSERT INTO dbo.SubhostPolka(ID_SUBHOST, ID_PERIOD, POLKA)
			--VALUES(@SH_ID, @PR_ID, @POLKA)
		SELECT SH_ID, @PR_ID, @POLKA
		FROM dbo.SubhostTable
		WHERE NOT EXISTS
			(
				SELECT *
				FROM dbo.SubhostPolka
				WHERE ID_SUBHOST = SH_ID
					AND ID_PERIOD = @PR_ID
			)
END

