USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	
/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[CONSIGNMENT_DETAIL_DEFAULT_GET]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT UN_NAME AS SO_INV_UNIT, 1 AS CSD_COUNT, TX_CAPTION, TX_ID, TX_PERCENT
	FROM dbo.UnitTable, dbo.TaxTable
	WHERE UN_ID = 2 AND TX_ID = 2
END

