USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[ACT_FACT_ALL_GET]	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AFM_DATE, ACT_DATE = IsNull(Max(ACT_DATE), AFM_DATE), COUNT(*) AS AFM_COUNT
	FROM dbo.ActFactMasterTable M
	LEFT JOIN dbo.ActTable A ON M.ACT_ID = A.ACT_ID
	GROUP BY AFM_DATE
	ORDER BY AFM_DATE DESC
END


