USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[CLIENT_BILL_FACT_ROW_EDIT]
	@BFD_ID INT,
	@BILL_STR VARCHAR(150), 
	@TX_PERCENT DECIMAL(8, 4), 
	@TX_NAME VARCHAR(50), 
	@SYS_NAME VARCHAR(250), 
	@SYS_ORDER SMALLINT, 
	@DIS_ID INT, 
	@DIS_NUM VARCHAR(20), 
	@PR_ID SMALLINT,	
	@PR_MONTH VARCHAR(50), 
	@PR_DATE SMALLDATETIME, 
	@BD_UNPAY MONEY,	
	@BD_TAX_UNPAY MONEY, 
	@BD_TOTAL_UNPAY MONEY
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.BillFactDetailTable
	SET BILL_STR = @BILL_STR, 
		TX_PERCENT = @TX_PERCENT, 
		TX_NAME = @TX_NAME, 
		SYS_NAME = @SYS_NAME, 
		SYS_ORDER = @SYS_ORDER, 
		DIS_ID = @DIS_ID, 
		DIS_NUM = @DIS_NUM, 
		PR_ID = @PR_ID, 
		PR_MONTH = @PR_MONTH, 
		PR_DATE = @PR_DATE, 
		BD_UNPAY = @BD_UNPAY, 
		BD_TAX_UNPAY = @BD_TAX_UNPAY, 
		BD_TOTAL_UNPAY = @BD_TOTAL_UNPAY	
	WHERE BFD_ID = @BFD_ID
END
