USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[PRICE_TYPE_DEPEND_GET]
	@PT_ID		SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @PR_ID	SMALLINT
	DECLARE @PR_NAME	VARCHAR(50)

	SELECT @PR_ID = PR_ID, @PR_NAME = PR_NAME
	FROM dbo.PeriodTable
	WHERE GETDATE() BETWEEN PR_DATE AND PR_END_DATE

	SELECT 
		a.PT_ID, a.PT_NAME, @PR_ID AS PR_ID, @PR_NAME AS PR_NAME,
		c.PT_ID AS PT_ID_DEPEND, c.PT_NAME AS PT_NAME_DEPEND, ISNULL(PD_COEF, 1) AS PD_COEF
	FROM 
		dbo.PriceTypeTable a
		LEFT OUTER JOIN dbo.PriceDepend b ON a.PT_ID = b.PD_ID_TYPE AND PD_ID_PERIOD = @PR_ID
		LEFT OUTER JOIN dbo.PriceTypeTable c ON c.PT_ID = b.PD_ID_SOURCE
	WHERE a.PT_ID = @PT_ID
END
