USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INCOME_TYPE_SELECT]
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT IT_ID, IT_NAME
	FROM 
		dbo.IncomeTypeTable 
	WHERE IT_ACTIVE = ISNULL(@active, IT_ACTIVE)
END
