USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_NORM_SET]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@NORM	DECIMAL(8, 4)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SubhostNorm
	SET NORM = @NORM
	WHERE ID_PERIOD = @PR_ID
		--AND ID_SUBHOST = @SH_ID
		
	--IF @@ROWCOUNT = 0
	INSERT INTO dbo.SubhostNorm(ID_SUBHOST, ID_PERIOD, NORM)
		--VALUES(@SH_ID, @PR_ID, @NORM)
		SELECT SH_ID, @PR_ID, @NORM
		FROM dbo.SubhostTable
		WHERE NOT EXISTS
			(
				SELECT *
				FROM dbo.SubhostNorm
				WHERE ID_SUBHOST = SH_ID
					AND ID_PERIOD = @PR_ID
			)
END

