USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GLOBAL_SETTINGS_READ]
	@NAME	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT GS_VALUE
	FROM dbo.GlobalSettingsTable
	WHERE GS_NAME = @NAME
END
