USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_VKSP_SET]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@VKSP	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SubhostVKSP
	SET VKSP = @VKSP
	WHERE ID_PERIOD = @PR_ID
		AND ID_SUBHOST = @SH_ID
		
	IF @@ROWCOUNT = 0
		INSERT INTO dbo.SubhostVKSP(ID_SUBHOST, ID_PERIOD, VKSP)
			VALUES(@SH_ID, @PR_ID, @VKSP)
END
