USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[PRICE_SYSTEM_TYPE_EDIT]
	@PST_ID	INT,
	@SYS_ID	SMALLINT,
	@PT_ID	SMALLINT,
	@SST_ID	SMALLINT,
	@COEF	DECIMAL(8, 4),
	@FIXED	MONEY,
	@DISC	DECIMAL(8, 4),
	@START	SMALLDATETIME,
	@END	SMALLDATETIME,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.PriceSystemType
	SET PST_ID_SYSTEM = @SYS_ID, 
		PST_ID_PRICE = @PT_ID, 
		PST_ID_TYPE = @SST_ID, 
		PST_COEF = @COEF, 
		PST_FIXED = @FIXED, 
		PST_DISCOUNT = @DISC, 
		PST_START = @START,
		PST_END = @END,
		PST_ACTIVE = @ACTIVE
	WHERE PST_ID = @PST_ID
END
