USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SYSTEM_EXCHANGE_GET]
	@SYS_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SYS_ID, SYS_SHORT_NAME, SYS_ORDER	
	FROM dbo.SystemTable
	WHERE SYS_ID_HOST IN 
		(
			SELECT SYS_ID_HOST 
			FROM dbo.SystemTable
			WHERE SYS_ID = @SYS_ID
		)
	ORDER BY SYS_ORDER
END
