USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[CONSIGNMENT_DETAIL_SELECT]
	@csgid INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CSD_ID, DIS_ID, DIS_STR, CSD_NUM, CSD_COST, CSD_PRICE, CSD_TAX_PRICE, CSD_TOTAL_PRICE, 
		CSD_PAYED_PRICE, CSD_CODE, CSD_COUNT, CSD_NAME, CSD_UNIT, CSD_OKEI, CSD_PACKING, 
		CSD_COUNT_IN_PLACE, CSD_PLACE, CSD_MASS, TX_ID, TX_CAPTION
	FROM
		dbo.ConsignmentDetailTable LEFT OUTER JOIN
		dbo.DistrView WITH(NOEXPAND) ON DIS_ID = CSD_ID_DISTR LEFT OUTER JOIN
		dbo.TaxTable ON TX_ID = CSD_ID_TAX
	WHERE CSD_ID_CONS = @csgid		
END
