USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[TO_DISTR_FORCED]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.TODistrTable
	SET TD_FORCED = CASE TD_FORCED WHEN 1 THEN 0 ELSE 1 END
	WHERE TD_ID = @ID
END