USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Автор:			
Дата создания:  	
Описание:		
*/
CREATE PROCEDURE [dbo].[REPORT_REG_NODE_COMPARE_DEFAULT]	
AS
BEGIN
	SET NOCOUNT ON;
/*
	SELECT a.PR_NAME AS SPR_NAME, a.PR_ID AS SPR_ID, b.PR_NAME AS DPR_NAME, b.PR_ID AS DPR_ID
	FROM
		dbo.PeriodTable a,
		dbo.PeriodTable b
	WHERE DATEADD(MONTH, -1, GETDATE()) >= a.PR_DATE AND DATEADD(MONTH, -1, GETDATE()) < DATEADD(d, 1, a.PR_END_DATE)
		AND DATEADD(MONTH, -0, GETDATE()) >= b.PR_DATE AND DATEADD(MONTH, -0, GETDATE()) < DATEADD(d, 1, b.PR_END_DATE)
*/		
	DECLARE @DPR_ID SMALLINT
	DECLARE @SPR_ID SMALLINT
		
	SELECT @DPR_ID = MAX(REG_ID_PERIOD) 
	FROM dbo.PeriodRegTable
	
	SELECT @SPR_ID = dbo.PERIOD_PREV(@DPR_ID)
	
	SELECT a.PR_NAME AS SPR_NAME, a.PR_ID AS SPR_ID, b.PR_NAME AS DPR_NAME, b.PR_ID AS DPR_ID
	FROM
		dbo.PeriodTable a,
		dbo.PeriodTable b
	WHERE a.PR_ID = @SPR_ID AND b.PR_ID = @DPR_ID
END