USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[ACT_CHANGE_COUR]
	@actid INT,
	@courid SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ActTable
	SET ACT_ID_COUR = @courid
	WHERE ACT_ID = @actid
	
	DECLARE @CLIENT	INT
	DECLARE @TXT	VARCHAR(MAX)
	
	EXEC dbo.ACT_PROTOCOL @actid, @CLIENT OUTPUT, @TXT OUTPUT	

	EXEC dbo.FINANCING_PROTOCOL_ADD 'ACT', 'Смена СИ', @TXT, @CLIENT, @actid 
END
