USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[REG_PROTOCOL_COMP]
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT DISTINCT RPR_COMPUTER
	FROM dbo.RegProtocol
	ORDER BY RPR_COMPUTER
END
