USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INCOME_SUMMARY_SELECT]
	@date SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	SELECT CL_ID, CL_PSEDO, DIS_ID, DIS_STR, SL_DATE, PR_DATE, ID_PRICE, SL_REST
    FROM dbo.SaldoIncomeSummaryView
    WHERE SL_DATE = @date
    ORDER BY CL_PSEDO, CL_ID, DIS_STR, PR_DATE
END

