USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ACT_INVOICE_CLEAR]
	@ACT_ID INT
AS
BEGIN	
	SET NOCOUNT ON;

	INSERT INTO dbo.FinancingProtocol(ID_CLIENT, ID_DOCUMENT, TP, OPER, TXT)
		SELECT ACT_ID_CLIENT, ACT_ID, 'ACT', 'Отвязка от счета-фактуры', 'Был номер ' + CONVERT(VARCHAR(20), INS_NUM) + '/' + CONVERT(VARCHAR(20), INS_NUM_YEAR)
		FROM 
			dbo.ActTable a
			INNER JOIN dbo.InvoiceSaleTable b ON a.ACT_ID_INVOICE = b.INS_ID
		WHERE a.ACT_ID = @ACT_ID

    UPDATE dbo.ActTable
	SET ACT_ID_INVOICE = NULL
	WHERE ACT_ID = @ACT_ID	
END
