USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERIOD_SELECT]   
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT PR_ID, PR_NAME, PR_DATE, PR_END_DATE
	FROM dbo.PeriodTable
	WHERE PR_ACTIVE = ISNULL(@active, PR_ACTIVE)
	ORDER BY PR_DATE DESC

	SET NOCOUNT OFF
END
