USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISTR_HISTORY_SELECT]
	@CL_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	IF @CL_ID IS NULL
	BEGIN
		SELECT DDH_ID, DIS_STR, CL_OLD_ID, CL_OLD_PSEDO, CL_NEW_ID, CL_NEW_PSEDO, DDH_NOTE, DDH_USER, DDH_DATE
		FROM dbo.DistrHistoryView
		ORDER BY DDH_DATE
	END
	ELSE
	BEGIN
		SELECT DDH_ID, DIS_STR, CL_OLD_ID, CL_OLD_PSEDO, CL_NEW_ID, CL_NEW_PSEDO, DDH_NOTE, DDH_USER, DDH_DATE
		FROM dbo.DistrHistoryView
		WHERE CL_OLD_ID = @CL_ID OR CL_NEW_ID = @CL_ID
		ORDER BY DDH_DATE
	END
END
