USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*
Автор:		  Денисов Алексей
Описание:	  
*/

CREATE PROCEDURE [dbo].[CONTRACT_KIND_ADD]   
	@NAME	VARCHAR(100),
	@HEADER VARCHAR(100),
	@CENTER	VARCHAR(100),
	@FOOTER	VARCHAR(100),
	@active BIT = 1,	
	@returnvalue BIT = 1
AS

BEGIN
	SET NOCOUNT ON

	INSERT INTO dbo.ContractKind(CK_NAME, CK_HEADER, CK_CENTER, CK_FOOTER, CK_ACTIVE) 
		VALUES (@NAME, @HEADER, @CENTER, @FOOTER, @ACTIVE)

	IF @returnvalue = 1
		SELECT SCOPE_IDENTITY() AS NEW_IDEN

	SET NOCOUNT OFF
END

