USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[ORGANIZATION_CALC_GET] 
	@id SMALLINT = NULL
AS
BEGIN
	SET NOCOUNT ON
	
	SELECT 
		ORGC_ID, ORGC_NAME, ORG_ID, ORG_SHORT_NAME, BA_ID, BA_NAME, ORGC_ACCOUNT, ORGC_ACTIVE
	FROM 
		dbo.OrganizationCalc INNER JOIN 
		dbo.OrganizationTable ON ORGC_ID_ORG = ORG_ID INNER JOIN
		dbo.BankTable ON BA_ID = ORGC_ID_BANK
	WHERE ORGC_ID = @id 

	SET NOCOUNT OFF
END
