USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	
/*
Автор:		  Денисов Алексей
Описание:	  
*/

CREATE PROCEDURE [dbo].[SYSTEM_NET_COUNT_SELECT] 
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT SNC_ID, SN_NAME, SNC_NET_COUNT, SNC_TECH, SNC_SHORT, SNC_ODON, SNC_ODOFF
	FROM 
		dbo.SystemNetCountTable a INNER JOIN
		dbo.SystemNetTable b ON a.SNC_ID_SN = b.SN_ID 
	WHERE SNC_ACTIVE = ISNULL(@active, SNC_ACTIVE)
	ORDER BY SNC_NET_COUNT

	SET NOCOUNT OFF
END






