USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERIOD_INC]
	@PR_ID	SMALLINT,
	@CNT	SMALLINT,
	@PR_OUT	SMALLINT OUTPUT,
	@PR_TXT	VARCHAR(50) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @PR_OUT = PR_ID, @PR_TXT = PR_NAME
	FROM dbo.PeriodTable
	WHERE PR_DATE = (SELECT DATEADD(MONTH, @CNT, PR_DATE) FROM dbo.PeriodTable WHERE PR_ID = @PR_ID)
END
