USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[NET_TYPE_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NT_ID, NT_SHORT
	FROM dbo.NetType
	--WHERE SN_ACTIVE = ISNULL(@active, SN_ACTIVE)
	ORDER BY NT_NET, NT_TECH
END
