USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_GET]
	@STW_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT STW_WEIGHT, STW_ACTIVE, SYS_ID, SYS_SHORT_NAME, SST_ID, SST_CAPTION
	FROM 
		dbo.SystemTypeWeightTable INNER JOIN
		dbo.SystemTable ON STW_ID_SYSTEM = SYS_ID INNER JOIN
		dbo.SystemTypeTable ON STW_ID_TYPE = SST_ID
	WHERE STW_ID = @STW_ID
END
