USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_BILL_FACT_ROW_SELECT]
	@bfmid INT	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		BFD_ID, 
		BFD_ID_BFM, 
		BILL_STR, 
		TX_PERCENT, 
		TX_NAME, 
		a.SYS_NAME, 
		a.SYS_ORDER, 
		a.DIS_ID, 
		a.DIS_NUM, 
		DIS_STR,
		PR_ID, 
		PR_MONTH, 
		PR_DATE, 
		BD_UNPAY, 
		BD_TAX_UNPAY, 
		BD_TOTAL_UNPAY
	FROM dbo.BillFactDetailTable a 
	LEFT JOIN dbo.DistrView b WITH(NOEXPAND) ON a.DIS_ID = b.DIS_ID
	WHERE BFD_ID_BFM = @bfmid
	ORDER BY SYS_ORDER;
END
