USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[BOOK_DELETE]
	@ID		INT,
	@TYPE	NVARCHAR(32)
AS
BEGIN
	SET NOCOUNT ON;

	IF @TYPE = 'SALE'
	BEGIN
		DELETE FROM dbo.BookSaleDetail
		WHERE ID_SALE = @ID
		
		DELETE FROM dbo.BookSale
		WHERE ID = @ID
	END
	ELSE IF @TYPE = 'PURCHASE'
	BEGIN
		DELETE FROM dbo.BookPurchaseDetail
		WHERE ID_PURCHASE = @ID
		
		DELETE FROM dbo.BookPurchase
		WHERE ID = @ID
	END
END
