USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRICE_TYPE_SYSTEM_EDIT]
	@PTS_ID	INT,
	@PT_ID	SMALLINT,
	@SST_ID	SMALLINT,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.PriceTypeSystemTable
	SET PTS_ID_PT = @PT_ID, 
		PTS_ID_ST = @SST_ID, 
		PTS_ACTIVE = @ACTIVE
	WHERE PTS_ID = @PTS_ID	
END
