USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FILTER_PROTOCOL_OPER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT OPER, TP, CONVERT(BIT, 1) AS CHECKED
	FROM dbo.FinancingProtocol
	ORDER BY TP, OPER
END
