USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ACT_CLAIM_NEW_CHECK]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT COUNT(*) AS CNT
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ActCalc
	WHERE ISNULL(CALC_STATUS, '') <> 'Расчитан полностью' 
		AND 
			(
				ISNULL(CONFIRM_NEED,0) = 0
				OR
				CONFIRM_NEED = 1 AND CONFIRM_DATE IS NOT NULL
			)
		AND STATUS = 1
		AND (@DT IS NULL OR CONVERT(DATETIME, CONVERT(NVARCHAR(128), DATE, 120), 120) > @DT)
		
	SELECT @DT = MAX(DATE)
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ActCalc
	WHERE ISNULL(CALC_STATUS, '') <> 'Расчитан полностью' 
		AND 
			(
				ISNULL(CONFIRM_NEED,0) = 0
				OR
				CONFIRM_NEED = 1 AND CONFIRM_DATE IS NOT NULL
			)
		AND STATUS = 1
		--AND (@DT IS NULL OR DATE > @DT)
END
