USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SUBHOST_DELIVERY_PRICE_TYPE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		PT_ID, PT_NAME, PT_COEF, PTS_ID_ST
	FROM 
		dbo.PriceGroupTable INNER JOIN
		dbo.PriceTypeTable ON PT_ID_GROUP = PG_ID INNER JOIN
		dbo.PriceTypeSystemTable ON PTS_ID_PT = PT_ID
	WHERE PG_ID = 4
	ORDER BY PT_ORDER
END