USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PRICE_CALC_SAVE_CLIENT]
	@PR_ID	SMALLINT,
	@SYS_ID	SMALLINT,
	@PRICE	MONEY
AS
BEGIN
	SET NOCOUNT ON;

	SET @PRICE = ISNULL(@PRICE, 0)

	UPDATE dbo.PriceSystemTable
	SET PS_PRICE = @PRICE
	WHERE PS_ID_PERIOD = @PR_ID
		AND PS_ID_SYSTEM = @SYS_ID
		AND PS_ID_TYPE = 1

	IF @@ROWCOUNT = 0
		INSERT INTO dbo.PriceSystemTable(PS_ID_PERIOD, PS_ID_SYSTEM, PS_ID_TYPE, PS_PRICE)
			VALUES(@PR_ID, @SYS_ID, 1, @PRICE)
END
