USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[FILTER_PROTOCOL_USER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT USR_NAME, CONVERT(BIT, 1) AS CHECKED
	FROM dbo.FinancingProtocol
	ORDER BY USR_NAME
END
