USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_VKSP_GET]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT VKSP
	FROM dbo.SubhostVKSP
	WHERE ID_PERIOD = @PR_ID
		AND ID_SUBHOST = @SH_ID
END
