USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROTOCOL_DOCUMENT_SEARCH]
	@TP	NVARCHAR(64),
	@DOC	INT
AS
BEGIN
	SET NOCOUNT ON;	

	SELECT CL_ID, CL_PSEDO, OPER, TXT, USR_NAME, UPD_DATE
	FROM 
		dbo.FinancingProtocol
		LEFT OUTER JOIN dbo.ClientTable ON CL_ID = ID_CLIENT
	WHERE TP = @TP AND ID_DOCUMENT = @DOC
	ORDER BY UPD_DATE DESC, ID
END
