USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISTR_FINANCING_BEGIN]
	@CLIENT	INT,
	@BEGIN	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.DistrFinancingTable
	SET DF_BEGIN = @BEGIN
	WHERE DF_ID_DISTR IN
		(
			SELECT DIS_ID
			FROM dbo.DistrFinancingView
			WHERE DSS_REPORT = 1
				--AND (ISNULL(DF_FIXED_PRICE, 0) <> 0 OR ISNULL(DF_DISCOUNT, 0) <> 0)
				AND CD_ID_CLIENT = @CLIENT
		)
END
