USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ACT_ACT_FACT_SELECT]
	@actid	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		AFM_DATE,
		PR_MONTH AS PR_NAME,
		ORG_SHORT_NAME,
		CL_PSEDO, CL_FULL_NAME,
		(SELECT SUM(AD_TOTAL_PRICE) FROM dbo.ActFactDetailTable WHERE AFD_ID_AFM = AFM_ID) AS AFM_TOTAL_PRICE
	FROM dbo.ActFactMasterTable
	WHERE ACT_ID = @actid
	ORDER BY AFM_DATE DESC
END
