USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_SELECT]
	@ACTIVE BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	SELECT STW_ID, SYS_ID, SYS_SHORT_NAME, SST_ID, SST_CAPTION, STW_WEIGHT
	FROM 
		dbo.SystemTypeWeightTable INNER JOIN
		dbo.SystemTable ON STW_ID_SYSTEM = SYS_ID INNER JOIN
		dbo.SystemTypeTable ON STW_ID_TYPE = SST_ID
	WHERE STW_ACTIVE = ISNULL(@ACTIVE, STW_ACTIVE)
END
