USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_KBU_GET]
	@SK_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SK_ID, SH_ID, SH_SHORT_NAME, PR_NAME, PR_ID, SYS_ID, SYS_SHORT_NAME, SK_KBU, SK_ACTIVE
	FROM
		dbo.SubhostKBUTable INNER JOIN
		dbo.SubhostTable ON SK_ID_HOST = SH_ID INNER JOIN
		dbo.SystemTable ON SYS_ID = SK_ID_SYSTEM INNER JOIN
		dbo.PeriodTable ON PR_ID = SK_ID_PERIOD
	WHERE SK_ID = @SK_ID
END
