USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[CONSIGNMENT_GET]
	@csgid INT	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CSG_CONSIGN_NAME, CSG_CONSIGN_ADDRESS, CSG_CONSIGN_INN, CSG_CONSIGN_KPP, 
		CSG_CONSIGN_OKPO, CSG_CLIENT_NAME, CSG_CLIENT_ADDRESS, 
		CSG_CLIENT_PHONE, CSG_CLIENT_BANK, CSG_FOUND, CSG_NUM, CSG_DATE, 
		ORG_ID, ORG_SHORT_NAME
	FROM 
		dbo.ConsignmentTable LEFT OUTER JOIN		
		dbo.OrganizationTable ON ORG_ID = CSG_ID_ORG		
	WHERE CSG_ID = @csgid 

END

