USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERIOD_GET_NEXT]
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PR_ID, PR_NAME
	FROM dbo.PeriodTable
	WHERE PR_ID = dbo.PERIOD_NEXT(@PR_ID)
END
