USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_ADD]
	@SYS_ID	SMALLINT,
	@SST_ID	SMALLINT,
	@WEIGHT	SMALLINT,
	@ACTIVE	BIT,	
	@RETURN BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.SystemTypeWeightTable(STW_ID_SYSTEM, STW_ID_TYPE, STW_WEIGHT, STW_ACTIVE)
	VALUES(@SYS_ID, @SST_ID, @WEIGHT, @ACTIVE)

	IF @RETURN = 1
		SELECT SCOPE_IDENTITY() AS NEW_IDEN
END
