USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_EDIT]
	@STW_ID	INT,
	@SYS_ID	SMALLINT,
	@SST_ID	SMALLINT,
	@WEIGHT	SMALLINT,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SystemTypeWeightTable
	SET STW_ID_SYSTEM = @SYS_ID,
		STW_ID_TYPE = @SST_ID,
		STW_WEIGHT = @WEIGHT,
		STW_ACTIVE = @ACTIVE
	WHERE STW_ID = @STW_ID
END
