USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Автор:			
Дата создания:  	
Описание:		
*/

CREATE PROCEDURE [dbo].[REPORT_INCOME]
	@date SMALLDATETIME,
	@orgid SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CL_ID, CL_PSEDO, CL_FULL_NAME, IN_DATE, IN_PAY_DATE, IN_PAY_NUM, 
		ID_PRICE, DIS_STR, DIS_ID, SYS_ORDER
	FROM 
		dbo.IncomeTable INNER JOIN
		dbo.IncomeDistrTable ON ID_ID_INCOME = IN_ID INNER JOIN
		dbo.ClientTable ON CL_ID = IN_ID_CLIENT INNER JOIN
		dbo.DistrView ON DIS_ID = ID_ID_DISTR
	WHERE IN_DATE = @date AND IN_ID_ORG = @orgid
	ORDER BY CL_PSEDO, CL_ID, IN_ID
END

