USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[PRICE_TYPE_GROUP_SELECT]
	@GROUP NVARCHAR(64) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PT_ID, PT_SHORT, PT_GROUP
	FROM Price.PriceType
	WHERE PT_GROUP = @GROUP OR @GROUP IS NULL
	ORDER BY PT_ORDER
END
