USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[PRICE_TYPE_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PT_ID, PT_SHORT, PT_GROUP
	FROM Price.PriceType
	--WHERE SN_ACTIVE = ISNULL(@active, SN_ACTIVE)
	ORDER BY PT_ORDER
END
