USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Price].[NET_TYPE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NT_ID, NT_SHORT, 'NET' + CONVERT(VARCHAR(20), NT_ID) AS NT_FIELD
	FROM dbo.NetType
	ORDER BY NT_NET, NT_TECH
END
