USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[PRICE_SYSTEM_NET_LIST_SELECT]	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		PT_ID, PT_SHORT, SST_ID, SST_CAPTION, NT_ID, NT_SHORT, 
		(
			SELECT INDEXING
			FROM Price.PriceSettings
			WHERE ID_PRICE = PT_ID
				AND ID_SYS_TYPE = SST_ID
				AND ID_NET_TYPE = NT_ID
		) AS INDEXING
	FROM 
		Price.PriceType
		CROSS JOIN dbo.SystemTypeTable
		CROSS JOIN dbo.NetType
	ORDER BY PT_ORDER, SST_ORDER, NT_NET, NT_TECH
END
