USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Ric].[KBU_GET]
	@PR_ID	SMALLINT,
	@PR_ALG	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	IF dbo.PeriodDelta(@PR_ALG, 1) = @PR_ID
		SELECT RK_TOTAL AS KBU
		FROM Ric.KBU
		WHERE RK_ID_QUARTER = dbo.QuarterDelta(dbo.PeriodQuarter(@PR_ID), -1)
	ELSE
		SELECT RK_TOTAL AS KBU
		FROM Ric.KBU
		WHERE RK_ID_QUARTER = dbo.PeriodQuarter(@PR_ID)
END