USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Ric].[GROW_STANDARD_SAVE]
	@PR_ID	SMALLINT,
	@VALUE	DECIMAL(10, 4)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @QR_ID	SMALLINT

	SET @QR_ID = dbo.PeriodQuarter(@PR_ID)

	UPDATE Ric.GrowStandard
	SET GS_VALUE = @VALUE
	WHERE GS_ID_QUARTER = @QR_ID

	IF @@ROWCOUNT = 0
		INSERT INTO Ric.GrowStandard(GS_ID_QUARTER, GS_VALUE)
			SELECT @QR_ID, @VALUE
END
