USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Ric].[KBU_LIST_GET]
	@QR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT QR_NAME, QR_ID, RK_KBU, RK_STOCK, RK_TOTAL
	FROM 
		Ric.KBU
		INNER JOIN dbo.Quarter ON QR_ID = RK_ID_QUARTER
	WHERE QR_ID = @QR_ID
END
