USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Ric].[KBU_LIST_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RK_ID_QUARTER, QR_NAME, RK_KBU, RK_STOCK, RK_TOTAL
	FROM 
		Ric.KBU
		INNER JOIN dbo.Quarter ON QR_ID = RK_ID_QUARTER
	ORDER BY QR_BEGIN DESC
END
