USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Ric].[GROW_NETWORK_AVG_SAVE]
	@PR_ID	SMALLINT,
	@VALUE	DECIMAL(10, 4)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @QR_ID	SMALLINT

	SET @QR_ID = dbo.PeriodQuarter(@PR_ID)

	UPDATE Ric.GrowNetworkAvg
	SET GNA_VALUE = @VALUE
	WHERE GNA_ID_QUARTER = @QR_ID

	IF @@ROWCOUNT = 0
		INSERT INTO Ric.GrowNetworkAvg(GNA_ID_QUARTER, GNA_VALUE)
			SELECT @QR_ID, @VALUE
END
