USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Ric].[STAGE_GET]
	@PR_ALG	SMALLINT,
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @PR_DATE	SMALLDATETIME

	SELECT @PR_DATE = PR_DATE
	FROM dbo.PeriodTable
	WHERE PR_ID = @PR_ALG

	DECLARE @RES	DECIMAL(10, 4)

	IF @PR_DATE >= '20120601'
	BEGIN
		SELECT @RES = ISNULL(
				(
					SELECT ST_VALUE
					FROM Ric.Stage
					WHERE ST_ID_QUARTER = dbo.PeriodQuarter(@PR_ID)
				),
				(
					SELECT TOP 1 ST_VALUE
					FROM 
						Ric.Stage
						INNER JOIN dbo.Quarter ON ST_ID_QUARTER = QR_ID
					WHERE QR_BEGIN <= (SELECT PR_DATE FROM dbo.PeriodTable WHERE PR_ID = @PR_ID)
					ORDER BY QR_BEGIN DESC
				))
	END
	
	SELECT @RES AS ST_VALUE
END
