USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Salary].[SERVICE_DETAIL_SELECT]
	@COURIER	SMALLINT,
	@PERIOD		SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ID UNIQUEIDENTIFIER
	
	SELECT @ID = ID
	FROM Salary.Service
	WHERE ID_COURIER = @COURIER AND ID_PERIOD = @PERIOD

	SELECT 
		ID, ID_CLIENT, CL_NAME, TO_ID, TO_NAME, ID_CITY, CT_NAME, ID_TYPE, CLT_NAME, KGS, ID_PERIOD, PR_DATE, CL_TERR, 
		CLIENT_TOTAL_PRICE, TO_COUNT, TO_PRICE, CPS_PERCENT, TO_CALC, CPS_MIN, CPS_MAX, CPS_INET, CPS_PAY, CPS_COEF, SYS_COUNT, KOB, 
		PAY, CALC, NOTE, UPDATES, ACT, INET, 
		TO_RESULT, TO_HANDS, TO_PAY_RESULT, TO_PAY_HANDS, 
		HOLD
	FROM 
		Salary.ServiceDetail a
		INNER JOIN dbo.ClientTypeTable c ON c.CLT_ID = a.ID_TYPE
		INNER JOIN dbo.PeriodTable d ON d.PR_ID = a.ID_PERIOD
	WHERE ID_SALARY = @ID
END
