USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Salary].[SERVICE_SELECT]
	@PERIOD		SMALLINT,
	@COURIER	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, PR_DATE, COUR_NAME, PR_ID, COUR_ID, (1 - ISNULL(COEF, 0)) * (SELECT SUM(TO_PAY_RESULT) FROM Salary.ServiceDetail d WHERE a.ID = d.ID_SALARY) AS COUR_TOTAL, COEF
	FROM 
		Salary.Service a
		INNER JOIN 
			(
				SELECT COUR_NAME, COUR_ID
				FROM
					dbo.CourierTable b 
					INNER JOIN dbo.GET_TABLE_FROM_LIST(@COURIER, ',') ON COUR_ID = ITEM
				
				UNION
				
				SELECT COUR_NAME, COUR_ID
				FROM dbo.CourierTable
			) AS b ON a.ID_COURIER = b.COUR_ID
		INNER JOIN dbo.PeriodTable c ON c.PR_ID = a.ID_PERIOD
	WHERE (ID_PERIOD = @PERIOD OR @PERIOD IS NULL)
	ORDER BY PR_DATE DESC, COUR_NAME
END
