USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_DELETE]
	@LS_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostLessonPrice
	WHERE SLP_ID_LESSON = @LS_ID

	DELETE
	FROM Subhost.SubhostStudy
	WHERE SS_ID_LESSON = @LS_ID

	DELETE
	FROM Subhost.Lesson
	WHERE LS_ID = @LS_ID
END
