USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_COMPENSATION_LAST]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE 
	FROM Subhost.SubhostCompensationTable
	WHERE SCP_ID_SUBHOST = @SH_ID AND SCP_ID_PERIOD = @PR_ID

	INSERT INTO Subhost.SubhostCompensationTable(
			SCP_ID_SUBHOST, SCP_ID_PERIOD, SCP_ID_SYSTEM, SCP_ID_TYPE, 
			SCP_ID_NET, SCP_ID_TECH, SCP_DISTR, SCP_COMP, SCP_COMMENT
			)
		SELECT 
			SCP_ID_SUBHOST, @PR_ID, SCP_ID_SYSTEM, SCP_ID_TYPE, 
			SCP_ID_NET, SCP_ID_TECH, SCP_DISTR, SCP_COMP, SCP_COMMENT
		FROM Subhost.SubhostCompensationTable
		WHERE SCP_ID_SUBHOST = @SH_ID AND SCP_ID_PERIOD = dbo.PERIOD_PREV(@PR_ID)
END
