USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_CALC_UNCLOSE]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT	
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostCalcReport
	WHERE SCR_ID_SUBHOST = @SH_ID
		AND SCR_ID_PERIOD = @PR_ID		

	UPDATE Subhost.SubhostCalc
	SET SHC_CLOSED = 0
	WHERE SHC_ID_SUBHOST = @SH_ID
		AND SHC_ID_PERIOD = @PR_ID
END
