USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_POSITION_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LP_ID, LP_NAME, LP_ACTIVE
	FROM Subhost.LessonPosition
	WHERE LP_ACTIVE = ISNULL(@ACTIVE, LP_ACTIVE)
	ORDER BY LP_ORDER
END
