USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_COMPENSATION_DELETE]
	@SCP_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM Subhost.SubhostCompensationTable
	WHERE SCP_ID = @SCP_ID
END
