USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_PRICE_SYSTEM_DELETE]
	@SPS_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostPriceSystemTable
	WHERE SPS_ID = @SPS_ID
END
