USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_EDIT]
	@LS_ID	INT,	
	@LS_NAME	VARCHAR(50),
	@LS_ORDER	SMALLINT,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Subhost.Lesson
	SET LS_NAME = @LS_NAME, 		
		LS_ORDER = @LS_ORDER,
		LS_ACTIVE = @ACTIVE
	WHERE LS_ID = @LS_ID
END
