USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_CALC_ORG_DEFAULT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ORG_ID, ORG_PSEDO, NULL AS PR_ID, NULL AS PR_DATE
	FROM dbo.OrganizationTable
	WHERE ORG_ID = 7
END
