USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LS_ID, LS_NAME, LS_ACTIVE
	FROM Subhost.Lesson
	WHERE LS_ACTIVE = ISNULL(@ACTIVE, LS_ACTIVE)
	ORDER BY LS_ORDER
END
