USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_PRICE_SYSTEM_EDIT]
	@SPS_ID	INT,
	@SYS_ID	SMALLINT,
	@PT_ID	SMALLINT,	
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@PRICE	MONEY,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Subhost.SubhostPriceSystemTable
	SET SPS_ID_SYSTEM = @SYS_ID,
		SPS_ID_TYPE = @PT_ID,
		SPS_ID_HOST = @SH_ID,
		SPS_ID_PERIOD = @PR_ID,
		SPS_PRICE = @PRICE,
		SPS_ACTIVE = @ACTIVE
	WHERE SPS_ID = @SPS_ID
END
