USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_PRICE_COPY]
	@SOURCE	SMALLINT,
	@DEST	SMALLINT,
	@COEF	DECIMAL(8, 4),
	@REPL	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @REPL = 1
		DELETE FROM Subhost.SubhostProductPrice WHERE SPP_ID_PERIOD = @DEST
	
	INSERT INTO Subhost.SubhostProductPrice(SPP_ID_PERIOD, SPP_ID_PRODUCT, SPP_PRICE)
		SELECT @DEST, SPP_ID_PRODUCT, CAST(ROUND(SPP_PRICE * @COEF, 0) AS MONEY)
		FROM Subhost.SubhostProductPrice
		WHERE SPP_ID_PERIOD = @SOURCE
END
