USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_GET]
	@SPG_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SPG_ID, SPG_NAME, SPG_ORDER, SPG_ACTIVE
	FROM Subhost.SubhostProductGroup 
	WHERE SPG_ID = @SPG_ID
END
