USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_KBU_ADD]
	@SH_ID	SMALLINT,
	@SYS_ID	SMALLINT,
	@KBU	DECIMAL(8, 4),
	@ACTIVE	BIT,
	@return	BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Subhost.SubhostKBUTable(SK_ID_HOST, SK_ID_SYSTEM, SK_KBU, SK_ACTIVE)
		VALUES(@SH_ID, @SYS_ID, @KBU, @ACTIVE)

	IF @RETURN = 1
		SELECT SCOPE_IDENTITY() AS NEW_IDEN
END
