USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_POSITION_GET]
	@LP_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LP_ID, LP_NAME, LP_ORDER, LP_ACTIVE
	FROM Subhost.LessonPosition
	WHERE LP_ID = @LP_ID
END
