USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_COMPENSATION_EDIT]
	@SCP_ID	INT,
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@SYS_ID	SMALLINT,
	@SST_ID	SMALLINT,
	@SN_ID	SMALLINT,
	@TT_ID	SMALLINT,
	@DISTR	INT,
	@COMP	TINYINT,
	@COMMENT	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Subhost.SubhostCompensationTable
	SET SCP_ID_SUBHOST = @SH_ID,
		SCP_ID_PERIOD = @PR_ID,
		SCP_ID_SYSTEM = @SYS_ID,
		SCP_ID_NET = @SN_ID,
		SCP_ID_TYPE = @SST_ID,
		SCP_ID_TECH = @TT_ID,
		SCP_DISTR = @DISTR,
		SCP_COMP = @COMP,
		SCP_COMMENT = @COMMENT
	WHERE SCP_ID = @SCP_ID
END
