USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_CALC_SELECT_LAST]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM Subhost.SubhostCalc
	WHERE SHC_ID_SUBHOST = @SH_ID
		AND SHC_ID_PERIOD = dbo.PERIOD_PREV(@PR_ID)
END
