USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_LESSON_GET]
	@LS_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LS_ID, LS_NAME, LS_ORDER, LS_ACTIVE
	FROM Subhost.Lesson
	WHERE LS_ID = @LS_ID
END
