USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_STUDY_SELECT]
	@SH_ID	SMALLINT,
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		LS_ID, LS_NAME, 
		(
			SELECT SS_COUNT
			FROM Subhost.SubhostStudy
			WHERE SS_ID_PERIOD = @PR_ID 
				AND SS_ID_SUBHOST = @SH_ID
				AND SS_ID_LESSON = LS_ID							
		) AS SS_COUNT, 
		(
			SELECT SLP_PRICE
			FROM Subhost.SubhostLessonPrice
			WHERE SLP_ID_PERIOD = @PR_ID			
				AND SLP_ID_LESSON = LS_ID
		) AS SLP_PRICE,
		(
			SELECT SLP_PRICE
			FROM Subhost.SubhostLessonPrice
			WHERE SLP_ID_PERIOD = @PR_ID			
				AND SLP_ID_LESSON = LS_ID
		) AS SLP_ET_PRICE
	FROM 
		Subhost.Lesson
	WHERE LS_ACTIVE = 1
	ORDER BY LS_ORDER
END
