USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SPG_ID, SPG_NAME, SPG_ACTIVE
	FROM Subhost.SubhostProductGroup 
	WHERE SPG_ACTIVE = ISNULL(@ACTIVE, SPG_ACTIVE)
	ORDER BY SPG_ORDER
END
