USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[SUBHOST_CALC_DATES]
	@PR_ID	SMALLINT,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

    UPDATE Subhost.SubhostCalcDates
	SET SCD_DATE	=	@DATE
	WHERE SCD_ID_PERIOD = @PR_ID

	IF @@ROWCOUNT = 0
		INSERT INTO Subhost.SubhostCalcDates(SCD_ID_PERIOD, SCD_DATE)	
			VALUES(@PR_ID, @DATE)
END
