USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[SUBHOST_REG_COMPLECT]
	@PR_ID	SMALLINT,
	@COMPLECT	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	IF @COMPLECT = ''
		SET @COMPLECT = NULL

	SELECT 
		REG_ID, 
		SYS_SHORT_NAME, REG_ID_SYSTEM, SYS_ORDER, 
		REG_DISTR_NUM, REG_COMP_NUM, 
		SST_NAME, REG_ID_TYPE, 
		DS_REG, DS_NAME, REG_ID_STATUS, 
		REG_DATE, REG_COMMENT, 
		SNC_NET_COUNT, REG_ID_NET, SNC_ID_SN,
		NULL AS TT_NAME, NULL AS REG_ID_TECH_TYPE, 
		REG_COMPLECT, CONVERT(BIT, 0) AS REG_SELECT
	FROM dbo.PeriodRegView
	WHERE REG_ID_PERIOD = @PR_ID AND
		REG_COMPLECT = @COMPLECT
	ORDER BY SYS_ORDER, REG_DISTR_NUM
END
