USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ClaimTypeView]
AS
SELECT 1 AS TP, N'Прайс' AS NAME
UNION ALL
SELECT 2 AS TP, N'Демо1' AS NAME
UNION ALL
SELECT 3 AS TP, N'Онлайн' AS NAME
UNION ALL
SELECT 4 AS TP, N'Демо2' AS NAME
