USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [Common].[PeriodCurrent]
(
	@TYPE TINYINT
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @RES UNIQUEIDENTIFIER

	SELECT @RES = ID
	FROM Common.Period
	WHERE TYPE = @TYPE
		AND START =
			(
				SELECT MAX(START)
				FROM Common.Period
				WHERE START < GETDATE()
				AND TYPE = @TYPE
			)

	RETURN @RES
END