USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[Rand_f]', 'FN') IS NULL EXEC('CREATE FUNCTION [Common].[Rand_f] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Common].[Rand_f]() RETURNS FLOAT BEGIN RETURN (SELECT V FROM Common.RandView); END;
GO
