USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[DateAssign]
(
	@DT	DATETIME,
	@TM	DATETIME
)
RETURNS DATETIME
WITH SCHEMABINDING
AS
BEGIN
	RETURN CONVERT(DATETIME, LEFT(CONVERT(NVARCHAR(64), @DT, 120), 10) + N' ' + RIGHT(CONVERT(NVARCHAR(64), @TM, 120), 8), 120)
END
GO
