USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MonthRodString]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[MonthRodString] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE OR ALTER FUNCTION [dbo].[MonthRodString]
(
	@DATE	SMALLDATETIME
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @RES VARCHAR(100)

	SET @RES = CONVERT(VARCHAR(50), DATEPART(DAY, @DATE)) + ' '

	SELECT @RES = @RES + ROD
	FROM dbo.Month
	WHERE NUM = DATEPART(MONTH, @DATE)

	SELECT @RES = @RES + ' ' + CONVERT(VARCHAR(50), DATEPART(YEAR, @DATE))

	RETURN @RES
END
GO
