USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[PhoneString]
(
	@PHONE VARCHAR(512)
)
RETURNS VARCHAR(256)
AS
BEGIN
	DECLARE @POS INT
	SET @pos = LEN(@PHONE)

	WHILE @pos > 0
	BEGIN
		IF SUBSTRING(@PHONE, @POS, 1) NOT LIKE '[0123456789,]'
		
		SET @PHONE = STUFF(@PHONE, @POS, 1, '')

		SET @POS = @POS - 1
	END

	DECLARE @RES VARCHAR(256)

	SELECT @RES = ISNULL(
		REVERSE(STUFF(REVERSE(
			(
				SELECT ITEM + ','
				FROM dbo.GET_STRING_TABLE_FROM_LIST(@PHONE, ',')
				ORDER BY Item FOR XML PATH('')
			)), 1, 1, '')), '')

	RETURN @RES
END
