USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[TimeMinToStr]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[TimeMinToStr] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[TimeMinToStr]
(
	@TIME INT
)
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @RESULT NVARCHAR(50)

	SET @RESULT = ''

	IF ROUND(@TIME / 60, 0) <> 0
		SET @RESULT = @RESULT + CONVERT(VARCHAR(20), ROUND(@TIME / 60, 0)) + ' ч.'
	IF ROUND((@TIME - ROUND(@TIME / 60, 0) * 60), 0) <> 0
		SET @RESULT = @RESULT + CONVERT(VARCHAR(20), ROUND((@TIME - ROUND(@TIME / 60, 0) * 60), 0)) + ' м.'

	RETURN @RESULT
END
GO
