USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MonthOf]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[MonthOf] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE OR ALTER FUNCTION dbo.MonthOf
(
	@DT	DATETIME
)
RETURNS SMALLDATETIME
WITH SCHEMABINDING
AS
BEGIN
	RETURN (CONVERT(SMALLDATETIME,((CONVERT(VARCHAR(20),DATEPART(YEAR,@DT),0)+REPLICATE('0',(2)-LEN(CONVERT(VARCHAR(20),DATEPART(MONTH,@DT),0))))+CONVERT(VARCHAR(20),DATEPART(MONTH,@DT),0))+'01',(112)))
END
GO
