USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [Maintenance].[GlobalContractYear]
()
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @RES UNIQUEIDENTIFIER

	DECLARE @TMP VARCHAR(500)

	SELECT @TMP = GS_VALUE
	FROM Maintenance.GlobalSettings
	WHERE GS_NAME = 'CONTRACT_YEAR'

	SET @RES = Cast(@TMP AS UniqueIdentifier)

	RETURN @RES
END
GO
