USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Maintenance].[GlobalMessageDelay]', 'FN') IS NULL EXEC('CREATE FUNCTION [Maintenance].[GlobalMessageDelay] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Maintenance].[GlobalMessageDelay]
()
RETURNS INT
AS
BEGIN
	DECLARE @RES INT

	DECLARE @TMP VARCHAR(500)

	SELECT @TMP = GS_VALUE
	FROM Maintenance.GlobalSettings
	WHERE GS_NAME = 'MESSAGE_DELAY'

	IF @TMP IS NULL
		SET @RES = 5
	ELSE
		SET @RES = CONVERT(INT, @TMP)

	RETURN @RES
END
GO
