USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [Maintenance].[GlobalMessageDelayMax]
()
RETURNS INT
AS
BEGIN
	DECLARE @RES INT

	DECLARE @TMP VARCHAR(500)

	SELECT @TMP = GS_VALUE
	FROM Maintenance.GlobalSettings
	WHERE GS_NAME = 'MESSAGE_DELAY_MAX'

	IF @TMP IS NULL
		SET @RES = 20
	ELSE 
		SET @RES = CONVERT(INT, @TMP)
		
	RETURN @RES
END
