USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[IPSTTView]
AS	
	SELECT CSD_SYS, CSD_DISTR, CSD_COMP, CSD_START, CSD_END
	FROM [PC275-SQL\OMEGA].IPLogs.dbo.ClientStatDetail
	WHERE CSD_STT_SEND = 1 AND CSD_STT_RESULT = 1
