USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFActView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFActView]  AS SELECT 1')
GO
CREATE OR ALTER VIEW [dbo].[DBFActView]
AS
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, AD_TOTAL_PRICE
	FROM dbo.DBFAct
GO
