USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[TaskDBView]
AS
	SELECT EXECUTE_DATE_S, DETAIL_DATA, EXECUTOR_NOTE
	FROM [Knowledge].[Task.Tasks]
	WHERE STATUS = 1
		AND MAIN_DATA = 'ClientDB'
		AND EXECUTE_DATE IS NOT NULL
	--ORDER BY EXECUTE_DATE_S DESC
GO
