USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFTOView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFTOView]  AS SELECT 1')
GO

ALTER VIEW [dbo].[DBFTOView]
AS
	SELECT
		TO_ID, TO_NUM, TO_NAME, COUR_NAME, ST_CITY_NAME + ', ' + TA_HOME AS TA_STR,
		REVERSE(STUFF(REVERSE((
			SELECT DIS_STR + ','
			FROM [DBF].[dbo.RegNodeTable] z
			INNER JOIN [DBF].[dbo.TODistrView] y ON RN_SYS_NAME = y.SYS_REG_NAME AND RN_DISTR_NUM = DIS_NUM AND RN_COMP_NUM = DIS_COMP_NUM
			INNER JOIN [DBF].[dbo.SystemTable] x ON RN_SYS_NAME = x.SYS_REG_NAME
			WHERE TD_ID_TO = TO_ID AND RN_SERVICE = 0
			ORDER BY SYS_ORDER, DIS_NUM, DIS_COMP_NUM FOR XML PATH('')
		)), 1, 1, '')) AS DIS_LIST
	FROM [DBF].[dbo.TOTable]
	LEFT JOIN [DBF].[dbo.TOAddressView] ON TA_ID_TO = TO_ID
	LEFT JOIN [DBF].[dbo.CourierTable] ON TO_ID_COUR = COUR_ID
GO
