USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFBillRestView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFBillRestView]  AS SELECT 1')
GO
CREATE OR ALTER VIEW [dbo].[DBFBillRestView]
AS
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, BD_REST
	FROM dbo.DBFBillRest
GO
