USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[InfoBankSizeView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[InfoBankSizeView]  AS SELECT 1')
GO
CREATE OR ALTER VIEW [dbo].[InfoBankSizeView]
WITH SCHEMABINDING
AS
	SELECT IBS_DATE, IBF_ID_IB, SUM(IBS_SIZE) AS IBS_SIZE, COUNT_BIG(*) AS IBS_CNT
	FROM
		dbo.InfoBankSize
		INNER JOIN dbo.InfoBankFile ON IBS_ID_FILE = IBF_ID
	GROUP BY IBS_DATE, IBF_ID_IB

GO
CREATE UNIQUE CLUSTERED INDEX [UC_dbo.InfoBankSizeView(IBF_ID_IB,IBS_DATE)] ON [dbo].[InfoBankSizeView] ([IBF_ID_IB] ASC, [IBS_DATE] ASC);
CREATE NONCLUSTERED INDEX [IX_dbo.InfoBankSizeView(IBS_DATE)+(IBS_SIZE)] ON [dbo].[InfoBankSizeView] ([IBS_DATE] ASC) INCLUDE ([IBS_SIZE]);
GO
