USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[RivalDataView]
AS
	SELECT 
		CR_ID, 
		ISNULL(CONVERT(BIT,(
			SELECT MAX(CONVERT(INT, CRR_CLAIM))
			FROM dbo.ClientRivalReaction
			WHERE CRR_ID_RIVAL = CR_ID
		)), 0) AS CRR_CLAIM,
		ISNULL(CONVERT(BIT,(
			SELECT MAX(CONVERT(INT, CRR_COMPARE))
			FROM dbo.ClientRivalReaction
			WHERE CRR_ID_RIVAL = CR_ID
		)), 0) AS CRR_COMPARE,
		ISNULL(CONVERT(BIT,(
			SELECT MAX(CONVERT(INT, CRR_REJECT))
			FROM dbo.ClientRivalReaction
			WHERE CRR_ID_RIVAL = CR_ID
		)), 0) AS CRR_REJECT,
		ISNULL(CONVERT(BIT,(
			SELECT MAX(CONVERT(INT, CRR_PARTNER))
			FROM dbo.ClientRivalReaction
			WHERE CRR_ID_RIVAL = CR_ID
		)), 0) AS CRR_PARTNER
	FROM dbo.ClientRival
