USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFIncomeView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFIncomeView]  AS SELECT 1')
GO
ALTER VIEW [dbo].[DBFIncomeView]
AS
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, ID_PRICE
	FROM dbo.DBFIncome
GO
