USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DBFDistrLastPayView]
AS	
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, LAST_ACT, LAST_PAY_MON, LAST_BILL_SUM, LAST_INCOME_SUM, NEXT_MONTH, PAY_DELTA
	FROM [PC275-SQL\DELTA].DBF.dbo.DistrLastPayView