USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[IPLogView]
AS
	SELECT LF_DATE, LF_SYS, LF_DISTR, LF_COMP
	FROM [PC275-SQL\OMEGA].IPLogs.dbo.LogFiles
GO
