USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[HotlineChatView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[HotlineChatView]  AS SELECT 1')
GO
ALTER VIEW [dbo].[HotlineChatView]
WITH SCHEMABINDING
AS
	SELECT
		ID, SYS, DISTR, COMP, HostID, FIRST_DATE, START, FINISH,
		PROFILE, FIO, EMAIL, PHONE, CHAT, LGN, RIC_PERSONAL, LINKS,
		--DATEADD(HOUR, 7, CONVERT(DATETIME, SUBSTRING(CHAT, 8, 4) + '-' + SUBSTRING(CHAT, 5, 2) + '-' + SUBSTRING(CHAT, 2, 2) + ' ' + SUBSTRING(CHAT, 13, 8), 120)) AS FIRST_ANS
		CASE
			WHEN CHARINDEX('] РИЦ (', CHAT) <> 0 THEN
				DATEADD(HOUR, 7, CONVERT(DATETIME, SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] РИЦ (', CHAT) - 19, 19), 7, 4) + '-' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] РИЦ (', CHAT) - 19, 19), 4, 2) + '-' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] РИЦ (', CHAT) - 19, 19), 1, 2) + ' ' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] РИЦ (', CHAT) - 19, 19), 12, 8), 120))
			ELSE NULL
		END AS FIRST_ANS,
		dbo.DateOf(FIRST_DATE) AS DATE_S
	FROM
		dbo.HotlineChat a
		INNER JOIN dbo.SystemTable b ON a.SYS = b.SystemNumber AND b.SystemRic = 20

GO
CREATE UNIQUE CLUSTERED INDEX [UC_dbo.HotlineChatView(ID)] ON [dbo].[HotlineChatView] ([ID] ASC);
CREATE NONCLUSTERED INDEX [IX_dbo.HotlineChatView(START,DISTR,COMP,HostID)] ON [dbo].[HotlineChatView] ([START] ASC, [DISTR] ASC, [COMP] ASC, [HostID] ASC);
GO
