USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFIncomeDateView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFIncomeDateView]  AS SELECT 1')
GO
ALTER VIEW [dbo].[DBFIncomeDateView]
AS
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, IN_DATE
	FROM dbo.DBFIncomeDate
GO
