USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DBFActView]
AS	
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, AD_TOTAL_PRICE
	--FROM [PC275-SQL\DELTA].DBF.dbo.ActAllIXView WITH(NOEXPAND)
	FROM dbo.DBFAct