USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFTODistrView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFTODistrView]  AS SELECT 1')
GO

ALTER VIEW [dbo].[DBFTODistrView]
AS
	SELECT DIS_NUM, TD_ID_TO
	FROM [DBF].[dbo.TODistrView]
GO
