USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ContractRegisterView]
AS	
	SELECT 
		a.ID, c.NAME AS VEN_NAME, YEAR, DATE, NUM, NUM_STR, b.NAME AS TP_NAME, a.NOTE, a.CLIENT, CLIENTID
	FROM 
		[PC275-SQL\GAMMA].ContractDB.dbo.Contract a
		INNER JOIN [PC275-SQL\GAMMA].ContractDB.dbo.ContractType b ON a.ID_TYPE = b.ID
		INNER JOIN [PC275-SQL\GAMMA].ContractDB.dbo.Vendor c ON a.ID_VENDOR = c.ID
	WHERE STATUS = 1 AND CLIENT_PLACE = 'OIS' 
