USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DBFPriceView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[DBFPriceView]  AS SELECT 1')
GO
CREATE OR ALTER VIEW [dbo].[DBFPriceView]
AS
	SELECT SYS_REG_NAME, PR_DATE, PT_NAME, PS_PRICE
	FROM [DBF].[dbo].[PriceExportView]
	WHERE SYS_REG_NAME NOT IN ('-', '--')
GO
