USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[DBFBillView]
AS	
	SELECT SYS_REG_NAME, DIS_NUM, DIS_COMP_NUM, PR_DATE, BD_TOTAL_PRICE
	FROM [PC275-SQL\DELTA].DBF.dbo.BillAllIXView WITH(NOEXPAND)