USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[HotlineChatView]
WITH SCHEMABINDING
AS
	SELECT 
		ID, SYS, DISTR, COMP, HostID, FIRST_DATE, START, FINISH, 
		PROFILE, FIO, EMAIL, PHONE, CHAT, LGN, RIC_PERSONAL, LINKS,
		--DATEADD(HOUR, 7, CONVERT(DATETIME, SUBSTRING(CHAT, 8, 4) + '-' + SUBSTRING(CHAT, 5, 2) + '-' + SUBSTRING(CHAT, 2, 2) + ' ' + SUBSTRING(CHAT, 13, 8), 120)) AS FIRST_ANS
		CASE 
			WHEN CHARINDEX('] –»÷ (', CHAT) <> 0 THEN
				DATEADD(HOUR, 7, CONVERT(DATETIME, SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] –»÷ (', CHAT) - 19, 19), 7, 4) + '-' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] –»÷ (', CHAT) - 19, 19), 4, 2) + '-' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] –»÷ (', CHAT) - 19, 19), 1, 2) + ' ' + SUBSTRING(SUBSTRING(CHAT, CHARINDEX('] –»÷ (', CHAT) - 19, 19), 12, 8), 120)) 
			ELSE NULL
		END AS FIRST_ANS,
		dbo.DateOf(FIRST_DATE) AS DATE_S
	FROM 
		dbo.HotlineChat a
		INNER JOIN dbo.SystemTable b ON a.SYS = b.SystemNumber AND b.SystemRic = 20
	