USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[IPReturnCodeView]
AS	
	SELECT RC_ID, RC_NUM, RC_TEXT, RC_TYPE, RC_ERROR, RC_WARNING
	FROM [PC275-SQL\OMEGA].IPLogs.dbo.ReturnCode
