USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[IPReturnCodeView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[IPReturnCodeView]  AS SELECT 1')
GO

ALTER VIEW [dbo].[IPReturnCodeView]
AS
	SELECT RC_ID, RC_NUM, RC_TEXT, RC_TYPE, RC_ERROR, RC_WARNING
	FROM IPLogs.dbo.ReturnCode
GO
