USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [IP].[ClientStatView]
AS
	SELECT CSD_SYS, CSD_DISTR, CSD_COMP, CSD_ID, ISNULL(CSD_START, CSD_END) AS CSD_DATE
	FROM [PC275-SQL\OMEGA].IPLogs.dbo.ClientStatDetail
