USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Reg].[RegHistoryActiveView]
AS
	SELECT 
		b.ID, ID_HOST, DISTR, COMP, ID_DISTR, DATE, ID_SYSTEM, ID_NET, ID_TYPE, SUBHOST, 
		TRAN_COUNT, TRAN_LEFT, ID_STATUS, REG_DATE, FIRST_REG, COMPLECT, COMMENT
	FROM 
		Reg.RegDistr a
		INNER JOIN Reg.RegHistory b ON a.ID = b.ID_DISTR
	WHERE b.ID = 
		(
			SELECT TOP 1 ID
			FROM Reg.RegHistory c
			WHERE c.ID_DISTR = b.ID_DISTR
			ORDER BY DATE DESC
		)
