USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Reg].[RegDisconnectView]
AS
	SELECT RPR_ID_HOST, RPR_DISTR, RPR_COMP, DATE
	FROM Reg.RegProtocolDisconnectView WITH(NOEXPAND)

	UNION ALL

	SELECT ID_HOST, DISTR, COMP, DATE
	FROM Reg.RegProtocolTextDisconnectView WITH(NOEXPAND)