USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Reg].[RegHistoryView]
WITH SCHEMABINDING 
AS
	SELECT 
		ID, ID_DISTR, DATE, 
		SystemShortName, NT_SHORT, SST_SHORT,
		SUBHOST, TRAN_COUNT, TRAN_LEFT, 
		DS_NAME, DS_REG, REG_DATE, FIRST_REG, COMPLECT, COMMENT
	FROM 
		Reg.RegHistory
		INNER JOIN dbo.SystemTable ON ID_SYSTEM = SystemID
		INNER JOIN Din.SystemType ON ID_TYPE = SST_ID
		INNER JOIN Din.NetType ON ID_NET = NT_ID
		INNER JOIN dbo.DistrStatus ON ID_STATUS = DS_ID
