USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Reg].[RegProtocolTextDisconnectView]
WITH SCHEMABINDING
AS
	SELECT ID_HOST, DISTR, COMP, DATE, COUNT_BIG(*) AS CNT
	FROM Reg.ProtocolText a
	WHERE COMMENT LIKE '%Отключение%'
	GROUP BY ID_HOST, DISTR, COMP, DATE