USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [USR].[USRDateKindView]
WITH SCHEMABINDING
AS
	SELECT UD_ID, UD_ID_CLIENT, USRFileKindName, UIU_DATE_S, COUNT_BIG(*) AS CNT
	FROM
		USR.USRData 
		INNER JOIN USR.USRFile ON UF_ID_COMPLECT = UD_ID
		INNER JOIN USR.USRIB ON UI_ID_USR = UF_ID
		INNER JOIN USR.USRUpdates ON UIU_ID_IB = UI_ID
		INNER JOIN dbo.USRFileKindTable ON USRFileKindID = UIU_ID_KIND
	WHERE UD_ID_CLIENT IS NOT NULL
	GROUP BY UD_ID, UD_ID_CLIENT, USRFileKindName, UIU_DATE_S
