USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[USR].[USRIBComplianceView]', 'V ') IS NULL EXEC('CREATE VIEW [USR].[USRIBComplianceView]  AS SELECT 1')
GO
CREATE OR ALTER VIEW [USR].[USRIBComplianceView]
WITH SCHEMABINDING
AS
	SELECT UD_ID_CLIENT, UF_ID, UI_ID_BASE, UI_LAST
	FROM
		USR.USRData
		INNER JOIN USR.USRFile ON UF_ID_COMPLECT = UD_ID
		INNER JOIN USR.USRIB ON UI_ID_USR = UF_ID
		INNER JOIN dbo.ComplianceTypeTable ON ComplianceTypeID = UI_ID_COMP
	WHERE ComplianceTypeName = '#HOST'

GO
CREATE UNIQUE CLUSTERED INDEX [UC_USR.USRIBComplianceView(UF_ID,UI_ID_BASE)] ON [USR].[USRIBComplianceView] ([UF_ID] ASC, [UI_ID_BASE] ASC);
CREATE NONCLUSTERED INDEX [IX_USR.USRIBComplianceView(UD_ID_CLIENT,UI_LAST)+(UI_ID_BASE)] ON [USR].[USRIBComplianceView] ([UD_ID_CLIENT] ASC, [UI_LAST] ASC) INCLUDE ([UI_ID_BASE]);
GO
