USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE VIEW [USR].[USRComplianceView]
WITH SCHEMABINDING
AS
	SELECT UD_ID_CLIENT, UD_ID, UF_ID, UF_DATE, UF_COMPLIANCE
	FROM 
		USR.USRData
		INNER JOIN USR.USRFile ON UD_ID = UF_ID_COMPLECT
