USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE VIEW [USR].[___USRComplectGlobalStatusView]
--WITH SCHEMABINDING
AS
		SELECT 
			UD_ID, UD_COMPLECT, Service AS UD_SERVICE,
			d.SystemNumber AS UD_SYS,
			CONVERT(INT, 
						CASE 
							WHEN CHARINDEX('_', REVERSE(UD_COMPLECT)) > 3 THEN 
									RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT))
							ELSE LEFT(RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT)), CHARINDEX('_', RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT))) - 1)
						END) AS UD_DISTR,
			CASE 
				WHEN CHARINDEX('_', REVERSE(UD_COMPLECT)) > 3 THEN 1
				ELSE CONVERT(INT, REVERSE(LEFT(REVERSE(UD_COMPLECT), CHARINDEX('_', REVERSE(UD_COMPLECT)) - 1)))
			END AS UD_COMP
		FROM 
			USR.USRData a
			INNER JOIN dbo.SystemTable b ON LEFT(UD_COMPLECT, CHARINDEX('_', UD_COMPLECT) - 1) = SystemNumber
			INNER JOIN dbo.SystemTable d ON d.HostID = b.HostID AND d.SystemRic = 20
			INNER JOIN dbo.RegNodeTable c ON d.SystemBaseName = c.SystemName AND 
							CONVERT(INT, 
									CASE 
										WHEN CHARINDEX('_', REVERSE(UD_COMPLECT)) > 3 THEN 
												RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT))
										ELSE LEFT(RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT)), CHARINDEX('_', RIGHT(UD_COMPLECT, LEN(UD_COMPLECT) - CHARINDEX('_', UD_COMPLECT))) - 1)
									END) = DistrNumber
							AND 
								CASE 
									WHEN CHARINDEX('_', REVERSE(UD_COMPLECT)) > 3 THEN 1
									ELSE CONVERT(INT, REVERSE(LEFT(REVERSE(UD_COMPLECT), CHARINDEX('_', REVERSE(UD_COMPLECT)) - 1)))
								END = CompNumber
