USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [USR].[ClientUSRPathView]
AS
	SELECT UD_ID_CLIENT, UF_PATH, COUNT(*) AS CNT
	FROM 
		USR.USRData a
		INNER JOIN USR.USRFile ON UF_ID_COMPLECT = UD_ID
	WHERE UD_ACTIVE = 1 AND UD_ID_CLIENT IS NOT NULL
		AND UF_ACTIVE = 1
		AND UF_PATH <> 3
		AND UF_DATE BETWEEN DATEADD(MONTH, -1, GETDATE()) AND GETDATE()
	GROUP BY UD_ID_CLIENT, UF_PATH