USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [USR].[USRIBComplianceView]
WITH SCHEMABINDING
AS
	SELECT UD_ID_CLIENT, UF_ID, UI_ID_BASE, UI_LAST
	FROM
		USR.USRData
		INNER JOIN USR.USRFile ON UF_ID_COMPLECT = UD_ID
		INNER JOIN USR.USRIB ON UI_ID_USR = UF_ID
		INNER JOIN dbo.ComplianceTypeTable ON ComplianceTypeID = UI_ID_COMP
	WHERE ComplianceTypeName = '#HOST'
