USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Book].[BOOK_PRICE_INSERT]
	@HLF_ID		UNIQUEIDENTIFIER,
	@BP_PRICE	MONEY,
	@BP_DATE	SMALLDATETIME,
	@BP_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_PRICE', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)	

	DECLARE @MASTERID UNIQUEIDENTIFIER
	
	INSERT INTO Book.BookPrice(BPMS_ID) 
	OUTPUT INSERTED.BPMS_ID INTO @TBL 
	DEFAULT VALUES

	
	SELECT	@MASTERID = ID 
	FROM	@TBL

	DELETE 
	FROM @TBL	


	INSERT INTO 
			Book.BookPriceDetail(
				BP_ID_HALF,
				BP_PRICE,
				BP_DATE,
				BP_ID_MASTER
			)
	OUTPUT INSERTED.BP_ID INTO @TBL(ID)
	VALUES	(
				@HLF_ID,
				@BP_PRICE,
				@BP_DATE,
				@MASTERID
			)
	
	SELECT	@BP_ID = ID
	FROM	@TBL

	
	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_PRICE', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_PRICE', 'Новая запись', @MASTERID, @OLD, @NEW

END

