USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Book].[BOOK_DELIVERY_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = BD_ID_MASTER
	FROM Book.BookBonusDelivery
	WHERE BD_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @MASTERID, @OLD OUTPUT

	UPDATE	Book.BookDeliveryDetail
	SET		BD_END	=	@DATE,
			BD_REF	=	3
	WHERE	BD_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_DELIVERY', 'Удаление', @MASTERID, @OLD, @NEW

	
	SELECT	@RC	=	@@ROWCOUNT
END

