USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_PRICE_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(BPMS_LAST)
	FROM	Book.BookPrice
END
GO
GRANT EXECUTE ON [Book].[BOOK_PRICE_LAST] TO rl_book_price_r;
GO