USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_DELIVERY_INSERT]
	@BD_PRICE	MONEY,
	@BD_COUNT	SMALLINT,
	@BD_DATE	SMALLDATETIME,
	@BD_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Book.BookDelivery(BDMS_ID)
	OUTPUT INSERTED.BDMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT @MASTERID = ID
	FROM @TBL

	DELETE
	FROM @TBL


	INSERT INTO
			Book.BookDeliveryDetail(
				BD_PRICE,
				BD_COUNT,
				BD_DATE,
				BD_ID_MASTER
			)
	OUTPUT INSERTED.BD_ID INTO @TBL(ID)
	VALUES	(
				@BD_PRICE,
				@BD_COUNT,
				@BD_DATE,
				@MASTERID
			)

	SELECT	@BD_ID = ID
	FROM	@TBL


	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_DELIVERY', 'Новая запись', @MASTERID, @OLD, @NEW

END

