USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_BONUS_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(BBMS_LAST)
	FROM	Book.BookBonus
END
GO
GRANT EXECUTE ON [Book].[BOOK_BONUS_LAST] TO rl_book_bonus_r;
GO
