USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[BOOK_DELIVERY_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Book].[BOOK_DELIVERY_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Book].[BOOK_DELIVERY_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(BDMS_LAST)
	FROM	Book.BookDelivery
END
GO
