USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_PRICE_OVER_ONE]
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = BP_ID_MASTER
	FROM Book.BookPriceDetail
	WHERE BP_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_PRICE', @MASTERID, @OLD OUTPUT

	UPDATE	Book.BookPriceDetail
	SET		BP_END	=	@DATE,
			BP_REF	=	3
	WHERE	BP_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_PRICE', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_PRICE', 'Удаление', @MASTERID, @OLD, @NEW
END

GO
