USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[COMPETITION_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Book].[COMPETITION_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Book].[COMPETITION_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(CPMS_LAST)
	FROM	Book.Competition
END
GO
GRANT EXECUTE ON [Book].[COMPETITION_LAST] TO rl_competition_r;
GO
