USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[COMPETITION_OVER_ONE]
	@IDLIST UNIQUEIDENTIFIER,
	@DATE SMALLDATETIME,
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = CP_ID_MASTER
	FROM Book.CompetitionDetail
	WHERE CP_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', @MASTERID, @OLD OUTPUT

	UPDATE	Book.CompetitionDetail
	SET		CP_END	=	@DATE,
			CP_REF	=	3
	WHERE	CP_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'COMPETITION', 'Удаление', @MASTERID, @OLD, @NEW

END

GO
