USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_BONUS_UPDATE]
	@BB_ID		UNIQUEIDENTIFIER,
	@PT_ID		UNIQUEIDENTIFIER,
	@BB_PERCENT	DECIMAL(8, 4),
	@BB_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @BB_ID_MASTER UNIQUEIDENTIFIER

	SELECT @BB_ID_MASTER = BB_ID_MASTER
	FROM Book.BookBonusDetail
	WHERE BB_ID = @BB_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_BONUS', @BB_ID_MASTER, @OLD OUTPUT

	UPDATE	Book.BookBonusDetail
	SET		BB_ID_PT	=	@PT_ID,
			BB_PERCENT	=	@BB_PERCENT,
			BB_DATE		=	@BB_DATE
	WHERE	BB_ID		=	@BB_ID

	UPDATE	Book.BookBonus
	SET		BBMS_LAST = GETDATE()
	WHERE	BBMS_ID	=
		(
			SELECT	BB_ID_MASTER
			FROM	Book.BookBonusDetail
			WHERE	BB_ID	=	@BB_ID
		)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_BONUS', @BB_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_BONUS', 'Редактирование', @BB_ID_MASTER, @OLD, @NEW
END

GO
GRANT EXECUTE ON [Book].[BOOK_BONUS_UPDATE] TO rl_book_bonus_u;
GO