USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_BONUS_OVER_ONE]
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = BB_ID_MASTER
	FROM Book.BookBonusDetail
	WHERE BB_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_BONUS', @MASTERID, @OLD OUTPUT

	UPDATE	Book.BookBonusDetail
	SET		BB_END	=	@DATE,
			BB_REF	=	3
	WHERE	BB_ID = @IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_BONUS', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_BONUS', 'Удаление', @MASTERID, @OLD, @NEW
END

GO
