USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[COMPETITION_UPDATE]
	@CP_ID		UNIQUEIDENTIFIER,
	@HLF_ID		UNIQUEIDENTIFIER,
	@CP_NAME	VARCHAR(100),
	@CP_COUNT	TINYINT,
	@CP_BONUS	MONEY,
	@CP_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @CP_ID_MASTER UNIQUEIDENTIFIER

	SELECT @CP_ID_MASTER = CP_ID_MASTER
	FROM Book.CompetitionDetail
	WHERE CP_ID = @CP_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', @CP_ID_MASTER, @OLD OUTPUT



	UPDATE	Book.CompetitionDetail
	SET		CP_ID_HALF	=	@HLF_ID,
			CP_NAME		=	@CP_NAME,
			CP_COUNT	=	@CP_COUNT,
			CP_BONUS	=	@CP_BONUS,
			CP_DATE		=	@CP_DATE
	WHERE	CP_ID		=	@CP_ID

	UPDATE	Book.Competition
	SET		CPMS_LAST = GETDATE()
	WHERE	CPMS_ID	=
		(
			SELECT	CP_ID_MASTER
			FROM	Book.CompetitionDetail
			WHERE	CP_ID	=	@CP_ID
		)


	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', @CP_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'COMPETITION', 'Редактирование', @CP_ID_MASTER, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Book].[COMPETITION_UPDATE] TO rl_competition_u;
GO
