USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[BOOK_DELIVERY_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Book].[BOOK_DELIVERY_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Book].[BOOK_DELIVERY_DELETED]
	@RC	INT	=	NULL	OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Book].[BookDeliveryDeleted]

	SELECT	@RC	=	@@ROWCOUNT
END
GO
