USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[COMPETITION_INSERT]
	@HLF_ID		UNIQUEIDENTIFIER,
	@CP_NAME	VARCHAR(100),
	@CP_COUNT	TINYINT,
	@CP_BONUS	MONEY,
	@CP_DATE	SMALLDATETIME,
	@CP_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', NULL, @OLD OUTPUT

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Book.Competition(CPMS_ID)
	OUTPUT INSERTED.CPMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Book.CompetitionDetail(
				CP_ID_HALF,
				CP_NAME,
				CP_COUNT,
				CP_BONUS,
				CP_DATE,
				CP_ID_MASTER
			)
	OUTPUT INSERTED.CP_ID INTO @TBL(ID)
	VALUES	(
				@HLF_ID,
				@CP_NAME,
				@CP_COUNT,
				@CP_BONUS,
				@CP_DATE,
				@MASTERID
			)

	SELECT	@CP_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'COMPETITION', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'COMPETITION', 'Новая запись', @MASTERID, @OLD, @NEW

END

GRANT EXECUTE ON [Book].[COMPETITION_INSERT] TO rl_competition_i;
GO