USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_DELIVERY_CHRONO]
	@BD_PRICE		MONEY,
	@BD_COUNT		SMALLINT,
	@BD_DATE		SMALLDATETIME,
	@BD_ID_MASTER	UNIQUEIDENTIFIER,
	@BD_END			SMALLDATETIME,
	@BD_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @BD_ID_MASTER, @OLD OUTPUT

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Book.BookDeliveryDetail
		SET		BD_END	=	@BD_END,
				BD_REF	=	2
		WHERE	BD_ID	=	@BD_ID

		UPDATE	Book.BookDelivery
		SET		BDMS_LAST	=	GETDATE()
		WHERE	BDMS_ID		=	@BD_ID_MASTER

		INSERT INTO
				Book.BookDeliveryDetail(
					BD_ID_MASTER,
					BD_PRICE,
					BD_COUNT,
					BD_DATE
				)
		OUTPUT INSERTED.BD_ID INTO @TBL
		VALUES	(
					@BD_ID_MASTER,
					@BD_PRICE,
					@BD_COUNT,
					@BD_DATE
				)

		SELECT	@BD_ID	=	ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @BD_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_DELIVERY', 'Хронологическое изменение', @BD_ID_MASTER, @OLD, @NEW

END

