USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Book].[BOOK_DELIVERY_UPDATE]
	@BD_ID		UNIQUEIDENTIFIER,
	@BD_PRICE	MONEY,
	@BD_COUNT	SMALLINT,
	@BD_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @BD_ID_MASTER UNIQUEIDENTIFIER

	SELECT @BD_ID_MASTER = BD_ID_MASTER
	FROM Book.BookDeliveryDetail
	WHERE BD_ID = @BD_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @BD_ID_MASTER, @OLD OUTPUT

	UPDATE	Book.BookDeliveryDetail
	SET		BD_PRICE	=	@BD_PRICE,
			BD_COUNT	=	@BD_COUNT,
			BD_DATE		=	@BD_DATE
	WHERE	BD_ID		=	@BD_ID

	UPDATE	Book.BookDelivery
	SET		BDMS_LAST = GETDATE()
	WHERE	BDMS_ID	=
		(
			SELECT	BD_ID_MASTER
			FROM	Book.BookDeliveryDetail
			WHERE	BD_ID	=	@BD_ID
		)


	EXEC Common.PROTOCOL_VALUE_GET 'BOOK_DELIVERY', @BD_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BOOK_DELIVERY', 'Редактирование', @BD_ID_MASTER, @OLD, @NEW

END

GO
