USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Claim].[CLAIM_SELECT]
	@BDATE	SMALLDATETIME = NULL,
	@EDATE	SMALLDATETIME =	NULL,
	@NUM	INT = NULL,
	@NAME	VARCHAR(100) = NULL,
	@SYS_ID	UNIQUEIDENTIFIER = NULL,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CLM_ID, CLM_DATE, CLM_NUM, 
		US_ID, US_ID_MASTER, US_NAME,
		CLD_ID, 
		CL_ID, CL_ID_MASTER, CL_NAME, 
		SYS_ID, SYS_ID_MASTER, SYS_SHORT, 
		DT_ID, DT_ID_MASTER, DT_SHORT, 		
		NT_ID, NT_ID_MASTER, NT_SHORT, 
		TT_ID, TT_ID_MASTER, TT_SHORT, 
		CLD_COUNT
	FROM Claim.ClaimFullView	
	WHERE	(CLM_DATE >= @BDATE OR @BDATE IS NULL) AND
			(CLM_DATE <= @EDATE OR @EDATE IS NULL) AND
			(CLM_NUM = @NUM OR @NUM IS NULL) AND
			(CL_NAME LIKE @NAME OR @NAME IS NULL) AND
			(SYS_ID_MASTER = @SYS_ID OR @SYS_ID IS NULL)
	
	SELECT @RC = @@ROWCOUNT
END
