USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Claim].[CLAIM_DETAIL_PROCESS]
	@CLD_ID	UNIQUEIDENTIFIER,
	@CLM_ID	UNIQUEIDENTIFIER,
	@CL_ID	UNIQUEIDENTIFIER,
	@VD_ID	UNIQUEIDENTIFIER,
	@SYS_ID	UNIQUEIDENTIFIER,
	@DT_ID	UNIQUEIDENTIFIER,
	@NT_ID	UNIQUEIDENTIFIER,
	@TT_ID	UNIQUEIDENTIFIER,
	@COUNT	TINYINT,
	@COMM	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	IF @CLD_ID IS NOT NULL
	BEGIN
		UPDATE Claim.ClaimDetail
		SET	CLD_ID_CLIENT =	@CL_ID,
			CLD_ID_VENDOR = @VD_ID,
			CLD_ID_SYSTEM = @SYS_ID,
			CLD_ID_TYPE = @DT_ID,
			CLD_ID_NET = @NT_ID,
			CLD_ID_TECH = @TT_ID,
			CLD_COUNT = @COUNT,
			CLD_COMMENT = @COMM
		WHERE CLD_ID = @CLD_ID
	END
	ELSE
	BEGIN
		INSERT INTO Claim.ClaimDetail
			(
				CLD_ID_CLAIM, CLD_ID_CLIENT, CLD_ID_VENDOR, CLD_ID_SYSTEM, CLD_ID_TYPE,
				CLD_ID_NET, CLD_ID_TECH, CLD_COUNT, CLD_COMMENT
			)
			VALUES
				(
					@CLM_ID, @CL_ID, @VD_ID, @SYS_ID, @DT_ID, @NT_ID, @TT_ID, @COUNT, @COMM
				)
	END
END
GO
GRANT EXECUTE ON [Claim].[CLAIM_DETAIL_PROCESS] TO rl_claim_w;
GO
