USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Claim].[CLAIM_DETAIL_DELETE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Claim].[CLAIM_DETAIL_DELETE]  AS SELECT 1')
GO
ALTER PROCEDURE [Claim].[CLAIM_DETAIL_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Claim.ClaimDetail
	WHERE CLD_ID IN
		(
			SELECT *
			FROM Common.TableFromList(@ID, ',')
		)
END
GO
GRANT EXECUTE ON [Claim].[CLAIM_DETAIL_DELETE] TO rl_claim_w;
GO
