USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Claim].[CLAIM_DETAIL_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CLD_ID, CLD_ID_CLAIM AS CLM_ID, 
		CL_ID_MASTER, CL_NAME, 
		VD_ID_MASTER, VD_NAME, 
		SYS_ID_MASTER, SYS_SHORT, SYS_ORDER, 
		DT_ID_MASTER, DT_SHORT, 
		NT_ID_MASTER, NT_SHORT, 
		TT_ID_MASTER, TT_SHORT, 
		CLD_COUNT, CLD_COMMENT
	FROM 
		Claim.ClaimDetailView
	WHERE CLD_ID_CLAIM = @ID
	ORDER BY CL_NAME, CL_ID_MASTER, SYS_ORDER
END
