USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Clients].[CLIENTS_INSERT]
	@CL_NAME	VARCHAR(150),
	@CL_DATE	SMALLDATETIME,
	@CL_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'CLIENTS', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)	

	DECLARE @MASTERID UNIQUEIDENTIFIER
	
	INSERT INTO Clients.Clients(CLMS_ID) 
	OUTPUT INSERTED.CLMS_ID INTO @TBL 
	DEFAULT VALUES

	
	SELECT	@MASTERID = ID 
	FROM	@TBL

	DELETE 
	FROM	@TBL	


	INSERT INTO 
			Clients.ClientDetail(
				CL_NAME,
				CL_DATE,
				CL_ID_MASTER
			)
	OUTPUT INSERTED.CL_ID INTO @TBL(ID)
	VALUES	(
				@CL_NAME,
				@CL_DATE,
				@MASTERID
			)
	
	SELECT	@CL_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'CLIENTS', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'CLIENTS', 'Новая запись', @MASTERID, @OLD, @NEW

END

