USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Clients].[VENDOR_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Clients].[VENDOR_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Clients].[VENDOR_SELECT]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Clients].[VendorActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Clients].[VENDOR_SELECT] TO rl_vendor_r;
GO
