USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Clients].[CLIENTS_CHRONO]
	@CL_NAME		VARCHAR(150),
	@CL_DATE		SMALLDATETIME,
	@CL_ID_MASTER	UNIQUEIDENTIFIER,
	@CL_END			SMALLDATETIME,
	@CL_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'CLIENTS', @CL_ID_MASTER, @OLD OUTPUT


	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Clients.ClientDetail
		SET		CL_END	=	@CL_END,
				CL_REF	=	2
		WHERE	CL_ID	=	@CL_ID

		UPDATE	Clients.Clients
		SET		CLMS_LAST	=	GETDATE()
		WHERE	CLMS_ID		=	@CL_ID_MASTER

		INSERT INTO
				Clients.ClientDetail(
					CL_ID_MASTER,
					CL_NAME,
					CL_DATE
				)
		OUTPUT INSERTED.CL_ID INTO @TBL
		VALUES	(
					@CL_ID_MASTER,
					@CL_NAME,
					@CL_DATE
				)

		SELECT	@CL_ID = ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'CLIENTS', @CL_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'CLIENTS', 'Хронологическое изменение', @CL_ID_MASTER, @OLD, @NEW

END

GRANT EXECUTE ON [Clients].[CLIENTS_CHRONO] TO rl_clients_u;
GO