USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Clients].[CLIENTS_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Clients].[ClientActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Clients].[CLIENTS_SELECT] TO rl_clients_r;
GO
