USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Clients].[VENDOR_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Clients].[VENDOR_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Clients].[VENDOR_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(VDMS_LAST)
	FROM	Clients.Vendors
END
GO
GRANT EXECUTE ON [Clients].[VENDOR_LAST] TO rl_vendor_r;
GO
