USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Clients].[VENDOR_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = VD_ID_MASTER
	FROM Clients.VendorDetail
	WHERE VD_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'VENDOR', @MASTERID, @OLD OUTPUT

	UPDATE	Clients.VendorDetail
	SET		VD_END	=	@DATE,
			VD_REF	=	3
	WHERE	VD_ID	=	@IDLIST
		

	EXEC Common.PROTOCOL_VALUE_GET 'VENDOR', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'VENDOR', 'Удаление', @MASTERID, @OLD, @NEW
END

