USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[PERIOD_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[PERIOD_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[PERIOD_SELECT]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*, DATEDIFF(MONTH, PR_BEGIN_DATE, GETDATE()) AS PR_DIFF
	FROM	[Common].[PeriodActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Common].[PERIOD_SELECT] TO rl_period_r;
GO
