USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[PERIOD_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[PERIOD_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[PERIOD_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Common].[PeriodDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Common].[PERIOD_DELETED] TO rl_period_r;
GO
