USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[HALF_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = HLF_ID_MASTER
	FROM Common.HalfDetail
	WHERE HLF_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'HALF', @MASTERID, @OLD OUTPUT

	UPDATE	Common.HalfDetail
	SET		HLF_END	=	@DATE,
			HLF_REF	=	3
	WHERE	HLF_ID	=	@IDLIST
		

	EXEC Common.PROTOCOL_VALUE_GET 'HALF', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'HALF', 'Удаление', @MASTERID, @OLD, @NEW
END

