USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[PERIOD_SELECT]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*, DATEDIFF(MONTH, PR_BEGIN_DATE, GETDATE()) AS PR_DIFF
	FROM	[Common].[PeriodActive]
	
	SELECT	@RC = @@ROWCOUNT
END
