USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Common].[PERIOD_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT = MAX(PRMS_LAST)
	FROM	Common.Period
END
GO
GRANT EXECUTE ON [Common].[PERIOD_LAST] TO rl_period_r;
GO
