USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[PERIOD_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = PR_ID_MASTER
	FROM Common.PeriodDetail
	WHERE PR_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERIOD', @MASTERID, @OLD OUTPUT

	UPDATE	Common.PeriodDetail
	SET		PR_END	=	@DATE,
			PR_REF	=	3
	WHERE	PR_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'PERIOD', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERIOD', 'Удаление', @MASTERID, @OLD, @NEW
		
END

