USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[PROTOCOL_INSERT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[PROTOCOL_INSERT]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[PROTOCOL_INSERT]
	@REF	VARCHAR(50),
	@NOTE	VARCHAR(100),
	@KEY	UNIQUEIDENTIFIER,
	@OLD	VARCHAR(MAX),
	@NEW	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF ISNULL(@OLD, '') <> ISNULL(@NEW, '')
	BEGIN
		INSERT INTO Security.Protocol
			(
				PTL_REFERENCE, PTL_REF_NOTE, PTL_KEY, PTL_OLD_VALUE, PTL_NEW_VALUE
			)
			VALUES (@REF, @NOTE, @KEY, @OLD, @NEW)
	END
END
GO
GRANT EXECUTE ON [Common].[PROTOCOL_INSERT] TO public;
GO
