USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Common].[PERIOD_INSERT]
	@PR_NAME		VARCHAR(50),
	@PR_BEGIN_DATE	SMALLDATETIME,
	@PR_END_DATE	SMALLDATETIME,
	@PR_DATE		SMALLDATETIME,
	@PR_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERIOD', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Common.Period(PRMS_ID)
	OUTPUT INSERTED.PRMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Common.PeriodDetail(
				PR_NAME,
				PR_BEGIN_DATE,
				PR_END_DATE,
				PR_DATE,
				PR_ID_MASTER
			)
	OUTPUT INSERTED.PR_ID INTO @TBL(ID)
	VALUES	(
				@PR_NAME,
				@PR_BEGIN_DATE,
				@PR_END_DATE,
				@PR_DATE,
				@MASTERID
			)

	SELECT	@PR_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'PERIOD', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERIOD', 'Новая запись', @MASTERID, @OLD, @NEW


END

GRANT EXECUTE ON [Common].[PERIOD_INSERT] TO rl_period_i;
GO