USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[WEIGHT_UPDATE]
	@WG_ID			UNIQUEIDENTIFIER,
	@WG_NAME		VARCHAR(50),
	@WG_ID_SYSTEM	UNIQUEIDENTIFIER,
	@WG_VALUE		DECIMAL(8, 4),
	@WG_DATE		SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @WG_ID_MASTER UNIQUEIDENTIFIER

	SELECT @WG_ID_MASTER = WG_ID_MASTER
	FROM Distr.WeightDetail
	WHERE WG_ID = @WG_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'WEIGHT', @WG_ID_MASTER, @OLD OUTPUT


	UPDATE	Distr.WeightDetail
	SET		WG_NAME			=	@WG_NAME,
			WG_ID_SYSTEM	=	@WG_ID_SYSTEM,
			WG_VALUE		=	@WG_VALUE,
			WG_DATE			=	@WG_DATE
	WHERE	WG_ID			=	@WG_ID

	UPDATE	Distr.Weight
	SET		WGMS_LAST	=	GETDATE()
	WHERE	WGMS_ID =
		(
			SELECT	WG_ID_MASTER
			FROM	Distr.WeightDetail
			WHERE	WG_ID	=	@WG_ID
		)

	EXEC Common.PROTOCOL_VALUE_GET 'WEIGHT', @WG_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'WEIGHT', 'Редактирование', @WG_ID_MASTER, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Distr].[WEIGHT_UPDATE] TO rl_weight_u;
GO