USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[HOST_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[HOST_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[HOST_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Distr].[HostDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Distr].[HOST_DELETED] TO rl_host_r;
GO
