USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[WEIGHT_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT = MAX(WGMS_LAST)
	FROM	Distr.Weight
END
GO
GRANT EXECUTE ON [Distr].[WEIGHT_LAST] TO rl_weight_r;
GO
