USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_DELETE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_DELETE]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_DELETE]
	@DH_ID		UNIQUEIDENTIFIER,
	@DH_END		SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	Distr.DistrStore
	SET		DS_LAST	=	GETDATE()
	WHERE	DS_ID	=
		(
			SELECT	DH_ID_DISTR
			FROM	Distr.DistrHistory
			WHERE	DH_ID	=	@DH_ID
		)

	UPDATE	Distr.DistrHistory
	SET		DH_END	=	@DH_END
	WHERE	DH_ID	=	@DH_ID


END
GO
GRANT EXECUTE ON [Distr].[DISTR_DELETE] TO rl_distr_store_d;
GO
