USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[WEIGHT_CHRONO]
	@WG_NAME		VARCHAR(50),
	@WG_ID_SYSTEM	UNIQUEIDENTIFIER,
	@WG_VALUE		DECIMAL(8, 4),
	@WG_DATE		SMALLDATETIME,
	@WG_ID_MASTER	UNIQUEIDENTIFIER,
	@WG_END			SMALLDATETIME,
	@WG_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'WEIGHT', @WG_ID_MASTER, @OLD OUTPUT


	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Distr.WeightDetail
		SET		WG_END	=	@WG_END,
				WG_REF	=	2
		WHERE	WG_ID	=	@WG_ID

		UPDATE	Distr.Weight
		SET		WGMS_LAST	=	GETDATE()
		WHERE	WGMS_ID		=	@WG_ID_MASTER

		INSERT INTO
				Distr.WeightDetail(
					WG_ID_MASTER,
					WG_NAME,
					WG_ID_SYSTEM,
					WG_VALUE,
					WG_DATE
				)
		OUTPUT INSERTED.WG_ID INTO @TBL
		VALUES	(
					@WG_ID_MASTER,
					@WG_NAME,
					@WG_ID_SYSTEM,
					@WG_VALUE,
					@WG_DATE
				)

		SELECT	@WG_ID = ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'WEIGHT', @WG_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'WEIGHT', 'Хронологическое изменение', @WG_ID_MASTER, @OLD, @NEW

END

GRANT EXECUTE ON [Distr].[WEIGHT_CHRONO] TO rl_weight_u;
GO