USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[NET_ALL_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT = MAX(LAST)
	FROM	Distr.NetAll
END
GO
GRANT EXECUTE ON [Distr].[NET_ALL_LAST] TO rl_distr_income_r;
GO
