USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Distr].[DISTR_EXCHANGE_INSERT]
	@TYPE	UNIQUEIDENTIFIER,
	@NUM	INT,
	@COMP	TINYINT,
	@SYS	UNIQUEIDENTIFIER,
	@OSYS	UNIQUEIDENTIFIER,
	@NSYS	UNIQUEIDENTIFIER,
	@NET	UNIQUEIDENTIFIER,
	@ONET	UNIQUEIDENTIFIER,
	@NNET	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@COM	NVARCHAR(150),
	@SH		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Distr.DistrIncome(ID_TYPE, NUM, COMP, ID_SYSTEM, ID_OLD_SYS, ID_NEW_SYS, ID_NET, ID_OLD_NET, ID_NEW_NET, INCOME_DATE, COMMENT, ID_SUBHOST)
		VALUES(@TYPE, @NUM, @COMP, @SYS, @OSYS, @NSYS, @NET, @ONET, @NNET, @DATE, @COM, @SH)
END
