USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Distr].[SYSTEM_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = SYS_ID_MASTER
	FROM Distr.SystemDetail
	WHERE SYS_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'SYSTEM', @MASTERID, @OLD OUTPUT

	UPDATE	Distr.SystemDetail
	SET		SYS_END	=	@DATE,
			SYS_REF	=	3
	WHERE	SYS_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'SYSTEM', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'SYSTEM', 'Удаление', @MASTERID, @OLD, @NEW
END

