USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[TECH_TYPE_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT = MAX(TTMS_LAST)
	FROM	Distr.TechType
END
GO
GRANT EXECUTE ON [Distr].[TECH_TYPE_LAST] TO rl_tech_type_r;
GO
