USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_NEW_INSERT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_NEW_INSERT]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_NEW_INSERT]
	@TYPE	UNIQUEIDENTIFIER,
	@NUM	INT,
	@COMP	TINYINT,
	@SYS	UNIQUEIDENTIFIER,
	@NET	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Distr.DistrIncome(ID_TYPE, NUM, COMP, ID_SYSTEM, ID_NET, INCOME_DATE)
		VALUES(@TYPE, @NUM, @COMP, @SYS, @NET, @DATE)
END
GO
GRANT EXECUTE ON [Distr].[DISTR_NEW_INSERT] TO rl_distr_income_w;
GO
