USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Distr].[HOST_UPDATE]
	@HST_ID		UNIQUEIDENTIFIER,
	@HST_NAME	VARCHAR(250),
	@HST_REG	VARCHAR(50),
	@HST_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @HST_ID_MASTER UNIQUEIDENTIFIER
	
	SELECT @HST_ID_MASTER = HST_ID_MASTER
	FROM Distr.HostDetail
	WHERE HST_ID = @HST_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', @HST_ID_MASTER, @OLD OUTPUT


	UPDATE	Distr.HostDetail
	SET		HST_NAME	=	@HST_NAME,
			HST_REG		=	@HST_REG,
			HST_DATE	=	@HST_DATE
	WHERE	HST_ID		=	@HST_ID 

	UPDATE	Distr.Hosts
	SET		HSTMS_LAST	=	GETDATE()
	WHERE	HSTMS_ID =
		(
			SELECT	HST_ID_MASTER
			FROM	Distr.HostDetail	
			WHERE	HST_ID	=	@HST_ID
		)

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', @HST_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'HOST', 'Редактирование', @HST_ID_MASTER, @OLD, @NEW

END

