USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_EXCHANGE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_EXCHANGE]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_EXCHANGE]
	@DH_ID		UNIQUEIDENTIFIER,
	@DS_ID		UNIQUEIDENTIFIER,
	@SYS_ID		UNIQUEIDENTIFIER,
	@DT_ID		UNIQUEIDENTIFIER,
	@NT_ID		UNIQUEIDENTIFIER,
	@TT_ID		UNIQUEIDENTIFIER,
	@DH_DATE	SMALLDATETIME,
	@DH_END		SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR', @DS_ID, @OLD OUTPUT




	UPDATE	Distr.DistrStore
	SET		DS_LAST	=	GETDATE()
	WHERE	DS_ID	=	@DS_ID

	UPDATE	Distr.DistrHistory
	SET		DH_END	=	@DH_END,
			DH_REF	=	2
	WHERE	DH_ID	=	@DH_ID

	INSERT INTO	Distr.DistrHistory
			(
				DH_ID_DISTR, DH_ID_SYSTEM, DH_ID_NET,
				DH_ID_TYPE, DH_ID_TECH, DH_DATE
			)
	VALUES
			(
				@DS_ID, @SYS_ID, @NT_ID, @DT_ID, @TT_ID, @DH_DATE
			)

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR', @DS_ID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'DISTR', 'Замена дистрибутива', @DS_ID, @OLD, @NEW


END
GO
GRANT EXECUTE ON [Distr].[DISTR_EXCHANGE] TO rl_distr_store_u;
GO
