USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[WEIGHT_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[WEIGHT_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[WEIGHT_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Distr].[WeightDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Distr].[WEIGHT_DELETED] TO rl_weight_r;
GO
