USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_TYPE_INSERT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_TYPE_INSERT]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_TYPE_INSERT]
	@DT_NAME	VARCHAR(50),
	@DT_SHORT	VARCHAR(50),
	@DT_REG		VARCHAR(50),
	@DT_DATE	SMALLDATETIME,
	@DT_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR_TYPE', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Distr.DistrType(DTMS_ID)
	OUTPUT INSERTED.DTMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Distr.DistrTypeDetail(
				DT_NAME,
				DT_SHORT,
				DT_REG,
				DT_DATE,
				DT_ID_MASTER
			)
	OUTPUT INSERTED.DT_ID INTO @TBL(ID)
	VALUES	(
				@DT_NAME,
				@DT_SHORT,
				@DT_REG,
				@DT_DATE,
				@MASTERID
			)

	SELECT	@DT_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR_TYPE', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'DISTR_TYPE', 'Новая запись', @MASTERID, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Distr].[DISTR_TYPE_INSERT] TO rl_distr_type_i;
GO
