USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[HOST_OVER_ONE]
	@IDLIST	VARCHAR(MAX),
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = HST_ID_MASTER
	FROM Distr.HostDetail
	WHERE HST_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', @MASTERID, @OLD OUTPUT

	UPDATE	Distr.HostDetail
	SET		HST_END	=	@DATE,
			HST_REF	=	3
	WHERE	HST_ID	=	@IDLIST

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'HOST', 'Удаление', @MASTERID, @OLD, @NEW
END

GO
