USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[TECH_TYPE_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[TECH_TYPE_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[TECH_TYPE_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Distr].[TechTypeDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Distr].[TECH_TYPE_DELETED] TO rl_tech_type_r;
GO
