USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[DISTR_INCOME_CHECK]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT COUNT(*) AS CNT
	FROM Distr.DistrIncome
END
GRANT EXECUTE ON [Distr].[DISTR_INCOME_CHECK] TO public;
GO