USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[NET_TYPE_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[NET_TYPE_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[NET_TYPE_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(NTMS_LAST)
	FROM	Distr.NetType
END
GO
GRANT EXECUTE ON [Distr].[NET_TYPE_LAST] TO rl_net_type_r;
GO
