USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Distr].[NET_TYPE_CHRONO]
	@NT_NAME		VARCHAR(50),
	@NT_SHORT		VARCHAR(50),
	@NT_FULL		VARCHAR(50),
	@NT_COEF		DECIMAL(8, 4),
	@NT_DATE		SMALLDATETIME,
	@NT_ID_MASTER	UNIQUEIDENTIFIER,
	@NT_END			SMALLDATETIME,
	@NT_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'NET_TYPE', @NT_ID_MASTER, @OLD OUTPUT


	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Distr.NetTypeDetail
		SET		NT_END	=	@NT_END,
				NT_REF	=	2
		WHERE	NT_ID	=	@NT_ID	

		UPDATE	Distr.NetType
		SET		NTMS_LAST	=	GETDATE()
		WHERE	NTMS_ID		=	@NT_ID_MASTER

		INSERT INTO 
				Distr.NetTypeDetail(
					NT_ID_MASTER,
					NT_NAME,
					NT_SHORT,
					NT_FULL,
					NT_COEF,
					NT_DATE
				)
		OUTPUT INSERTED.NT_ID INTO @TBL
		VALUES	(
					@NT_ID_MASTER,
					@NT_NAME,
					@NT_SHORT,
					@NT_FULL,
					@NT_COEF,
					@NT_DATE
				)

		SELECT	@NT_ID = ID
		FROM	@TBL		
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'NET_TYPE', @NT_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'NET_TYPE', 'Хронологическое изменение', @NT_ID_MASTER, @OLD, @NEW

END

