USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_INCOME_CHECK]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_INCOME_CHECK]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_INCOME_CHECK]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT COUNT(*) AS CNT
	FROM Distr.DistrIncome
END
GO
GRANT EXECUTE ON [Distr].[DISTR_INCOME_CHECK] TO public;
GO
