USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[DISTR_HISTORY_SELECT]
	@DS_ID	UNIQUEIDENTIFIER,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		DS_ID, 
		SYS_ID_MASTER, SYS_SHORT,
		DS_NUM, DS_COMP,
		NT_ID_MASTER, NT_NAME,
		DT_ID_MASTER, DT_NAME,
		TT_ID_MASTER, TT_NAME,
		DH_ID, DH_DATE, DH_END, DH_STR
	FROM	Distr.DistrAll
	WHERE	DS_ID	=	@DS_ID

	SELECT @RC = @@ROWCOUNT
END
GRANT EXECUTE ON [Distr].[DISTR_HISTORY_SELECT] TO rl_distr_store_r;
GO