USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	=	MAX(DS_LAST)
	FROM	Distr.DistrStore
END
GO
GRANT EXECUTE ON [Distr].[DISTR_LAST] TO rl_distr_store_r;
GO
