USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DISTR_TYPE_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[DISTR_TYPE_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[DISTR_TYPE_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT = MAX(DTMS_LAST)
	FROM	Distr.DistrType
END
GO
GRANT EXECUTE ON [Distr].[DISTR_TYPE_LAST] TO rl_distr_type_r;
GO
