USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[SUBHOST_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[SUBHOST_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[SUBHOST_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*, ID AS ID_MASTER
	FROM	[Distr].[Subhost]
	ORDER BY NAME

	SELECT	@RC = @@ROWCOUNT
END
GRANT EXECUTE ON [Distr].[SUBHOST_SELECT] TO rl_distr_income_rGO
GRANT EXECUTE ON [Distr].[SUBHOST_SELECT] TO rl_distr_income_r;
GO
