USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[DISTR_TYPE_CHRONO]
	@DT_NAME		VARCHAR(50),
	@DT_SHORT		VARCHAR(50),
	@DT_REG			VARCHAR(50),
	@DT_DATE		SMALLDATETIME,
	@DT_ID_MASTER	UNIQUEIDENTIFIER,
	@DT_END			SMALLDATETIME,
	@DT_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR_TYPE', @DT_ID_MASTER, @OLD OUTPUT

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Distr.DistrTypeDetail
		SET		DT_END	=	@DT_END,
				DT_REF	=	2
		WHERE	DT_ID	=	@DT_ID

		INSERT INTO
				Distr.DistrTypeDetail(
					DT_ID_MASTER,
					DT_NAME,
					DT_SHORT,
					DT_REG,
					DT_DATE
				)
		OUTPUT INSERTED.DT_ID INTO @TBL
		VALUES	(
					@DT_ID_MASTER,
					@DT_NAME,
					@DT_SHORT,
					@DT_REG,
					@DT_DATE
				)

		SELECT	@DT_ID = ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'DISTR_TYPE', @DT_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'DISTR_TYPE', 'Хронологическое изменение', @DT_ID_MASTER, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Distr].[DISTR_TYPE_CHRONO] TO rl_distr_type_u;
GO
