USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[DISTR_IMPORT_NEW_SELECT]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		CONVERT(BIT, 1) AS CHECKED,
		DF_ID, DT_ID_MASTER, DT_SHORT, DF_DISTR, DF_COMP, c.SYS_ID_MASTER, c.SYS_SHORT, d.ID AS NT_ID, d.SHORT AS NT_SHORT, DF_CREATE
	FROM
		[PC275-SQL\ALPHA].ClientDB.Din.DistrNewView	a
		LEFT OUTER JOIN Distr.DistrTypeActive b ON a.SST_REG = b.DT_REG
		LEFT OUTER JOIN Distr.SystemActive c ON c.SYS_REG = a.SystemBaseName
		LEFT OUTER JOIN Distr.NetAll d ON d.NET_COUNT = a.NT_NET AND d.TECH = a.NT_TECH
	WHERE DF_RIC = 20
		AND (DF_CREATE >= @BEGIN OR @BEGIN IS NULL)
		AND (DF_CREATE <= @END OR @END IS NULL)
		AND NOT EXISTS
			(
				SELECT *
				FROM Distr.DistrIncome z
				WHERE z.ID_TYPE = DT_ID_MASTER
					AND z.NUM = DF_DISTR
					AND z.COMP = DF_COMP
					AND z.ID_SYSTEM = c.SYS_ID_MASTER
					AND z.ID_NET = d.ID
					AND z.INCOME_DATE = DF_CREATE
			)
	ORDER BY DF_CREATE DESC, SystemOrder, DF_DISTR
END
GO
GRANT EXECUTE ON [Distr].[DISTR_IMPORT_NEW_SELECT] TO rl_distr_income_w;
GO