USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Distr].[HOST_CHRONO]
	@HST_NAME		VARCHAR(250),
	@HST_REG		VARCHAR(50),
	@HST_DATE		SMALLDATETIME,
	@HST_ID_MASTER	UNIQUEIDENTIFIER,
	@HST_END		SMALLDATETIME,
	@HST_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', @HST_ID_MASTER, @OLD OUTPUT

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Distr.HostDetail
		SET		HST_END	=	@HST_END,
				HST_REF	=	2
		WHERE	HST_ID	=	@HST_ID

		UPDATE	Distr.Hosts
		SET		HSTMS_LAST	=	GETDATE()
		WHERE	HSTMS_ID	=	@HST_ID_MASTER

		INSERT INTO
				Distr.HostDetail(
					HST_ID_MASTER,
					HST_NAME,
					HST_REG,
					HST_DATE
				)
		OUTPUT INSERTED.HST_ID INTO @TBL
		VALUES	(
					@HST_ID_MASTER,
					@HST_NAME,
					@HST_REG,
					@HST_DATE
				)

		SELECT	@HST_ID = ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION

	EXEC Common.PROTOCOL_VALUE_GET 'HOST', @HST_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'HOST', 'Хронологическое изменение', @HST_ID_MASTER, @OLD, @NEW

END

GRANT EXECUTE ON [Distr].[HOST_CHRONO] TO rl_host_u;
GO