USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[HOST_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Distr].[HOST_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Distr].[HOST_SELECT]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Distr].[HostActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Distr].[HOST_SELECT] TO rl_host_r;
GO
