USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_REPAY_DETAIL_SELECT]
	@IN_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ID_ID UNIQUEIDENTIFIER
	SELECT @ID_ID = ID_ID
	FROM Income.IncomeDetail
	WHERE ID_ID_INCOME = @IN_ID

	SELECT
		ID_ID, IN_ID,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		DT_ID, DT_ID_MASTER, DT_NAME,
		NT_ID, NT_ID_MASTER, NT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		ID_COUNT,
		(
			ID_DEL_PRICE * ID_COUNT -
				ISNULL((
					SELECT SUM(ID_DEL_SUM)
					FROM
						Income.IncomeDetail
					WHERE ID_ID IN
						(
							SELECT ID_ID
							FROM Income.IncomeDetailAllGet(a.ID_ID)
						)
				), 0)
		) AS ID_DEL_SUM, ID_DEL_PRICE, ID_DEL_DISCOUNT,
		ID_ACTION, ID_RESTORE, ID_EXCHANGE, 
		ID_FULL_DATE, ID_SALARY,
		PR_FIRST_ID, PR_FIRST_ID_MASTER, PR_FIRST_NAME,
		PR_FULL_ID, PR_FULL_ID_MASTER, PR_FULL_NAME,
		ID_MON_CNT,
		(
			ID_COUNT * ID_SUP_MONTH * ID_MON_CNT -
				ISNULL((
					SELECT SUM(ID_SUP_PRICE)
					FROM
						Income.IncomeDetail
					WHERE ID_ID IN
						(
							SELECT ID_ID
							FROM Income.IncomeDetailAllGet(a.ID_ID)
						)
				), 0)
		) AS ID_SUP_PRICE,
		ID_SUP_DISCOUNT, ID_SUP_MONTH, 
		ID_LOCK, ID_REPAY, ID_NOTE
	FROM Income.IncomeDetailFullView a
	WHERE ID_ID IN
		(
			SELECT ID_ID
			FROM Income.IncomeMasterGet(@ID_ID)
		)
END
GO
GRANT EXECUTE ON [Income].[INCOME_REPAY_DETAIL_SELECT] TO rl_income_w;
GO
