USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Income].[INCOME_PERSONAL_SET]
	@ID_ID		NVARCHAR(MAX),
	@PER_ID		UNIQUEIDENTIFIER,
	@PERCENT	DECIMAL(8, 4),
	@PERCENT2	DECIMAL(8, 4) = NULL
AS
BEGIN
	SET NOCOUNT ON;	

	DECLARE @ID UNIQUEIDENTIFIER

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)


	DECLARE ID CURSOR LOCAL FOR
		SELECT	ID
		FROM	Common.TableFromList(@ID_ID, ',')
	
	OPEN ID

	FETCH NEXT FROM ID INTO @ID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_PERSONAL', @ID, @OLD OUTPUT

		INSERT INTO Income.IncomePersonal(IP_ID_INCOME, IP_ID_PERSONAL, IP_PERCENT, IP_PERCENT2)
		VALUES (@ID, @PER_ID, @PERCENT, @PERCENT2)
				
		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_PERSONAL', @ID, @NEW OUTPUT

		EXEC Common.PROTOCOL_INSERT 'INCOME_PERSONAL', 'Новая запись', @ID, @OLD, @NEW

		FETCH NEXT FROM ID INTO @ID
	END

	CLOSE ID
	DEALLOCATE ID
END
