USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_BOOK_PERSONAL_SET]
	@IB_ID	VARCHAR(MAX),
	@PER_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	DECLARE @ID		UNIQUEIDENTIFIER

	DECLARE ID CURSOR LOCAL FOR
		SELECT ID
		FROM Common.TableFromList(@IB_ID, ',')

	OPEN ID

	FETCH NEXT FROM ID INTO @ID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_BOOK', @ID, @OLD OUTPUT

		UPDATE	Income.IncomeBook
		SET		IB_ID_PERSONAL	=	@PER_ID
		WHERE	IB_ID	= @ID

		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_BOOK', @ID, @NEW OUTPUT

		EXEC Common.PROTOCOL_INSERT 'INCOME_BOOK', 'Указание сотрудника ГК', @ID, @OLD, @NEW

		FETCH NEXT FROM ID INTO @ID
	END

	CLOSE ID
	DEALLOCATE ID

END
GO
GRANT EXECUTE ON [Income].[INCOME_BOOK_PERSONAL_SET] TO rl_income_book_personal;
GO
