USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Income].[INCOME_TO_INSTALL_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Income].[INCOME_TO_INSTALL_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Income].[INCOME_TO_INSTALL_SELECT]
	@RC		INT	= NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		IN_ID, IN_DATE, IN_PAY,
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_ID, VD_ID_MASTER, VD_NAME,
		ID_ID,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		DT_ID, DT_ID_MASTER, DT_NAME,
		NT_ID, NT_ID_MASTER, NT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		ID_COUNT,
		ID_DEL_SUM, ID_DEL_PRICE, ID_DEL_DISCOUNT,
		ID_ACTION, ID_RESTORE, ID_EXCHANGE, 
		ID_FULL_DATE,
		PR_FIRST_ID, PR_FIRST_ID_MASTER, PR_FIRST_NAME,
		ID_MON_CNT, ID_SUP_PRICE, ID_SUP_DISCOUNT,
		ID_SUP_MONTH,
		ID_PREPAY,
		ID_SUP_CONTRACT, ID_SUP_DATE,
		ID_LOCK
	FROM Income.IncomeFullView
	WHERE
		NOT EXISTS
			(
				SELECT *
				FROM Install.InstallDetail
				WHERE ID_ID = IND_ID_INCOME
			) AND ISNULL(ID_REPAY, 0) = 0
		--AND ID_LOCK = 0

	SELECT @RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Income].[INCOME_TO_INSTALL_SELECT] TO rl_income_r;
GO
