USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_MASTER_SELECT]
	@CL_ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

    SELECT *
	FROM Income.IncomeFullView
	WHERE CL_ID_MASTER = @CL_ID
		--AND ID_REPAY = 0
	ORDER BY IN_DATE, SYS_ORDER

END
GO
GRANT EXECUTE ON [Income].[INCOME_MASTER_SELECT] TO rl_income_w;
GO
