USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Income].[INCOME_BOOK_FREE_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Income].[INCOME_BOOK_FREE_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Income].[INCOME_BOOK_FREE_SELECT]
	@RC		INT				= NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		IN_ID, IN_DATE, IN_PAY,
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_ID, VD_ID_MASTER, VD_NAME,
		IB_ID, IB_COUNT, IB_PRICE, IB_SUM, IB_FULL_PAY,
		HLF_ID, HLF_ID_MASTER, HLF_NAME,
		IB_LOCK, IB_NOTE
	FROM Income.IncomeBookFullView
	WHERE NOT EXISTS
		(
			SELECT	*
			FROM	Book.PersonalBook
			WHERE	PB_ID_IB = IB_ID
		)



	SELECT @RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Income].[INCOME_BOOK_FREE_SELECT] TO rl_income_book_r;
GO
