USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Income].[INCOME_DETAIL_INSERT]
	@IN_ID				UNIQUEIDENTIFIER,
	@SYS_ID				UNIQUEIDENTIFIER,
	@DT_ID				UNIQUEIDENTIFIER,
	@NT_ID				UNIQUEIDENTIFIER,
	@TT_ID				UNIQUEIDENTIFIER,	
	@ID_COUNT			TINYINT,
	@ID_DEL_SUM			MONEY,
	@ID_DEL_PRICE		MONEY,
	@ID_DEL_DISCOUNT	DECIMAL(8, 4),
	@ID_ACTION			BIT,
	@ID_RESTORE			BIT,
	@ID_EXCHANGE		BIT,
	--@ID_ID_FULL_PAY		UNIQUEIDENTIFIER,
	--@ID_FULL_DATE		SMALLDATETIME,
	@ID_ID_FIRST_MON	UNIQUEIDENTIFIER,	
	@ID_MON_CNT			TINYINT,
	@ID_SUP_PRICE		MONEY,
	@ID_SUP_DISCOUNT	DECIMAL(8, 4),
	@ID_SUP_MONTH		MONEY,
	--@ID_PREPAY			BIT,
	--@ID_SUP_CONTRACT	SMALLDATETIME,
	--@ID_SUP_DATE		SMALLDATETIME,	
	@ID_LOCK			BIT,
	@ID_REPAY			BIT,
	@ID_NOTE			VARCHAR(250),
	@ID_ID_FULL_PAY		UNIQUEIDENTIFIER = NULL,
	@ID_SALARY			MONEY = NULL,
	@ID_INSTALL			BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'INCOME_DETAIL', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
	DECLARE @ID_ID UNIQUEIDENTIFIER

	INSERT INTO Income.IncomeDetail(
			ID_ID_INCOME, ID_ID_SYSTEM, ID_ID_TYPE, ID_ID_NET, ID_ID_TECH,
			ID_COUNT, ID_DEL_SUM, ID_DEL_PRICE, ID_DEL_DISCOUNT,
			ID_ACTION, ID_RESTORE, ID_EXCHANGE,
			ID_ID_FIRST_MON, ID_ID_FULL_PAY,
			ID_MON_CNT, ID_SUP_PRICE, ID_SUP_DISCOUNT,
			ID_SUP_MONTH, ID_REPAY, ID_LOCK, ID_NOTE,
			ID_SALARY, ID_INSTALL
			/*ID_SUP_CONTRACT, ID_SUP_DATE, ID_PREPAY*/)	
	OUTPUT INSERTED.ID_ID INTO @TBL
	VALUES(
			@IN_ID, @SYS_ID, @DT_ID, @NT_ID, @TT_ID,
			@ID_COUNT, @ID_DEL_SUM, @ID_DEL_PRICE, @ID_DEL_DISCOUNT,
			@ID_ACTION, @ID_RESTORE, @ID_EXCHANGE,
			@ID_ID_FIRST_MON, @ID_ID_FULL_PAY,
			@ID_MON_CNT, @ID_SUP_PRICE, @ID_SUP_DISCOUNT,
			@ID_SUP_MONTH, ISNULL(@ID_REPAY, 0), @ID_LOCK, @ID_NOTE,
			@ID_SALARY, @ID_INSTALL
			/*@ID_SUP_CONTRACT, @ID_SUP_DATE, @ID_PREPAY*/
			)

	
	SELECT @ID_ID = ID
	FROM @TBL	

	IF (
			SELECT SYS_MAIN
			FROM Income.IncomeFullView 
			WHERE ID_ID = @ID_ID 
				AND ID_RESTORE = 0 
				AND ID_EXCHANGE = 0 
				AND ID_REPAY = 0
		) = 1
		UPDATE Income.IncomeDetail
		SET ID_COLOR = 65535
		WHERE ID_ID = @ID_ID
	ELSE IF 
		(
			SELECT SYS_MAIN
			FROM Income.IncomeFullView 
			WHERE ID_ID = @ID_ID 
				AND ID_RESTORE = 1 
				AND ID_EXCHANGE = 0 
				AND ID_REPAY = 0
		) = 1
		UPDATE Income.IncomeDetail
		SET ID_COLOR = 16711935
		WHERE ID_ID = @ID_ID


	EXEC Income.INCOME_DETAIL_FULL_DATE @ID_ID

	EXEC Common.PROTOCOL_VALUE_GET 'INCOME_DETAIL', @ID_ID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'INCOME_DETAIL', '¬вод оплаты', @ID_ID, @OLD, @NEW


	IF ISNULL(@ID_REPAY, 0) = 0 AND ISNULL(@ID_INSTALL, 1) = 1
		EXEC Install.INSTALL_FROM_INCOME_INSERT @ID_ID	
END
