USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE Income.INCOME_SET_CALC
	@ID_ID	VARCHAR(MAX),
	@CALC	BIT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	DECLARE @ID		UNIQUEIDENTIFIER

	DECLARE ID CURSOR LOCAL FOR
		SELECT ID
		FROM Common.TableFromList(@ID_ID, ',')

	OPEN ID

	FETCH NEXT FROM ID INTO @ID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_DETAIL', @ID, @OLD OUTPUT

		UPDATE	Income.IncomeDetail
		SET		ID_CALC		=	@CALC
		WHERE	ID_ID	= @ID

		EXEC Common.PROTOCOL_VALUE_GET 'INCOME_DETAIL', @ID, @NEW OUTPUT

		EXEC Common.PROTOCOL_INSERT 'INCOME_DETAIL', '”казание признака "печатать"', @ID, @OLD, @NEW

		FETCH NEXT FROM ID INTO @ID
	END

	CLOSE ID
	DEALLOCATE ID

END
GO
GRANT EXECUTE ON [Income].[INCOME_SET_CALC] TO rl_income_prepay_dates;
GO
