USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_PERCENT_CHANGE]
	@IP_ID VARCHAR(MAX),
	@PER_VALUE DECIMAL(8, 4)
AS
BEGIN
	SET NOCOUNT ON;

    UPDATE Income.IncomePersonal
	SET IP_PERCENT = @PER_VALUE
	WHERE IP_ID IN
		(
			SELECT ID
			FROM Common.TableFromList(@IP_ID, ',')
		)
END
GO
GRANT EXECUTE ON [Income].[INCOME_PERCENT_CHANGE] TO rl_income_personal;
GO