USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_BOOK_UPDATE]
	@IB_ID			UNIQUEIDENTIFIER,
	@IB_DATE		SMALLDATETIME,
	@IB_ID_CLIENT	UNIQUEIDENTIFIER,
	@IB_ID_VENDOR	UNIQUEIDENTIFIER,
	@IB_PRICE		MONEY,
	@IB_SUM			MONEY,
	@IB_COUNT		TINYINT,
	@IB_FULL_PAY	SMALLDATETIME,
	@IB_ID_HALF		UNIQUEIDENTIFIER,
	@IB_ID_PERSONAL	UNIQUEIDENTIFIER,
	@IB_LOCK		BIT,
	@IB_NOTE		VARCHAR(250)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'INCOME_BOOK', @IB_ID, @OLD OUTPUT

	UPDATE	Income.IncomeBook
	SET		IB_DATE			=	@IB_DATE,
			IB_ID_CLIENT	=	@IB_ID_CLIENT,
			IB_ID_VENDOR	=	@IB_ID_VENDOR,
			IB_PRICE		=	@IB_PRICE,
			IB_SUM			=	@IB_SUM,
			IB_COUNT		=	@IB_COUNT,
			IB_FULL_PAY		=	@IB_FULL_PAY,
			IB_ID_HALF		=	@IB_ID_HALF,
			IB_ID_PERSONAL	=	@IB_ID_PERSONAL,
			IB_LOCK			=	@IB_LOCK,
			IB_NOTE			=	@IB_NOTE
	WHERE	IB_ID		=	@IB_ID

	EXEC Common.PROTOCOL_VALUE_GET 'INCOME_BOOK', @IB_ID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'INCOME_BOOK', 'Изменение оплаты ГК', @IB_ID, @OLD, @NEW
END
GO
GRANT EXECUTE ON [Income].[INCOME_BOOK_UPDATE] TO rl_income_book_u;
GO