USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Income].[INCOME_SET_REPAY]
	@MASTER UNIQUEIDENTIFIER,
	@DETAIL UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

    UPDATE Income.Incomes
	SET IN_ID_INCOME = @MASTER
	WHERE IN_ID = @DETAIL

END
GO
GRANT EXECUTE ON [Income].[INCOME_SET_REPAY] TO rl_income_w;
GO
