USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Income].[INCOME_DELETE]
	@IN_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @DEST VARCHAR(MAX)

	SET @DEST = ''

	SELECT	@DEST = @DEST + CONVERT(VARCHAR(50), ID_ID) + ','
	FROM	Income.IncomeDetail
	WHERE	ID_ID_INCOME	=	@IN_ID

	IF @DEST <> ''
		SET @DEST = LEFT(@DEST, LEN(@DEST) - 1)

	EXEC Income.INCOME_DETAIL_DELETE @DEST

	DELETE
	FROM	Income.Incomes
	WHERE	IN_ID	=	@IN_ID	
END
