USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Install].[INSTALL_DETAIL_SELECT]
	@INS_ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		IND_ID, INS_ID, 
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		DT_ID, DT_ID_MASTER, DT_NAME,
		NT_ID, NT_ID_MASTER, NT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		IND_LOCK,
		ID_ID
	FROM Install.InstallDetailFullView
	WHERE INS_ID = @INS_ID
END
GO
GRANT EXECUTE ON [Install].[INSTALL_DETAIL_SELECT] TO rl_install_r;
GO