USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Install].[INSTALL_ACT_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Install].[INSTALL_ACT_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Install].[INSTALL_ACT_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Install].[InstallActActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Install].[INSTALL_ACT_SELECT] TO rl_install_act_r;
GO
