USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Install].[INSTALL_ACT_INSERT]
	@IA_NAME	VARCHAR(50),
	@IA_NORM	BIT,
	@IA_DATE	SMALLDATETIME,
	@IA_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'INSTALL_ACT', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)	

	DECLARE @MASTERID UNIQUEIDENTIFIER
	
	INSERT INTO Install.InstallAct(IAMS_ID) 
	OUTPUT INSERTED.IAMS_ID INTO @TBL 
	DEFAULT VALUES

	
	SELECT	@MASTERID = ID 
	FROM	@TBL

	DELETE 
	FROM	@TBL	


	INSERT INTO 
			Install.InstallActDetail(
				IA_NAME,
				IA_NORM,
				IA_DATE,
				IA_ID_MASTER
			)
	OUTPUT INSERTED.IA_ID INTO @TBL(ID)
	VALUES	(
				@IA_NAME,
				@IA_NORM,
				@IA_DATE,
				@MASTERID
			)
	
	SELECT	@IA_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'INSTALL_ACT', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'INSTALL_ACT', 'Новая запись', @MASTERID, @OLD, @NEW

END
