USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Install].[INSTALL_COMMENT_ADD]
	@IND_ID		VARCHAR(MAX),
	@IC_USER	VARCHAR(50),
	@IC_TEXT	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Install.InstallComments(IC_ID_IND, IC_USER, IC_TEXT)
		SELECT ID, @IC_USER, @IC_TEXT
		FROM Common.TableFromList(@IND_ID, ',')
END
GRANT EXECUTE ON [Install].[INSTALL_COMMENT_ADD] TO rl_install_comment_i;
GO