USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Install].[INSTALL_UPDATE]
	@INS_ID		UNIQUEIDENTIFIER,
	@CL_ID		UNIQUEIDENTIFIER,
	@VD_ID		UNIQUEIDENTIFIER,
	@INS_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'INSTALL', @INS_ID, @OLD OUTPUT

	UPDATE	Install.Install
	SET		INS_ID_CLIENT	=	@CL_ID,
			INS_ID_VENDOR	=	@VD_ID,
			INS_DATE		=	ISNULL(@INS_DATE, INS_DATE)
	WHERE	INS_ID			=	@INS_ID


	EXEC Common.PROTOCOL_VALUE_GET 'INSTALL', @INS_ID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'INSTALL', 'Редактирование', @INS_ID, @OLD, @NEW
END
GO
GRANT EXECUTE ON [Install].[INSTALL_UPDATE] TO rl_install_u;
GO