USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Install].[INSTALL_BOX_DATE_SET]
	@IND_ID		VARCHAR(MAX),
	@BOX_DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	Install.InstallDetail
	SET		IND_BOX_DATE	=	@BOX_DATE
	WHERE	IND_ID	IN
		(
			SELECT ID
			FROM Common.TableFromList(@IND_ID, ',')
		)
END
