USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Install].[INSTALL_PERSONAL_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM Personal.PersonalLast
	ORDER BY PER_NAME
END
GO
GRANT EXECUTE ON [Install].[INSTALL_PERSONAL_SELECT] TO rl_install_personal;
GO