USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Install].[INSTALL_COMMENT_UPDATE]
	@IC_ID		UNIQUEIDENTIFIER,
	@IC_TEXT	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	Install.InstallComments
	SET		IC_TEXT	=	@IC_TEXT
	WHERE	IC_ID	=	@IC_ID
END
