USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Install].[INSTALL_SELECT]
	@INS_ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		INS_ID, INS_DATE,
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_ID, VD_ID_MASTER, VD_NAME
	FROM Install.InstallMasterView
	WHERE INS_ID = @INS_ID
END
GO
GRANT EXECUTE ON [Install].[INSTALL_SELECT] TO rl_install_r;
GO
