USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Install].[INSTALL_ACT_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Install].[INSTALL_ACT_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Install].[INSTALL_ACT_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Install].[InstallActDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Install].[INSTALL_ACT_DELETED] TO rl_install_act_r;
GO
