USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Meta].[FIELDS_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT FL_ID, FL_NAME, FL_CAPTION, FL_WIDTH, FL_VISIBLE, FL_SYSTEM
	FROM Meta.Fields
END
