USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[PERSONAL_INSERT]
	@PER_ID_DEP		UNIQUEIDENTIFIER,
	@PER_NAME		VARCHAR(150),
	@PER_ID_TYPE	UNIQUEIDENTIFIER,
	@PER_DATE		SMALLDATETIME,
	@PER_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Personal.Personals(PERMS_ID)
	OUTPUT INSERTED.PERMS_ID INTO @TBL
	DEFAULT VALUES

	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Personal.PersonalDetail(
				PER_ID_DEP,
				PER_NAME,
				PER_ID_TYPE,
				PER_DATE,
				PER_ID_MASTER
			)
	OUTPUT INSERTED.PER_ID INTO @TBL(ID)
	VALUES	(
				@PER_ID_DEP,
				@PER_NAME,
				@PER_ID_TYPE,
				@PER_DATE,
				@MASTERID
			)

	SELECT	@PER_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERSONAL', 'Новая запись', @MASTERID, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Personal].[PERSONAL_INSERT] TO rl_personal_i;
GO
