USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[DEPARTMENT_INSERT]
	@DP_NAME	VARCHAR(50),
	@DP_FULL	VARCHAR(250),
	@DP_DATE	SMALLDATETIME,
	@DP_ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'DEPARTMENT', NULL, @OLD OUTPUT


	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Personal.Department(DPMS_ID)
	OUTPUT INSERTED.DPMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Personal.DepartmentDetail(
				DP_NAME,
				DP_FULL,
				DP_DATE,
				DP_ID_MASTER
			)
	OUTPUT INSERTED.DP_ID INTO @TBL(ID)
	VALUES	(
				@DP_NAME,
				@DP_FULL,
				@DP_DATE,
				@MASTERID
			)

	SELECT	@DP_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'DEPARTMENT', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'DEPARTMENT', 'Новая запись', @MASTERID, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Personal].[DEPARTMENT_INSERT] TO rl_department_i;
GO
