USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Personal].[DEPARTMENT_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Personal].[DEPARTMENT_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Personal].[DEPARTMENT_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Personal].[DepartmentActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Personal].[DEPARTMENT_SELECT] TO rl_department_r;
GO
