USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[PERSONAL_OVER_ONE]
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = PER_ID_MASTER
	FROM Personal.PersonalDetail
	WHERE PER_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', @MASTERID, @OLD OUTPUT

	UPDATE	Personal.PersonalDetail
	SET		PER_END	=	@DATE,
			PER_REF	=	3
	WHERE	PER_ID	=	@IDLIST


	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERSONAL', 'Удаление', @MASTERID, @OLD, @NEW
END

