USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[PERSONAL_TYPE_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Personal].[PersonalTypeActive]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Personal].[PERSONAL_TYPE_SELECT] TO rl_personal_type_r;
GO
