USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Personal].[PERSONAL_TYPE_DELETED]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Personal].[PERSONAL_TYPE_DELETED]  AS SELECT 1')
GO
ALTER PROCEDURE [Personal].[PERSONAL_TYPE_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Personal].[PersonalTypeDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Personal].[PERSONAL_TYPE_DELETED] TO rl_personal_type_r;
GO
