USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[PERSONAL_UPDATE]
	@PER_ID			UNIQUEIDENTIFIER,
	@PER_ID_DEP		UNIQUEIDENTIFIER,
	@PER_NAME		VARCHAR(150),
	@PER_ID_TYPE	UNIQUEIDENTIFIER,
	@PER_DATE		SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @PER_ID_MASTER UNIQUEIDENTIFIER

	SELECT @PER_ID_MASTER = PER_ID_MASTER
	FROM Personal.PersonalDetail
	WHERE PER_ID = @PER_ID

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', @PER_ID_MASTER, @OLD OUTPUT


	UPDATE	Personal.PersonalDetail
	SET		PER_ID_DEP	=	@PER_ID_DEP,
			PER_NAME	=	@PER_NAME,
			PER_ID_TYPE	=	@PER_ID_TYPE,
			PER_DATE	=	@PER_DATE
	WHERE	PER_ID		=	@PER_ID

	UPDATE	Personal.Personals
	SET		PERMS_LAST	=	GETDATE()
	WHERE	PERMS_ID	=
		(
			SELECT	PER_ID_MASTER
			FROM	Personal.PersonalDetail
			WHERE	PER_ID	=	@PER_ID
		)

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL', @PER_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERSONAL', 'Редактирование', @PER_ID_MASTER, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Personal].[PERSONAL_UPDATE] TO rl_personal_u;
GO
