USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Personal].[DEPARTMENT_CHRONO]
	@DP_NAME		VARCHAR(50),
	@DP_FULL		VARCHAR(250),
	@DP_DATE		SMALLDATETIME,
	@DP_ID_MASTER	UNIQUEIDENTIFIER,
	@DP_END			SMALLDATETIME,
	@DP_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'DEPARTMENT', @DP_ID_MASTER, @OLD OUTPUT

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	DECLARE @MASTERID UNIQUEIDENTIFIER


	BEGIN TRANSACTION

	BEGIN TRY
		UPDATE	Personal.DepartmentDetail
		SET		DP_END	=	@DP_END,
				DP_REF	=	2
		WHERE	DP_ID	=	@DP_ID

		UPDATE	Personal.Department
		SET		DPMS_LAST	=	GETDATE()
		WHERE	DPMS_ID		=	@DP_ID_MASTER

		INSERT INTO
				Personal.DepartmentDetail(
					DP_ID_MASTER,
					DP_NAME,
					DP_FULL,
					DP_DATE
				)
		OUTPUT INSERTED.DP_ID INTO @TBL
		VALUES	(
					@DP_ID_MASTER,
					@DP_NAME,
					@DP_FULL,
					@DP_DATE
				)

		SELECT	@DP_ID = ID
		FROM	@TBL
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
	        ROLLBACK TRANSACTION
	END CATCH

	IF @@TRANCOUNT > 0
        COMMIT TRANSACTION


	EXEC Common.PROTOCOL_VALUE_GET 'DEPARTMENT', @DP_ID_MASTER, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'DEPARTMENT', 'Хронологическое изменение', @DP_ID_MASTER, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Personal].[DEPARTMENT_CHRONO] TO rl_department_u;
GO