USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Personal].[PERSONAL_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Personal].[PERSONAL_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Personal].[PERSONAL_SELECT]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT
		PER_ID, PER_ID_MASTER, PER_NAME, PER_EMAIL,
		PT_ID_MASTER, PT_NAME,
		DP_ID_MASTER, DP_NAME,
		PER_DATE, PER_END
	FROM
		[Personal].[PersonalActive]											INNER JOIN
		[Personal].[PersonalTypeLast]	ON	PT_ID_MASTER	=	PER_ID_TYPE	INNER JOIN
		[Personal].[DepartmentLast]		ON	DP_ID_MASTER	=	PER_ID_DEP

	SELECT @RC = @@ROWCOUNT
END
GO
GRANT EXECUTE ON [Personal].[PERSONAL_SELECT] TO rl_personal_r;
GO
