USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Personal].[PERSONAL_FROM_CLIENT_REFRESH]	
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

    DECLARE @DEP_ID UNIQUEIDENTIFIER
	DECLARE @TYPE_ID UNIQUEIDENTIFIER

	SELECT @DEP_ID = DP_ID_MASTER
	FROM Personal.DepartmentActive
	WHERE DP_NAME = 'Œ»—'

	SELECT @TYPE_ID = PT_ID_MASTER
	FROM Personal.PersonalTypeActive
	WHERE PT_NAME = '—»'

	DECLARE A CURSOR LOCAL FOR
		SELECT ServiceName
		FROM ClientDB.dbo.ServiceTable
		WHERE NOT EXISTS
			(
				SELECT *
				FROM FirstInstall.Personal.PersonalLast
				WHERE PER_ID_DEP = @DEP_ID
					--AND PER_ID_TYPE = @TYPE_ID
					AND PER_NAME = ServiceName
			)

	DECLARE @NAME VARCHAR(100)
	DECLARE @DATE SMALLDATETIME

	SET @DATE = GETDATE()

	OPEN A

	FETCH NEXT FROM A INTO @NAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC Personal.PERSONAL_INSERT @DEP_ID, @NAME, @TYPE_ID, @DATE, NULL

		FETCH NEXT FROM A INTO @NAME
	END

	CLOSE A
	DEALLOCATE A
END
