USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_DETAIL_DELETE]
	@PSD_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM	Salary.PersonalSalaryDetail
	WHERE	PSD_ID	=	@PSD_ID
END
GO
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_DETAIL_DELETE] TO rl_salary_w;
GO