USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Salary].[BONUS_CONDITION_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Salary].[BONUS_CONDITION_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Salary].[BONUS_CONDITION_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	= MAX(BCMS_LAST)
	FROM	Salary.BonusCondition
END
GO
GRANT EXECUTE ON [Salary].[BONUS_CONDITION_LAST] TO rl_bonus_condition_r;
GO
