USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Salary].[PERSONAL_SALARY_LOCK]
	@PS_ID	VARCHAR(MAX),
	@LOCK	BIT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL_SALARY', @PS_ID, @OLD OUTPUT

	UPDATE	Salary.PersonalSalary
	SET		PS_LOCK	=	@LOCK
	WHERE	PS_ID	=	@PS_ID

	EXEC Common.PROTOCOL_VALUE_GET 'PERSONAL_SALARY', @PS_ID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'PERSONAL_SALARY', 'Блокировка', @PS_ID, @OLD, @NEW
END
