USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_DETAIL_CALC]
	@PS_ID			UNIQUEIDENTIFIER,
	@ID_ID			UNIQUEIDENTIFIER,
	@PSD_PRICE		MONEY,
	@PSD_SUM		MONEY,
	@PSD_COUNT		TINYINT,
	@PSD_PERCENT	DECIMAL(8, 4),
	@PSD_MON		TINYINT,
	@PSD_TOTAL		MONEY,
	@PSD_PAYED		BIT,
	@PSD_SECOND		BIT,
	@PSD_PAY_DATE	SMALLDATETIME = NULL
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Salary.PersonalSalaryDetail(PSD_ID_MASTER, PSD_ID_INCOME, PSD_PRICE, PSD_SUM, PSD_COUNT, PSD_PERCENT, PSD_MON, PSD_TOTAL, PSD_PAYED, PSD_SECOND, PSD_PAY_DATE)
	VALUES (@PS_ID, @ID_ID, @PSD_PRICE, @PSD_SUM, @PSD_COUNT, @PSD_PERCENT, @PSD_MON, @PSD_TOTAL, @PSD_PAYED, @PSD_SECOND, @PSD_PAY_DATE)
END
GO
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_DETAIL_CALC] TO rl_salary_w;
GO