USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Salary].[PERSONAL_SALARY_SUMMARY_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Salary].[PERSONAL_SALARY_SUMMARY_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_SUMMARY_SELECT]
	@PR_ID	UNIQUEIDENTIFIER,
	@VD_ID	UNIQUEIDENTIFIER,
	@PT_ID	UNIQUEIDENTIFIER = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @PT_ID IS NULL
		SELECT
			ROW_NUMBER() OVER (ORDER BY PER_NAME) AS NUM,
			PER_NAME, PS_DATE,
			CAST(ROUND((
				SELECT SUM(PSD_TOTAL)
				FROM Salary.PersonalSalaryDetail
				WHERE PSD_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_SALE,
			PS_SALARY,
			--0 AS PS_VISIT,
			--0 AS PS_BONUS,
			CAST(ROUND((
				SELECT CP_BONUS
				FROM Book.CompetitionLast
				WHERE CP_ID_MASTER = PS_ID_COMPETITION
			), 0) AS MONEY) AS PS_COMPETITION,
			CAST(ROUND((
				SELECT SUM(PSB_TOTAL)
				FROM Salary.PersonalSalaryBook
				WHERE PSB_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_BOOK,
			--SUM(PSB_TOTAL) AS PS_BOOK,
			CAST(ROUND((
				SELECT SUM(PSB_DELIVERY)
				FROM Salary.PersonalSalaryBook
				WHERE PSB_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_DELIVERY,
			--SUM(PSB_DELIVERY) AS PS_DELIVERY,
			--SUM(PSD_TOTAL) AS PS_SALE,
			PS_CORRECT,
			PS_COMMENT
		FROM
			Personal.PersonalLast	INNER JOIN
			Salary.PersonalSalary	ON	PER_ID_MASTER	=	PS_ID_PERSONAL
		WHERE PS_ID_PERIOD = @PR_ID AND PS_ID_VENDOR = @VD_ID
		ORDER BY PER_NAME
	ELSE
		SELECT
			ROW_NUMBER() OVER (ORDER BY PER_NAME) AS NUM,
			PER_NAME, PS_DATE,
			CAST(ROUND((
				SELECT SUM(PSD_TOTAL)
				FROM Salary.PersonalSalaryDetail
				WHERE PSD_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_SALE,
			PS_SALARY,
			--0 AS PS_VISIT,
			--0 AS PS_BONUS,
			CAST(ROUND((
				SELECT CP_BONUS
				FROM Book.CompetitionLast
				WHERE CP_ID_MASTER = PS_ID_COMPETITION
			), 0) AS MONEY) AS PS_COMPETITION,
			CAST(ROUND((
				SELECT SUM(PSB_TOTAL)
				FROM Salary.PersonalSalaryBook
				WHERE PSB_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_BOOK,
			--SUM(PSB_TOTAL) AS PS_BOOK,
			CAST(ROUND((
				SELECT SUM(PSB_DELIVERY)
				FROM Salary.PersonalSalaryBook
				WHERE PSB_ID_MASTER = PS_ID
			), 0) AS MONEY) AS PS_DELIVERY,
			--SUM(PSB_DELIVERY) AS PS_DELIVERY,
			--SUM(PSD_TOTAL) AS PS_SALE,
			PS_CORRECT, PS_DEBT,
			CASE PS_ID_PERIOD
				WHEN PS_ID_PAY THEN CAST(1 AS SMALLINT)
				ELSE CAST(0 AS SMALLINT)
			END AS PS_CALC_NOW,
			PS_COMMENT
		FROM
			Personal.PersonalLast	INNER JOIN
			Salary.PersonalSalary	ON	PER_ID_MASTER	=	PS_ID_PERSONAL
		WHERE PS_ID_PERIOD = @PR_ID AND PS_ID_VENDOR = @VD_ID AND PER_ID_TYPE = @PT_ID
		ORDER BY PER_NAME
END
GO
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_SUMMARY_SELECT] TO rl_salary_w;
GO
