USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [Salary].[PERSONAL_SALARY_DELETE]
	@PR_ID UNIQUEIDENTIFIER,
	@PER_ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

    DELETE FROM Salary.PersonalSalaryDetail
	WHERE PSD_ID_MASTER IN
		(
			SELECT PS_ID
			FROM Salary.PersonalSalary
			WHERE PS_ID_PERSONAL = @PER_ID
				AND PS_ID_PERIOD = @PR_ID
		)

	DELETE FROM Salary.PersonalSalaryBook
	WHERE PSB_ID_MASTER IN
		(
			SELECT PS_ID
			FROM Salary.PersonalSalary
			WHERE PS_ID_PERSONAL = @PER_ID
				AND PS_ID_PERIOD = @PR_ID
		)

	DELETE FROM Salary.PersonalSalary
	WHERE PS_ID_PERSONAL = @PER_ID
		AND PS_ID_PERIOD = @PR_ID
END
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_DELETE] TO rl_salary_w;
GO