USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Salary].[PERSONAL_SALARY_BOOK_COMMENT_SET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Salary].[PERSONAL_SALARY_BOOK_COMMENT_SET]  AS SELECT 1')
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_BOOK_COMMENT_SET]
	@PS_ID		UNIQUEIDENTIFIER,
	@COMMENT	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Salary.PersonalSalary
	SET PS_COMMENT = @COMMENT
	WHERE PS_ID = @PS_ID
END
GO
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_BOOK_COMMENT_SET] TO rl_salary_w;
GO
