USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[SALARY_CONDITION_INSERT]
	@SC_WEIGHT		DECIMAL(8, 4),
	@SC_VALUE		MONEY,
	@SC_ID_PER_TYPE	UNIQUEIDENTIFIER,
	@SC_DATE		SMALLDATETIME,
	@SC_ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'SALARY_CONDITION', NULL, @OLD OUTPUT

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	DECLARE @MASTERID UNIQUEIDENTIFIER

	INSERT INTO Salary.SalaryCondition(SCMS_ID)
	OUTPUT INSERTED.SCMS_ID INTO @TBL
	DEFAULT VALUES


	SELECT	@MASTERID = ID
	FROM	@TBL

	DELETE
	FROM	@TBL


	INSERT INTO
			Salary.SalaryConditionDetail(
				SC_WEIGHT,
				SC_VALUE,
				SC_ID_PER_TYPE,
				SC_DATE,
				SC_ID_MASTER
			)
	OUTPUT INSERTED.SC_ID INTO @TBL(ID)
	VALUES	(
				@SC_WEIGHT,
				@SC_VALUE,
				@SC_ID_PER_TYPE,
				@SC_DATE,
				@MASTERID
			)

	SELECT	@SC_ID = ID
	FROM	@TBL

	EXEC Common.PROTOCOL_VALUE_GET 'SALARY_CONDITION', @MASTERID, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'SALARY_CONDITION', 'Новая запись', @MASTERID, @OLD, @NEW

END

GO
GRANT EXECUTE ON [Salary].[SALARY_CONDITION_INSERT] TO rl_salary_condition_i;
GO
