USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[BONUS_CONDITION_LAST]
	@DT	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT	@DT	= MAX(BCMS_LAST)
	FROM	Salary.BonusCondition
END
GRANT EXECUTE ON [Salary].[BONUS_CONDITION_LAST] TO rl_bonus_condition_r;
GO