USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Salary].[BONUS_CONDITION_OVER_ONE] 
	@IDLIST	UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	DECLARE @MASTERID UNIQUEIDENTIFIER

	SELECT @MASTERID = BC_ID_MASTER
	FROM Salary.BonusConditionDetail
	WHERE BC_ID = @IDLIST

	DECLARE @OLD	VARCHAR(MAX)
	DECLARE @NEW	VARCHAR(MAX)

	EXEC Common.PROTOCOL_VALUE_GET 'BONUS_CONDITION', @MASTERID, @OLD OUTPUT

	UPDATE	Salary.BonusConditionDetail
	SET		BC_END	=	@DATE,
			BC_REF	=	3
	WHERE	BC_ID	=	@IDLIST
		
	
	EXEC Common.PROTOCOL_VALUE_GET 'BONUS_CONDITION', NULL, @NEW OUTPUT

	EXEC Common.PROTOCOL_INSERT 'BONUS_CONDITION', 'Удаление', @MASTERID, @OLD, @NEW
	
END

