USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[BONUS_CONDITION_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Salary].[BonusConditionDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GRANT EXECUTE ON [Salary].[BONUS_CONDITION_DELETED] TO rl_bonus_condition_r;
GO