USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Salary].[PERSONAL_SALARY_BOOK_NORM_SET]
	@PS_ID	UNIQUEIDENTIFIER,
	@NORM	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Salary.PersonalSalary
	SET PS_BOOK_NORM = @NORM
	WHERE PS_ID = @PS_ID
END
