USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_COMPETITION_SET]
	@PS_ID			UNIQUEIDENTIFIER,
	@COMPETITION	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Salary.PersonalSalary
	SET PS_ID_COMPETITION = @COMPETITION
	WHERE PS_ID = @PS_ID
END
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_COMPETITION_SET] TO rl_salary_w;
GO