USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Salary].[PERSONAL_SALARY_BOOK_COMMENT_SET]
	@PS_ID		UNIQUEIDENTIFIER,
	@COMMENT	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Salary.PersonalSalary
	SET PS_COMMENT = @COMMENT
	WHERE PS_ID = @PS_ID
END
