USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_CALC]
	@PER_ID		UNIQUEIDENTIFIER,
	@PR_ID		UNIQUEIDENTIFIER,
	@VD_ID		UNIQUEIDENTIFIER,
	@PS_SALARY	MONEY,
	@PS_ID	UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @PS_ID = PS_ID
	FROM Salary.PersonalSalary
	WHERE PS_ID_PERIOD = @PR_ID AND PS_ID_PERSONAL = @PER_ID

	IF @PS_ID IS NULL
	BEGIN
		DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

		DECLARE @DEBT MONEY

		SELECT @DEBT =
				SUM(
					ISNULL(PS_SALARY, 0) + ISNULL(PS_COMPETITION, 0) +
					ISNULL(PS_BOOK, 0) + ISNULL(PS_DELIVERY, 0) +
					ISNULL(PS_CORRECT, 0) + ISNULL(PS_SALE, 0))
		FROM Salary.PersonalSalarySummaryView
		WHERE PER_ID = @PER_ID AND PS_PAYED = 0 AND PS_ID_PERIOD <> @PR_ID
			AND PS_LOCK = 0

		INSERT INTO Salary.PersonalSalary(
				PS_ID_PERSONAL, PS_ID_PERIOD, PS_ID_VENDOR,
				PS_SALARY, PS_BOOK_NORM, PS_ID_COMPETITION, PS_CORRECT, PS_COMMENT,
				PS_ID_PAY, PS_DEBT, PS_LOCK)
		OUTPUT INSERTED.PS_ID INTO @TBL
		VALUES(@PER_ID, @PR_ID, @VD_ID, @PS_SALARY, 0, NULL, 0, '', @PR_ID, @DEBT, 0)

		SELECT	@PS_ID = ID
		FROM	@TBL
	END
END
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_CALC] TO rl_salary_w;
GO