USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[PERSONAL_SALARY_BOOK_CALC]
	@PS_ID			UNIQUEIDENTIFIER,
	@IB_ID			UNIQUEIDENTIFIER,
	@PSB_SUM		MONEY,
	@PSB_PERCENT	MONEY,
	@PSB_COUNT		MONEY,
	@PSB_TOTAL		MONEY,
	@PSB_DELIVERY	MONEY,
	@PSB_PAYED		BIT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Salary.PersonalSalaryBook(PSB_ID_MASTER, PSB_ID_IB, PSB_SUM, PSB_PERCENT, PSB_COUNT, PSB_TOTAL, PSB_DELIVERY, PSB_PAYED)
	VALUES (@PS_ID, @IB_ID, @PSB_SUM, @PSB_PERCENT, @PSB_COUNT, @PSB_TOTAL, @PSB_DELIVERY, @PSB_PAYED)
END
GO
GRANT EXECUTE ON [Salary].[PERSONAL_SALARY_BOOK_CALC] TO rl_salary_w;
GO
