USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[KILL_USER]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Security].[KILL_USER]  AS SELECT 1')
GO
ALTER PROCEDURE [Security].[KILL_USER]
	@SPID INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQL NVARCHAR(MAX)

	IF @SPID = @@SPID
		RETURN

	SET @SQL = 'KILL ' + CONVERT(VARCHAR(20), @SPID)

	EXEC (@SQL)
END
GO
