USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[USER_ROLE_SET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Security].[USER_ROLE_SET]  AS SELECT 1')
GO
ALTER PROCEDURE [Security].[USER_ROLE_SET]
	@US_ID	UNIQUEIDENTIFIER,
	@RL_ID	UNIQUEIDENTIFIER,
	@MODE	VARCHAR(10)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @LOGIN	VARCHAR(50)

	SELECT @LOGIN = US_LOGIN
	FROM Security.UserActive
	WHERE US_ID_MASTER = @US_ID

	DECLARE ROLES CURSOR LOCAL FOR
		SELECT RL_ROLE
		FROM Security.RoleTreeSelect(@RL_ID)
		WHERE RL_ROLE <> ''

	OPEN ROLES

	DECLARE @RL_NAME VARCHAR(50)

	FETCH NEXT FROM ROLES INTO @RL_NAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF @MODE = 'GRANT'
			EXEC sp_addrolemember @RL_NAME, @LOGIN
		ELSE IF @MODE = 'DENY'
			EXEC sp_droprolemember @RL_NAME, @LOGIN

		FETCH NEXT FROM ROLES INTO @RL_NAME
	END

	CLOSE ROLES
	DEALLOCATE ROLES
END
GO
