USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Security].[ROLE_USER_MESSAGE_DELETE]
	@US_ID	UNIQUEIDENTIFIER,
	@RL_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Security.RoleMessages
	WHERE RM_ID_ROLE = @RL_ID AND RM_ID_USER = @US_ID
END
GO
