USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Security].[ROLE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100),
	@ROLE	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TROLE VARCHAR(100)

	SELECT @TROLE = RL_ROLE 
	FROM Security.Roles 
	WHERE RL_ID = @ID

	IF (@TROLE <> @ROLE) AND (@ROLE <> '') AND (@TROLE <> '')
		EXEC ('ALTER ROLE [' + @TROLE + '] WITH NAME = [' + @ROLE + ']')

	UPDATE	Security.Roles
	SET		RL_NAME	=	@NAME,
			RL_ROLE	=	@ROLE
	WHERE	RL_ID	=	@ID
END
