USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[USER_OVER] 
	@IDLIST VARCHAR(MAX),
	@DATE SMALLDATETIME,
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	
	UPDATE	Security.UserDetail
	SET		US_END	=	@DATE,
			US_REF	=	3
	WHERE	US_ID IN 
		(
			SELECT	ID 
			FROM	Common.TableFromList(@IDLIST, ',')
		)	

	SELECT @RC = @@ROWCOUNT	
END

