USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[ROLE_USER_MESSAGE_ADD]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Security].[ROLE_USER_MESSAGE_ADD]  AS SELECT 1')
GO
ALTER PROCEDURE [Security].[ROLE_USER_MESSAGE_ADD]
	@US_ID	UNIQUEIDENTIFIER,
	@RL_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Security.RoleMessages(RM_ID_ROLE, RM_ID_USER)
		VALUES(@RL_ID, @US_ID)
END
GO
