USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Security].[USER_DELETED]
	@RC INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	SELECT	*
	FROM	[Security].[UserDeleted]

	SELECT	@RC = @@ROWCOUNT
END
GRANT EXECUTE ON [Security].[USER_DELETED] TO rl_user_r;
GO