USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Client].[CompanyControlView]
WITH SCHEMABINDING
AS
	SELECT ID, ID_COMPANY
	FROM Client.CompanyControl a
	WHERE a.STATUS = 1 AND a.REMOVE_DATE IS NULL
