USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Ric].[DepthCoefCalc]', 'FN') IS NULL EXEC('CREATE FUNCTION [Ric].[DepthCoefCalc] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Ric].[DepthCoefCalc]
(
	@COEF	DECIMAL(10, 4)
)
RETURNS DECIMAL(10, 4)
AS
BEGIN
	DECLARE @RES DECIMAL(10, 4)

	IF @COEF <= 1
		SET @RES = 1
	ELSE IF (@COEF > 1) AND (@COEF <= 1.4)
		SET @RES = 1 + 0.5 * (@COEF - 1)
	ELSE IF (@COEF > 1.4) AND (@COEF <= 1.7)
		SET @RES = 1.2 + 1.5 * (@COEF - 1.4)
	ELSE IF @COEF > 1.7
		SET @RES = 1.65 + 3 * (@COEF - 1.7)
	ELSE
		SET @RES = NULL

	SET @RES = ROUND(@RES, 2)

	RETURN @RES
END

GO
