USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[NetTypes@Get?Offile]()
RETURNS TABLE
AS
RETURN
(
    SELECT SNC.[SNC_ID_SN]
    FROM [dbo].[SystemNetCountTable] AS SNC
    WHERE SNC.[SNC_TECH] > 3
)
GO
