USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[NewIdView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[NewIdView]  AS SELECT 1')
GO
ALTER VIEW [dbo].[NewIdView]
AS
	SELECT NewId() AS [NewID]
GO
