USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[InvoiceFullView]
AS
SELECT
		INS_ID,
		INR_ID_INVOICE,
		INS_ID_CLIENT, INS_ID_ORG, INS_NUM, INS_NUM_YEAR, INS_DATE,
		ORG_SHORT_NAME, ORG_ADDRESS, ORG_INN, ORG_KPP,
		INS_CLIENT_NAME,INS_CLIENT_ADDR, INS_DOC_STRING, INS_CONSIG_NAME, INS_CONSIG_ADDR,
		INS_CLIENT_INN, INS_CLIENT_KPP,
		SO_INV_STR, SYS_NAME, SO_INV_UNIT,
		INR_SUM, INR_TNDS, INR_SNDS, INR_SALL,
		ORG_DIR_SHORT, ORG_BUH_SHORT,
		INR_NAME,
		INR_ID_PERIOD, SYS_ID_SO,
		INS_STORNO,
		INS_COMMENT,
		INS_PREPAY,
		INR_ID,
		INR_ID_TAX,
		INR_ID_DISTR,
		CL_INN, CL_KPP, CL_SHORT_NAME

		FROM	dbo.InvoiceSaleTable	A									INNER JOIN
				dbo.InvoiceRowTable		B	ON	A.INS_ID=B.INR_ID_INVOICE	LEFT JOIN
				dbo.DistrView			C WITH(NOEXPAND)	ON	B.INR_ID_DISTR=C.DIS_ID		INNER JOIN
				dbo.OrganizationView	D	ON	A.INS_ID_ORG=D.ORG_ID		LEFT JOIN
				dbo.SaleObjectTable		E	ON	C.SYS_ID_SO=E.SO_ID			INNER JOIN
				dbo.ClientTable			F	ON	A.INS_ID_CLIENT=F.CL_ID
		/*WHERE	INR_ID_PERIOD=@prid	AND
				SYS_ID_SO	 =@soid*/
GO
