USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[AddressView]
AS
	SELECT ST_ID, CT_ID, ST_PREFIX, ST_NAME, ST_SUFFIX, CT_PREFIX, CT_NAME
	FROM
		dbo.StreetTable LEFT OUTER JOIN
        dbo.CityTable ON CT_ID = ST_ID_CITY
