USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[RegNodeView]
--WITH SCHEMABINDING
AS
	SELECT
		CONVERT(BIGINT, CONVERT(BIGINT, SYS_ID) * CONVERT(BIGINT, 100000000) + CONVERT(BIGINT, RN_DISTR_NUM) * CONVERT(BIGINT, 100) + CONVERT(BIGINT, RN_COMP_NUM)) AS RN_ID,
		RN_SYS_NAME, RN_DISTR_NUM, RN_COMP_NUM, RN_DISTR_TYPE, RN_TECH_TYPE, RN_NET_COUNT,
		RN_SUBHOST, RN_TRANSFER_COUNT, RN_TRANSFER_LEFT, RN_SERVICE, RN_REG_DATE,
		RN_FIRST_REG, RN_COMMENT, RN_COMPLECT, RN_REPORT_CODE, RN_REPORT_VALUE, RN_SHORT, RN_MAIN
	FROM
		dbo.RegNodeTable
		INNER JOIN dbo.SystemTable ON RN_SYS_NAME = SYS_REG_NAME
