USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[VMRView] AS
SELECT 
		VMR_RIC_NUM, VMR_TO_NUM, VMR_TO_NAME,
		VMR_INN, VMR_REGION, VMR_CITY, VMR_ADDR,
		VMR_FIO_1, VMR_JOB_1, VMR_TELS_1,
		VMR_FIO_2, VMR_JOB_2, VMR_TELS_2,
		VMR_FIO_3, VMR_JOB_3, VMR_TELS_3,
		VMR_FIO_4, VMR_JOB_4, VMR_TELS_4,
		VMR_FIO_5, VMR_JOB_5, VMR_TELS_5,
		VMR_SERV, VMR_DISTR, VMR_COMMENT
FROM dbo.VMIReportTable
