USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[BillView]
AS
SELECT
		BL_ID, PR_DATE, PR_ID, BL_ID_CLIENT, SO_NAME, SO_ID,
		ISNULL(SUM(BD_TOTAL_PRICE), 0) AS BL_PRICE, ORG_ID, ORG_PSEDO
	FROM
		dbo.BillTable INNER JOIN
		dbo.OrganizationTable ON ORG_ID = BL_ID_ORG INNER JOIN
		dbo.PeriodTable ON BL_ID_PERIOD = PR_ID LEFT OUTER JOIN
		dbo.BillDistrTable ON BD_ID_BILL = BL_ID LEFT OUTER JOIN
		dbo.DistrView WITH(NOEXPAND) ON DIS_ID = BD_ID_DISTR LEFT OUTER JOIN
		dbo.SaleObjectTable ON SO_ID = SYS_ID_SO
	GROUP BY BL_ID, PR_DATE, PR_ID, BL_ID_CLIENT, SO_NAME, SO_ID, ORG_ID, ORG_PSEDO
GO
