USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ActIXView]
WITH SCHEMABINDING
AS
	SELECT ACT_ID_CLIENT, AD_ID_PERIOD, AD_ID_DISTR, SUM(AD_TOTAL_PRICE) AS AD_TOTAL_PRICE, COUNT_BIG(*) AS AD_CNT
	FROM        
		dbo.ActDistrTable INNER JOIN
        dbo.ActTable ON AD_ID_ACT = ACT_ID
	GROUP BY ACT_ID_CLIENT, AD_ID_PERIOD, AD_ID_DISTR