USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[TODistrView]
AS
SELECT
			DIS_ID, TD_ID, TD_ID_TO, DIS_STR, TO_ID_CLIENT, TD_ID_DISTR,
			DIS_NUM, DIS_COMP_NUM, SYS_ID, SYS_REG_NAME, SYS_REPORT, HST_REG_NAME,
			SYS_IB, TD_FORCED
	FROM
		dbo.TODistrTable a INNER JOIN
		dbo.TOTable b ON a.TD_ID_TO = b.TO_ID INNER JOIN
		dbo.DistrView c WITH(NOEXPAND) ON a.TD_ID_DISTR = c.DIS_ID
GO
