USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[ClientActiveContractDistrView]
AS
	SELECT CO_ID_CLIENT, CO_ID, CO_NUM, COD_ID_CONTRACT, COD_ID_DISTR
FROM 
	dbo.ClientTable INNER JOIN
	dbo.ContractTable ON CO_ID_CLIENT = CL_ID INNER JOIN
	dbo.ContractDistrTable ON COD_ID_CONTRACT = CO_ID 
WHERE CO_ACTIVE = 1 --AND CL_ID = 3759

UNION ALL


SELECT CO_ID_CLIENT, CO_ID, CO_NUM, COD_ID_CONTRACT, COD_ID_DISTR
FROM 
	dbo.ClientTable INNER JOIN
	dbo.ContractTable ON CO_ID_CLIENT = CL_ID INNER JOIN
	dbo.ContractDistrTable ON COD_ID_CONTRACT = CO_ID
WHERE NOT EXISTS
	(
		SELECT *
		FROM ContractTable
		WHERE CO_ID_CLIENT = CL_ID 
			AND CO_ACTIVE = 1
	) --AND CL_ID = 3759
