USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ClientCourView]
AS

SELECT 
	CL_ID, CL_PSEDO, CL_FULL_NAME,
	(
		SELECT TOP 1 COUR_NAME
		FROM 
			dbo.TOTable INNER JOIN
			dbo.CourierTable ON COUR_ID = TO_ID_COUR
		WHERE TO_ID_CLIENT = CL_ID
		ORDER BY TO_MAIN DESC, COUR_NAME
	) AS COUR_NAME,
	(
		SELECT TOP 1 COUR_ID
		FROM 
			dbo.TOTable INNER JOIN
			dbo.CourierTable ON COUR_ID = TO_ID_COUR
		WHERE TO_ID_CLIENT = CL_ID
		ORDER BY TO_MAIN DESC, COUR_NAME
	) AS COUR_ID
FROM 
	dbo.ClientTable
WHERE EXISTS
	(
		SELECT *
		FROM dbo.TOTable
		WHERE TO_ID_CLIENT = CL_ID
	)