USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[ActPeriodView]
AS
	/*
	SELECT
		ACT_ID, ACT_DATE, ACT_ID_CLIENT, ACT_SIGN,
		(
			SELECT TOP 1 PR_ID
			FROM
				dbo.PeriodTable INNER JOIN
				dbo.ActDistrTable ON AD_ID_PERIOD = PR_ID
			WHERE AD_ID_ACT = ACT_ID
			ORDER BY PR_DATE DESC
		) AS ACT_ID_PERIOD
	FROM
		dbo.ActTable
	*/

	SELECT TOP 1 WITH TIES
		ACT_ID, ACT_DATE, ACT_ID_CLIENT, ACT_SIGN, PR_ID AS ACT_ID_PERIOD, ACT_ID_COUR--, MAX(PR_DATE) AS PR_DATE
	FROM
		dbo.ActTable INNER JOIN
		dbo.ActDistrTable ON AD_ID_ACT = ACT_ID INNER JOIN
		dbo.PeriodTable ON AD_ID_PERIOD = PR_ID
	GROUP BY ACT_ID, ACT_DATE, ACT_ID_CLIENT, ACT_SIGN, PR_DATE, PR_ID, ACT_ID_COUR
	ORDER BY ROW_NUMBER() OVER(PARTITION BY ACT_ID ORDER BY PR_DATE DESC)