USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ConsignmentPeriodView]', 'V ') IS NULL EXEC('CREATE VIEW [dbo].[ConsignmentPeriodView]  AS SELECT 1')
GO
ALTER VIEW [dbo].[ConsignmentPeriodView]
AS
	/*
	SELECT
		ACT_ID, ACT_DATE, ACT_ID_CLIENT, ACT_SIGN,
		(
			SELECT TOP 1 PR_ID
			FROM
				dbo.PeriodTable INNER JOIN
				dbo.ActDistrTable ON AD_ID_PERIOD = PR_ID
			WHERE AD_ID_ACT = ACT_ID
			ORDER BY PR_DATE DESC
		) AS ACT_ID_PERIOD
	FROM
		dbo.ActTable
	*/

	SELECT TOP 1 WITH TIES
		CSG_ID, CSG_DATE, CSG_ID_CLIENT, CSG_SIGN, PR_ID AS CSG_ID_PERIOD--, MAX(PR_DATE) AS PR_DATE
	FROM
		dbo.ConsignmentTable INNER JOIN
		dbo.ConsignmentDetailTable ON CSD_ID_CONS = CSG_ID INNER JOIN
		dbo.PeriodTable ON CSD_ID_PERIOD = PR_ID
	GROUP BY CSG_ID, CSG_DATE, CSG_ID_CLIENT, CSG_SIGN, PR_DATE, PR_ID
	ORDER BY ROW_NUMBER() OVER(PARTITION BY CSG_ID ORDER BY PR_DATE DESC)GO
