USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[DistrView] 
AS
SELECT    
		SYS_ID, SYS_SHORT_NAME, DIS_NUM, DIS_COMP_NUM, DIS_ID, SYS_REG_NAME, 
		DIS_ACTIVE, HST_ID, HST_REG_NAME, SYS_REPORT, SYS_PREFIX,
		CASE DIS_COMP_NUM 
			WHEN 1 THEN SYS_SHORT_NAME + ' ' + CONVERT(VARCHAR, DIS_NUM)
			ELSE SYS_SHORT_NAME + ' ' + CONVERT(VARCHAR, DIS_NUM) + '/' + CONVERT(VARCHAR, DIS_COMP_NUM)
		END AS DIS_STR, 
		SYS_ID_SO, SYS_ORDER, SYS_NAME, SYS_MAIN, SYS_1C_CODE, SYS_1C_CODE2, SYS_IB
	FROM         
		dbo.SystemTable INNER JOIN
		dbo.DistrTable ON SYS_ID = DIS_ID_SYSTEM LEFT OUTER JOIN
		dbo.HostTable ON SYS_ID_HOST = HST_ID
