USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[PeriodRegView]
AS
SELECT	
		REG_ID,
		PR_DATE,		REG_ID_PERIOD,
		SYS_SHORT_NAME,	REG_ID_SYSTEM, SYS_ORDER, SYS_ID_HOST,
		REG_DISTR_NUM,
		REG_COMP_NUM,
		SH_SHORT_NAME,	REG_ID_HOST,
		SST_NAME,		REG_ID_TYPE,
		DS_REG, DS_NAME,		REG_ID_STATUS,	--REG_STATUS,
		REG_DATE,
		REG_COMMENT,
		REG_NUM_CLIENT,
		REG_PSEDO_CLIENT,
		COUR_NAME,		REG_ID_COUR,
		SNC_ID_SN, SNC_NET_COUNT, SNC_TECH,	REG_ID_NET, SNC_SHORT,
		REG_COMPLECT

FROM	dbo.PeriodRegTable		A									LEFT JOIN
		dbo.PeriodTable			B	ON	A.REG_ID_PERIOD = B.PR_ID	LEFT JOIN
		dbo.SystemTable			C	ON	A.REG_ID_SYSTEM = C.SYS_ID	LEFT JOIN
		dbo.SubHostTable		D	ON	A.REG_ID_HOST = D.SH_ID		LEFT JOIN
		dbo.SystemTypeTable		E	ON	A.REG_ID_TYPE = E.SST_ID	LEFT JOIN
		dbo.SystemNetCountTable	F	ON	A.REG_ID_NET = F.SNC_ID		LEFT JOIN
		dbo.CourierTable		G	ON	A.REG_ID_COUR = G.COUR_ID	LEFT JOIN
		dbo.DistrStatustable	H	ON	A.REG_ID_STATUS = H.DS_ID	
