USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[PeriodRegNewView]
AS
SELECT	
		RNN_ID,
		PR_NAME,	PR_DATE,	RNN_ID_PERIOD,
		SYS_SHORT_NAME,	RNN_ID_SYSTEM,
		RNN_DISTR_NUM,
		RNN_COMP_NUM,
		SH_SHORT_NAME,	RNN_ID_HOST,
		SST_NAME,		RNN_ID_TYPE,
		RNN_DATE,
		RNN_DATE_ON,
		RNN_COMMENT,
		RNN_NUM_CLIENT,
		RNN_PSEDO_CLIENT,
--		COUR_NAME,		RNN_ID_COUR,
		SNC_NET_COUNT,	RNN_ID_NET

FROM	dbo.PeriodRegNewTable	A									LEFT JOIN
		dbo.PeriodTable			B	ON A.RNN_ID_PERIOD = B.PR_ID	LEFT JOIN
		dbo.SystemTable			C	ON A.RNN_ID_SYSTEM = C.SYS_ID	LEFT JOIN
		dbo.SubHostTable		D	ON A.RNN_ID_HOST = D.SH_ID		LEFT JOIN
		dbo.SystemTypeTable		E	ON A.RNN_ID_TYPE = E.SST_ID		LEFT JOIN
		dbo.SystemNetCountTable	F	ON A.RNN_ID_NET = F.SNC_ID		
WHERE NOT EXISTS
	(
		SELECT *
		FROM dbo.DistrExchange z
		WHERE z.NEW_HOST = c.SYS_ID_HOST
			AND z.NEW_NUM = a.RNN_DISTR_NUM
			AND z.NEW_COMP = a.RNN_COMP_NUM
	)
--		dbo.CourierTable		G	ON A.RNN_ID_COUR= G.COUR_ID
