USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[LOG_TYPE]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[LOG_TYPE] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[LOG_TYPE]
(
	@NAME	NVARCHAR(512)
)
RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @RESULT	VARCHAR(10)

	SET @RESULT = dbo.LOG_PARSE(@NAME, 'TYPE')

	RETURN @RESULT
END
GO
