USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[LOG_SYS]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[LOG_SYS] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[LOG_SYS]
(
	@NAME	NVARCHAR(512)
)
RETURNS SMALLINT
AS
BEGIN
	DECLARE @RESULT	SMALLINT

	SET @RESULT = dbo.LOG_PARSE(@NAME, 'SYS')

	RETURN @RESULT
END
GO
