USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[TimeSecToStr]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[TimeSecToStr] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[TimeSecToStr]
(
	@TIME INT
)
RETURNS NVARCHAR(50)
AS
BEGIN
	DECLARE @RESULT NVARCHAR(50)

	SET @RESULT = ''

	IF ROUND(@TIME / 3600, 0) <> 0
		SET @RESULT = @RESULT + CONVERT(VARCHAR(20), ROUND(@TIME / 3600, 0)) + ' ч.'
	IF ROUND((@TIME - ROUND(@TIME / 3600, 0) * 3600) / 60, 0) <> 0
		SET @RESULT = @RESULT + CONVERT(VARCHAR(20), ROUND((@TIME - ROUND(@TIME / 3600, 0) * 3600) / 60, 0)) + ' м.'
	IF 	ROUND(@TIME - ROUND(@TIME / 3600, 0) * 3600 - ROUND((@TIME - ROUND(@TIME / 3600, 0) * 3600) / 60, 0) * 60, 0) <> 0
		SET @RESULT = @RESULT + CONVERT(VARCHAR(20), ROUND(@TIME - ROUND(@TIME / 3600, 0) * 3600 - ROUND((@TIME - ROUND(@TIME / 3600, 0) * 3600) / 60, 0) * 60, 0)) + ' c.'

	RETURN @RESULT
END
GO
