USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[LOG_FILE]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[LOG_FILE] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[LOG_FILE]
(
	@NAME	NVARCHAR(512)
)
RETURNS NVARCHAR(128)
AS
BEGIN
	DECLARE @RESULT	NVARCHAR(128)

	SET @RESULT = dbo.LOG_PARSE(@NAME, 'FILE')

	RETURN @RESULT
END
GO
