USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[LOG_DISTR]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[LOG_DISTR] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[LOG_DISTR]
(
	@NAME	NVARCHAR(512)
)
RETURNS INT
AS
BEGIN
	DECLARE @RESULT	INT

	SET @RESULT = dbo.LOG_PARSE(@NAME, 'DISTR')

	RETURN @RESULT
END
GO
