USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Claim].[CLIENT_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Claim].[CLIENT_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Claim].[CLIENT_SELECT]
	@TYPE	NVARCHAR(64),
	@FILTER	NVARCHAR(512),
	@RC		INT = NULL OUTPUT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		IF @TYPE = N'OIS'
		BEGIN
			IF OBJECT_ID('tempdb..#ois') IS NOT NULL
				DROP TABLE #ois

			CREATE TABLE #ois
				(
					ID		INT,
					NAME	NVARCHAR(1024),
					PARAL	NVARCHAR(1024),
					ADDR	NVARCHAR(1024),
					SERV	NVARCHAR(256),
					MAN		NVARCHAR(256),
					SIND	INT,
					ORI		BIT,
					CONTR	BIT,
					TRUST	BIT,
					REG		BIT,
					IPLOCK	BIT,
					STUDY	SMALLDATETIME,
					DNAME	VARCHAR(50),
					DORD	INT,
					SSTART	DATETIME,
					CONT_2	BIT
				)

			INSERT INTO #ois
				EXEC [PC275-SQL\ALPHA].ClientDB.dbo.CLIENT_FULL_SEARCH @SIMPLE = @FILTER, @COUNT = @RC OUTPUT

			SELECT CONVERT(NVARCHAR(128), ID) AS ID, NAME, SERV + '/' + MAN + '/' + ADDR AS NOTE
			FROM #ois
			ORDER BY NAME

			IF OBJECT_ID('tempdb..#ois') IS NOT NULL
				DROP TABLE #ois
		END
		ELSE IF @TYPE = N'SALE'
		BEGIN
			IF OBJECT_ID('tempdb..#sale') IS NOT NULL
				DROP TABLE #sale

			CREATE TABLE #sale
				(
					ID		UNIQUEIDENTIFIER,
					NUMBER	INT,
					STATUS	BIT,
					SHORT	NVARCHAR(128),
					NAME	NVARCHAR(1024),
					WRITE	BIT,
					AVA		NVARCHAR(256),
					POT		NVARCHAR(256),
					WS		NVARCHAR(256),
					PC		NVARCHAR(256), 
					PHONE	NVARCHAR(256),
					SALE	NVARCHAR(256),
					MAN		NVARCHAR(256),
					RIV		NVARCHAR(256),
					MON		NVARCHAR(256),
					MON_DT	SMALLDATETIME,
					WORK	NVARCHAR(256),
					BLACK	BIT,
					CHAR	NVARCHAR(256),
					PAPER	BIT,
					DEPO	BIT,
					PRJ		NVARCHAR(128),
					CONTROL	BIT,
					ARCH	BIT,
					HISTORY	BIT,
					CDATE	SMALLDATETIME,
					INDX	SMALLINT,
					AVA_CH	BIT,
					AVA_COL	INT,
					WARNING	BIT,
					DEPO_N	INT
				)

			INSERT INTO #sale
				EXEC SaleDB.Client.COMPANY_SELECT @SEARCH = @FILTER, @RC = @RC OUTPUT

			SELECT 2 AS TP, CONVERT(NVARCHAR(128), ID) AS ID, NAME, SALE + '/' + MAN AS NOTE
			FROM #sale

			UNION ALL

			SELECT 1 AS TP, N'00000000-0000-0000-0000-000000000000' AS ID, N'Оптовый' AS NAME, N'' AS NOTE

			ORDER BY TP, NAME

			IF OBJECT_ID('tempdb..#sale') IS NOT NULL
				DROP TABLE #sale
		END

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		ROLLBACK

		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Claim].[CLIENT_SELECT] TO rl_claim_u;
GO
