USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Claim].[PERSONAL_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Claim].[PERSONAL_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Claim].[PERSONAL_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ServiceName
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ServiceTable
	WHERE ServiceDismiss IS NULL

	UNION ALL

	SELECT SHORT
	FROM SaleDB.Personal.OfficePersonal
	WHERE END_DATE IS NULL

	UNION ALL

	SELECT N'Гончарова'

	UNION ALL

	SELECT N'Литвин'

	UNION ALL

	SELECT N'Лукашова'

	ORDER BY ServiceName
END
GO
GRANT EXECUTE ON [Claim].[PERSONAL_SELECT] TO rl_claim_r;
GO
