USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Claim].[CLAIM_SERVICE_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Claim].[CLAIM_SERVICE_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Claim].[CLAIM_SERVICE_SELECT]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		SELECT 
			a.ID_SERVICE, c.NAME + '\' + b.NAME AS SERV_STR, CNT
		FROM
			Claim.DocumentService a
			INNER JOIN Claim.Service b ON a.ID_SERVICE = b.ID
			INNER JOIN Claim.ServiceGroup c ON b.ID_GROUP = c.ID
		WHERE ID_DOCUMENT = @ID
		ORDER BY c.NAME, b.NAME

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Claim].[CLAIM_SERVICE_SELECT] TO rl_claim_r;
GO
