USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[REFERENCE_LAST]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[REFERENCE_LAST]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[REFERENCE_LAST]
	@LAST DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		SELECT N'ACTION' AS REF_NAME, MAX(LAST) AS LAST
		FROM Claim.Action

		UNION ALL

		SELECT N'MONTH_BONUS' AS REF_NAME, MAX(LAST) AS LAST
		FROM Claim.MonthBonus

		UNION ALL

		SELECT N'CONDITION' AS REF_NAME, MAX(LAST) AS LAST
		FROM Claim.Condition

		UNION ALL

		SELECT N'CLIENT_TYPE', MAX(LAST)
		FROM Claim.ClientType

		UNION ALL

		SELECT N'SERVICE', MAX(LAST)
		FROM Claim.Service

		UNION ALL

		SELECT N'SERVICE_GROUP', MAX(LAST)
		FROM Claim.ServiceGroup

		UNION ALL

		SELECT N'DOCUMENT_TYPE', MAX(LAST)
		FROM Claim.Type

		UNION ALL

		SELECT N'VENDOR', MAX(LAST)
		FROM Claim.Vendor

		UNION ALL

		SELECT N'HOST', MAX(LAST)
		FROM Distr.Host

		UNION ALL

		SELECT N'NET', MAX(LAST)
		FROM Distr.Net

		UNION ALL

		SELECT N'SYSTEM', MAX(LAST)
		FROM Distr.System

		UNION ALL

		SELECT N'DISTR_TYPE', MAX(LAST)
		FROM Distr.Type

		UNION ALL

		SELECT N'DEPARTMENT', MAX(LAST)
		FROM Security.Department

		UNION ALL

		SELECT N'ROLE_GROUP', MAX(LAST)
		FROM Security.RoleGroup

		UNION ALL

		SELECT N'USER', MAX(LAST)
		FROM Security.Users

		UNION ALL

		SELECT N'STAGE', MAX(LAST)
		FROM Document.Stage

		UNION ALL

		SELECT N'DOC_TYPE', MAX(LAST)
		FROM Document.Type

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Common].[REFERENCE_LAST] TO public;
GO
