USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[VERSION_ACTUAL]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[VERSION_ACTUAL]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[VERSION_ACTUAL]
	@VER	NVARCHAR(64) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @VER = VERSION
	FROM Maintenance.Version
	WHERE STATUS = 1
END
GO
GRANT EXECUTE ON [Common].[VERSION_ACTUAL] TO public;
GO
