USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[SETTINGS_DEFAULT_GET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[SETTINGS_DEFAULT_GET]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[SETTINGS_DEFAULT_GET]
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		SELECT CAST(SETTINGS AS NVARCHAR(MAX)) AS SETTINGS
		FROM Common.Settings
		WHERE [USER_NAME] IS NULL

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Common].[SETTINGS_DEFAULT_GET] TO public;
GO
