USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[SETTINGS_SAVE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Common].[SETTINGS_SAVE]  AS SELECT 1')
GO
ALTER PROCEDURE [Common].[SETTINGS_SAVE]
	@SETTINGS	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		DECLARE @XML XML

		SET @XML = CAST(@SETTINGS AS XML)

		UPDATE Common.Settings
		SET SETTINGS = @XML
		WHERE [USER_NAME] = ORIGINAL_LOGIN()

		IF @@ROWCOUNT = 0
			INSERT INTO Common.Settings([USER_NAME], SETTINGS)
				SELECT ORIGINAL_LOGIN(), @XML

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Common].[SETTINGS_SAVE] TO public;
GO
