USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Maintenance].[START_PROC]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Maintenance].[START_PROC]  AS SELECT 1')
GO
ALTER PROCEDURE [Maintenance].[START_PROC]
	@ID	INT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		IF ((SELECT Maintenance.G_ProcedureLog()) = 1)
			OR ((SELECT Maintenance.G_ProcedureTime()) = 1)
			INSERT INTO Maintenance.ExecutionLog(PROC_SCHEMA, PROC_NAME, DIRECTION)
				SELECT OBJECT_SCHEMA_NAME(@ID), OBJECT_NAME(@ID), N'START'
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
