USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Notify].[NOTIFY_CHECK]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Notify].[NOTIFY_CHECK]  AS SELECT 1')
GO
ALTER PROCEDURE [Notify].[NOTIFY_CHECK]
	@CNT	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		SELECT @CNT = COUNT(*)
		FROM
			Notify.Message a
			INNER JOIN Security.Users b ON a.ID_RECEIVER = b.ID
		WHERE b.NAME = ORIGINAL_LOGIN() AND RECEIVE_DATE IS NULL

		SELECT TXT, MODULE, ID_EVENT
		FROM
			Notify.Message a
			INNER JOIN Security.Users b ON a.ID_RECEIVER = b.ID
		WHERE b.NAME = ORIGINAL_LOGIN() AND RECEIVE_DATE IS NULL
		ORDER BY DATE DESC
		/*
		UPDATE a
		SET RECEIVE_DATE = GETDATE()
		FROM
			Notify.Message a
			INNER JOIN Security.Users b ON a.ID_RECEIVER = b.ID
		WHERE b.NAME = ORIGINAL_LOGIN() AND RECEIVE_DATE IS NULL
		*/

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Notify].[NOTIFY_CHECK] TO public;
GO
