USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[ROLE_UPDATE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Security].[ROLE_UPDATE]  AS SELECT 1')
GO
ALTER PROCEDURE [Security].[ROLE_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@PARENT		UNIQUEIDENTIFIER,
	@NAME		NVARCHAR(128),
	@CAPTION	NVARCHAR(256),
	@NOTE		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		EXEC Maintenance.START_PROC @@PROCID

		DECLARE @OLD_NAME	NVARCHAR(128)

		SELECT @OLD_NAME = NAME
		FROM Security.Roles
		WHERE ID = @ID

		IF (ISNULL(@OLD_NAME, N'') = N'') AND ISNULL(@NAME, N'') <> N''
		BEGIN
			EXEC ('CREATE ROLE [' + @NAME + ']')
		END
		ELSE IF (ISNULL(@OLD_NAME, N'') <> N'') AND ISNULL(@NAME, N'') = N''
		BEGIN
			EXEC ('DROP ROLE [' + @NAME + ']')
		END
		ELSE IF (ISNULL(@OLD_NAME, N'') <> N'') AND (ISNULL(@NAME, N'') <> N'') AND (@OLD_NAME <> @NAME)
		BEGIN
			EXEC ('ALTER ROLE [' + @OLD_NAME + '] WITH NAME = [' + @NAME + ']')
		END

		UPDATE Security.Roles
		SET NAME = @NAME,
			CAPTION = @CAPTION,
			NOTE = @NOTE,
			LAST = GETDATE()
		WHERE ID = @ID

		EXEC Maintenance.FINISH_PROC @@PROCID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Maintenance.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Security].[ROLE_UPDATE] TO rl_role_u;
GO
