USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[PayCoefGet]
(
	@SYS_COUNT SMALLINT
)
RETURNS DECIMAL(8, 4)
AS
BEGIN	
	DECLARE @RESULT DECIMAL(8, 4)

	SELECT @RESULT = PC_VALUE
	FROM dbo.PayCoefTable
	WHERE PC_START <= @SYS_COUNT
		AND PC_END >= @SYS_COUNT

	IF @RESULT IS NULL
		SET @RESULT = 0

	RETURN @RESULT
END
