USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[PERIOD_DELTA]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[PERIOD_DELTA] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[PERIOD_DELTA]
(
	@PR_ID	SMALLINT,
	@DELTA	SMALLINT
)
RETURNS SMALLINT
AS
BEGIN
	DECLARE @RES	SMALLINT

	SELECT @RES = PR_ID
	FROM dbo.PeriodTable
	WHERE PR_DATE =
		(
			SELECT DATEADD(MONTH, @DELTA, PR_DATE)
			FROM dbo.PeriodTable
			WHERE PR_ID = @PR_ID
		)

	RETURN @RES
END
GO
