USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[IncomeSystemPayString]', 'FN') IS NULL EXEC('CREATE FUNCTION [dbo].[IncomeSystemPayString] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [dbo].[IncomeSystemPayString]
(
	@CL_ID	INT,
	@SYS_ID	INT,
	@DATE SMALLDATETIME
)
RETURNS VARCHAR(150)
AS
BEGIN
	DECLARE @RESULT VARCHAR(50)

	SET @RESULT = ''

	SELECT @RESULT = @RESULT + CONVERT(VARCHAR(20), IN_PAY_NUM) + ','
	FROM
		(
			SELECT DISTINCT IN_PAY_NUM
			FROM
				dbo.IncomeTable INNER JOIN
				dbo.IncomeDistrTable ON ID_ID_INCOME = IN_ID INNER JOIN
				dbo.DistrTable ON DIS_ID = ID_ID_DISTR
			WHERE @CL_ID = IN_ID_CLIENT AND IN_DATE = @DATE AND DIS_ID_SYSTEM = @SYS_ID
		) AS o_O
	ORDER BY IN_PAY_NUM

	IF LEN(@RESULT) > 1
		SET @RESULT = LEFT(@RESULT, LEN(@RESULT) - 1)

	RETURN @RESULT
END
GO
