USE [DBF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[GlobalPriceCoef]
()
RETURNS Numeric(12,4)
AS
BEGIN
	RETURN (SELECT CAST(GS_VALUE AS Numeric(12, 4)) FROM dbo.GlobalSettingsTable WHERE GS_NAME = 'PRICE_COEF')
END
GO
