USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE FUNCTION [dbo].[MoneyWithoutTax]
(
	@VAL	MONEY,
	@TAX	DECIMAL(18, 10)
)
RETURNS MONEY
AS
BEGIN
	DECLARE @RES MONEY
	
	DECLARE @TAX_COEF	DECIMAL(18, 10)

	SET @TAX_COEF = (100 + @TAX) / 100

	DECLARE @TAX_REVERSE DECIMAL(18, 10)

	SET @TAX_REVERSE = (100 - @TAX) / 100

	DECLARE @TAX_QUADRO DECIMAL(18, 10)

	SET @TAX_QUADRO = (10000 - @TAX * @TAX) / 10000

	DECLARE @SUM_1	MONEY
	DECLARE @SUM_2	MONEY
	DECLARE @SUM_3	MONEY

	SET @SUM_1 = ROUND((ROUND(@VAL / @TAX_COEF, 1) * @TAX_COEF), 2)
	SET @SUM_2 = ROUND(ROUND(@VAL * @TAX_REVERSE, 2)/@TAX_QUADRO, 2)

	IF ROUND(ROUND(ROUND(@VAL * @TAX_REVERSE, 1)/@TAX_QUADRO, 2) * @TAX_COEF, 2) = @VAL
	BEGIN
		SET @RES = ROUND(ROUND(@VAL * @TAX_REVERSE, 1)/@TAX_QUADRO, 2)		
	END
	ELSE IF ROUND(ROUND(ROUND(@VAL * @TAX_REVERSE, 2)/@TAX_QUADRO, 2) * @TAX_COEF, 2) = @VAL
	BEGIN
		SET @RES = ROUND(ROUND(@VAL * @TAX_REVERSE, 2)/@TAX_QUADRO, 2)
	END
	ELSE
		SET @RES = ROUND(@VAL / @TAX_COEF, 2)

	RETURN @RES
END
