USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE FUNCTION [Ric].[KBUValue]
(
	@PR_ID	SMALLINT
)
RETURNS DECIMAL(10, 4)
AS
BEGIN
	DECLARE @RES DECIMAL(10, 4)

	SELECT @RES = RK_KBU
	FROM 
		Ric.KBU
		INNER JOIN dbo.Quarter ON QR_ID = RK_ID_QUARTER
		INNER JOIN dbo.PeriodTable ON PR_DATE BETWEEN QR_BEGIN AND QR_END
	WHERE PR_ID = @PR_ID

	IF @RES IS NULL
		SET @RES = Ric.KBUCalc(@PR_ID)

	RETURN @RES
END