USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CONFIG_LOAD]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TOP 1
		MAIL_HOST, MAIL_LOGIN, MAIL_PASS, MAIL_NAME, MAIL_ADDRESS, MAIL_TIME, MAIL_TIME2,
		MAIL_SUBJECT, MAIL_FILE_NAME,
		ROBOT_HOST, ROBOT_LOGIN, ROBOT_PASS, ROBOT_EMAIL
	FROM dbo.Config
	ORDER BY UPD_DATE DESC
END
GO
GRANT EXECUTE ON [dbo].[CONFIG_LOAD] TO public;
GO