USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_PERSONAL_SAVE]
	@CLAIM		UNIQUEIDENTIFIER,
	@PERSONAL	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.Claim
	SET PERSONAL	=	@PERSONAL,
		DELIVERY_DATE = GETDATE()
	WHERE ID = @CLAIM
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_PERSONAL_SAVE] TO rl_write;
GO