USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_SEND]
	@ID	UNIQUEIDENTIFIER,
	@TP	INT = 1
AS
BEGIN
	SET NOCOUNT ON;

	IF @TP = 1
		INSERT INTO dbo.ClaimEmail(ID_CLAIM)
			VALUES(@ID)
	ELSE IF @TP = 2
		INSERT INTO dbo.ClaimEmail2(ID_CLAIM)
			VALUES(@ID)
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_SEND] TO rl_robot;
GO