USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_WORK_SAVE]
	@CLAIM		UNIQUEIDENTIFIER,
	@DATE		DATETIME,
	@STATUS		UNIQUEIDENTIFIER,
	@TOTAL_NOTE	NVARCHAR(MAX),
	@DISTR		NVARCHAR(256),
	@MEETING	BIT = NULL,
	@OFFER		BIT = NULL,
	@COMPANY	INT = NULL,
	@MAILING	BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	/*
	IF @ID IS NULL
		INSERT INTO dbo.ClaimWork(ID_CLAIM, DATE, NOTE)
			VALUES(@CLAIM, @DATE, @NOTE)
	ELSE
		UPDATE dbo.ClaimWork
		SET	DATE		=	@DATE,
			NOTE		=	@NOTE,
			UPD_DATE	=	GETDATE(),
			UPD_USER	=	ORIGINAL_LOGIN()
		WHERE ID = @ID
	*/

	UPDATE dbo.Claim
	SET ID_STATUS	=	@STATUS,
		NOTE		=	@TOTAL_NOTE,
		DISTR		=	@DISTR,
		WORK_DATE	=	@DATE,
		MEETING		=	@MEETING,
		OFFER		=	@OFFER,
		COMPANY		=	@COMPANY,
		MAILING		=	@MAILING
	WHERE ID = @CLAIM
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_WORK_SAVE] TO rl_write;
GO