USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CONFIG_SAVE]
	@MAIL_HOST	NVARCHAR(256),
	@MAIL_LOGIN	NVARCHAR(256),
	@MAIL_PASS	NVARCHAR(256),
	@MAIL_NAME	NVARCHAR(256),
	@MAIL_ADDR	NVARCHAR(256),
	@MAIL_TIME	SMALLINT,
	@MAIL_TIME2	SMALLINT,
	@MAIL_SUBJ	NVARCHAR(256),
	@MAIL_FILE	NVARCHAR(MAX),
	@RBT_HOST	NVARCHAR(256),
	@RBT_LOGIN	NVARCHAR(256),
	@RBT_PASS	NVARCHAR(256),
	@RBT_EMAIL	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.Config(
				MAIL_HOST, MAIL_LOGIN, MAIL_PASS, MAIL_NAME, MAIL_ADDRESS, MAIL_TIME, MAIL_TIME2,
				MAIL_SUBJECT, MAIL_FILE_NAME,
				ROBOT_HOST, ROBOT_LOGIN, ROBOT_PASS, ROBOT_EMAIL)
		VALUES(
				@MAIL_HOST, @MAIL_LOGIN, @MAIL_PASS, @MAIL_NAME, @MAIL_ADDR, @MAIL_TIME, @MAIL_TIME2,
				@MAIL_SUBJ, @MAIL_FILE,
				@RBT_HOST, @RBT_LOGIN, @RBT_PASS, @RBT_EMAIL)
END
GO
GRANT EXECUTE ON [dbo].[CONFIG_SAVE] TO rl_robot;
GO