USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_STATUS_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME, IND
	FROM dbo.ClaimStatus
	ORDER BY NAME
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_STATUS_SELECT] TO rl_read;
GO