USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_TYPE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TP, NAME
	FROM dbo.ClaimTypeView
	ORDER BY NAME
END
GRANT EXECUTE ON [dbo].[CLAIM_TYPE_SELECT] TO rl_read;
GO