USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_SPECIAL_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT SPECIAL
	FROM dbo.Claim
	WHERE SPECIAL IS NOT NULL
		AND SPECIAL <> ''
		AND TP = 3
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_SPECIAL_SELECT] TO rl_read;
GO