USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLAIM_IMPORT]
	@TP		TINYINT,
	@NUM	INT,
	@DATE	DATETIME,
	@FIO	NVARCHAR(256),
	@CLIENT	NVARCHAR(256),
	@CITY	NVARCHAR(256),
	@EMAIL	NVARCHAR(256),
	@PHONE	NVARCHAR(256),
	@SPECIAL NVARCHAR(MAX) = NULL,
	@ACTIONS NVARCHAR(MAX) = NULL,
	@PAGEURL	NVARCHAR(256) = NULL,
	@PAGETITLE	NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.Claim(TP, NUM, DATE, FIO, CLIENT, CITY, EMAIL, PHONE, SPECIAL, ACTIONS, PAGE_URL, PAGE_TITLE, ID_STATUS)
		SELECT @TP, @NUM, @DATE, @FIO, @CLIENT, @CITY, @EMAIL, @PHONE, @SPECIAL, @ACTIONS, @PAGEURL, @PAGETITLE, 'f3df1bbe-0315-e711-b717-0007e92aafc5'
		WHERE NOT EXISTS
			(
				SELECT *
				FROM dbo.Claim
				WHERE TP = @TP
					AND NUM = @NUM
					AND DATE = @DATE
					AND FIO = @FIO
					AND CLIENT = @CLIENT
					AND CITY = @CITY
					AND EMAIL = @EMAIL
					AND PHONE = @PHONE
			)
END
GO
GRANT EXECUTE ON [dbo].[CLAIM_IMPORT] TO rl_robot;
GO