USE [VMIClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ROLES_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT MAX(RL_READ) AS RL_READ, MAX(RL_WRITE) AS RL_WRITE, MAX(RL_ROBOT) AS RL_ROBOT, MAX(RL_CALL) AS RL_CALL
	FROM
		(
			SELECT IS_MEMBER('rl_read') AS RL_READ, IS_MEMBER('rl_write') AS RL_WRITE, IS_MEMBER('rl_robot') AS RL_ROBOT, IS_MEMBER('rl_call') AS RL_CALL
			UNION ALL
			SELECT IS_SRVROLEMEMBER('sysadmin') AS RL_READ, IS_SRVROLEMEMBER('sysadmin') AS RL_WRITE, IS_SRVROLEMEMBER('sysadmin') AS RL_ROBOT, 0
		) AS o_O
END
GO
GRANT EXECUTE ON [dbo].[ROLES_SELECT] TO public;
GO