USE [DBF]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	

CREATE FUNCTION [dbo].[GET_PERIOD_LIST_BY_DATE]
(@date SMALLDATETIME)  
RETURNS @tbl TABLE (ITEM SMALLINT NOT NULL) AS
BEGIN
	INSERT INTO @tbl
  		SELECT PR_ID
		FROM dbo.PeriodTable
		WHERE PR_DATE <= DATEADD(MONTH, -1, @date) AND @date <= DATEADD(MONTH, 1, PR_END_DATE)


	-- Возвращение результата работы функции	
	RETURN
END


