USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPLECT_SYSLIST]
(
        [ID]            Int   Identity(1,1)   NOT NULL,
        [COMPLECT_ID]   Int                   NOT NULL,
        [SYSTEM_ID]     Int                   NOT NULL,
        CONSTRAINT [PK_dbo.COMPLECT_SYSLIST] PRIMARY KEY CLUSTERED ([ID]),
        CONSTRAINT [FK_dbo.COMPLECT_SYSLIST(COMPLECT_ID)_dbo.COMPLECT_LIST(ID)] FOREIGN KEY  ([COMPLECT_ID]) REFERENCES [dbo].[COMPLECT_LIST] ([ID])
);GO
GRANT ALTER ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT CONTROL ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT DELETE ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT INSERT ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT REFERENCES ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT SELECT ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GRANT UPDATE ON [dbo].[COMPLECT_SYSLIST] TO COMPLECTBASE;
GO
