USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BLACK_LIST_COMMENT]
(
        [COMMENT_ID]         Int            Identity(1,1)   NOT NULL,
        [COMMENT_NAME]       VarChar(128)                       NULL,
        [COMMENT_FULLNAME]   VarChar(512)                       NULL,
);
GO
GRANT DELETE ON [dbo].[BLACK_LIST_COMMENT] TO BL_ADMIN;
GRANT INSERT ON [dbo].[BLACK_LIST_COMMENT] TO BL_ADMIN;
GRANT SELECT ON [dbo].[BLACK_LIST_COMMENT] TO BL_ADMIN;
GRANT UPDATE ON [dbo].[BLACK_LIST_COMMENT] TO BL_ADMIN;
GRANT SELECT ON [dbo].[BLACK_LIST_COMMENT] TO BL_EDITOR;
GRANT SELECT ON [dbo].[BLACK_LIST_COMMENT] TO BL_PARAM;
GRANT SELECT ON [dbo].[BLACK_LIST_COMMENT] TO BL_READER;
GRANT SELECT ON [dbo].[BLACK_LIST_COMMENT] TO BL_RGT;
GO
