USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [USR].[USRFileData]
(
        [UF_ID]     Int            NOT NULL,
        [UF_DATA]   varbinary      NOT NULL,
        CONSTRAINT [PK_USR.USRFileData] PRIMARY KEY CLUSTERED ([UF_ID]),
        CONSTRAINT [FK_USR.USRFileData(UF_ID)_USR.USRFile(UF_ID)] FOREIGN KEY  ([UF_ID]) REFERENCES [USR].[USRFile] ([UF_ID])
);
GO
