USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[SETTINGS_LOAD]
AS
BEGIN
	SET NOCOUNT ON;

	IF NOT EXISTS
		(
			SELECT *
			FROM Common.Settings
			WHERE USR_NAME = ORIGINAL_LOGIN()
		)
		SELECT CAST(SETTINGS AS NVARCHAR(MAX)) AS SETTINGS
		FROM Common.Settings
		WHERE USR_NAME IS NULL
	ELSE
		SELECT CAST(SETTINGS AS NVARCHAR(MAX)) AS SETTINGS
		FROM Common.Settings
		WHERE USR_NAME = ORIGINAL_LOGIN()
END
