USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[PERIOD_INSERT]
	@TYPE		TINYINT,
	@NAME		NVARCHAR(256),	
	@START		SMALLDATETIME,
	@FINISH		SMALLDATETIME,
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO Common.Period(TYPE, NAME, START, FINISH)
		OUTPUT INSERTED.ID INTO @TBL
		VALUES(@TYPE, @NAME, @START, @FINISH)

	SELECT @ID = ID FROM @TBL
END