USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[PERIOD_ACTIVE_YEAR]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Year Int;
	DECLARE @Active Bit;
	
	SELECT 
		@Year = DatePart(Year, START),
		@Active = ACTIVE
	FROM Common.Period
	WHERE	ID			=	@ID

	UPDATE	Common.Period
	SET		ACTIVE		=	CASE @Active WHEN 1 THEN 0 ELSE 1 END,
			LAST		=	GETDATE()
	WHERE	DatePart(Year, START) = @Year
END
