USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Common].[PERIOD_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@TYPE		TINYINT,
	@NAME		NVARCHAR(256),
	@START		SMALLDATETIME,
	@FINISH		SMALLDATETIME	
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	Common.Period
	SET		NAME		=	@NAME,
			TYPE		=	@TYPE,
			START		=	@START,
			FINISH		=	@FINISH,
			LAST		=	GETDATE()
	WHERE	ID			=	@ID
END