USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[TAX_INSERT]
	@NAME		NVARCHAR(128),
	@CAPTION	NVARCHAR(128),
	@RATE		DECIMAL(6, 2),
	@DEFAULT	BIT,
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO Common.Tax(NAME, CAPTION, RATE, [DEFAULT])
		OUTPUT INSERTED.ID INTO @TBL
		VALUES(@NAME, @CAPTION, @RATE, @DEFAULT)

	SELECT @ID = ID FROM @TBL
END