USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Common].[PERIOD_CURRENT_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		(
			SELECT TOP 1 ID
			FROM Common.Period
			WHERE GETDATE() BETWEEN START AND DATEADD(DAY, 1, FINISH)
				AND TYPE = 2
		) AS MON,
		(
			SELECT TOP 1 ID
			FROM Common.Period
			WHERE DATEADD(MONTH, 1, GETDATE()) BETWEEN START AND DATEADD(DAY, 1, FINISH)
				AND TYPE = 2
		) AS MON_NEXT,
		(
			SELECT TOP 1 ID
			FROM Common.Period
			WHERE GETDATE() BETWEEN START AND DATEADD(DAY, 1, FINISH)
				AND TYPE = 3
		) AS QUART,
		(
			SELECT TOP 1 ID
			FROM Common.Period
			WHERE GETDATE() BETWEEN START AND DATEADD(DAY, 1, FINISH)
				AND TYPE = 4
		) AS HALF,
		(
			SELECT TOP 1 ID
			FROM Common.Period
			WHERE GETDATE() BETWEEN START AND DATEADD(DAY, 1, FINISH)
				AND TYPE = 5
		) AS YR
END