USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Common].[TAX_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@NAME		NVARCHAR(128),
	@CAPTION	NVARCHAR(128),
	@RATE		DECIMAL(6, 2),
	@DEFAULT	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @DEFAULT = 1
		UPDATE Common.Tax
		SET [DEFAULT] = 0
		WHERE [DEFAULT] = 1
			AND ID <> @ID

	UPDATE	Common.Tax
	SET		NAME		=	@NAME,
			CAPTION		=	@CAPTION,
			RATE		=	@RATE,
			[DEFAULT]	=	@DEFAULT,
			LAST		=	GETDATE()
	WHERE	ID			=	@ID
END