USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Contract].[FORM_SAVE]
	@ID UNIQUEIDENTIFIER OUTPUT,
	@NUM	NVARCHAR(128),
	@NAME	NVARCHAR(1024),
	@PATH	NVARCHAR(1024)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
		
		INSERT INTO Contract.Forms(NUM, NAME, FILE_PATH)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@NUM, @NAME, @PATH)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
	BEGIN
		UPDATE Contract.Forms
		SET	NAME = @NAME,
			NUM = @NUM,
			FILE_PATH = @PATH,
			LAST = GETDATE()
		WHERE ID = @ID
	END	
END
