USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[SPECIFICATION_SAVE]
	@ID			UNIQUEIDENTIFIER OUTPUT,
	@NUM		NVARCHAR(128),
	@NAME		NVARCHAR(256),
	@NOTE		NVARCHAR(MAX),
	@FILE_PATH	NVARCHAR(512),
	@FORMS		NVARCHAR(MAX) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
		
		INSERT INTO Contract.Specification(NUM, NAME, NOTE, FILE_PATH)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@NUM, @NAME, @NOTE, @FILE_PATH)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
		UPDATE Contract.Specification
		SET NUM			=	@NUM,
			NAME		=	@NAME,
			NOTE		=	@NOTE,
			FILE_PATH	=	@FILE_PATH,
			LAST		=	GETDATE()
		WHERE ID = @ID
		
	DELETE 
	FROM Contract.SpecificationForms
	WHERE ID_SPECIFICATION = @ID
		AND ID_FORM NOT IN
			(
				SELECT a.ID
				FROM dbo.TableGUIDFromXML(@FORMS) AS a
			)

	INSERT INTO Contract.SpecificationForms(ID_SPECIFICATION, ID_FORM)
		SELECT @ID, a.ID
		FROM dbo.TableGUIDFromXML(@FORMS) AS a
		WHERE NOT EXISTS
			(
				SELECT *
				FROM Contract.SpecificationForms
				WHERE ID_SPECIFICATION = @ID
					AND ID_FORM = a.ID
			)
END
