USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[FORM_SELECT]
	@FILTER NVARCHAR(128) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NUM, NAME, FILE_PATH
	FROM Contract.Forms
	WHERE @FILTER IS NULL
		OR NAME LIKE @FILTER
		OR NUM LIKE @FILTER
	ORDER BY NUM
END
