USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Contract].[SPECIFICATION_SELECT]
	@FILTER	NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NUM, NAME, NOTE, FILE_PATH
	FROM Contract.Specification
	WHERE @FILTER IS NULL
		OR NUM LIKE @FILTER
		OR NAME LIKE @FILTER
		OR NOTE LIKE @FILTER
	ORDER BY NUM	
END
