USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Contract].[CONTRACT_ADDITIONAL_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NUM, REG_DATE, DATE, RETURN_DATE, a.NOTE
	FROM 
		Contract.Additional a
	WHERE ID_CONTRACT = @ID
	ORDER BY NUM, DATE
END
