USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[CONTRACT_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NUM, ID_TYPE, ID_VENDOR, REG_DATE, DATE, ID_YEAR, NOTE, ID_CLIENT, CLIENT, LAW
	FROM Contract.Contract
	WHERE ID = @ID
END
