USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[CLIENT_SPECIFICATION_SELECT]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, ID_SPECIFICATION, b.NAME, a.NUM, a.REG_DATE, a.DATE, FINISH_DATE, a.RETURN_DATE, a.ID_STATUS, c.IND, a.NOTE
	FROM 
		Contract.ContractSpecification a
		INNER JOIN Contract.Contract d ON d.ID = a.ID_CONTRACT
		INNER JOIN Contract.Specification b ON a.ID_SPECIFICATION = b.ID
		INNER JOIN Contract.Status c ON a.ID_STATUS = c.ID
	WHERE ID_CLIENT = @ID
	ORDER BY NUM, DATE
END
