USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[CONTRACT_SPECIFICATION_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, ID_SPECIFICATION, b.NAME, a.NUM, REG_DATE, DATE, FINISH_DATE, RETURN_DATE, a.ID_STATUS, c.IND, a.NOTE
	FROM 
		Contract.ContractSpecification a
		INNER JOIN Contract.Specification b ON a.ID_SPECIFICATION = b.ID
		INNER JOIN Contract.Status c ON a.ID_STATUS = c.ID
	WHERE ID_CONTRACT = @ID
	ORDER BY NUM, DATE
END
