USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Control].[CLIENT_CONTROL_GET]
	@ID UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NOTE, NOTIFY, ID_GROUP, REMOVE_GROUP, REMOVE_AUTHOR, RECEIVER
	FROM Control.ClientControl
	WHERE ID = @ID
END
