USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Contract].[CLIENT_CONTRACT_SELECT_DATES]
	@Contract_Id	UniqueIdentifier
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT DATE
	FROM Contract.ClientContractsDetails
	WHERE Contract_Id = @Contract_Id
	ORDER BY DATE DESC
END
