USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_QUESTION_INSERT]	
	@TEXT	VARCHAR(500),
	@SINGLE	BIT,
	@BOLD	BIT,
	@ORDER	INT,
	@ACTIVE	BIT,
	@ID	UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.SatisfactionQuestion(SQ_TEXT, SQ_SINGLE, SQ_BOLD, SQ_ORDER, SQ_ACTIVE)
		OUTPUT INSERTED.SQ_ID INTO @TBL
		VALUES(@TEXT, @SINGLE, @BOLD, @ORDER, @ACTIVE)

	SELECT @ID = ID FROM @TBL
END