USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_ONLINE_DATA_SELECT]
	@HOST	INT,
	@DISTR	INT,
	@COMP	TINYINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		b.NAME, LGN, CASE ACTIVITY WHEN 1 THEN 'Да' WHEN 0 THEN 'Нет' ELSE '???' END AS ACTIVITY_DATA,
		ACTIVITY, LOGIN_CNT, dbo.TimeMinToStr(SESSION_TIME) AS SESSION_TIME
	FROM 
		dbo.OnlineActivity a
		INNER JOIN Common.Period b ON a.ID_WEEK = b.ID
	WHERE a.ID_HOST = @HOST AND a.DISTR = @DISTR AND a.COMP = @COMP
	ORDER BY b.START DESC
END
