USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[JOURNAL_SELECT]
	@FILTER	NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME, DEF
	FROM dbo.Journal
	WHERE @FILTER IS NULL
		OR NAME LIKE @FILTER		
	ORDER BY NAME
END
