USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SATISFACTION_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CS_ID_TYPE, CS_NOTE, CS_TYPE
	FROM dbo.ClientSatisfaction
	WHERE CS_ID_CALL = @ID
END