USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_SYSTEM_DELIVERY]
	@ID		VARCHAR(MAX),
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientSystemsTable
	SET ClientID = @CLIENT
	WHERE ID IN
		(
			SELECT ID
			FROM dbo.TableIDFromXML(@ID)
		)
END