USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISCONNECT_REASON_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.DisconnectReason
	SET DR_NAME = @NAME,
		DR_LAST = GETDATE()
	WHERE DR_ID = @ID
END