USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ORI_CONTRACT_INSERT]	
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@SYSTEM	VARCHAR(MAX),
	@NOTE	VARCHAR(MAX),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.OriContractTable(ClientID, OriContractDate, OriContractSystem, OriContractNote)
		VALUES(@CLIENT, @DATE, @SYSTEM, @NOTE)
	
	SELECT @ID = SCOPE_IDENTITY()
END