USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DEBT_SAVE]
	@ID		UNIQUEIDENTIFIER,
	@CLIENT	INT,
	@DEBT	UNIQUEIDENTIFIER,
	@START	UNIQUEIDENTIFIER,
	@FINISH	UNIQUEIDENTIFIER,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.ClientDebt(ID_CLIENT, ID_DEBT, START, FINISH, NOTE)
			VALUES(@CLIENT, @DEBT, @START, @FINISH, @NOTE)
	ELSE
		UPDATE dbo.ClientDebt
		SET ID_DEBT	=	@DEBT,
			START	=	@START,
			FINISH	=	@FINISH,
			NOTE	=	@NOTE
		WHERE ID = @ID
END
