USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[INNOVATION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(256),
	@NOTE	NVARCHAR(MAX),
	@START	SMALLDATETIME,
	@FINISH	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.Innovation
	SET NAME	=	@NAME,
		NOTE	=	@NOTE,
		START	=	@START,
		FINISH	=	@FINISH,
		LAST	=	GETDATE()
	WHERE ID = @ID
END
