USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VISIT_PAY_UPDATE]
	@ID	INT,
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@VALUE	MONEY
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE dbo.VisitPayTable
	SET VisitPayBegin = @BEGIN,
		VisitPayEnd = @END,
		VisitPayValue = @VALUE
	WHERE VisitPayID = @ID
END