USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISTR_STATUS_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(64),
	@REG	TINYINT,
	@IMAGE	VARBINARY(MAX),
	@INDEX	TINYINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.DistrStatus
	SET DS_NAME = @NAME,
		DS_REG = @REG,
		DS_IMAGE = @IMAGE,
		DS_INDEX = @INDEX,
		DS_LAST = GETDATE()
	WHERE DS_ID = @ID
END