USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DEBT_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@SHORT	NVARCHAR(32),
	@NAME	VARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.DebtType
	SET SHORT = @SHORT,
		NAME = @NAME,
		LAST = GETDATE()
	WHERE ID = @ID
END