USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[REF_VALUE_COLUMN_GET]
	@REF_NAME	NVARCHAR(128)
AS
BEGIN
	SELECT ValueColumn
	FROM dbo.RefColumnMeta
	WHERE RefName = @REF_NAME
END

