USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@DAY	INT,
	@DAILY	INT,
	@PAPPER	SMALLINT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientTypeTable(ClientTypeName, ClientTypeDailyDay, ClientTypeDay, ClientTypePapper)
		VALUES(@NAME, @DAILY, @DAY, @PAPPER)

	SELECT @ID = SCOPE_IDENTITY()
END