USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[INFO_BANK_INSERT]	
	@NAME	VARCHAR(20),
	@SHORT	VARCHAR(20),
	@FULL	VARCHAR(250),
	@ORDER	INT,
	@PATH	VARCHAR(255),
	@ACTIVE	BIT,
	@DAILY	BIT,
	@ACTUAL	BIT,	
	@ID	INT = NULL OUTPUT,
	@START	SMALLDATETIME = NULL
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.InfoBankTable(
		InfoBankName, InfoBankShortName, InfoBankFullName, InfoBankOrder, 
		InfoBankPath, InfoBankActive, InfoBankDaily, InfoBankActual, InfoBankStart)
	VALUES(@NAME, @SHORT, @FULL, @ORDER, @PATH, @ACTIVE, @DAILY, @ACTUAL, @START)
	
	SELECT @ID = SCOPE_IDENTITY()
END
