USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_DELETE]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
	
	INSERT INTO dbo.ClientStudy(ID_MASTER, ID_CLIENT, ID_CLAIM, DATE, ID_PLACE, ID_TEACHER, NEED, RECOMEND, NOTE, TEACHED, ID_TYPE, STATUS, UPD_DATE, UPD_USER)
		OUTPUT inserted.ID INTO @TBL 
		SELECT ID, ID_CLIENT, ID_CLAIM, DATE, ID_PLACE, ID_TEACHER, NEED, RECOMEND, NOTE, TEACHED, ID_TYPE, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientStudy
		WHERE ID = @ID
		
	DECLARE @NEWID UNIQUEIDENTIFIER
	
	SELECT @NEWID = ID
	FROM @TBL
	
	UPDATE dbo.ClientStudy
	SET STATUS		=	3,
		UPD_DATE	=	GETDATE(),
		UPD_USER	=	ORIGINAL_LOGIN()
	WHERE ID = @ID
	
	UPDATE dbo.ClientStudyPeople
	SET ID_STUDY = @NEWID
	WHERE ID_STUDY = @ID
		
	INSERT INTO dbo.ClientStudyPeople(ID_STUDY, SURNAME, NAME, PATRON, POSITION, NUM, GR_COUNT, ID_SERT_TYPE, SERT_COUNT, NOTE, ID_RDD_POS)
		SELECT 
			@ID, SURNAME, NAME, PATRON, POSITION, NUM, GR_COUNT, ID_SERT_TYPE, SERT_COUNT, NOTE, ID_RDD_POS
		FROM dbo.ClientStudyPeople
		WHERE ID_STUDY = @NEWID
END
