USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[EVENT_TYPE_INSERT]
	@NAME	VARCHAR(50),
	@REPORT	BIT,
	@HIDE	BIT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.EventTypeTable(EventTypeName, EventTypeReport, EventTypeHide)
		VALUES(@NAME, @REPORT, @HIDE)
	
	SELECT @ID = SCOPE_IDENTITY()
END