USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CALL_INSERT]
	@CLIENT		INT,
	@DATE		SMALLDATETIME,
	@PERSONAL	VARCHAR(250),
	@SERVICE	VARCHAR(150),
	@NOTE		VARCHAR(MAX),
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.ClientCall(CC_ID_CLIENT, CC_DATE, CC_PERSONAL, CC_SERVICE, CC_NOTE)
		OUTPUT INSERTED.CC_ID INTO @TBL
		VALUES(@CLIENT, @DATE, @PERSONAL, @SERVICE, @NOTE)

	SELECT @ID = ID FROM @TBL
END