USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DBF_DETAIL_SELECT]
	@ID	INT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;	

	SELECT 
		TO_NAME, CL_PSEDO, CL_FULL_NAME, TO_INN, ACTIVITY,
		TA_INDEX, TA_HOME, ADDR_STR, STREET_ID,
		DIR_SURNAME, DIR_NAME, DIR_OTCH, DIR_POS, DIR_PHONE,
		BUH_SURNAME, BUH_NAME, BUH_OTCH, BUH_POS, BUH_PHONE,
		RES_SURNAME, RES_NAME, RES_OTCH, RES_POS, RES_PHONE
	FROM dbo.DBFTODetailView
	WHERE TO_ID = @ID
END
