USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFO_PANEL_SELECT]
	@FILTER	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, TEXT, DETAIL
	FROM dbo.InfoPanel
	WHERE @FILTER IS NULL
		OR TEXT LIKE @FILTER
		OR DETAIL LIKE @FILTER
	ORDER BY TEXT
END
