USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VENDOR_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, SHORT, FULL_NAME, DIRECTOR
	FROM dbo.Vendor
	WHERE @FILTER IS NULL
		OR FULL_NAME LIKE @FILTER
		OR SHORT LIKE @FILTER
		OR DIRECTOR LIKE @FILTER
	ORDER BY SHORT
END