USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RIVAL_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.RivalTypeTable(RivalTypeName)
		VALUES(@NAME)
		
	SELECT @ID = SCOPE_IDENTITY()
END