USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[RES_VERSION_INSERT]	
	@NUMBER	VARCHAR(100),
	@LATEST	BIT,
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ResVersionTable(
			ResVersionNumber, ResVersionBegin, ResVersionEnd, IsLatest
		)
		VALUES(@NUMBER, @BEGIN, @END, @LATEST)

	SELECT @ID = SCOPE_IDENTITY()
END