USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[RANGE_UPDATE]
	@ID	INT,
	@VALUE	DECIMAL(8, 4)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.RangeTable
	SET RangeValue = @VALUE,
		RangeLast = GETDATE()
	WHERE RangeID = @ID
END