USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DOCUMENT_TYPE_SAVE]
	@ID UNIQUEIDENTIFIER OUTPUT,
	@NAME	NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
		
		INSERT INTO dbo.DocumentType(NAME)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@NAME)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
	BEGIN
		UPDATE dbo.DocumentType
		SET NAME = @NAME,
			LAST = GETDATE()
		WHERE ID = @ID
	END
END
