USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_ERROR_REASON_SAVE]
	@ID		UNIQUEIDENTIFIER OUTPUT,
	@TP		NVARCHAR(128),
	@NAME	NVARCHAR(128),
	@GROUP	UNIQUEIDENTIFIER,
	@TYPE	TINYINT,
	@ORD	INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
	
	IF @ID IS NULL
		INSERT INTO dbo.ClientErrorReason(TP, NAME, ID_GROUP, RS_TYPE, ORD)
			OUTPUT inserted.ID INTO @TBL
			SELECT @TP, @NAME, @GROUP, @TYPE, ISNULL((SELECT MAX(ORD) + 1 FROM dbo.ClientErrorReason WHERE TP = @TP), 1)
	ELSE
		UPDATE dbo.ClientErrorReason
		SET NAME	=	@NAME,
			ORD		=	@ORD
		WHERE ID = @ID
		
	IF @ID IS NULL
		SELECT @ID = ID
		FROM @TBL
END
