USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_JOURNAL_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientJournal(ID_MASTER, ID_CLIENT, ID_JOURNAL, START, FINISH, NOTE, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_CLIENT, ID_JOURNAL, START, FINISH, NOTE, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientJournal
		WHERE ID = @ID
		
	UPDATE dbo.ClientJournal
	SET STATUS		=	3,
		UPD_DATE	=	GETDATE(),
		UPD_USER	=	ORIGINAL_LOGIN()
	WHERE ID = @ID
END
