USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[LAWYER_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@SHORT	VARCHAR(50),
	@FULL	VARCHAR(250),
	@LOGIN	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.Lawyer
	SET LW_SHORT = @SHORT,
		LW_FULL = @FULL,
		LW_LOGIN = @LOGIN,
		LW_LAST = GETDATE()
	WHERE LW_ID = @ID
END