USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFO_PANEL_USER_GET]
	@PANEL	UNIQUEIDENTIFIER
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT 
		US_ID, US_SQL_NAME, US_NAME, US_USER, 
		CONVERT(BIT, CASE WHEN EXISTS
			(
				SELECT *
				FROM dbo.InfoPanelUser
				WHERE ID_PANEL = @PANEL
					AND USR_NAME = US_SQL_NAME
			) THEN 1
			ELSE 0
		END) AS CHECKED
	FROM Security.UserView a	
	ORDER BY US_USER, US_NAME	
END
