USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[POSITION_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PositionTypeID, PositionTypeName
	FROM dbo.PositionTypeTable
	WHERE @FILTER IS NULL
		OR PositionTypeName LIKE @FILTER
	ORDER BY PositionTypeName
END