USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_ANSWER_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@TEXT	VARCHAR(500),
	@ORDER	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SatisfactionAnswer
	SET SA_TEXT = @TEXT,
		SA_ORDER = @ORDER
	WHERE SA_ID = @ID
END