USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_QUESTION_DELETE]
	@id INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.ClientQuestionTable	
	WHERE ClientQuestionID = @id	
END