USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RICH_COEF_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RichCoefID, RichCoefStart, RichCoefEnd, RichCoefVal
	FROM dbo.RichCoefTable
	ORDER BY RichCoefVal
END