USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SYSTEM_PREPARE]
	@CLIENT	INT,
	@TEXT	VARCHAR(100) = NULL OUTPUT,
	@COLOR	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SET @TEXT = NULL
	
	SET @COLOR = 0

	/*
	IF EXISTS
		(
			SELECT * 
			FROM dbo.ClientSystemView 
			WHERE ClientID = @CLIENT
				AND REG_ERROR <> ''
		)
		SET @COLOR = 1
	*/
END