USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[KGS_DISTR_LIST_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT KDL_ID, KDL_NAME
	FROM dbo.KGSDistrList
	WHERE @FILTER IS NULL
		OR KDL_NAME LIKE @FILTER
		OR EXISTS
			(
				SELECT *
				FROM dbo.KGSDistr
				WHERE KD_ID_LIST = KDL_ID
					AND CONVERT(VARCHAR(20), KD_DISTR) LIKE @FILTER
			)
	ORDER BY KDL_NAME
END