USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DUTY_INSERT]	
	@NAME	VARCHAR(100),
	@LOGIN	VARCHAR(100),
	@ACTIVE	BIT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.DutyTable(DutyName, DutyLogin, DutyActive)
		VALUES(@NAME, @LOGIN, @ACTIVE)
		
	SELECT @ID = SCOPE_IDENTITY()
END