USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_RIVAL_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CR_DATE, CR_ID_TYPE, CR_CONDITION, CR_ID_STATUS, CR_SURNAME, CR_NAME, CR_PATRON, CR_PHONE
	FROM dbo.ClientRival
	WHERE CR_ID = @ID
END