USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HOTLINE_DISTR_SET]
	@HOST	INT,
	@DISTR	INT,
	@COMP	INT,
	@STATE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @STATE = 1 AND NOT EXISTS (SELECT * FROM dbo.HotlineDistr WHERE ID_HOST = @HOST AND DISTR = @DISTR AND COMP = @COMP AND STATUS = 1)
		INSERT INTO dbo.HotlineDistr(ID_HOST, DISTR, COMP)
			VALUES(@HOST, @DISTR, @COMP)
	ELSE IF @STATE = 0 AND EXISTS (SELECT * FROM dbo.HotlineDistr WHERE ID_HOST = @HOST AND DISTR = @DISTR AND COMP = @COMP AND STATUS = 1)
		UPDATE dbo.HotlineDistr
		SET STATUS = 2,
			UNSET_DATE = GETDATE(),
			UNSET_USER = ORIGINAL_LOGIN()
		WHERE ID_HOST = @HOST AND DISTR = @DISTR AND COMP = @COMP AND STATUS = 1
END
