USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_QUALITY_TYPE_SELECT]
	@FILTER	NVARCHAR(512) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME
	FROM dbo.StudyQualityType
	ORDER BY NAME
END
