USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Выборка всех систем клиента

CREATE PROCEDURE [dbo].[DELETE_BLACKLIST_SYSTEMS]
@ID INT,
@COMMENT varchar(300) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON

    UPDATE dbo.BLACK_LIST_REG 
	SET 
	COMMENT_DELETE=@COMMENT,
	U_LOGIN_DELETE=ORIGINAL_LOGIN(),
	DATE_DELETE=GETDATE(),
	P_DELETE=1
	WHERE ID = @ID
	SET NOCOUNT OFF
END