USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[OWNERSHIP_UPDATE]
	@ID	INT,
	@NAME	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.OwnershipTable
	SET OwnershipName = @NAME
	WHERE OwnershipID = @ID
END