USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PAY_TYPE_UPDATE]
	@ID	INT,
	@NAME	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.PayTypeTable
	SET PayTypeName = @NAME,
		PayTypeLast = GETDATE()
	WHERE PayTypeID = @ID
END