USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ACT_CALC_CONFIRM]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ActCalc
	SET CONFIRM_NEED = 0,
		CONFIRM_USER = ORIGINAL_LOGIN(),
		CONFIRM_DATE = GETDATE()
	WHERE ID = @ID
END
