USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DELIVERY_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, b.NAME, a.EMAIL, a.START, a.FINISH, a.NOTE
	FROM 
		dbo.ClientDelivery a
		INNER JOIN dbo.Delivery b ON a.ID_DELIVERY = b.ID
	WHERE a.ID_CLIENT = @CLIENT
	ORDER BY START DESC, FINISH
END
