USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_KIND_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT Id, Name, SortIndex
	FROM dbo.ClientKind
	WHERE	@FILTER IS NULL
		OR	Name LIKE @FILTER
	ORDER BY SortIndex
END
