USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_STUDY_CLAIM_WORK_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TP, DATE, NOTE
	FROM dbo.ClientStudyClaimWork
	WHERE ID = @ID
END
