USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_EVENT_PERSONAL_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT EventCreateUser
	FROM dbo.EventTable
	WHERE EventID = MasterID AND EventCreateUser IS NOT NULL AND EventCreateUser <> ''
	ORDER BY EventCreateUser
END
