USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AREA_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AR_NAME, AR_ID_REGION, AR_PREFIX, AR_SUFFIX
	FROM dbo.Area
	WHERE AR_ID = @ID
END