USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SEARCH_HISTORY_DELETE_LAST]
	@CLIENTID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @DATE DATETIME

	SELECT @DATE = MAX(SearchGet)
	FROM dbo.ClientSearchTable
	WHERE ClientID = @CLIENTID

	DELETE FROM dbo.ClientSearchTable
	WHERE ClientID = @CLIENTID AND SearchGet = @DATE
END