USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[RIVAL_STATUS_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RS_ID, RS_NAME
	FROM dbo.RivalStatus
	WHERE @FILTER IS NULL
		OR RS_NAME LIKE @FILTER
	ORDER BY RS_NAME
END