USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ORI_CONTRACT_UPDATE]
	@ID	INT,
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@SYSTEM	VARCHAR(MAX),
	@NOTE	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.OriContractTable
	SET OriContractDate = @DATE,
		OriContractSystem = @SYSTEM,
		OriContractNote = @NOTE
	WHERE OriContractID = @ID
END