USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ADDRESS_TYPE_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@NAME		VARCHAR(100),
	@REQUIRED	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.AddressType
	SET		AT_NAME		=	@NAME,
			AT_REQUIRED	=	@REQUIRED,
			AT_LAST		=	GETDATE()
	WHERE	AT_ID	=	@ID
END