USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MAILING_LOG_ADD]
	@TYPE_ID	SMALLINT,
	@ADDRESS	NVARCHAR(129),
	@SUBJ		NVARCHAR(50),
	@BODY		NVARCHAR(MAX),
	@STATUS		SMALLINT,
	@ERROR		NVARCHAR(255) = NULL,
	@DATE		DATETIME = NULL
AS
BEGIN
	IF @DATE IS NULL
		SET @DATE = GETDATE()

	INSERT INTO Common.MailingLog([TypeID], [Address], [Subject], [Body], [Date], [Status], [Error])	
	VALUES (@TYPE_ID, @ADDRESS, @SUBJ, @BODY, @DATE, @STATUS, @ERROR)
END