USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DISCONNECT_REASON_CHANGE]
	@ID		UNIQUEIDENTIFIER,
	@REASON	UNIQUEIDENTIFIER,
	@NOTE	VARCHAR(MAX),
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientDisconnect
	SET CD_ID_REASON	=	@REASON,
		CD_NOTE			=	@NOTE,
		CD_DATE			=	@DATE
	WHERE CD_ID = @ID
END
