USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_VISIT_DAY]	
AS
BEGIN
	SET NOCOUNT ON;
  
	SELECT DayID, DayName, DayOrder
	FROM dbo.DayTable 
	ORDER BY DayOrder
END