USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[INFO_PANEL_SAVE]
	@ID		UNIQUEIDENTIFIER,
	@TEXT	NVARCHAR(512),
	@DETAIL	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.InfoPanel(TEXT, DETAIL)
			VALUES(@TEXT, @DETAIL)
	ELSE
		UPDATE dbo.InfoPanel
		SET TEXT	=	@TEXT,
			DETAIL	=	@DETAIL
		WHERE ID = @ID
END
