USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SET_BLACKLIST_PARAM]
@PARAMNAME varchar(50),
@ParamValue varchar(2048)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON

	if EXISTS (
	SELECT ID
	FROM dbo.BLACK_LIST_PARAMS
	WHERE PARAMNAME=@PARAMNAME)
	BEGIN
		UPDATE dbo.BLACK_LIST_PARAMS SET PARAMVALUE=@ParamValue
		WHERE PARAMNAME=@PARAMNAME
	END
	ELSE 
	BEGIN
		INSERT INTO dbo.BLACK_LIST_PARAMS (PARAMNAME,PARAMVALUE)
		VALUES (@PARAMNAME, @ParamValue)
	END
	SET NOCOUNT OFF
END