USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GET_VISIT_PAY] 
AS
BEGIN
	SET NOCOUNT ON

	SELECT VisitPayID, VisitPayValue 
	FROM dbo.VisitPayTable
	ORDER BY VisitPayBegin DESC
END