USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONTRACT_REGISTER_SELECT]
	@ID	INT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT C.ID, NUM_S, ID_VENDOR, VEN_NAME = V.SHORT, DATE, CLIENT, SORT_INDEX = CASE WHEN C.ID_CLIENT = @ID THEN 1 ELSE 2 END
	FROM Contract.Contract	C
	INNER JOIN dbo.Vendor	V ON C.ID_VENDOR = V.ID
	ORDER BY
		SORT_INDEX, DATE DESC, NUM DESC
END
