USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_MESSAGE_CHECK]
	@RES	TINYINT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	IF EXISTS
		(
			SELECT *
			FROM dbo.ClientMessage
			WHERE RECEIVE_USER = ORIGINAL_LOGIN()
				AND REMIND_DATE < GETDATE()
				AND RECEIVE_DATE IS NULL
				AND STATUS = 1
		)
		SET @RES = 1
	ELSE
		SET @RES = 0
END
