USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SERVICE_STATE_SELECT]
	@SERVICE	INT,
	@DATE		DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ID UNIQUEIDENTIFIER
	
	SELECT @ID = ID, @DATE = DATE
	FROM dbo.ServiceState
	WHERE ID_SERVICE = @SERVICE AND STATUS = 1	

	IF OBJECT_ID('tempdb..#t') IS NOT NULL
		DROP TABLE #t
		
	CREATE TABLE #t
		(
			ID			UNIQUEIDENTIFIER PRIMARY KEY,
			ID_MASTER	UNIQUEIDENTIFIER,
			TP_NAME		NVARCHAR(32),
			TP_ORD		INT,
			TP_NOTE		NVARCHAR(512),			
			CNT			INT,
			NOTE		NVARCHAR(MAX)
		)
		
	INSERT INTO #t(ID, TP_NAME, TP_ORD, TP_NOTE, CNT)		
		SELECT NEWID() AS ID, TP_NAME, TP_ORD, TP_NOTE,
			(
				SELECT COUNT(*)
				FROM dbo.ServiceStateDetail z
				WHERE TP = TP_NAME
					AND ID_STATE = @ID
			) AS CNT
		FROM 
			(
				SELECT DISTINCT TP
				FROM dbo.ServiceStateDetail
			) AS a
			INNER JOIN dbo.ServiceStateTypeView AS b ON a.TP = b.TP_NAME 

	INSERT INTO #t(ID, ID_MASTER, TP_NOTE, NOTE)
		SELECT NEWID(), (SELECT ID FROM #t WHERE TP_NAME = TP), ClientFullName, DETAIL
		FROM 
			dbo.ServiceStateDetail
			INNER JOIN dbo.ClientTable ON ClientID = ID_CLIENT
		WHERE ID_STATE = @ID

	SELECT ID, ID_MASTER, TP_NOTE, CASE WHEN CNT IS NOT NULL THEN CONVERT(NVARCHAR(MAX), CNT) ELSE NOTE END AS NOTE, TP_NAME, TP_ORD
	FROM #t
	ORDER BY TP_ORD, TP_NOTE
END
