USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_PERSONAL_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CPT_ID, CPT_NAME, CPT_PSEDO, CPT_REQUIRED
	FROM dbo.ClientPersonalType
	WHERE @FILTER IS NULL
		OR CPT_NAME LIKE @FILTER
		OR CPT_PSEDO LIKE @FILTER		
	ORDER BY CPT_REQUIRED DESC, CPT_ORDER, CPT_NAME
END