USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[KD_VERSION_INSERT]	
	@NAME	NVARCHAR(128),
	@SHORT	NVARCHAR(64),
	@ACTIVE	BIT,
	@START	SMALLDATETIME,
	@FINISH	SMALLDATETIME,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.KDVersion(
			NAME, SHORT, ACTIVE, START, FINISH
		)
		OUTPUT inserted.ID INTO @TBL
		VALUES(@NAME, @SHORT, @ACTIVE, @START, @FINISH)

	SELECT @ID = ID FROM @TBL
END
