USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USR_FILE_KIND_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT USRFileKindID, USRFileKindName, USRFileKindShortName, USRFileKindShort
	FROM dbo.USRFileKindTable
	WHERE @FILTER IS NULL
		OR USRFileKindName LIKE @FILTER
		OR USRFileKindShortName LIKE @FILTER
		OR USRFileKindShort LIKE @FILTER
	ORDER BY USRFileKindName
END