USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SERVICE_TYPE_INSERT]	
	@NAME		VARCHAR(100),
	@SHORT		VARCHAR(50),
	@VISIT		BIT,
	@DEFAULT	BIT,
	@ID			INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ServiceTypeTable(
			ServiceTypeName, ServiceTypeShortName, ServiceTypeVisit, ServiceTypeDefault)
		VALUES(@NAME, @SHORT, @VISIT, @DEFAULT)
		
	SELECT @ID = SCOPE_IDENTITY()
END