USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_MANAGER_SENDER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT SENDER
	FROM Task.Tasks
	WHERE STATUS = 1 AND ID_CLIENT IS NOT NULL
	
	UNION
	
	SELECT DISTINCT PERSONAL
	FROM dbo.ClientContact
	WHERE STATUS = 1
	
	ORDER BY SENDER
END
