USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[HOSTS_INSERT]	
	@SHORT	VARCHAR(50),
	@REG	VARCHAR(50),
	@ORDER	INT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO dbo.Hosts(HostShort, HostReg, HostOrder)
		VALUES(@SHORT, @REG, @ORDER)
	
	SET @ID = SCOPE_IDENTITY()
END