USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SYSTEM_UPDATE]
	@ID		INT,
	@CLIENT	INT,
	@SYSTEM	INT,
	@DISTR	INT,
	@COMP	TINYINT,
	@STYPE	INT,
	@DTYPE	INT,
	@STATUS	UNIQUEIDENTIFIER,
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientSystemsTable
	SET	SystemID		=	@SYSTEM, 
		SystemDistrNumber	=	@DISTR, 
		CompNumber		=	@COMP, 
		SystemTypeID	=	@STYPE, 
		DistrTypeID		=	@DTYPE, 
		DistrStatusID	=	@STATUS
	WHERE ID = @ID

	
	DECLARE @BDATE SMALLDATETIME
	DECLARE @EDATE SMALLDATETIME

	SELECT TOP 1 @BDATE = SystemBegin, @EDATE = SystemEnd
	FROM dbo.ClientSystemDatesTable 
	WHERE IDMaster = @ID
	ORDER BY SystemDate DESC

	IF 
		(
			(@BDATE IS NOT NULL AND @BEGIN IS NOT NULL) AND
			(@BDATE <> @BEGIN)
		) OR
		(
			@BDATE IS NULL AND @BEGIN IS NOT NULL
		) OR
		(
			@BDATE IS NOT NULL AND @BEGIN IS NULL
		) OR
		(
			(@EDATE IS NOT NULL AND @END IS NOT NULL) AND
			(@EDATE <> @END)
		) OR
		(
			@EDATE IS NULL AND @END IS NOT NULL
		) OR
		(
			@EDATE IS NOT NULL AND @END IS NULL
		)
	BEGIN
		INSERT INTO dbo.ClientSystemDatesTable (IDMaster, SystemBegin, SystemEnd)
			VALUES(@ID, @BEGIN, @END)
	END
END