USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SYSTEM_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SystemTypeID, SystemTypeName
	FROM dbo.SystemTypeTable
	WHERE @FILTER IS NULL
		OR SystemTypeName LIKE @FILTER
	ORDER BY SystemTypeName
END