USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_SATISFACTION_ANSWER_PROCESS]
	@CSQ_ID	UNIQUEIDENTIFIER,
	@SA_ID	UNIQUEIDENTIFIER,
	@CHECKED	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @CHECKED = 0
		DELETE FROM dbo.ClientSatisfactionAnswer 
		WHERE CSA_ID_QUESTION = @CSQ_ID
			AND CSA_ID_ANSWER = @SA_ID
	ELSE
	BEGIN
		INSERT INTO dbo.ClientSatisfactionAnswer(CSA_ID_QUESTION, CSA_ID_ANSWER)
			SELECT @CSQ_ID, @SA_ID
			WHERE NOT EXISTS
				(
					SELECT *
					FROM dbo.ClientSatisfactionAnswer
					WHERE CSA_ID_QUESTION = @CSQ_ID
						AND CSA_ID_ANSWER = @SA_ID
				)
	END
END