USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_PERSONAL_TYPE_INSERT]
	@NAME		VARCHAR(100),
	@PSEDO		VARCHAR(50),
	@REQUIRED	BIT,	
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.ClientPersonalType(CPT_NAME, CPT_PSEDO, CPT_REQUIRED)
		OUTPUT INSERTED.CPT_ID INTO @TBL
		VALUES(@NAME, @PSEDO, @REQUIRED)
	
	SELECT @ID = ID FROM @TBL
END