USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[POSITION_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.PositionTypeTable(PositionTypeName)
		VALUES(@NAME)

	SELECT @ID = SCOPE_IDENTITY()
END