USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PERSONAL_INSERT]	
	@DEP	VARCHAR(50),
	@SHORT	VARCHAR(50),
	@FULL	VARCHAR(500),
	@ID		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.PersonalTable(DepartmentName, PersonalShortName, PersonalFullName)
		VALUES(@DEP, @SHORT, @FULL)

	SELECT @ID = SCOPE_IDENTITY()
END