USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DISTR_INSERT]
	@CLIENT	INT,
	@SYSTEM	INT,
	@DISTR	INT,
	@COMP	TINYINT,
	@STYPE	INT,
	@DTYPE	INT,
	@STATUS	UNIQUEIDENTIFIER,
	@BEGIN	SMALLDATETIME,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.ClientDistr(ID_CLIENT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_TYPE, ID_NET, ID_STATUS, ON_DATE)
		OUTPUT inserted.ID INTO @TBL
		SELECT @CLIENT, HostID, @SYSTEM, @DISTR, @COMP, @STYPE, @DTYPE, @STATUS, @BEGIN
		FROM dbo.SystemTable
		WHERE SystemID = @system

	SELECT @ID = ID FROM @TBL
	
	IF (SELECT Maintenance.GlobalClientAutoClaim()) = 1
	BEGIN			
		INSERT INTO dbo.ClientStudyClaim(ID_CLIENT, DATE, NOTE, REPEAT, UPD_USER)
			SELECT @CLIENT, dbo.Dateof(GETDATE()), 'Новый дистриубтив', 0, 'Автомат'
			WHERE NOT EXISTS
				(
					SELECT *
					FROM dbo.ClientStudyClaim a
					WHERE ID_CLIENT = @CLIENT
						AND UPD_USER = 'Автомат'
				)
		
		EXEC dbo.CLIENT_REINDEX_CURRENT @CLIENT
	END
END