USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_RIVAL_PRINT]
	@CL_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CR_ID, CR_DATE, RivalTypeName, CR_COMPLETE, 
		CR_CONTROL, CR_CONTROL_DATE, CR_CONDITION,

		CRR_DATE, CRR_COMMENT
	FROM
		dbo.ClientRival
		LEFT OUTER JOIN dbo.RivalTypeTable ON RivalTypeID = CR_ID_TYPE
		LEFT OUTER JOIN dbo.ClientRivalReaction ON CR_ID = CRR_ID_RIVAL
	WHERE CR_ACTIVE = 1 AND ISNULL(CRR_ACTIVE, 1) = 1
		AND CL_ID = @CL_ID
	ORDER BY CR_DATE DESC, CR_ID, CRR_DATE DESC
END