USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SUBHOST_COMPLECT_CLEAR]
	@HOST	INT,
	@DISTR	INT,
	@COMP	TINYINT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.SubhostComplect
	WHERE SC_ID_HOST	=	@HOST
		AND SC_DISTR	=	@DISTR
		AND SC_COMP		=	@COMP
END
