USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(128),
	@PSEDO	NVARCHAR(64)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.StudyType
	SET		NAME	=	@NAME,
			PSEDO	=	@PSEDO,
			LAST	=	GETDATE()
	WHERE	ID	=	@ID
END
