USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ORI_PERSON_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OriPersonID, OriPersonName, OriPersonPhone, OriPersonPlace
	FROM dbo.OriPersonTable
	WHERE ClientID = @CLIENT
	ORDER BY OriPersonName
END