USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DELIVERY_INCLUDE]
	@ID		UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientDelivery(ID_CLIENT, ID_DELIVERY, EMAIL, START, NOTE)
		SELECT ID_CLIENT, ID_DELIVERY, EMAIL, @DATE, NOTE
		FROM dbo.ClientDelivery
		WHERE ID = @ID
END
