USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONTACT_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC [dbo].[CLIENT_CONTACT_ARCH] @ID

	UPDATE dbo.ClientContact
	SET STATUS = 3,
		UPD_DATE = GETDATE(),
		UPD_USER = ORIGINAL_LOGIN()		
	WHERE ID = @ID
END
