USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_WORK_SELECT]
	@CLIENT	INT,
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@TYPE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ClientID, TP, DT, NOTE, AUTHOR
	FROM dbo.ClientWorkView
	WHERE ClientID = @CLIENT
		AND (DT >= @BEGIN OR @BEGIN IS NULL)
		AND (DT <= @END OR @END IS NULL)
		AND 
			(
				TP IN (SELECT ID FROM dbo.TableStringFromXML(@TYPE))
				OR @TYPE IS NULL
			)
	ORDER BY DT DESC, TP
END
