USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ADDRESS_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AT_ID, AT_NAME, AT_REQUIRED
	FROM dbo.AddressType
	WHERE @FILTER IS NULL
		OR AT_NAME LIKE @FILTER
	ORDER BY AT_NAME
END