USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[LOCK_DELETE]
	@ID	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.Locks
	WHERE LC_ID IN (SELECT ID FROM dbo.TableGUIDFromXML(@ID))
END