USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_ERROR_SAVE]
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT,
	@CLIENT	INT,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.ClientError(ID_CLIENT, NOTE)
			VALUES(@CLIENT, @NOTE)
	ELSE
	BEGIN
		INSERT INTO dbo.ClientError(ID_MASTER, ID_CLIENT, NOTE, STATUS, UPD_DATE, UPD_USER)
			SELECT @ID, ID_CLIENT, NOTE, 2, UPD_DATE, UPD_USER
			FROM dbo.ClientError
			WHERE ID = @ID
			
		UPDATE dbo.ClientError
		SET NOTE		=	@NOTE,
			UPD_DATE	=	GETDATE(),
			UPD_USER	=	ORIGINAL_LOGIN()
		WHERE ID = @ID
	END
END
