USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[HOTLINE_PERSONAL_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT Item AS PERSONAL
	FROM
		(
			SELECT DISTINCT RIC_PERSONAL
			FROM dbo.HotlineChat
		) AS a
		CROSS APPLY
		(
			SELECT Item
			FROM dbo.GET_STRING_TABLE_FROM_LIST(RIC_PERSONAL, ',')
		) AS b
	ORDER BY PERSONAL
END
