USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_EVENT_GET]
	@ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT EventDate, EventComment, EventTypeID
	FROM dbo.EventTable
	WHERE EventID = @ID
END