USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[IMPORT_JOURNAL_LAST]
	@DOCS		VARCHAR(512) = NULL OUTPUT,
	@SIZE		VARCHAR(512) = NULL OUTPUT,
	@REG		VARCHAR(512) = NULL OUTPUT,
	@PROT		VARCHAR(512) = NULL OUTPUT,
	@PROT_TEXT	VARCHAR(512) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @DOCS = CONVERT(VARCHAR(20), DATE, 104) + ' ' + CONVERT(VARCHAR(20), DATE, 108) + ' (загружено ' + CONVERT(VARCHAR(20), RECORD) + ' всего ' + CONVERT(VARCHAR(20), TOTAL) + ')'
	FROM dbo.ImportJournal
	WHERE TYPE = 'DOCS' AND DATE = 
		(
			SELECT MAX(DATE)
			FROM dbo.ImportJournal
			WHERE TYPE = 'DOCS'
		)

	SELECT @SIZE = CONVERT(VARCHAR(20), DATE, 104) + ' ' + CONVERT(VARCHAR(20), DATE, 108) + ' (загружено ' + CONVERT(VARCHAR(20), RECORD) + ' всего ' + CONVERT(VARCHAR(20), TOTAL) + ')'
	FROM dbo.ImportJournal
	WHERE TYPE = 'SIZE' AND DATE = 
		(
			SELECT MAX(DATE)
			FROM dbo.ImportJournal
			WHERE TYPE = 'SIZE'
		)
		
	SELECT @REG = CONVERT(VARCHAR(20), DATE, 104) + ' ' + CONVERT(VARCHAR(20), DATE, 108) + ' (всего ' + CONVERT(VARCHAR(20), TOTAL) + ')'
	FROM dbo.ImportJournal
	WHERE TYPE = 'REG' AND DATE = 
		(
			SELECT MAX(DATE)
			FROM dbo.ImportJournal
			WHERE TYPE = 'REG'
		)
		
	SELECT @PROT = CONVERT(VARCHAR(20), DATE, 104) + ' ' + CONVERT(VARCHAR(20), DATE, 108) + ' (загружено ' + CONVERT(VARCHAR(20), RECORD) + ' всего ' + CONVERT(VARCHAR(20), TOTAL) + ')'
	FROM dbo.ImportJournal
	WHERE TYPE = 'PROT' AND DATE = 
		(
			SELECT MAX(DATE)
			FROM dbo.ImportJournal
			WHERE TYPE = 'PROT'
		)
		
	SELECT @PROT_TEXT = CONVERT(VARCHAR(20), DATE, 104) + ' ' + CONVERT(VARCHAR(20), DATE, 108) + ' (загружено ' + CONVERT(VARCHAR(20), RECORD) + ' всего ' + CONVERT(VARCHAR(20), TOTAL) + ')'
	FROM dbo.ImportJournal
	WHERE TYPE = 'PROT_TEXT' AND DATE = 
		(
			SELECT MAX(DATE)
			FROM dbo.ImportJournal
			WHERE TYPE = 'PROT_TEXT'
		)		
END
