USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_FLASH_POP]	
    @FLASHID VARCHAR(1023)

AS
BEGIN
	SET NOCOUNT ON;
    
    UPDATE dbo.ServiceFlashTable
    SET NUM_COUNT = (NUM_COUNT+1), LAST_DATE = GETDATE()
    WHERE ID_FLASH=@FLASHID

	INSERT INTO dbo.ServiceFlashTableCount (ID_FLASH, LAST_DATE) VALUES (@FLASHID, GETDATE())

END