USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CALL_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CC_ID_CLIENT, CC_DATE, CC_PERSONAL, CC_SERVICE, CC_NOTE, 
		(
			SELECT CT_ID 
			FROM dbo.ClientTrust 
			WHERE CT_ID_CALL = CC_ID
		) AS CT_ID, 
		(
			SELECT CS_ID 
			FROM dbo.ClientSatisfaction
			WHERE CS_ID_CALL = CC_ID
		) AS CS_ID
	FROM dbo.ClientCall
	WHERE CC_ID = @ID
END