USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CALL_TYPE_UPDATE]
	@ID	INT,
	@NAME	VARCHAR(50),
	@SHORT	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.CallTypeTable
	SET CallTypeName = @NAME,
		CallTypeShort = @SHORT
	WHERE CallTypeID = @ID
END