USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[VISIT_PAY_INSERT]	
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@VALUE	MONEY,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	
	INSERT INTO dbo.VisitPayTable(VisitPayBegin, VisitPayEnd, VisitPayValue)
		VALUES(@BEGIN, @END, @VALUE)

	SELECT @ID = SCOPE_IDENTITY()
END