USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_FLASH_ADD]	
	@SERVICEID INT,
    @FLASHID VARCHAR(1023),
	@UN 	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
    DECLARE @CN INT
    
    SET @CN = (SELECT COUNT(*) FROM dbo.ServiceFlashTable WHERE ID_FLASH=@FLASHID)
   
    if (@CN=0)
	INSERT INTO	dbo.ServiceFlashTable(ID_SERVICE, ID_FLASH, UN_FLASH, NUM_COUNT, LAST_DATE)
		VALUES(@SERVICEID, @FLASHID, @UN, 0, GETDATE())	
    ELSE 
    UPDATE dbo.ServiceFlashTable
    SET ID_SERVICE=@SERVICEID,  NUM_COUNT=0, LAST_DATE = GETDATE()
    WHERE ID_FLASH=@FLASHID

END