USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISCONNECT_REASON_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DR_ID, DR_NAME
	FROM dbo.DisconnectReason
	WHERE @FILTER IS NULL
		OR DR_NAME LIKE @FILTER
	ORDER BY DR_NAME
END