USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISTR_STATUS_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DS_ID, DS_NAME, DS_REG
	FROM dbo.DistrStatus
	WHERE @FILTER IS NULL
		OR DS_NAME LIKE @FILTER	
	ORDER BY DS_REG
END