USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_VISIT_DELETE]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientStudyVisit(ID_MASTER, ID_CLIENT, ID_TEACHER, DATE, NOTE, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_CLIENT, ID_TEACHER, DATE, NOTE, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientStudyVisit
		WHERE ID = @ID
		
	UPDATE dbo.ClientStudyVisit
	SET	STATUS		=	3,
		UPD_DATE	=	GETDATE(),
		UPD_USER	=	ORIGINAL_LOGIN()
	WHERE ID = @ID
END
