USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SEARCH_ADD]
	@CAT	VARCHAR(50),
	@TXT	VARCHAR(250)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.SearchTable(SearchCategory, SearchText)
	VALUES(@CAT, @TXT)
END