USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISTR_TYPE_COEF_SELECT]
	@NET	INT,
	@PERIOD	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NAME, DistrTypeName, COEF, WEIGHT, RND, b.ID, c.DistrTypeID
	FROM 
		dbo.DistrTypeCoef a
		INNER JOIN Common.Period b ON a.ID_MONTH = b.ID
		INNER JOIN dbo.DistrTypeTable c ON c.DistrTypeID = a.ID_NET
	WHERE (DistrTypeID = @NET OR @NET IS NULL)
		AND (b.ID = @PERIOD OR @PERIOD IS NULL)
		AND START <= DATEADD(MONTH, 3, GETDATE())
	ORDER BY START DESC, DistrTypeOrder
END
