USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISTR_TYPE_INSERT]	
	@NAME	VARCHAR(50),
	@ORDER	INT,
	@FULL	NVARCHAR(50),
	@CHECK	BIT,
	@Code	VarChar(100),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.DistrTypeTable(DistrTypeName, DistrTypeOrder, DistrTypeFull, DistrTypeBaseCheck, DistrTypeCode)
	VALUES(@NAME, @ORDER, @FULL, @CHECK, @Code);
		
	SELECT @ID = SCOPE_IDENTITY()
END
