USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFO_PANEL_USER_SET]
	@ID		UNIQUEIDENTIFIER,
	@USER	NVARCHAR(128),
	@STATE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @STATE = 0
		DELETE
		FROM dbo.InfoPanelUser
		WHERE ID_PANEL = @ID AND USR_NAME = @USER
	ELSE
		INSERT INTO dbo.InfoPanelUser(ID_PANEL, USR_NAME)
			VALUES(@ID, @USER)
END
