USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISTR_STATUS_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DS_NAME, DS_REG, DS_IMAGE, DS_INDEX
	FROM dbo.DistrStatus
	WHERE DS_ID = @ID
END