USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_MESSAGE_GET]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @MAX_DELAY	INT
	
	SELECT @MAX_DELAY = Maintenance.GlobalMessageDelayMax()	

	SELECT 
		ID, SENDER, DATE, NOTE, HARD_READ, 
		CONVERT(BIT, 
			CASE
				WHEN DELAY_MIN >= @MAX_DELAY THEN 0
				ELSE 1
			END) AS CAN_DELAY,
		CONVERT(BIT, 0) AS READED,
		ClientFullName
	FROM 
		dbo.ClientMessage a
		LEFT OUTER JOIN dbo.ClientTable ON ClientID = ID_CLIENT
	WHERE RECEIVE_USER = ORIGINAL_LOGIN()
		AND REMIND_DATE < GETDATE()
		AND RECEIVE_DATE IS NULL
		AND a.STATUS = 1
	ORDER BY DATEADD(MINUTE, DELAY_MIN, UPD_DATE)
END
