USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_INSERT]	
	@NAME	VARCHAR(100),
	@POS	INT,
	@MANAGER	INT,
	@PHONE	VARCHAR(100),
	@LOGIN	VARCHAR(50),
	@FULL	VARCHAR(250),
	@CITY	NVARCHAR(MAX),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO	dbo.ServiceTable(ServiceName, ServicePositionID, ManagerID, ServicePhone,
				ServiceLogin, ServiceFullName, ServiceFirst)
		VALUES(@NAME, @POS, @MANAGER, @PHONE, @LOGIN, @FULL, GETDATE())	

	SELECT @ID = SCOPE_IDENTITY()

	INSERT INTO dbo.ServiceCity(ID_SERVICE, ID_CITY)
		SELECT @ID, ID
		FROM dbo.TableGUIDFromXML(@CITY)
END