USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[LAWYER_INSERT]	
	@SHORT	VARCHAR(50),
	@FULL	VARCHAR(250),
	@LOGIN	VARCHAR(100),	
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.Lawyer(LW_SHORT, LW_FULL, LW_LOGIN)
		OUTPUT inserted.LW_ID INTO @TBL
		VALUES(@SHORT, @FULL, @LOGIN)
		
	SELECT @ID = ID FROM @TBL
END