USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AREA_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AR_ID, AR_NAME, RG_NAME, AR_PREFIX, AR_SUFFIX
	FROM
		dbo.Area
		INNER JOIN dbo.Region ON RG_ID = AR_ID_REGION
	WHERE @FILTER IS NULL
		OR AR_NAME LIKE @FILTER
		OR RG_NAME LIKE @FILTER
		OR CONVERT(VARCHAR(20), RG_NUM) LIKE @FILTER
	ORDER BY AR_NAME
END