USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[BACKUP_DATABASE]
	@PATH NVARCHAR(500)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQL NVARCHAR(MAX)

	SET @PATH = @PATH + 'ClientDB' + CONVERT(VARCHAR(50), GETDATE(), 112) + '.bak'

	SET @SQL = 'BACKUP DATABASE  [' + DB_NAME() + '] TO  DISK = ''' + @PATH + N'''
			WITH  
				INIT ,  
				NOUNLOAD ,  
				NAME = ''ClientDB FULL BACKUP'',
				SKIP ,  
				STATS = 10,  
				NOFORMAT 
		'

	EXEC (@SQL)
END