USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_QUALITY_SAVE]
	@ID			UNIQUEIDENTIFIER,
	@CLIENT		INT,
	@DATE		SMALLDATETIME,
	@TEACHER	INT,
	@NOTE		NVARCHAR(MAX),
	@TYPE		UNIQUEIDENTIFIER,
	@WEIGHT		DECIMAL(8, 4),
	@SYS_LIST	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.StudyQuality(ID_CLIENT, DATE, NOTE, ID_TEACHER, ID_TYPE, WEIGHT, SYS_LIST)
			VALUES(@CLIENT, @DATE, @NOTE, @TEACHER, @TYPE, @WEIGHT, @SYS_LIST)
	ELSE
		UPDATE dbo.StudyQuality
		SET	DATE		=	@DATE,
			ID_TEACHER	=	@TEACHER,
			NOTE		=	@NOTE,
			ID_TYPE		=	@TYPE,
			WEIGHT		=	@WEIGHT,
			SYS_LIST	=	@SYS_LIST
		WHERE ID = @ID
	
END
