USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_RIVAL_CONTROL]
	@CR_ID	INT,
	@CONTROL	BIT,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientRival
	SET CR_CONTROL = @CONTROL,
		CR_CONTROL_DATE = @DATE
	WHERE CR_ID = @CR_ID
END