USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[KD_VERSION_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NAME, SHORT, ACTIVE, START, FINISH
	FROM dbo.KDVersion
	WHERE ID = @ID
END
