USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_COMMENT_GET_NEW]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ClientLastUpdate
	FROM dbo.ClientTable	a
	WHERE ClientID = @ID
END