USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INNOVATION_INSERT]
	@NAME	NVARCHAR(256),
	@NOTE	NVARCHAR(MAX),
	@START	SMALLDATETIME,
	@FINISH	SMALLDATETIME,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
	
	INSERT INTO dbo.Innovation(NAME, NOTE, START, FINISH)
		OUTPUT inserted.ID INTO @TBL
		VALUES(@NAME, @NOTE, @START, @FINISH)
		
	SELECT @ID = ID
	FROM @TBL
END
