USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_ADDRESS_SAVE]
	@CLIENT		INT,
	@TYPE		UNIQUEIDENTIFIER,
	@NAME		VARCHAR(150),
	@INDEX		VARCHAR(20),
	@STREET		UNIQUEIDENTIFIER,
	@HOME		VARCHAR(50),
	@OFFICE		VARCHAR(100),
	@HINT		VARCHAR(MAX),
	@NOTE		VARCHAR(MAX),
	@DISTRICT	UNIQUEIDENTIFIER = NULL,
	@MAP		VARBINARY(MAX) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientAddress(CA_ID_CLIENT, CA_ID_TYPE, CA_NAME, CA_INDEX, CA_ID_STREET, CA_HOME, CA_OFFICE, CA_HINT, CA_NOTE, CA_ID_DISTRICT)
		VALUES(@CLIENT, @TYPE, @NAME, @INDEX, @STREET, @HOME, @OFFICE, @HINT, @NOTE, @DISTRICT)
END