USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CALL_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@CLIENT		INT,
	@DATE		SMALLDATETIME,
	@PERSONAL	VARCHAR(250),
	@SERVICE	VARCHAR(150),
	@NOTE		VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientCall
	SET CC_DATE		=	@DATE, 
		CC_PERSONAL	=	@PERSONAL,
		CC_SERVICE	=	@SERVICE,
		CC_NOTE		=	@NOTE
	WHERE CC_ID = @ID
END