USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DELETE_USER]
	@login VARCHAR(50)    
AS
BEGIN	
	SET NOCOUNT ON;

    EXEC('DROP USER ' + @login )
    EXEC('DROP LOGIN ' + @login )

    SET NOCOUNT OFF
END