USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERTIFICAT_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SertificatType
	SET NAME = @NAME
	WHERE ID = @ID
END
