USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_HST_PROCESS_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ClientID, ClientFullName, ServiceName, PATH, FILE_DATE, 0 AS NEW_DOC, CONVERT(NVARCHAR(512), '') AS NOTE,
		CONVERT(NVARCHAR(512), '') AS CLIENT_NOTE
	FROM dbo.ClientView WITH(NOEXPAND) CROSS JOIN dbo.ClientHST
	WHERE 1 = 0
END
