USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[LETTERS_SAVE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(256),
	@GRP	NVARCHAR(256),
	@DATA	NVARCHAR(MAX),
	@TXT	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.Letter(ID, NAME, GRP, DATA, TXT)
			VALUES(@ID, @NAME, @GRP, @DATA, @TXT)
	ELSE
		UPDATE dbo.Letter
		SET	NAME	=	@NAME,
			GRP		=	@GRP,
			DATA	=	@DATA,
			TXT		=	@TXT
		WHERE ID = @ID
END
