USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AREA_UPDATE]
	@ID	UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100),
	@PREFIX	VARCHAR(20),
	@SUFFIX	VARCHAR(20),
	@REGION	UNIQUEIDENTIFIER	
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.Area
	SET		AR_ID_REGION	=	@REGION, 
			AR_NAME			=	@NAME, 
			AR_PREFIX		=	@PREFIX, 
			AR_SUFFIX		=	@SUFFIX,
			AR_LAST			=	GETDATE()
	WHERE	AR_ID			=	@ID
END