USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_QUEST_INSERT]	
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@QUEST	INT,
	@ANS	INT,
	@TEXT	VARCHAR(150),
	@COMMENT	VARCHAR(MAX),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO	dbo.ClientQuestionTable(ClientID, QuestionID, ClientQuestionDate, 
					AnswerID, ClientQuestionText, ClientQuestionComment)
		VALUES(@CLIENT, @QUEST, @DATE, @ANS, @TEXT, @COMMENT)

	SELECT @ID = SCOPE_IDENTITY()
END