USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[REGION_INSERT]	
	@NAME	VARCHAR(100),
	@PREFIX	VARCHAR(20),
	@SUFFIX	VARCHAR(20),
	@NUM	TINYINT,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.Region(RG_NAME, RG_PREFIX, RG_SUFFIX, RG_NUM)
		OUTPUT INSERTED.RG_ID INTO @TBL
		VALUES(@NAME, @PREFIX, @SUFFIX, @NUM)
	
	SELECT @ID = ID FROM @TBL
END