USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_DISTR_CONNECT]
	@ID		UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @STATUS UNIQUEIDENTIFIER
	
	SELECT @STATUS = DS_ID
	FROM dbo.DistrStatus
	WHERE DS_REG = 0
	
	IF (SELECT ID_STATUS FROM dbo.ClientDistr WHERE ID = @ID) = @STATUS
	BEGIN
		RAISERROR('Дистрибутив уже подключен к сопровождению. Операция отменена', 16, 1)
		RETURN
	END
	
	INSERT INTO dbo.ClientDistr(ID_CLIENT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_TYPE, ID_NET, ID_STATUS, ON_DATE, OFF_DATE, STATUS, BDATE, EDATE, UPD_USER)
		SELECT ID_CLIENT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_TYPE, ID_NET, ID_STATUS, ON_DATE, OFF_DATE, 2, BDATE, GETDATE(), UPD_USER
		FROM dbo.ClientDistr
		WHERE ID = @ID
		
	UPDATE dbo.ClientDistr
	SET ID_STATUS	= @STATUS,
		ON_DATE		= @DATE,
		BDATE		= GETDATE(),
		UPD_USER	= ORIGINAL_LOGIN()		
	WHERE ID = @ID
END