USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[QUESTION_ANSWER_SET]
	@ID		INT,
	@QUEST	INT,
	@NAME	VARCHAR(150)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NOT NULL
		UPDATE dbo.AnswerTable
		SET AnswerName = @NAME
		WHERE AnswerID = @ID
	ELSE
		INSERT INTO dbo.AnswerTable(QuestionID, AnswerName)
			VALUES(@QUEST, @NAME)
END