USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[LESSON_PLACE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LessonPlaceID, LessonPlaceName, LessonPlaceReport
	FROM dbo.LessonPlaceTable
	WHERE @FILTER IS NULL
		OR LessonPlaceName LIKE @FILTER
	ORDER BY LessonPlaceName
END