USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SATISFACTION_QUESTION_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		SQ_ID, SQ_TEXT, SQ_SINGLE, SQ_BOLD, SQ_ORDER, SQ_ACTIVE
	FROM dbo.SatisfactionQuestion
	WHERE SQ_ID = @ID
END