USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONS_ERR]
	@HOST	INT,
	@DISTR	INT,
	@COMP	TINYINT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TOP 1 ERROR_DATA AS UF_ERROR_LOG
	FROM 
		dbo.IPConsErrView b
		INNER JOIN dbo.SystemTable c ON b.UF_SYS = c.SystemNumber
	WHERE b.UF_DISTR = @DISTR AND b.UF_COMP = @COMP AND c.HostID = @HOST
	ORDER BY UF_DATE DESC
END
