USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_COMMENTS_GET]
	@CLIENTID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CM_TEXT, CONVERT(DATETIME, CM_DATE, 121) AS CM_DATE
	FROM 
		dbo.ClientTable a
		INNER JOIN dbo.ClientSearchComments b ON a.ClientID = b.CSC_ID_CLIENT CROSS APPLY
		(
			SELECT 
				z.value('@TEXT[1]', 'VARCHAR(250)') AS CM_TEXT, 
				z.value('@DATE[1]', 'VARCHAR(50)') AS CM_DATE
			FROM CSC_COMMENTS.nodes('/ROOT/COMMENT') x(z)
		) AS o_O
	WHERE ClientID = @CLIENTID
END