USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STUDY_TYPE_INSERT]	
	@NAME	NVARCHAR(128),
	@PSEDO	NVARCHAR(64),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.StudyType(NAME, PSEDO)
		OUTPUT INSERTED.ID INTO @TBL
		VALUES(@NAME, @PSEDO)

	SELECT @ID = ID FROM @TBL
END
