USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[LAWYER_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LW_SHORT, LW_FULL, LW_LOGIN
	FROM dbo.Lawyer
	WHERE LW_ID = @ID
END