USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_ERROR_REASON_SELECT]
	@TP			NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT ID, ID_GROUP, NAME, ORD, TP, RS_TYPE
	FROM dbo.ClientErrorReason
	WHERE TP = @TP
	ORDER BY ID_GROUP, ORD
END
