USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_RIVAL_EDIT]
	@CR_ID	INT,
	@TYPE	INT,
	@STATUS	INT,
	@CONDITION	VARCHAR(MAX),
	@PERSONAL	VARCHAR(MAX),
	@SURNAME	NVARCHAR(256) = NULL,
	@NAME		NVARCHAR(256) = NULL,
	@PATRON		NVARCHAR(256) = NULL,
	@PHONE		NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @ID INT

	INSERT INTO dbo.ClientRival(CR_ID_MASTER, CL_ID, CR_DATE, CR_ID_TYPE, CR_ID_STATUS, CR_COMPLETE, CR_CONTROL, CR_CONDITION, CR_SURNAME, CR_NAME, CR_PATRON, CR_PHONE, CR_CREATE_USER, CR_CREATE_DATE)
		SELECT CR_ID_MASTER, CL_ID, CR_DATE, @TYPE, @STATUS, CR_COMPLETE, CR_CONTROL, @CONDITION, @SURNAME, @NAME, @PATRON, @PHONE, CR_CREATE_USER, CR_CREATE_DATE
		FROM dbo.ClientRival
		WHERE CR_ID = @CR_ID

	SELECT @ID = SCOPE_IDENTITY()

	UPDATE dbo.ClientRivalReaction
	SET CRR_ID_RIVAL = @ID
	WHERE CRR_ID_RIVAL = @CR_ID
	
	UPDATE dbo.ClientRival
	SET CR_ACTIVE = 0
	WHERE CR_ID = @CR_ID

	EXEC dbo.CLIENT_RIVAL_PERSONAL_SET_NEW @ID, @PERSONAL
END