USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_COMMENT_SET_NEW]
	@ID			INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientTable
	SET 
		ClientLastUpdate = GETDATE()
	WHERE ClientID = @ID
END