USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONTROL_DELETE]
	@CC_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM dbo.ClientControl	
	WHERE CC_ID = @CC_ID
END