USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_RIC_VIDEO]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 'Подписан на "Видео.Консультант" с ' + CONVERT(NVARCHAR(64), START, 104) AS TXT
	FROM dbo.ClientDelivery
	WHERE ID_CLIENT = @ID
		AND ID_DELIVERY = '25EEB199-A6DA-E511-9D3C-0007E92AAFC5'
		AND FINISH IS NULL
END
