USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_POSITION_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ServicePositionName
	FROM dbo.ServicePositionTable
	WHERE ServicePositionID = @ID
END