USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SEARCH_FILE_IMPORT]
	@CLIENT	INT,
	@MD5	VARCHAR(100),
	@FILE	VARBINARY(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientSearchFiles(CSF_ID_CLIENT, CSF_MD5, CSF_FILE)
		VALUES(@CLIENT, @MD5, @FILE)
END