USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[REGION_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RG_ID, RG_NAME, RG_PREFIX, RG_SUFFIX, RG_NUM
	FROM dbo.Region
	WHERE @FILTER IS NULL
		OR RG_NAME LIKE @FILTER
		OR CONVERT(VARCHAR(20), RG_NUM) LIKE @FILTER
	ORDER BY RG_NUM, RG_NAME
END