USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STREET_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ST_NAME, ST_ID_CITY, ST_PREFIX, ST_SUFFIX
	FROM dbo.Street
	WHERE ST_ID = @ID
END