USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONTROL_EDIT]
	@CC_ID	INT,
	@TEXT	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientControl
	SET CC_TEXT = @TEXT
	WHERE CC_ID = @CC_ID
END