USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_CLAIM_PEOPLE_GET]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		SURNAME, NAME, PATRON, POSITION, PHONE, GR_COUNT, NOTE,
		ISNULL(SURNAME + ' ', '') + ISNULL(NAME + ' ', '') + ISNULL(PATRON, '') AS FIO
	FROM dbo.ClientStudyClaimPeople
	WHERE ID_CLAIM = @ID
	ORDER BY SURNAME, NAME, PATRON, POSITION
END
