USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[PAY_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PayTypeID, PayTypeName
	FROM dbo.PayTypeTable
	WHERE @FILTER IS NULL
		OR PayTypeName LIKE @FILTER
	ORDER BY PayTypeName
END