USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[TEACHER_INSERT]	
	@NAME	VARCHAR(250),
	@LOGIN	VARCHAR(100),
	@REPORT	BIT,
	@NORMA	DECIMAL(4, 2),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.TeacherTable(TeacherName, TeacherLogin, TeacherReport, TeacherNorma)
		VALUES(@NAME, @LOGIN, @REPORT, @NORMA)
		
	SELECT @ID = SCOPE_IDENTITY()
END