USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[RISK_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		SEARCH_MON, SEARCH_CNT, 
		DUTY_MON, DUTY_CNT, 
		RIVAL_MON, RIVAL_CNT, 
		UPD_WEEK, UPD_CNT, 
		STUDY_MON, STUDY_CNT, 
		SEMINAR_MON, SEMINAR_CNT
	FROM dbo.Risk
	WHERE STATUS = 1
END
