USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[LOCK_RELEASE]
	@ID	NVARCHAR(MAX),
	@DATA	VARCHAR(64)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.Locks		
	WHERE LC_DATA = @DATA 
		AND LC_REC IN 
			(
				SELECT ID
				FROM dbo.TableStringFromXML(@ID)
			)	
END