USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ACT_CALC_EXPORT]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SET @END = DATEADD(DAY, 1, @END)

	SELECT 
		ID,
		SERVICE + '_' + REPLACE(REPLACE(REPLACE(CONVERT(NVARCHAR(64), DATE, 120), '-', '_'), ':', '_'), ' ', '_') + '.xml' AS FNAME,
		CONVERT(VARCHAR(MAX), (
			SELECT SYS_REG AS s, DISTR AS d, COMP AS c, CONVERT(VARCHAR(32), MON, 112) AS m
			FROM dbo.ActCalcDetail b
			WHERE a.ID = b.ID_MASTER
			FOR XML PATH('i'), ROOT('act_claim')
		)) AS DATA
	FROM dbo.ActCalc a
	WHERE STATUS = 1
		AND (DATE >= @BEGIN OR @BEGIN IS NULL)
		AND (DATE < @END OR @END IS NULL)
END
