USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PHONE_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PT_ID, PT_NAME, PT_SHORT
	FROM dbo.PhoneType
	WHERE @FILTER IS NULL
		OR PT_NAME LIKE @FILTER
		OR PT_SHORT LIKE @FILTER
	ORDER BY PT_NAME
END