USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DELIVERY_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.Delivery
	SET		NAME	=	@NAME,
			LAST	=	GETDATE()
	WHERE	ID		=	@ID
END