USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_DISTR_DELIVERY]
	@ID		VARCHAR(MAX),
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientDistr
	SET STATUS = 4,
		EDATE = GETDATE(),
		UPD_USER = ORIGINAL_LOGIN()
	WHERE ID IN
		(
			SELECT ID
			FROM dbo.TableGUIDFromXML(@ID)
		)

	INSERT INTO dbo.ClientDistr(ID_CLIENT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_TYPE, ID_NET, ID_STATUS, ON_DATE, OFF_DATE)
		SELECT @CLIENT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_TYPE, ID_NET, ID_STATUS, ON_DATE, OFF_DATE
		FROM dbo.ClientDistr
		WHERE ID IN 
			(
				SELECT ID
				FROM dbo.TableGUIDFromXML(@ID)
			)
END