USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DUTY_CONTROL_UPDATE]
	@CALL	UNIQUEIDENTIFIER,
	@ANSWER	TINYINT,
	@SATISF	TINYINT,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientDutyControl
	SET CDC_ANSWER	=	@ANSWER,
		CDC_SATISF	=	@SATISF,
		CDC_NOTE	=	@NOTE
	WHERE CDC_ID_CALL = @CALL
END
