USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_AUDIT_INSERT]
	@CLIENT		INT, 
	@DATE		SMALLDATETIME, 
	@STUDY		BIT, 
	@STUDY_DATE	SMALLDATETIME, 
	@SEARCH		BIT, 
	@SEARCH_NOTE	VARCHAR(MAX), 
	@DUTY		BIT, 
	@DUTY_DATE	SMALLDATETIME, 
	@DUTY_AVG	DECIMAL(8, 4), 
	@TRANSFER	BIT, 
	@TRANSFER_NOTE	VARCHAR(MAX), 
	@RIVAL		BIT, 
	@RIVAL_DATE	SMALLDATETIME, 
	@RIVAL_NOTE	VARCHAR(MAX), 
	@SYSTEM		BIT, 
	@SYSTEM_COUNT	INT, 
	@SYSTEM_ER_COUNT	INT,
	@INCOME		BIT,
	@INCOME_NOTE	VARCHAR(MAX),
	@NOTE		VARCHAR(MAX),
	@CONTROL	BIT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientAudit(
			CA_ID_CLIENT, CA_DATE, CA_STUDY, CA_STUDY_DATE, 
			CA_SEARCH, CA_SEARCH_NOTE, CA_DUTY, CA_DUTY_DATE, CA_DUTY_AVG, 
			CA_TRANSFER, CA_TRANSFER_NOTE, CA_RIVAL, CA_RIVAL_DATE, CA_RIVAL_NOTE, 
			CA_SYSTEM, CA_SYSTEM_COUNT, CA_SYSTEM_ER_COUNT, CA_INCOME, CA_INCOME_NOTE,
			CA_NOTE)
		VALUES(
			@CLIENT, @DATE, @STUDY, @STUDY_DATE, 
			@SEARCH, @SEARCH_NOTE, @DUTY, @DUTY_DATE, @DUTY_AVG, 
			@TRANSFER, @TRANSFER_NOTE, @RIVAL, @RIVAL_DATE, @RIVAL_NOTE, 
			@SYSTEM, @SYSTEM_COUNT, @SYSTEM_ER_COUNT, @INCOME, @INCOME_NOTE,
			@NOTE)

	SELECT @ID = SCOPE_IDENTITY()
END