USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONTROL_UPDATE]
	@CC_ID	INT,
	@TEXT	VARCHAR(MAX),
	@BEGIN	SMALLDATETIME = NULL
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientControl
	SET CC_TEXT		=	@TEXT,
		CC_BEGIN	=	@BEGIN
	WHERE CC_ID = @CC_ID
END