USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDENT_POSITION_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT StudentPositionName
	FROM dbo.StudentPositionTable
	WHERE StudentPositionID = @ID
END