USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[VENDOR_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@SHORT		NVARCHAR(64),
	@FULL		NVARCHAR(512),
	@DIRECTOR	NVARCHAR(512)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.Vendor
	SET		SHORT		=	@SHORT,
			FULL_NAME	=	@FULL,
			DIRECTOR	=	@DIRECTOR,
			LAST		=	GETDATE()
	WHERE	ID		=	@ID
END