USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_DISTR_DISCONNECT_LIST]
	@ID		UNIQUEIDENTIFIER,
	@TP		TINYINT, -- 0 - отключить, 1 - включить,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.DistrDisconnect
	SET STATUS = 2
	WHERE ID_DISTR = @ID AND STATUS = 1
	
	IF @TP = 0
	BEGIN
		UPDATE dbo.DistrDisconnect
		SET STATUS = 2
		WHERE ID_DISTR = @ID AND STATUS = 1
		
		INSERT INTO dbo.DistrDisconnect(ID_DISTR, NOTE)
			VALUES(@ID, @NOTE)
	END
END
