USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RIVAL_TYPE_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RivalTypeID, RivalTypeName
	FROM dbo.RivalTypeTable
	WHERE @FILTER IS NULL
		OR RivalTypeName LIKE @FILTER
	ORDER BY RivalTypeName
END