USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_RIVAL_PERSONAL_SET_NEW]
	@CR_ID	INT,
	@LIST	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @table TABLE (PT_ID INT)

	INSERT INTO @table
		SELECT *
		FROM dbo.GET_TABLE_FROM_LIST(@LIST, ',')

	DELETE 
	FROM dbo.ClientRivalPersonal
	WHERE CRP_ID_RIVAL = @CR_ID
		AND NOT EXISTS
			(
				SELECT *
				FROM @table
				WHERE PT_ID = CRP_ID_PERSONAL
			)

	INSERT INTO dbo.ClientRivalPersonal(CRP_ID_RIVAL, CRP_ID_PERSONAL)
		SELECT DISTINCT @CR_ID, PT_ID
		FROM @table	
END