USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ORI_PERSON_INSERT]	
	@CLIENT	INT,
	@NAME	VARCHAR(250),
	@PHONE	VARCHAR(250),
	@PLACE	VARCHAR(100),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.OriPersonTable(ClientID, OriPersonName, OriPersonPhone, OriPersonPlace)
		VALUES(@CLIENT, @NAME, @PHONE, @PLACE)
	
	SELECT @ID = SCOPE_IDENTITY()
END