USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_QUESTION_UPDATE]
	@ID	UNIQUEIDENTIFIER,
	@TEXT	VARCHAR(500),
	@SINGLE	BIT,
	@BOLD	BIT,
	@ORDER	INT,
	@ACTIVE	BIT	
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SatisfactionQuestion
	SET SQ_TEXT = @TEXT, 
		SQ_SINGLE = @SINGLE, 
		SQ_BOLD = @BOLD, 
		SQ_ORDER = @ORDER, 
		SQ_ACTIVE = @ACTIVE
	WHERE SQ_ID = @ID
END