USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DELETE_BLACKLIST_SYSTEMS_COMMENT]
@COMMENT varchar(300),
@COMMENT_DELETE varchar(300) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON

    UPDATE dbo.BLACK_LIST_REG 
	SET 
	COMMENT_DELETE=@COMMENT_DELETE,
	U_LOGIN_DELETE=ORIGINAL_LOGIN(),
	DATE_DELETE=GETDATE(),
	P_DELETE=1
	WHERE [COMPLECTNAME] = @COMMENT

	SET NOCOUNT OFF
END