USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[KD_VERSION_SELECT]
	@FILTER	NVARCHAR(128) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME, SHORT, ACTIVE, START, FINISH
	FROM dbo.KDVersion
	WHERE @FILTER IS NULL
		OR NAME LIKE @FILTER
	ORDER BY NAME DESC
END
