USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	
CREATE PROCEDURE [dbo].[GET_WHITELIST_SYSTEMS]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON

	SELECT R.SystemName, R.DistrNumber, R.CompNumber
	FROM dbo.RegNodeTable R
	LEFT JOIN dbo.SystemTable S ON S.SystemBaseName=R.SystemName
	LEFT JOIN dbo.BLACK_LIST_REG B ON (B.DISTR=R.DistrNumber)
	AND(B.COMP=R.CompNumber)AND(B.ID_SYS=S.SystemID)AND(B.[P_DELETE]=0)
	WHERE B.ID IS NULL
END