USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_INNOVATION_PERSONAL_GET]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DATE, SURNAME, NAME, PATRON, POSITION, NOTE
	FROM dbo.ClientInnovationPersonal
	WHERE ID = @ID
END
