USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[HOSTS_UPDATE]
	@ID	INT,
	@SHORT	VARCHAR(50),
	@REG	VARCHAR(50),
	@ORDER	INT
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE dbo.Hosts
	SET HostShort = @SHORT,
		HostReg = @REG,
		HostOrder = @ORDER,
		HostLast = GETDATE()
	WHERE HostID = @ID
END