USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[QUESTION_ANSWER_FULL_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AnswerID, QuestionID, AnswerName
	FROM dbo.AnswerTable
	ORDER BY QuestionID, AnswerName
END