USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_MESSAGE_RECEIVE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT DISTINCT RECEIVE_USER
	FROM dbo.ClientMessage
	WHERE STATUS = 1 AND HARD_READ = 1
	ORDER BY RECEIVE_USER
END
