USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[INFO_BANKS_SELECT]
	@SYSTEM	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM dbo.SystemBanksView WITH(NOEXPAND)
	WHERE SystemID = @SYSTEM
	ORDER BY InfoBankOrder
END