USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_SATISFACTION_QUESTION_PROCESS]
	@CS_ID	UNIQUEIDENTIFIER,
	@SQ_ID	UNIQUEIDENTIFIER,
	@NOTE	VARCHAR(500),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	IF @ID IS NULL
	BEGIN
		INSERT INTO dbo.ClientSatisfactionQuestion(CSQ_ID_CS, CSQ_ID_QUESTION, CSQ_NOTE)
			OUTPUT INSERTED.CSQ_ID INTO @TBL
			VALUES(@CS_ID, @SQ_ID, @NOTE)

		SELECT @ID = ID FROM @TBL
	END
	ELSE
		UPDATE dbo.ClientSatisfactionQuestion
		SET CSQ_NOTE = @NOTE
		WHERE CSQ_ID = @ID
END