USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(50),
	@RESULT	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.SatisfactionType
	SET		STT_NAME	=	@NAME,
			STT_RESULT	=	@RESULT
	WHERE	STT_ID = @ID
END