USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STUDY_QUALITY_FILTER]
	@BEGIN		SMALLDATETIME,
	@END		SMALLDATETIME,
	@TEACHER	INT,
	@TYPE		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, DATE, NOTE, ClientID, ClientFullName, ManagerName, ServiceName, d.NAME, WEIGHT, TeacherName
	FROM 
		dbo.StudyQuality a
		INNER JOIN dbo.ClientView b WITH(NOEXPAND) ON a.ID_CLIENT = b.ClientID
		INNER JOIN dbo.TeacherTable c ON a.ID_TEACHER = c.TeacherID
		INNER JOIN dbo.StudyQualityType d ON d.ID = a.ID_TYPE
	WHERE (a.DATE >= @BEGIN OR @BEGIN IS NULL)
		AND (a.DATE <= @END OR @END IS NULL)
		AND (a.ID_TEACHER = @TEACHER OR @TEACHER IS NULL)
		AND (a.ID_TYPE = @TYPE OR @TYPE IS NULL)
	ORDER BY DATE DESC
END
