USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[VISIT_PAY_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT VisitPayBegin, VisitPayEnd, VisitPayValue
	FROM dbo.VisitPayTable
	WHERE VisitPayID = @ID
END