USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[SATISFACTION_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT STT_ID, STT_NAME, STT_RESULT
	FROM dbo.SatisfactionType
	WHERE @FILTER IS NULL
		OR STT_NAME LIKE @FILTER
	ORDER BY STT_NAME
END