USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STUDY_SALE_SAVE]
	@ID		UNIQUEIDENTIFIER,
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@FIO	NVARCHAR(256),
	@NOTE	NVARCHAR(MAX)
	
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.StudySale(ID_CLIENT, DATE, FIO, NOTE)
			VALUES(@CLIENT, @DATE, @FIO, @NOTE)
	ELSE
		UPDATE dbo.StudySale
		SET DATE = @DATE,
			FIO = @FIO,
			NOTE = @NOTE
		WHERE ID = @ID
END
