USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AREA_INSERT]
	@NAME	VARCHAR(100),
	@PREFIX	VARCHAR(20),
	@SUFFIX	VARCHAR(20),
	@REGION	UNIQUEIDENTIFIER,
	@ID	UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.Area(AR_ID_REGION, AR_NAME, AR_PREFIX, AR_SUFFIX)
		OUTPUT INSERTED.AR_ID INTO @TBL
		VALUES(@REGION, @NAME, @PREFIX, @SUFFIX)

	SELECT @ID = ID
	FROM @TBL
END