USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_SATISFACTION_ANSWER]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SA_ID, SA_ID_QUESTION, SA_TEXT, CSA_ID, CONVERT(BIT, CASE WHEN CSA_ID IS NULL THEN 0 ELSE 1 END) AS CSA_CHECKED
	FROM 
		dbo.SatisfactionAnswer
		INNER JOIN dbo.SatisfactionQuestion ON SQ_ID = SA_ID_QUESTION		
		LEFT OUTER JOIN 
			(
				SELECT CSA_ID, CSA_ID_ANSWER, CSQ_ID_QUESTION
				FROM
					dbo.ClientCall 
					LEFT OUTER JOIN dbo.ClientSatisfaction ON CC_ID = CS_ID_CALL 
					LEFT OUTER JOIN dbo.ClientSatisfactionQuestion ON CSQ_ID_CS = CS_ID
					LEFT OUTER JOIN dbo.ClientSatisfactionAnswer ON CSQ_ID = CSA_ID_QUESTION
				WHERE CC_ID = @ID
			) AS o_O ON CSA_ID_ANSWER = SA_ID AND CSQ_ID_QUESTION = SQ_ID
	ORDER BY SQ_ORDER, SA_ORDER, SA_TEXT
END