USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DUTY_CONTROL_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CDC_ANSWER, CDC_SATISF, CDC_NOTE
	FROM dbo.ClientDutyControl
	WHERE CDC_ID_CALL = @ID
END
