USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONTROL_SELECT]
	@CL_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		CC_ID, CC_TEXT, CC_DATE, CC_AUTHOR, CC_READ_DATE, CC_READER, CC_REMOVE_DATE, CC_REMOVER,
		CASE CC_TYPE
			WHEN 1 THEN 'Аудит'
			WHEN 2 THEN 'Руководитель группы'
			WHEN 3 THEN 'Дежурная служба'
			WHEN 4 THEN 'Начальник отдела'
			WHEN 5 THEN 'Юрист'
			ELSE ''
		END AS CC_TYPE_STR
	FROM dbo.ClientControl
	WHERE CC_ID_CLIENT = @CL_ID
	ORDER BY CC_DATE DESC
END