USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_FLASH_GET]	
	@ID_FLASH VARCHAR(1023)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;


	SELECT	S.ServiceName, UN_FLASH, ID_SERVICE, NUM_COUNT, LAST_DATE FROM dbo.ServiceFlashTable
    LEFT JOIN [dbo].ServiceTable S ON S.ServiceID=ID_SERVICE
    WHERE ID_FLASH = @ID_FLASH

END