USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_MESSAGE_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT SENDER, DATE, NOTE, 
		REVERSE(STUFF(REVERSE(
			(
				SELECT
					RECEIVE_USER +
					ISNULL(' ' +
						CONVERT(VARCHAR(20), RECEIVE_DATE, 104) + ' ' +
						CONVERT(VARCHAR(20), RECEIVE_DATE, 108)
						, '') + 
					ISNULL(' ' + RECEIVE_HOST, '') + ', '
				FROM dbo.ClientMessage b
				WHERE a.SENDER = b.SENDER AND a.DATE = b.DATE AND a.NOTE = b.NOTE AND b.STATUS = 1
				ORDER BY TP, RECEIVE_USER FOR XML PATH('')
			)
		), 1, 2, '')) AS RECEIVE_DATA
	FROM dbo.ClientMessage a
	WHERE ID_CLIENT = @CLIENT AND STATUS = 1
	ORDER BY DATE DESC
END
