USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_RIVAL_COMPLETE]
	@CR_ID	INT,
	@COMPLETE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientRival
	SET CR_COMPLETE = @COMPLETE
	WHERE CR_ID = @CR_ID

	IF @COMPLETE = 1
		UPDATE dbo.ClientRival
		SET CR_CONTROL = 0
		WHERE CR_ID = @CR_ID
END