USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[RIVAL_STATUS_INSERT]	
	@NAME	VARCHAR(50),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.RivalStatus(RS_NAME)
		VALUES(@NAME)
	
	SELECT @ID = SCOPE_IDENTITY()
END