USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RICH_COEF_INSERT]	
	@START	INT,
	@END	INT,
	@VAL	DECIMAL(8, 4),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.RichCoefTable(RichCoefStart, RichCoefEnd, RichCoefVal)
		VALUES(@START, @END, @VAL)
		
	SELECT @ID = SCOPE_IDENTITY()
END