USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_CLAIM_WORK_DELETE]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientStudyClaimWork(ID_MASTER, ID_CLAIM, TP, DATE, NOTE, TEACHER, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_CLAIM, TP, DATE, NOTE, TEACHER, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientStudyClaimWork
		WHERE ID = @ID
			
	UPDATE dbo.ClientStudyClaimWork
	SET STATUS = 3,
		UPD_DATE = GETDATE(),
		UPD_USER = ORIGINAL_LOGIN()
	WHERE ID = @ID	
END
