USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_ERROR_DELETE]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientError(ID_MASTER, ID_CLIENT, NOTE, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_CLIENT, NOTE, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientError
		WHERE ID = @ID
			
	UPDATE dbo.ClientError
	SET STATUS		=	3,
		UPD_DATE	=	GETDATE(),
		UPD_USER	=	ORIGINAL_LOGIN()
	WHERE ID = @ID
END
