USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_INNOVATION_PERSONAL]
	@ID			UNIQUEIDENTIFIER,
	@INNOVATION	UNIQUEIDENTIFIER,
	@DATE		SMALLDATETIME,
	@SURNAME	NVARCHAR(256),
	@NAME		NVARCHAR(256),
	@PATRON		NVARCHAR(256),
	@POSITION	NVARCHAR(256),
	@NOTE		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.ClientInnovationPersonal(ID_INNOVATION, DATE, SURNAME, NAME, PATRON, POSITION, NOTE)
			VALUES(@INNOVATION, @DATE, @SURNAME, @NAME, @PATRON, @POSITION, @NOTE)
	ELSE
		UPDATE dbo.ClientInnovationPersonal
		SET	DATE		=	@DATE,
			SURNAME		=	@SURNAME,
			NAME		=	@NAME,
			PATRON		=	@PATRON,
			POSITION	=	@POSITION,
			NOTE		=	@NOTE
		WHERE ID = @ID
END
