USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USER_DELETE]
	@USER varchar(128),
	@LOGIN varchar(128)  
WITH EXECUTE AS OWNER  
AS
BEGIN	
	SET NOCOUNT ON;

	DELETE FROM dbo.Z_USER_LIST	WHERE [LOGIN_NAME] = @LOGIN

    EXEC('DROP USER [' + @USER +']')

    SET NOCOUNT OFF
END