USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[NAMED_SET_DELETE]
	@REF_NAME	NVARCHAR(128),
	@SET_NAME	NVARCHAR(128)
AS
BEGIN
SET NOCOUNT ON
DECLARE @SET_ID UNIQUEIDENTIFIER

SELECT @SET_ID=SetId
FROM dbo.NamedSets
WHERE SetName=@SET_NAME AND RefNaME=@REF_NAME

DELETE
FROM dbo.NamedSets
WHERE SetName=@SET_NAME AND RefNaME=@REF_NAME

DELETE
FROM dbo.NamedSetsItems
WHERE SetId=@SET_ID
END