USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISTRICT_INSERT]
	@CITY	UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.District(DS_ID_CITY, DS_NAME)
		OUTPUT INSERTED.DS_ID INTO @TBL
		VALUES(@CITY, @NAME)

	SELECT @ID = ID
	FROM @TBL
END