USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CALL_DIRECTION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(50),
	@DEF	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @DEF = 1
		UPDATE dbo.CallDirection
		SET DEF = 0
		WHERE ID <> @ID

	UPDATE	dbo.CallDirection
	SET		NAME	=	@NAME,
			DEF		=	@DEF,
			LAST	=	GETDATE()
	WHERE	ID		=	@ID
END