USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_INNOVATION_PERSONAL_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.ClientInnovationControl
	WHERE ID_PERSONAL = @ID
	
	DELETE
	FROM dbo.ClientInnovationPersonal
	WHERE ID = @ID
END
