USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_NAMES_SAVE]
	@CLIENT		INT,
	@NAME		VARCHAR(500)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ClientNames(ID_CLIENT, NAME)
		VALUES(@CLIENT, @NAME)
END