USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CONTRACT_TYPE_INSERT]
	@NAME	VARCHAR(100),
	@RATE	BIT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ContractTypeTable(ContractTypeName, ContractTypeRate)
		VALUES(@NAME, @RATE)
	
	SELECT @ID = SCOPE_IDENTITY()
END