USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_COMMENTS_SET]
	@CLIENT INT,	
	@COMMENT NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @XML XML
	DECLARE @HDOC INT
	
	SET @XML = CAST(@COMMENT AS XML)

	EXEC sp_xml_preparedocument @HDOC OUTPUT, @XML

	UPDATE dbo.ClientTable 
	SET ClientLastUpdate = GETDATE()
	WHERE ClientID = @CLIENT

	UPDATE dbo.ClientSearchComments
	SET CSC_COMMENTS = @XML
	WHERE CSC_ID_CLIENT = @CLIENT

	IF @@ROWCOUNT = 0
		INSERT INTO dbo.CLientSearchComments(CSC_ID_CLIENT, CSC_COMMENTS)
			VALUES(@CLIENT, @XML)
END