USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE	[dbo].[SYSTEM_LEFT_BANKS_GET]
	@SYS_LIST			NVARCHAR(128),
	@DISTR_TYPE_LIST	NVARCHAR(128) 
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @t	TABLE (InfoBank_ID	SMALLINT, InfoBankName	VARCHAR(20))

	DECLARE @SYS_END				BIT
	SET @SYS_END = 0

	DECLARE @DISTR_TYPE_END			BIT
	DECLARE @DISTR_TYPE_TEMP_LIST	NVARCHAR(128)

	DECLARE @TEMP_S					NVARCHAR(15)
	DECLARE @TEMP_D					NVARCHAR(15)

	WHILE @SYS_END = 0
	BEGIN
		IF (CHARINDEX(',', @SYS_LIST)<>0)
		BEGIN
			SET @TEMP_S = SUBSTRING(@SYS_LIST, 1, CHARINDEX(',', @SYS_LIST)-1)						--«ƒ≈—‹ ¬€“¿— »¬¿≈Ã œŒ ŒƒÕŒÃ” ID —»—“≈Ã€ »« —œ»— ¿
			SET @SYS_LIST = SUBSTRING(@SYS_LIST, CHARINDEX(',', @SYS_LIST)+1, LEN(@SYS_LIST))		
		END
		ELSE
		BEGIN
			SET @TEMP_S = @SYS_LIST
			SET @SYS_END = 1
		END
		
		SET @DISTR_TYPE_END = 0
		SET @DISTR_TYPE_TEMP_LIST = @DISTR_TYPE_LIST

		WHILE @DISTR_TYPE_END = 0
		BEGIN
			IF (CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)<>0)
			BEGIN					
				SET @TEMP_D = SUBSTRING(@DISTR_TYPE_TEMP_LIST, 1, CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)-1)
				SET @DISTR_TYPE_TEMP_LIST = SUBSTRING(@DISTR_TYPE_TEMP_LIST, CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)+1, LEN(@DISTR_TYPE_TEMP_LIST))
			END
			ELSE
			BEGIN
				SET @TEMP_D = @DISTR_TYPE_TEMP_LIST
				SET @DISTR_TYPE_END = 1
			END
			
			INSERT INTO @t(InfoBank_ID, InfoBankName)
			EXEC [dbo].[SYSTEM_BANKS_SELECT] @TEMP_S, @TEMP_D
		END
	END
	
	SELECT InfoBankID, InfoBankName, InfoBankShortName
	FROM InfoBankTable
	WHERE InfoBankID NOT IN (SELECT InfoBank_ID FROM @t)
	/*
	SELECT t.*, ibt.InfoBankShortName 
	FROM @t t
	INNER JOIN dbo.InfoBankTable ibt ON ibt.InfoBankID = t.InfoBank_ID
	GROUP BY InfoBank_ID, t.InfoBankName, InfoBankShortName
	*/
END
