USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[DISTR_STATUS_INSERT]	
	@NAME	VARCHAR(64),
	@REG	TINYINT,
	@IMAGE	VARBINARY(MAX),
	@INDEX	TINYINT,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.DistrStatus(DS_NAME, DS_REG, DS_IMAGE, DS_INDEX)
		OUTPUT INSERTED.DS_ID INTO @TBL
		VALUES(@NAME, @REG, @IMAGE, @INDEX)
	
	SELECT @ID = ID
	FROM @TBL
END