USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_QUESTION_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.SatisfactionAnswer
	WHERE SA_ID_QUESTION = @ID

	DELETE
	FROM dbo.SatisfactionQuestion
	WHERE SQ_ID = @ID
END