USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CALENDAR_WORK_SAVE]
	@ID		UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@TP		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(256),
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		INSERT INTO dbo.CalendarDate(DATE, ID_TYPE, NAME, NOTE)
			SELECT @DATE, @TP, @NAME, @NOTE
	END
	ELSE
	BEGIN
		EXEC dbo.CALENDAR_WORK_ARCH @ID
	
		UPDATE dbo.CalendarDate
		SET DATE		=	@DATE,
			ID_TYPE		=	@TP,
			NAME		=	@NAME,
			NOTE		=	@NOTE,
			UPD_DATE	=	GETDATE(),
			UPD_USER	=	ORIGINAL_LOGIN()
		WHERE ID = @ID
	END	
END
