USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CITY_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@REGION		UNIQUEIDENTIFIER,
	@AREA		UNIQUEIDENTIFIER,
	@CITY		UNIQUEIDENTIFIER,
	@NAME		VARCHAR(100),
	@PREFIX		VARCHAR(20),
	@SUFFIX		VARCHAR(20),
	@DISPLAY	BIT,
	@DEFAULT	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @DEFAULT = 1
		UPDATE dbo.City
		SET CT_DEFAULT = 0
		WHERE CT_DEFAULT = 1 AND CT_ID <> @ID

	UPDATE	dbo.City
	SET		CT_ID_REGION	=	@REGION,
			CT_ID_AREA		=	@AREA,
			CT_ID_CITY		=	@CITY,
			CT_NAME			=	@NAME,
			CT_PREFIX		=	@PREFIX,
			CT_SUFFIX		=	@SUFFIX,
			CT_DISPLAY		=	@DISPLAY,
			CT_DEFAULT		=	@DEFAULT,
			CT_LAST			=	GETDATE()
	WHERE	CT_ID			=	@ID
END