USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[NAMED_SET_EDIT]
	@SET_NAME	NVARCHAR(128),
	@REF_NAME	NVARCHAR(128),
	@VALUES		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @ID	UNIQUEIDENTIFIER

	SELECT @ID = SetId
	FROM dbo.NamedSets
	WHERE SetName=@SET_NAME AND RefName=@REF_NAME

	DELETE FROM dbo.NamedSets
	WHERE SetName=@SET_NAME AND RefName=@REF_NAME

	DELETE FROM dbo.NamedSetsItems
	WHERE SetId=@ID

	EXEC dbo.NAMED_SET_ADD @SET_NAME, @REF_NAME, @VALUES
END