USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DEBT_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, d.SHORT, b.NAME AS START_STR, c.NAME AS FINISH_STR, a.NOTE
	FROM 
		dbo.ClientDebt a
		INNER JOIN dbo.DebtType d ON d.ID = a.ID_DEBT
		INNER JOIN Common.Period b ON a.START = b.ID
		LEFT OUTER JOIN Common.Period c ON a.FINISH = c.ID
	WHERE a.ID_CLIENT = @CLIENT
	ORDER BY b.START, c.START
END
