USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CALL_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CallTypeID, CallTypeName, CallTypeShort
	FROM dbo.CallTypeTable
	WHERE @FILTER IS NULL
		OR CallTypeName LIKE @FILTER
		OR CallTypeShort LIKE @FILTER
	ORDER BY CallTypeName
END