USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DELIVERY_EXCLUDE]
	@ID		UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME,
	@LIST	NVARCHAR(MAX) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @LIST IS NULL
		UPDATE dbo.ClientDelivery
		SET FINISH = @DATE
		WHERE ID = @ID
	ELSE
		UPDATE dbo.ClientDelivery
		SET FINISH = @DATE
		WHERE ID IN (SELECT ID FROM dbo.TableGUIDFromXML(@LIST))
END
