USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ADDRESS_TYPE_INSERT]	
	@NAME		VARCHAR(100),
	@REQUIRED	BIT,
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.AddressType(AT_NAME, AT_REQUIRED)
		OUTPUT INSERTED.AT_ID INTO @TBL
		VALUES(@NAME, @REQUIRED)

	SELECT @ID = ID FROM @TBL
END