USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DISTR_STATUS_IMAGES]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DS_IMAGE
	FROM dbo.DistrStatus
	ORDER BY DS_INDEX
END