USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONTROL_CHECK]
	@CLIENT		INT,
	@CONTROL	BIT = NULL OUTPUT,
	@ID			INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SET @CONTROL = NULL
	
	IF @ID IS NULL
	BEGIN
		SELECT TOP 1 @CONTROL = 1
		FROM dbo.ClientControl
		WHERE CC_ID_CLIENT = @CLIENT
			--AND CC_READ_DATE IS NULL
			AND CC_REMOVE_DATE IS NULL
			--AND (CC_BEGIN IS NULL OR CC_BEGIN <= GETDATE())
		ORDER BY CC_DATE DESC
	END
	ELSE
	BEGIN
		SELECT TOP 1 @CONTROL = 1
		FROM dbo.ClientControl
		WHERE CC_ID = @ID
			AND CC_REMOVE_DATE IS NULL
	END
	
	--RAISERROR('Ошибканамэ!', 15, 1)
END