USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_TYPE_INSERT]
	@NAME	VARCHAR(50),
	@RESULT	BIT,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.SatisfactionType(STT_NAME, STT_RESULT)
		OUTPUT INSERTED.STT_ID INTO @TBL
		VALUES(@NAME, @RESULT)

	SELECT @ID = ID
	FROM @TBL
END