USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[INFO_BANK_PATH_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT InfoBankPath, InfoBankName
	FROM dbo.InfoBankTable
	WHERE ISNULL(InfoBankPath, '') <> ''
END