USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MAILING_TYPE_SELECT]
	@FILTER		VARCHAR(100) = NULL
AS
BEGIN
	SELECT
		MailingTypeID, MailingTypeName
	FROM
		Common.MailingType
	WHERE
		@FILTER IS NULL OR MailingTypeName LIKE '%'+@FILTER+'%'
END
