USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_CONTROL_GET]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TOP 1 CC_ID, CC_TEXT, CC_AUTHOR, CC_DATE
	FROM dbo.ClientControl
	WHERE CC_ID_CLIENT = @CLIENT
		AND CC_READ_DATE IS NULL
		AND CC_REMOVE_DATE IS NULL
		AND (CC_BEGIN IS NULL OR CC_BEGIN <= GETDATE())
	ORDER BY CC_DATE DESC
END