USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SATISFACTION_ANSWER_INSERT]
	@SQ_ID	UNIQUEIDENTIFIER,
	@TEXT	VARCHAR(500),
	@ORDER	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.SatisfactionAnswer(SA_ID_QUESTION, SA_TEXT, SA_ORDER)
		VALUES(@SQ_ID, @TEXT, @ORDER)
END