USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SERVICE_STATE_CLEAR]
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.ServiceStateDetail
	WHERE ID_STATE IN
		(
			SELECT ID
			FROM dbo.ServiceState
			WHERE STATUS <> 1
				AND DATE <= DATEADD(MONTH, -1, GETDATE())
		)
		
	DELETE
	FROM dbo.ServiceState
	WHERE STATUS <> 1
		AND DATE <= DATEADD(MONTH, -1, GETDATE())
END
