USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_LIST_SELECT]
AS
BEGIN
	SET NOCOUNT ON;	

	DECLARE @Client Table
	(
		CL_ID INT PRIMARY KEY CLUSTERED
	);
	
	DECLARE @RClient Table
	(
		RCL_ID INT PRIMARY KEY CLUSTERED
	);
	
	DECLARE @WClient Table
	(
		WCL_ID INT PRIMARY KEY CLUSTERED
	);

	INSERT INTO @RClient
	SELECT RCL_ID
	FROM dbo.ClientReadList()

	INSERT INTO @WClient
	SELECT WCL_ID
	FROM dbo.ClientWriteList()

	INSERT INTO @Client(CL_ID)
	SELECT RCL_ID
	FROM @RClient		
		

	SELECT 
		ClientID = CL_ID, 
		CASE 
			WHEN WCL_ID IS NULL THEN CONVERT(BIT, 0)
			ELSE CONVERT(BIT, 1)
		END AS ClientEdit
	FROM @Client
	LEFT MERGE JOIN @WClient ON CL_ID = WCL_ID
	ORDER BY CL_ID
END