USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[OWNERSHIP_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OwnershipID, OwnershipName
	FROM dbo.OwnershipTable
	WHERE @FILTER IS NULL
		OR OwnershipName LIKE @FILTER 
	ORDER BY OwnershipName
END