USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_VISIT_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, ID_TEACHER, TeacherName, DATE, NOTE
	FROM 
		dbo.ClientStudyVisit a
		INNER JOIN dbo.TeacherTable b ON a.ID_TEACHER = TeacherID
	WHERE a.STATUS = 1
		AND ID_CLIENT = @CLIENT
	ORDER BY DATE DESC
END
