USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[COMPLIANCE_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@SHORT	VARCHAR(100),
	@ORDER	INT,
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ComplianceTypeTable(
			ComplianceTypeName, ComplianceTypeShortName, ComplianceTypeOrder)
		VALUES(@NAME, @SHORT, @ORDER)
	
	SELECT @ID = SCOPE_IDENTITY()
END