USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[RIVAL_STATUS_UPDATE]
	@ID	INT,
	@NAME	VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.RivalStatus
	SET RS_NAME = @NAME
	WHERE RS_ID = @ID
END