USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[REGION_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RG_NAME, RG_PREFIX, RG_SUFFIX, RG_NUM
	FROM dbo.Region
	WHERE RG_ID = @ID
END