USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SUBHOST_STT_ARCH_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, BIN
	FROM Subhost.STTFiles
	WHERE PROCESS IS NULL
END
