USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_SEARCH_SELECT]
	@CLIENTID	INT,
	@BEGIN		DATETIME = NULL,
	@END		DATETIME = NULL,
	@TEXT		VARCHAR(100) = NULL,
	@RC			INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SearchText, SearchDate, SearchGet
	FROM dbo.ClientSearchTable
	WHERE ClientID = @CLIENTID
		AND (SearchDate >= @BEGIN OR @BEGIN IS NULL)
		AND (SearchDate < DATEADD(DAY, 1, @END) OR @END IS NULL)
		AND (SearchText LIKE @TEXT OR @TEXT IS NULL)
	ORDER BY SearchDate DESC

	SET @RC = @@ROWCOUNT
END