USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CALL_TYPE_INSERT]	
	@NAME	VARCHAR(50),
	@SHORT	VARCHAR(50),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.CallTypeTable(CallTypeName, CallTypeShort)
		VALUES(@NAME, @SHORT)
		
	SELECT @ID = SCOPE_IDENTITY()
END