USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_PRINT_PERSONAL_SELECT]
	@LIST	VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @CLIENT	TABLE(CL_ID INT PRIMARY KEY)	

	INSERT INTO @CLIENT
		SELECT ID
		FROM dbo.TableIDFromXML(@LIST)

	SELECT 
		CL_ID,
		CPT_SHORT, ISNULL(CP_SURNAME, '') + 
		CASE ISNULL(CP_NAME, '')	
			WHEN '' THEN ''
			ELSE ' ' + CP_NAME
		END +
		CASE ISNULL(CP_PATRON, '')
			WHEN '' THEN ''
			ELSE ' ' + CP_PATRON
		END AS CP_FIO, CP_POS, CP_NOTE,
		CP_PHONE, CP_EMAIL,
		CP_FAX		
	FROM 
		@CLIENT
		INNER JOIN dbo.ClientPersonal ON CP_ID_CLIENT = CL_ID
		LEFT OUTER JOIN dbo.ClientPersonalType ON CPT_ID = CP_ID_TYPE
	--ORDER BY CL_ID, ISNULL(CPT_REQUIRED, 0) DESC, CPT_ORDER, CP_SURNAME, CP_NAME
	ORDER BY CL_ID, CPT_REQUIRED DESC, CPT_ORDER, CP_SURNAME, CP_NAME
	
END
