USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STATUS_IMAGES_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ServiceImage
	FROM dbo.ServiceStatusTable
	ORDER BY ServiceStatusIndex
END