USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USR_FILE_KIND_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT USRFileKindName, USRFileKindShortName, USRFileKindShort
	FROM dbo.USRFileKindTable
	WHERE USRFileKindID = @ID
END