USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[PHONE_TYPE_INSERT]	
	@NAME	VARCHAR(50),
	@SHORT	VARCHAR(20),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.PhoneType(PT_NAME, PT_SHORT)
		OUTPUT INSERTED.PT_ID INTO @TBL
		VALUES(@NAME, @SHORT)

	SELECT @ID = ID FROM @TBL
END