USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_PERSONAL_TYPE_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@NAME		VARCHAR(100),
	@PSEDO		VARCHAR(50),
	@REQUIRED	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientPersonalType
	SET CPT_NAME		=	@NAME,
		CPT_PSEDO		=	@PSEDO,
		CPT_REQUIRED	=	@REQUIRED,
		CPT_LAST		=	GETDATE()
	WHERE CPT_ID		=	@ID
END