USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VENDOR_INSERT]
	@SHORT		NVARCHAR(64),
	@FULL		NVARCHAR(512),
	@DIRECTOR	NVARCHAR(512),
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO dbo.Vendor(SHORT, FULL_NAME, DIRECTOR)
		OUTPUT INSERTED.ID INTO @TBL
		VALUES(@SHORT, @FULL, @DIRECTOR)

	SELECT @ID = ID FROM @TBL
END