USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_RIVAL_REACTION_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CRR_DATE, CRR_COMMENT, CRR_COMPARE, CRR_CLAIM, CRR_REJECT, CRR_PARTNER
	FROM dbo.ClientRivalReaction
	WHERE CRR_ID = @ID
END