USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DELIVERY_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID_DELIVERY, EMAIL, START, FINISH, NOTE
	FROM dbo.ClientDelivery
	WHERE ID = @ID
END
