USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SYSTEM_BANKS_GET(OLD)]
	@SYS_LIST			NVARCHAR(MAX),
	@DISTR_TYPE_LIST	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @t	TABLE (InfoBank_ID	SMALLINT, InfoBankName	VARCHAR(20), InfoBankShortName	VARCHAR(20), Required	BIT, InfoBankOrder	INT)

	DECLARE @SYS_END				BIT
	SET @SYS_END = 0

	DECLARE @DISTR_TYPE_END			BIT
	DECLARE @DISTR_TYPE_TEMP_LIST	NVARCHAR(128)

	DECLARE @TEMP_S					NVARCHAR(15)
	DECLARE @TEMP_D					NVARCHAR(15)

	WHILE @SYS_END = 0
	BEGIN
		IF (CHARINDEX(',', @SYS_LIST)<>0)
		BEGIN
			SET @TEMP_S = SUBSTRING(@SYS_LIST, 1, CHARINDEX(',', @SYS_LIST)-1)						--«ƒ≈—‹ ¬€“¿— »¬¿≈Ã œŒ ŒƒÕŒÃ” ID —»—“≈Ã€ »« —œ»— ¿
			SET @SYS_LIST = SUBSTRING(@SYS_LIST, CHARINDEX(',', @SYS_LIST)+1, LEN(@SYS_LIST))		
		END
		ELSE
		BEGIN
			SET @TEMP_S = @SYS_LIST
			SET @SYS_END = 1
		END
		
		SET @DISTR_TYPE_END = 0
		SET @DISTR_TYPE_TEMP_LIST = @DISTR_TYPE_LIST

		WHILE @DISTR_TYPE_END = 0
		BEGIN
			IF (CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)<>0)
			BEGIN					
				SET @TEMP_D = SUBSTRING(@DISTR_TYPE_TEMP_LIST, 1, CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)-1)
				SET @DISTR_TYPE_TEMP_LIST = SUBSTRING(@DISTR_TYPE_TEMP_LIST, CHARINDEX(',', @DISTR_TYPE_TEMP_LIST)+1, LEN(@DISTR_TYPE_TEMP_LIST))
			END
			ELSE
			BEGIN
				SET @TEMP_D = @DISTR_TYPE_TEMP_LIST
				SET @DISTR_TYPE_END = 1
			END
			
			INSERT INTO @t(InfoBank_ID, InfoBankName, InfoBankShortName, Required, InfoBankOrder)
			EXEC [dbo].[SYSTEM_BANKS_SELECT] @TEMP_S, @TEMP_D
		END
	END

	SELECT * 
	FROM @t
	GROUP BY InfoBank_ID, InfoBankName, InfoBankShortName, Required, InfoBankOrder
	ORDER BY InfoBankOrder
	
END

