USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[PHONE_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(50),
	@SHORT	VARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	dbo.PhoneType
	SET		PT_NAME	=	@NAME,
			PT_SHORT=	@SHORT,
			PT_LAST	=	GETDATE()
	WHERE	PT_ID	=	@ID
END