USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[HOSTS_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT HostID, HostShort, HostReg, HostOrder
	FROM dbo.Hosts
	WHERE 
		(HostReg LIKE @FILTER OR HostShort LIKE @FILTER)
		OR @FILTER IS NULL
	ORDER BY HostOrder
END