USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[USR_FILE_KIND_INSERT]	
	@NAME	VARCHAR(100),
	@SNAME	VARCHAR(100),
	@SHORT	VARCHAR(100),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.USRFileKindTable(USRFileKindName, USRFileKindShortName, USRFileKindShort)
		VALUES(@NAME, @SNAME, @SHORT)
	
	SELECT @ID = SCOPE_IDENTITY()
END