USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SEMINAR_GRAPH]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@SCOUNT	INT = NULL OUTPUT,
	@CCOUNT	INT = NULL OUTPUT,
	@PCOUNT	INT = NULL OUTPUT,
	@UCOUNT	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.SMONTH, a.CNT AS CL_CNT, b.CNT AS PER_CNT, c.CNT AS SEM_CNT
	FROM
		(
			SELECT dbo.MonthOf(StudyDate) AS SMONTH, COUNT(DISTINCT ClientID) AS CNT
			FROM dbo.ClientSeminarView WITH(NOEXPAND)
			WHERE StudyDate BETWEEN @BEGIN AND @END
			GROUP BY dbo.MonthOf(StudyDate)
		) AS a
		INNER JOIN
		(
			SELECT dbo.MonthOf(StudyDate) AS SMONTH, COUNT(*) AS CNT
			FROM dbo.ClientSeminarView WITH(NOEXPAND)
			WHERE StudyDate BETWEEN @BEGIN AND @END
			GROUP BY dbo.MonthOf(StudyDate)
		) AS b ON a.SMONTH = b.SMONTH
		INNER JOIN 
		(
			SELECT dbo.MonthOf(StudyDate) AS SMONTH, COUNT(DISTINCT StudyDate) AS CNT
			FROM dbo.ClientSeminarView WITH(NOEXPAND)
			WHERE StudyDate BETWEEN @BEGIN AND @END
			GROUP BY dbo.MonthOf(StudyDate)
		) AS c ON a.SMONTH = c.SMONTH
	ORDER BY a.SMONTH
		
		
	SELECT @SCOUNT = COUNT(DISTINCT StudyDate) 
	FROM dbo.ClientSeminarView WITH(NOEXPAND)
	WHERE StudyDate BETWEEN @BEGIN AND @END

	SELECT @CCOUNT = COUNT(DISTINCT ClientID) 
	FROM dbo.ClientSeminarView WITH(NOEXPAND)
	WHERE StudyDate BETWEEN @BEGIN AND @END	
		
	SELECT @PCOUNT = COUNT(*) 
	FROM dbo.ClientSeminarView WITH(NOEXPAND)
	WHERE StudyDate BETWEEN @BEGIN AND @END
	
	SELECT @UCOUNT = COUNT(DISTINCT StudentFam + '+' + StudentName + '+' + StudentOtch) 
	FROM dbo.ClientSeminarView WITH(NOEXPAND)
	WHERE StudyDate BETWEEN @BEGIN AND @END
END