USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MANAGER_INSERT]	
	@NAME	VARCHAR(100),
	@LOGIN	VARCHAR(100),
	@FULL	VARCHAR(250),
	@ID	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ManagerTable(ManagerName, ManagerLogin, ManagerFullName)
		VALUES(@NAME, @LOGIN, @FULL)

	SELECT @ID = SCOPE_IDENTITY()
END