USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STUDY_CLAIM_APPLY]
	@ID			UNIQUEIDENTIFIER,
	@TEACHER	INT = NULL,
	@NOTE		NVARCHAR(MAX) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
	
	INSERT INTO dbo.ClientStudyClaim(ID_MASTER, ID_CLIENT, DATE, STUDY_DATE, CALL_DATE, NOTE, ID_TEACHER, TEACHER_NOTE, MEETING_DATE, MEETING_NOTE, STATUS, UPD_DATE, UPD_USER)
		OUTPUT inserted.ID INTO @TBL 
		SELECT ID, ID_CLIENT, DATE, STUDY_DATE, CALL_DATE, NOTE, ID_TEACHER, TEACHER_NOTE, MEETING_DATE, MEETING_NOTE, 2, UPD_DATE, UPD_USER
		FROM dbo.ClientStudyClaim
		WHERE ID = @ID
		
	DECLARE @NEWID UNIQUEIDENTIFIER
	
	SELECT @NEWID = ID
	FROM @TBL
	
	UPDATE dbo.ClientStudyClaim
	SET TEACHER_NOTE=	ISNULL(@NOTE, TEACHER_NOTE),
		ID_TEACHER  =   ISNULL(@TEACHER, ID_TEACHER),
		STATUS		= 1,
		UPD_DATE	=	GETDATE(),
		UPD_USER	=	ORIGINAL_LOGIN()
	WHERE ID = @ID
	
	UPDATE dbo.ClientStudyClaimPeople
	SET ID_CLAIM = @NEWID
	WHERE ID_CLAIM = @ID
		
	INSERT INTO dbo.ClientStudyClaimPeople(ID_CLAIM, SURNAME, NAME, PATRON, POSITION, PHONE, GR_COUNT, NOTE)
		SELECT 
			@ID, SURNAME, NAME, PATRON, POSITION, PHONE, GR_COUNT, NOTE
		FROM dbo.ClientStudyClaimPeople
		WHERE ID_CLAIM = @NEWID
END
