USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CALENDAR_WORK_GET]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DATE, ID_TYPE, NAME, NOTE
	FROM dbo.CalendarDate
	WHERE ID = @ID
END
