USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_CONTRACT_FOUNDATION]
	@ID		INT,	
	@ID_FOUND	UNIQUEIDENTIFIER,
	@FOUND_END	SMALLDATETIME,
	@NOTE		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.FoundationLog(ID_CONTRACT)
		VALUES(@ID)

	UPDATE dbo.ContractTable
	SET	ID_FOUNDATION = @ID_FOUND,
		FOUND_END = @FOUND_END,
		FOUND_NOTE = @NOTE
	WHERE ContractID = @ID
END