USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CONTACT_TYPE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientContactType
	SET NAME = @NAME,
		LAST = GETDATE()
	WHERE ID = @ID
END
