USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[LETTERS_SELECT]
	@FILTER	NVARCHAR(256) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME, GRP, DATA
	FROM dbo.Letter
	WHERE @FILTER IS NULL
		OR NAME LIKE @FILTER
	ORDER BY GRP, NAME
END
