USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[STUDY_CLAIM_GET]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DATE, NOTE, STUDY_DATE, CALL_DATE
	FROM dbo.ClientStudyClaim
	WHERE ID = @ID
END
