USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_DISTR_GET]
	@ID		UNIQUEIDENTIFIER,
	@CLIENT	INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ID, ID_SYSTEM, DISTR, COMP,
		ID_TYPE, ID_NET, 
		ID_STATUS, ON_DATE
	FROM dbo.ClientDistr a
	WHERE ID = @ID
END