USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLIENT_INNOVATION_CONTROL]
	@PERSONAL	UNIQUEIDENTIFIER,
	@DATE		SMALLDATETIME,
	@SURNAME	NVARCHAR(256),
	@NAME		NVARCHAR(256),
	@PATRON		NVARCHAR(256),
	@NOTE		NVARCHAR(MAX),
	@RESULT		TINYINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.ClientInnovationControl
	SET DATE	=	@DATE,
		AUDITOR	=	ORIGINAL_LOGIN(),
		SURNAME	=	@SURNAME,
		NAME	=	@NAME,
		PATRON	=	@PATRON,
		NOTE	=	@NOTE,
		RESULT	=	@RESULT
	WHERE ID_PERSONAL = @PERSONAL
	
	IF @@ROWCOUNT = 0
		INSERT INTO dbo.ClientInnovationControl(ID_PERSONAL, DATE, SURNAME, NAME, PATRON, NOTE, RESULT)
			VALUES(@PERSONAL, @DATE, @SURNAME, @NAME, @PATRON, @NOTE, @RESULT)
END
