USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STUDY_SALE_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, DATE, FIO, RIVAL_CLIENT_ID, RIVAL_CLIENT, LPR, USER_POST, NOTE
	FROM dbo.StudySale
	WHERE ID_CLIENT = @CLIENT
	ORDER BY DATE DESC
END
