USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[SYSTEM_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SST_ID, SST_NAME, SST_NOTE, SST_SHORT, SST_WEIGHT
	FROM Din.SystemType
	WHERE @FILTER IS NULL
		OR SST_NAME LIKE @FILTER
		OR SST_SHORT LIKE @FILTER
		OR SST_REG LIKE @FILTER
		OR SST_NOTE LIKE @FILTER
	ORDER BY SST_NAME, SST_NOTE
END