USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[SYSTEM_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@SHORT	VARCHAR(20),
	@NOTE	VARCHAR(100),
	@REG	VARCHAR(50),
	@WEIGHT	BIT,
	@COMPLECT	BIT,
	@MASTER	INT,
	@SALARY	DECIMAL(8,4),
	@ID		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;	

	INSERT INTO Din.SystemType(SST_NAME, SST_SHORT, SST_NOTE, SST_REG, SST_WEIGHT, SST_COMPLECT, SST_ID_MASTER, SST_SALARY)
		VALUES(@NAME, @SHORT, @NOTE, @REG, @WEIGHT, @COMPLECT, @MASTER, @SALARY)
	
	SELECT @ID = SCOPE_IDENTITY()
END