USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Din].[SYSTEM_TYPE_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;	

	SELECT SST_NAME, SST_SHORT, SST_NOTE, SST_REG, SST_WEIGHT, SST_ID_MASTER, SST_COMPLECT, SST_SALARY
	FROM Din.SystemType
	WHERE SST_ID = @ID
END