USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[NET_TYPE_INSERT]	
	@NAME	VARCHAR(100),
	@NOTE	VARCHAR(50),
	@NET	SMALLINT,
	@TECH	SMALLINT,
	@SHORT	VARCHAR(20),
	@MASTER	INT,
	@VMI_SHORT	VARCHAR(50),
	@ODOFF	SMALLINT,
	@ODON	SMALLINT,
	@TECH_USR	VarChar(20),
	@ID		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Din.NetType(NT_NAME, NT_NOTE, NT_NET, NT_TECH, NT_SHORT, NT_ID_MASTER, NT_VMI_SHORT, NT_ODOFF, NT_ODON, NT_TECH_USR)
		VALUES(@NAME, @NOTE, @NET, @TECH, @SHORT, @MASTER, @VMI_SHORT, @ODOFF, @ODON, @TECH_USR)

	SELECT @ID = SCOPE_IDENTITY()
END