USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[DIN_LIST_SELECT]
	@ID	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DF_DIN, DF_FILE
	FROM 
		Din.DinFiles
		INNER JOIN dbo.TableIDFromXML(@ID) ON ID = DF_ID
END