USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Din].[SYSTEM_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SystemID, SystemDin, SystemBaseName
	FROM dbo.SystemTable
END