USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[NET_TYPE_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NT_ID, NT_NAME, NT_NOTE, NT_SHORT
	FROM Din.NetType
	WHERE @FILTER IS NULL
		OR NT_NAME LIKE @FILTER
		OR NT_NOTE LIKE @FILTER
	ORDER BY NT_NAME, NT_NOTE
END