USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Din].[SYSTEM_TYPE_UPDATE]
	@ID	INT,
	@NAME	VARCHAR(100),
	@SHORT	VARCHAR(20),
	@NOTE	VARCHAR(100),
	@REG	VARCHAR(50),
	@WEIGHT	BIT,
	@COMPLECT	BIT,
	@MASTER	INT,
	@SALARY	DECIMAL(8,4)
AS
BEGIN
	SET NOCOUNT ON;	

	UPDATE Din.SystemType
	SET SST_NAME	=	@NAME,
		SST_SHORT	=	@SHORT,
		SST_NOTE	=	@NOTE,
		SST_REG		=	@REG,
		SST_WEIGHT	=	@WEIGHT,
		SST_COMPLECT	=	@COMPLECT,
		SST_ID_MASTER	=	@MASTER,
		SST_SALARY		=	@SALARY,
		SST_LAST	=	GETDATE()
	WHERE SST_ID = @ID
END