USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [IP].[CLIENT_STAT_STT_CACHE_REFRESH]
AS
BEGIN
	SET NOCOUNT ON;
	
	TRUNCATE TABLE IP.ClientStatSTTCache

	INSERT INTO
		IP.ClientStatSTTCache(CSD_SYS, CSD_DISTR, CSD_COMP, CSD_START, CSD_END)
	SELECT DISTINCT
		CSD_SYS, 
		CSD_DISTR, 
		CSD_COMP, 
		CSD_START, 
		CSD_END
	FROM [PC275-SQL\OMEGA].[IPLogs].[dbo].[ClientStatDetail]
	WHERE CSD_START IS NOT NULL
		AND CSD_STT_SEND = 1 
		AND CSD_STT_RESULT = 1
END;