USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CLIENT_STAT_DETAIL_INSERT]
@DISTR		INT,
@COMP		INT,
@NET		NVARCHAR(256),
@LOGIN_CNT	INT,
@USER_CNT	INT,
@W_USER_CNT	TINYINT,
@N_USER_CNT	TINYINT,
@WEEK_NUM	INT
AS
INSERT INTO dbo.ClientStatDetail ([UpDate], WeekId, HostId, Distr, Comp, Net, LoginCNT, UserCNT, WorkUserCNT, NotWorkUserCNT)
SELECT
	GETDATE(),
	(
	SELECT ID
	FROM Common.Period
	WHERE TYPE=1 AND START=(
							SELECT TOP(1) START
							FROM Common.Period
							WHERE TYPE=1 AND DATEPART(yy, START)=DATEPART(yy, GETDATE()) AND DATEPART(ww, START)=@WEEK_NUM
							ORDER BY START DESC
							)
	),
	1,
	@DISTR,
	@COMP,
	@NET,
	@LOGIN_CNT,
	@USER_CNT,
	@W_USER_CNT,
	@N_USER_CNT