USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [IP].[CLIENT_STAT_DETAIL_CACHE_REFRESH]
AS
TRUNCATE TABLE IP.ClientStatDetailCache

--DECLARE @t TABLE(rn INT, CSD_SYS SMALLINT, CSD_DISTR INT, CSD_COMP SMALLINT, CSD_START DATETIME, CSD_CODE_CLIENT INT, CSD_CODE_CLIENT_NOTE NVARCHAR(256), CSD_USR NVARCHAR(256))

--INSERT INTO @t (rn, CSD_SYS, CSD_DISTR, CSD_COMP, CSD_START, CSD_CODE_CLIENT, CSD_CODE_CLIENT_NOTE, CSD_USR)


INSERT INTO
	IP.ClientStatDetailCache(CSD_SYS, CSD_DISTR, CSD_COMP, CSD_START, CSD_CODE_CLIENT, CSD_CODE_CLIENT_NOTE, CSD_USR)
SELECT
	CSD_SYS, 
	CSD_DISTR, 
	CSD_COMP, 
	CSD_START, 
	CSD_CODE_CLIENT, 
	CSD_CODE_CLIENT_NOTE,
	CSD_USR
FROM 
	(
		SELECT
			ROW_NUMBER() OVER(PARTITION BY CSD_SYS, CSD_DISTR, CSD_COMP ORDER BY CSD_START DESC) AS [rn],
			CSD_SYS,
			CSD_DISTR,
			CSD_COMP,
			CSD_START,
			CSD_CODE_CLIENT,
			ISNULL((SELECT TOP 1 RC_TEXT
			     FROM dbo.IPReturnCodeView
			     WHERE RC_NUM = a.CSD_CODE_CLIENT 
						AND RC_TYPE = 'CLIENT'
		 		 ORDER BY RC_ID
            ), 'неизвестный код') as CSD_CODE_CLIENT_NOTE,
			CSD_USR
		FROM
			dbo.IPClientDetailView a
	) z
WHERE
	rn=1