USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE dbo.IP_STAT_CLIENT_SELECT
@HOST	TINYINT,
@DISTR	INT,
@COMP	TINYINT
AS
SELECT *
FROM dbo.ClientStatDetail
WHERE HostId=@HOST AND Distr=@DISTR AND Comp=@COMP