USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [IP].[LIST_INCLUDE]
	@TP		TINYINT,
	@HOST	SMALLINT,
	@DISTR	INT,
	@COMP	TINYINT,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO IP.Lists(ID_HOST, DISTR, COMP, TP, SET_DATE, SET_USER, SET_REASON)
		SELECT @HOST, @DISTR, @COMP, @TP, GETDATE(), ORIGINAL_LOGIN(), @NOTE
		WHERE NOT EXISTS
			(
				SELECT *
				FROM IP.Lists
				WHERE ID_HOST = @HOST AND DISTR = @DISTR AND COMP = @COMP AND TP = @TP AND UNSET_DATE IS NULL
			)
END
