USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [KGS].[MEMO_CLAIM_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		TP, DATE, ID_CLIENT, CL_NAME, ID_VENDOR, ID_TRADESITE, DATE_LIMIT, CLAIM_SUM, 
		TENDER_DATE, TENDER_NUM, DETAILS, RTRN, RTRN_RULE, CO_BEGIN, CO_END, CO_DISCOUNT, CO_SUM, NOTE
	FROM KGS.MemoClaim
	WHERE ID = @ID
END
