USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Kladr].[FIAS_SEARCH]
	@SEARCH	NVARCHAR(512),
	@LEVEL	NVARCHAR(MAX),
	@CHILD	BIT,
	@REGION	NVARCHAR(3)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQL NVARCHAR(MAX)

	SET @SQL = N'EXEC [PC275-SQL\SIGMA].Ric.Fias.SEARCH @SEARCH, @LEVEL, @CHILD, @REGION'
	
	EXEC sp_executesql @SQL, N'@SEARCH NVARCHAR(512), @LEVEL NVARCHAR(MAX), @CHILD BIT, @REGION NVARCHAR(3)', @SEARCH, @LEVEL, @CHILD, @REGION
END
