USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Kladr].[FIAS_LEVEL_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC('EXEC [PC275-SQL\SIGMA].Ric.Fias.LEVEL_SELECT')
END
