USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Mailing].[REQUEST_CONFIRM]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Mailing.Requests
	SET ConfirmDate = GetDate()
	WHERE ID = @ID
		AND ConfirmDate IS NULL
END
