USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Maintenance].[PROC_JOURNAL_CLEAR]
	@DATE	SMALLDATETIME = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @DATE IS NULL
		TRUNCATE TABLE Security.ExecutionLog
	ELSE
		DELETE 
		FROM Security.ExecutionLog
		WHERE LG_DATE < @DATE
END