USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Maintenance].[USR_JOURNAL_CLEAR]
	@DATE	SMALLDATETIME = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @DATE IS NULL
		TRUNCATE TABLE USR.ProcessJournal
	ELSE
		DELETE 
		FROM USR.ProcessJournal
		WHERE PR_DATE < @DATE
END