USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Maintenance].[BACKUP_CREATE]
	@PATH	NVARCHAR(512)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQL NVARCHAR(MAX)

	SET @PATH = @PATH + N'ClientDB' + CONVERT(NVARCHAR(100), GETDATE(), 112) + N'.bak'

	SET @SQL = N'BACKUP DATABASE  [' + DB_NAME() + N'] TO  DISK = ''' + @PATH + N'''
			WITH  
				INIT ,  
				NOUNLOAD ,  
				NAME = ''ClientDB FULL BACKUP'',
				SKIP ,  
				STATS = 10,  
				NOFORMAT 
		'

	EXEC (@SQL)
END