USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Maintenance].[JOB_FINISH]
	@Id		BigInt,
	@ERR	NVARCHAR(128) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Maintenance.Jobs
	SET 
		FINISH = GetDate(),
		ERR = @ERR
	WHERE ID = @Id;
END
