USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Maintenance].[JOB_DETAIL_SELECT]
	@ID			INT,
	@EX_TIME_ST	INT,
	@EX_TIME_FIN INT
AS
	SELECT TOP(100) *
	FROM Maintenance.Jobs
	WHERE	Type_Id=@ID AND
			(@EX_TIME_ST<DATEDIFF(s, START, FINISH) OR @EX_TIME_ST IS NULL)AND
			(@EX_TIME_FIN>DATEDIFF(s, START, FINISH) OR @EX_TIME_FIN IS NULL)
	ORDER BY START DESC