USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Maintenance].[STT_CLEAR]
	@DATE	SMALLDATETIME = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @DATE IS NULL
		TRUNCATE TABLE dbo.ClientStat
	ELSE
		DELETE 
		FROM dbo.ClientStat
		WHERE DATE < @DATE
END
