USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Memo].[CLIENT_MEMO_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@CLIENT	INT,
	@CONTRACT	NVARCHAR(512),
	@DISTR		NVARCHAR(MAX),
	@DOC_TYPE	UNIQUEIDENTIFIER,
	@SERVICE	UNIQUEIDENTIFIER,
	@VENDOR		UNIQUEIDENTIFIER,
	@START		SMALLDATETIME,
	@FINISH		SMALLDATETIME,
	@MONTH		MONEY,
	@PERIOD		MONEY,
	@PER_START	SMALLDATETIME,
	@PER_END	SMALLDATETIME,
	@PER_FULL	MONEY,
	@PAY_TYPE	INT,
	@FRAMEWORK	NVARCHAR(1024),
	@DOCUMENTS	NVARCHAR(1024),
	@CANCEL		BIT,
	@SYSTEM		NVARCHAR(MAX) = NULL,
	@ID_CONTRACT_PAY INT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Memo.ClientMemo
	SET	CURRENT_CONTRACT	=	@CONTRACT,
		DISTR				=	@DISTR,
		ID_DOC_TYPE			=	@DOC_TYPE,
		ID_SERVICE			=	@SERVICE,
		ID_VENDOR			=	@VENDOR,
		START				=	@START,
		FINISH				=	@FINISH,
		MONTH_PRICE			=	@MONTH,
		PERIOD_PRICE		=	@PERIOD,
		PERIOD_START		=	@PER_START,
		PERIOD_END			=	@PER_END,
		PERIOD_FULL_PRICE	=	@PER_FULL,
		ID_PAY_TYPE			=	@PAY_TYPE,
		ID_CONTRACT_PAY_TYPE = @ID_CONTRACT_PAY,
		FRAMEWORK			=	@FRAMEWORK,
		DOCUMENTS			=	@DOCUMENTS,
		LETTER_CANCEL		=	@CANCEL,
		SYSTEMS				=	@SYSTEM
	WHERE ID = @ID
	
	DELETE FROM Memo.ClientMemoConditions
	WHERE ID_MEMO = @ID
END
