USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Memo].[KGS_MEMO_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		NAME, DATE, PRICE, ID_MONTH, MON_CNT
	FROM Memo.KGSMemo a
	WHERE ID = @ID
END
