USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Memo].[CLIENT_CALCULATION_SAVE]
	@ID			UNIQUEIDENTIFIER,
	@CLIENT		INT,
	@NOTE		NVARCHAR(MAX),
	@DATE		SMALLDATETIME,
	@SYSTEMS	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO Memo.ClientCalculation(ID_CLIENT, DATE, NOTE, SYSTEMS)
			SELECT @CLIENT, dbo.DateOf(GETDATE()), @NOTE, @SYSTEMS
	ELSE
		UPDATE Memo.ClientCalculation
		SET NOTE = @NOTE,
			SYSTEMS = @SYSTEMS
		WHERE ID = @ID
END
