USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Memo].[SERVICE_INSERT]
	@NAME	NVARCHAR(512),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO Memo.Service(NAME)
		OUTPUT inserted.ID INTO @TBL
		VALUES(@NAME)
		
	SELECT @ID = ID FROM @TBL
END
