USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Memo].[CLIENT_MEMO_DELETE]
	@ID			UNIQUEIDENTIFIER,
	@TP			SMALLINT = 1
AS
BEGIN
	SET NOCOUNT ON;

	IF @TP = 1
	BEGIN
		DELETE FROM Memo.ClientMemoConditions
		WHERE ID_MEMO = @ID

		DELETE
		FROM Memo.ClientMemo	
		WHERE ID = @ID	
	END
	ELSE
		DELETE FROM Memo.ClientCalculation WHERE ID = @ID
END
