USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Poll].[CLIENT_POLL_DELETE]
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM Poll.ClientPollAnswer WHERE ID_QUESTION IN (SELECT ID FROM Poll.ClientPollQuestion WHERE ID_POLL = @ID)
	DELETE FROM Poll.ClientPollQuestion WHERE ID_POLL = @ID
	DELETE FROM Poll.ClientPoll WHERE ID = @ID
END
