USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Poll].[BLANK_QUESTION_ANSWER_SELECT]
	@QUESTION	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME
	FROM Poll.Answer
	WHERE ID_QUESTION = @QUESTION
	ORDER BY ORD
END
