USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Poll].[CLIENT_POLL_GET]
	@ID	UNIQUEIDENTIFIER,
	@CALL	UNIQUEIDENTIFIER = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @CALL IS NOT NULL
		SELECT ID, DATE, ID_BLANK, NOTE
		FROM Poll.ClientPoll		
		WHERE ID_CALL = @CALL
	ELSE
		SELECT ID, DATE, ID_BLANK, NOTE
		FROM Poll.ClientPoll
		WHERE ID = @ID
		
	/*
	SELECT ID, DATE, ID_BLANK, NOTE
	FROM Poll.ClientPoll
	WHERE (ID = @ID OR @ID IS NULL)
		AND (ID_CALL = @CALL OR @CALL IS NULL)
		AND (ID_CALL IS NOT NULL OR @ID IS NOT NULL)
		*/
END
