USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Poll].[CLIENT_POLL_SELECT]
	@CLIENT	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, DATE, b.NAME, NOTE
	FROM 
		Poll.ClientPoll a
		INNER JOIN Poll.Blank b ON a.ID_BLANK = b.ID
	WHERE ID_CLIENT = @CLIENT
	ORDER BY DATE DESC
END
