USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Poll].[CLIENT_POLL_SAVE]
	@ID		UNIQUEIDENTIFIER OUTPUT,
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@BLANK	UNIQUEIDENTIFIER,
	@NOTE	NVARCHAR(MAX),
	@ID_CALL	UNIQUEIDENTIFIER = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
		
		INSERT INTO Poll.ClientPoll(ID_CLIENT, DATE, ID_BLANK, NOTE, ID_CALL)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@CLIENT, @DATE, @BLANK, @NOTE, @ID_CALL)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
	BEGIN
		UPDATE Poll.ClientPoll
		SET DATE = @DATE,
			NOTE = @NOTE
		WHERE ID = @ID
		
		DELETE FROM Poll.ClientPollAnswer WHERE ID_QUESTION IN (SELECT ID FROM Poll.ClientPollQuestion WHERE ID_POLL = @ID)
		DELETE FROM Poll.ClientPollQuestion WHERE ID_POLL = @ID
	END
END
