USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[OFFER_OTHER_SET]
	@NOTE	VARBINARY(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Price.OfferOther
	SET NOTE = @NOTE	

	IF @@ROWCOUNT = 0
		INSERT INTO Price.OfferOther(NOTE)
			VALUES(@NOTE)
END
