USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[PRICE_HISTORY_SELECT]
	@SYSTEM	INT,
	@MONTH	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @START SMALLDATETIME

	SELECT @START = START
	FROM Common.Period
	WHERE ID = @MONTH

	SELECT NAME, PRICE
	FROM
		(
			SELECT START, NAME, PRICE, ROW_NUMBER() OVER(PARTITION BY PRICE ORDER BY START) AS RN
			FROM 
				Price.SystemPrice a
				INNER JOIN Common.Period b ON a.ID_MONTH = b.ID
			WHERE ID_SYSTEM = @SYSTEM AND START <= @START
		) AS o_O 
	WHERE RN = 1
	ORDER BY START DESC
END