USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Price].[PRICE_UPDATE]
	@MONTH	UNIQUEIDENTIFIER,
	@SYSTEM	INT,
	@PRICE	MONEY
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Price.SystemPrice
	SET PRICE = @PRICE
	WHERE ID_SYSTEM = @SYSTEM AND ID_MONTH = @MONTH
END
