USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Price].[PRICE_DELETE]
	@MONTH	UNIQUEIDENTIFIER,
	@SYSTEM	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Price.SystemPrice
	WHERE ID_SYSTEM = @SYSTEM AND ID_MONTH = @MONTH
END
