USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[GOOD_REQUIREMENT_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Purchase.ClientConditionGoodRequirement
	WHERE CCGR_ID_GR = @ID

	DELETE
	FROM Purchase.GoodRequirement
	WHERE GR_ID = @ID
END