USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PRICE_VALIDATION_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PV_ID, PV_NAME, PV_SHORT
	FROM Purchase.PriceValidation
	WHERE @FILTER IS NULL
		OR PV_NAME LIKE @FILTER
		OR PV_SHORT LIKE @FILTER
	ORDER BY PV_SHORT
END