USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PURCHASE_TYPE_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PT_ID, PT_NAME
	FROM Purchase.PurchaseType
	WHERE @FILTER IS NULL
		OR PT_NAME LIKE @FILTER
	ORDER BY PT_NAME
END