USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PURCHASE_REASON_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE 
	FROM Purchase.ClientConditionReason
	WHERE CCR_ID_PR = @ID

	DELETE
	FROM Purchase.PurchaseReason
	WHERE PR_ID = @ID
END