USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[TRADEMARK_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.Trademark
	SET TM_NAME		=	@NAME,
		TM_SHORT	=	@SHORT,
		TM_LAST		=	GETDATE()
	WHERE TM_ID = @ID
END