USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PAY_PERIOD_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(500),
	@SHORT	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PayPeriod
	SET PP_NAME		=	@NAME,
		PP_SHORT	=	@SHORT,
		PP_LAST		=	GETDATE()
	WHERE PP_ID = @ID
END