USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[SIGN_PERIOD_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(1000),
	@SHORT	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.SignPeriod
	SET SP_NAME		=	@NAME,
		SP_SHORT	=	@SHORT,
		SP_LAST		=	GETDATE()
	WHERE SP_ID = @ID
END