USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[TENDER_NAME_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(500),
	@SHORT	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.TenderName
	SET TN_NAME		=	@NAME,
		TN_SHORT	=	@SHORT
	WHERE TN_ID = @ID
END