USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[GOOD_REQUIREMENT_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT GR_NAME, GR_SHORT
	FROM Purchase.GoodRequirement
	WHERE GR_ID = @ID
END