USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[USE_CONDITION_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT UC_ID, UC_NAME, UC_SHORT
	FROM Purchase.UseCondition
	WHERE @FILTER IS NULL
		OR UC_NAME LIKE @FILTER
		OR UC_SHORT LIKE @FILTER
	ORDER BY UC_SHORT
END