USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PARTNER_REQUIREMENT_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PR_ID, PR_NAME, PR_SHORT
	FROM Purchase.PartnerRequirement
	WHERE @FILTER IS NULL
		OR PR_NAME LIKE @FILTER
		OR PR_SHORT LIKE @FILTER
	ORDER BY PR_SHORT
END