USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PLACEMENT_ORDER_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PO_ID, PO_NAME, PO_NUM
	FROM Purchase.PlacementOrder
	WHERE @FILTER IS NULL
		OR PO_NAME LIKE @FILTER
		OR CONVERT(VARCHAR(20), PO_NUM) LIKE @FILTER
	ORDER BY PO_NUM, PO_NAME
END