USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[CLAIM_CANCEL_REASON_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CCR_NAME, CCR_SHORT
	FROM Purchase.ClaimCancelReason
	WHERE CCR_ID = @ID
END