USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PURCHASE_REASON_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PR_ID, PR_NAME, PR_NUM
	FROM Purchase.PurchaseReason
	WHERE @FILTER IS NULL
		OR PR_NAME LIKE @FILTER
		OR CONVERT(VARCHAR(20), PR_NUM) LIKE @FILTER
	ORDER BY PR_NUM, PR_NAME
END