USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[CLAIM_CANCEL_REASON_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CCR_ID, CCR_NAME, CCR_SHORT
	FROM Purchase.ClaimCancelReason
	WHERE @FILTER IS NULL
		OR CCR_NAME LIKE @FILTER
		OR CCR_SHORT LIKE @FILTER
	ORDER BY CCR_SHORT
END