USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[TRADE_SITE_INSERT]
	@NAME	VARCHAR(4000),
	@URL	VARCHAR(250),
	@SHORT	VARCHAR(200),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO Purchase.TradeSite(TS_NAME, TS_URL, TS_SHORT)
		OUTPUT inserted.TS_ID INTO @TBL
		VALUES(@NAME, @URL, @SHORT)
		
	SELECT @ID = ID
	FROM @TBL
END