USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[TRADE_SITE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@URL	VARCHAR(250),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.TradeSite
	SET TS_NAME		=	@NAME,
		TS_URL		=	@URL,
		TS_SHORT	=	@SHORT
	WHERE TS_ID = @ID
END