USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[CLAIM_PROVISION_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CP_NAME, CP_SHORT
	FROM Purchase.ClaimProvision
	WHERE CP_ID = @ID
END