USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[APPLY_REASON_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT AR_NAME, AR_SHORT
	FROM Purchase.ApplyReason
	WHERE AR_ID = @ID
END