USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[CLAIM_PROVISION_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CP_ID, CP_NAME, CP_SHORT
	FROM Purchase.ClaimProvision
	WHERE @FILTER IS NULL
		OR CP_NAME LIKE @FILTER
		OR CP_SHORT LIKE @FILTER
	ORDER BY CP_SHORT, CP_NAME
END