USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[OTHER_PROVISION_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OP_ID, OP_NAME, OP_SHORT
	FROM Purchase.OtherProvision
	WHERE @FILTER IS NULL
		OR OP_NAME LIKE @FILTER
		OR OP_SHORT LIKE @FILTER
	ORDER BY OP_SHORT, OP_NAME
END