USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[CLAIM_CANCEL_REASON_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.ClaimCancelReason
	SET CCR_NAME	=	@NAME,
		CCR_SHORT	=	@SHORT,
		CCR_LAST	=	GETDATE()
	WHERE CCR_ID = @ID
END