USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[CONTRACT_EXECUTION_PROVISION_INSERT]
	@NAME	VARCHAR(250),
	@SHORT	VARCHAR(50),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO Purchase.ContractExecutionProvision(CEP_NAME, CEP_SHORT)
		OUTPUT inserted.CEP_ID INTO @TBL
		VALUES(@NAME, @SHORT)
		
	SELECT @ID = ID
	FROM @TBL
END