USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PLACEMENT_ORDER_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PO_NAME, PO_NUM
	FROM Purchase.PlacementOrder
	WHERE PO_ID = @ID
END