USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PLACEMENT_ORDER_INSERT]
	@NAME	VARCHAR(150),
	@NUM	SMALLINT,
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO Purchase.PlacementOrder(PO_NAME, PO_NUM)
		OUTPUT inserted.PO_ID INTO @TBL
		VALUES(@NAME, @NUM)
		
	SELECT @ID = ID
	FROM @TBL
END