USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[TENDER_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC Purchase.TENDER_ARCHIEVE @ID

	UPDATE Purchase.Tender
	SET TD_STATUS = 3,
		TD_UPDATE = GETDATE(),
		TD_UPDATE_USER = ORIGINAL_LOGIN()
	WHERE TD_ID = @ID
END