USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[USE_CONDITION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(MAX),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.UseCondition
	SET UC_NAME		=	@NAME,
		UC_SHORT	=	@SHORT
	WHERE UC_ID = @ID
END