USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PURCHASE_KIND_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PurchaseKind
	SET PK_NAME = @NAME,
		PK_LAST = GETDATE()
	WHERE PK_ID = @ID
END