USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PURCHASE_TYPE_INSERT]
	@NAME	VARCHAR(50),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO Purchase.PurchaseType(PT_NAME)
		OUTPUT inserted.PT_ID INTO @TBL
		VALUES(@NAME)	
		
	SELECT @ID = ID
	FROM @TBL
END