USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[CLAIM_PROVISION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.ClaimProvision
	SET CP_NAME		=	@NAME,
		CP_SHORT	=	@SHORT,
		CP_LAST		=	GETDATE()
	WHERE CP_ID = @ID
END