USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[TALK_HISTORY_INSERT]
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@WHO	VARCHAR(150),
	@PERS	VARCHAR(150),
	@THEME	VARCHAR(MAX),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

	INSERT INTO Purchase.TalkHistory(TH_ID_CLIENT, TH_DATE, TH_WHO, TH_PERSONAL, TH_THEME)
		OUTPUT inserted.TH_ID INTO @TBL
		VALUES(@CLIENT, @DATE, @WHO, @PERS, @THEME)

	SELECT @ID = ID
	FROM @TBL
END