USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[TALK_HISTORY_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Purchase.TalkHistory(TH_ID_MASTER, TH_ID_CLIENT, TH_DATE, TH_WHO, TH_PERSONAL, TH_THEME, TH_STATUS, TH_UPDATE, TH_USER)
		SELECT @ID, TH_ID_CLIENT, TH_DATE, TH_WHO, TH_PERSONAL, TH_THEME, 2, TH_UPDATE, TH_USER
		FROM Purchase.TalkHistory
		WHERE TH_ID = @ID

	UPDATE Purchase.TalkHistory
	SET TH_STATUS = 3,
		TH_UPDATE = GETDATE(),
		TH_USER = ORIGINAL_LOGIN()
	WHERE TH_ID = @ID
END