USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PLACEMENT_ORDER_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(150),
	@NUM	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PlacementOrder
	SET PO_NAME =	@NAME,
		PO_NUM	=	@NUM,
		PO_LAST =	GETDATE()
	WHERE PO_ID = @ID
END