USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[TRADEMARK_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TM_ID, TM_NAME, TM_SHORT
	FROM Purchase.Trademark
	WHERE @FILTER IS NULL
		OR TM_NAME LIKE @FILTER
		OR TM_SHORT LIKE @FILTER
	ORDER BY TM_SHORT
END