USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[APPLY_REASON_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.ApplyReason
	SET AR_NAME		=	@NAME,
		AR_SHORT	=	@SHORT,
		AR_LAST		=	GETDATE()
	WHERE AR_ID = @ID
END