USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[CONTRACT_EXECUTION_PROVISION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(250),
	@SHORT	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.ContractExecutionProvision
	SET CEP_NAME		=	@NAME,
		CEP_SHORT		=	@SHORT
	WHERE CEP_ID = @ID
END