USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PRICE_VALIDATION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PriceValidation
	SET PV_NAME		=	@NAME,
		PV_SHORT	=	@SHORT,
		PV_LAST		=	GETDATE()
	WHERE PV_ID = @ID
END