USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PURCHASE_REASON_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@NUM	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PurchaseReason
	SET PR_NAME =	@NAME,
		PR_NUM	=	@NUM,
		PR_LAST =	GETDATE()
	WHERE PR_ID = @ID
END