USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[DOCUMENT_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.Document
	SET DC_NAME		=	@NAME,
		DC_SHORT	=	@SHORT,
		DC_LAST		=	GETDATE()
	WHERE DC_ID = @ID
END