USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[USE_CONDITION_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Purchase.ClientConditionPlacementOrderUseCondition
	WHERE ID_UC = @ID

	DELETE
	FROM Purchase.UseCondition
	WHERE UC_ID = @ID
END