USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[GOOD_REQUIREMENT_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT GR_ID, GR_NAME, GR_SHORT
	FROM Purchase.GoodRequirement
	WHERE @FILTER IS NULL
		OR GR_NAME LIKE @FILTER
		OR GR_SHORT LIKE @FILTER
	ORDER BY GR_SHORT
END