USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PARTNER_REQUIREMENT_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(4000),
	@SHORT	VARCHAR(200)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Purchase.PartnerRequirement
	SET PR_NAME		=	@NAME,
		PR_SHORT	=	@SHORT,
		PR_LAST		=	GETDATE()
	WHERE PR_ID = @ID
END