USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Purchase].[PAY_PERIOD_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PP_ID, PP_NAME, PP_SHORT
	FROM Purchase.PayPeriod
	WHERE @FILTER IS NULL
		OR PP_NAME LIKE @FILTER
		OR PP_SHORT LIKE @FILTER
	ORDER BY PP_SHORT
END