USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[PRICE_VALIDATION_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Purchase.ClientConditionPriceValidation
	WHERE CCPV_ID_PV = @ID

	DELETE
	FROM Purchase.PriceValidation
	WHERE PV_ID = @ID
END