USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Purchase].[TENDER_NAME_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TN_ID, TN_NAME, TN_SHORT
	FROM Purchase.TenderName
	WHERE @FILTER IS NULL
		OR TN_NAME LIKE @FILTER
		OR TN_SHORT LIKE @FILTER
	ORDER BY TN_SHORT
END