USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Reg].[CLIENT_DISTR_PROTOCOL_TEXT]
	@ID		UNIQUEIDENTIFIER	= NULL,
	@STR	VARCHAR(50)			= NULL OUTPUT,
	@HST	INT					= NULL,
	@DISTR	INT					= NULL,
	@COMP	TINYINT				= NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NOT NULL
		SELECT 
			@HST = HostID, @DISTR = DISTR, @COMP = COMP,
			@STR = DistrStr
		FROM dbo.ClientDistrView a WITH(NOEXPAND)
		WHERE ID = @ID	
	ELSE
		SELECT @STR = DistrStr
		FROM 
			Reg.RegNodeSearchView a WITH(NOEXPAND)
			INNER JOIN dbo.SystemTable b ON a.SystemID = b.SystemID
		WHERE b.HostID = @HST AND DistrNumber = @DISTR AND CompNumber = @COMP

	SELECT DATE, CNT, COMMENT
	FROM Reg.ProtocolText
	WHERE ID_HOST = @HST AND DISTR = @DISTR AND COMP = @COMP
	ORDER BY DATE DESC, ID DESC
END