USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Reg].[ONLINE_PASSWORD_SET]
	@SYSTEM	INT,
	@HOST	INT,
	@DISTR	INT,
	@COMP	TINYINT,
	@PASS	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Reg.OnlinePassword
	SET STATUS = 2
	WHERE ID_HOST = @HOST AND DISTR = @DISTR AND COMP = @COMP
	
	INSERT INTO Reg.OnlinePassword(ID_SYSTEM, ID_HOST, DISTR, COMP, PASS)
		VALUES(@SYSTEM, @HOST, @DISTR, @COMP, @PASS)
END
