USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Report].[INNOVATION_REPORT]
	@PARAM	NVARCHAR(MAX) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT EXECUTE_DATE_S AS [Дата исполнения], DETAIL_DATA AS [Описание], EXECUTOR_NOTE AS [Примечание исполнителя]
	FROM dbo.TaskDBView
	ORDER BY EXECUTE_DATE_S DESC
END
