USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Salary].[SERVICE_SALARY_DISTR_SELECT]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ID, CLIENT, DISTR_STR, OPER, PRICE_OLD, PRICE_NEW, PRICE_NEW - PRICE_OLD AS PRICE_DELTA, 
		WEIGHT_OLD, WEIGHT_NEW, WEIGHT_NEW - WEIGHT_OLD AS WEIGHT_DELTA
	FROM 
		Salary.ServiceDistr		
	WHERE ID_SALARY = @ID
	ORDER BY CLIENT, DISTR_STR
END
