USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Salary].[SERVICE_SALARY_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE 
	FROM Salary.ServiceStudy
	WHERE ID_SALARY = @ID

	DELETE 
	FROM Salary.ServiceDistr
	WHERE ID_SALARY = @ID
	
	DELETE 
	FROM Salary.ServiceClient
	WHERE ID_SALARY = @ID

	DELETE 
	FROM Salary.Service
	WHERE ID = @ID
END
