USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Salary].[SERVICE_SALARY_STUDY_SELECT]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, ID_CLIENT, ClientFullName, DATE
	FROM 
		Salary.ServiceStudy
		INNER JOIN dbo.ClientTable ON ID_CLIENT = ClientID
	WHERE ID_SALARY = @ID
	ORDER BY ClientFullName	
END
