USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Salary].[SERVICE_SALARY_STUDY_IMPORT]
	@ID			UNIQUEIDENTIFIER,
	@MONTH		UNIQUEIDENTIFIER,
	@SERVICE	INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @START	SMALLDATETIME
	DECLARE @FINISH	SMALLDATETIME

	SELECT @START = START_REPORT, @FINISH = FINISH_REPORT
	FROM Common.Period
	WHERE ID = @MONTH

	INSERT INTO Salary.ServiceStudy(ID_SALARY, ID_CLIENT, DATE)
		SELECT DISTINCT @ID, ID_CLIENT, DATE
		FROM 
			dbo.ClientStudy a
			INNER JOIN dbo.ClientTable ON ClientID = ID_CLIENT
		WHERE a.STATUS = 1
			AND DATE BETWEEN @START AND @FINISH
			AND dbo.ClientServiceDate(ClientID, DATE) = @SERVICE
END
