USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[SEARCH_FREEZE_SELECT]
	@TYPE	NVARCHAR(64)	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CS_ID, CS_SHORT
	FROM Security.ClientSearch
	WHERE CS_TYPE = @TYPE		
		AND CS_FREEZE = 1
		AND CS_HOST = HOST_NAME()
		AND CS_USER = ORIGINAL_LOGIN()
	ORDER BY CS_SHORT DESC
END