USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Security].[USER_SHORT]
AS
BEGIN
	SET NOCOUNT ON;

	IF EXISTS
		(
			SELECT *			
			FROM Security.Users
			WHERE US_LOGIN = ORIGINAL_LOGIN()
		)
		SELECT
			CASE ISNULL(US_SHORT, '')
				WHEN '' THEN ORIGINAL_LOGIN()
				ELSE US_SHORT
			END AS US_SHORT	
		FROM Security.Users
		WHERE US_LOGIN = ORIGINAL_LOGIN()
	ELSE
		SELECT ORIGINAL_LOGIN() AS US_SHORT
END