USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Security].[SEARCH_SAVE]
	@TYPE	NVARCHAR(64),
	@SHORT	VARCHAR(250),
	@SEARCH	XML
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Security.ClientSearch(CS_TYPE, CS_SHORT, CS_SEARCH)
		VALUES(@TYPE, @SHORT, @SEARCH)
END