USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[USER_DELETE]
	@NAME	VARCHAR(50)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC ('DROP USER [' + @NAME + ']')
	EXEC ('DROP LOGIN [' + @NAME + ']')
END