USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[ROLE_MEMBER_SET]
	@ROLE	NVARCHAR(128),
	@MEMBER	NVARCHAR(128),
	@MODE	BIT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @MODE = 1
		EXEC sp_droprolemember @ROLE, @MEMBER
	ELSE IF @MODE = 0
		EXEC sp_addrolemember @ROLE, @MEMBER
END