USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[ROLE_DELETE]
	@RoleID			INT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE RL CURSOR LOCAL FOR
		SELECT RoleID
		FROM Security.Roles
		WHERE RoleMasterID = @RoleID

	OPEN RL

	DECLARE @RL INT

	FETCH NEXT FROM RL INTO @RL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		EXEC Security.ROLE_DELETE @RL

		FETCH NEXT FROM RL INTO @RL
	END

	CLOSE RL
	DEALLOCATE RL

	DECLARE @RoleName VARCHAR(50)

	SELECT @RoleName = RoleName
	FROM Security.Roles
	WHERE RoleID = @RoleID

	DELETE FROM Security.Roles
	WHERE RoleID = @RoleID

	IF @RoleName IS NOT NULL
		EXEC('DROP ROLE [' + @RoleName + ']')
END