USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Security].[SEARCH_FREEZE]
	@CS_ID	UNIQUEIDENTIFIER,
	@CHECK	BIT
AS
BEGIN
	SET NOCOUNT ON;

	IF @CHECK = 1
		INSERT INTO Security.ClientSearch(CS_TYPE, CS_SHORT, CS_SEARCH, CS_FREEZE)
			SELECT CS_TYPE, CS_SHORT, CS_SEARCH, 1
			FROM Security.ClientSearch
			WHERE CS_ID = @CS_ID
	ELSE
		DELETE
		FROM Security.ClientSearch
		WHERE CS_ID = @CS_ID
END