USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Security].[USER_PASS]
	@USER	NVARCHAR(128),
	@PASS	NVARCHAR(128)
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @SQL NVARCHAR(MAX)

	SET @SQL = 'ALTER LOGIN [' + @USER + '] WITH PASSWORD = ''' + @PASS + ''', CHECK_POLICY = OFF'
	PRINT(@SQL)
	EXEC (@SQL)
END