USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[SCHEDULE_PERSONAL_EMAIL]
	@ID		UNIQUEIDENTIFIER,
	@EMAIL	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	EXEC Seminar.SCHEDULE_PERSONAL_ARCH @ID
		
	UPDATE Seminar.Personal
	SET EMAIL		=	@EMAIL
	WHERE ID = @ID
END
