USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[WEB_SCHEDULE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		a.ID, LIMIT, CONVERT(NVARCHAR(32), DATE, 104) + ' ' + LEFT(CONVERT(NVARCHAR(32), TIME, 108), 5) + ' ' + b.NAME AS SUBJ_FULL,
		DATE, TIME, NOTE, READER
	FROM 
		Seminar.Schedule a
		INNER JOIN Seminar.Subject b ON a.ID_SUBJECT = b.ID
	WHERE a.WEB = 1
		AND DATE >= GETDATE()
	ORDER BY a.DATE
END
