USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Seminar].[SCHEDULE_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, ID_SUBJECT, DATE, TIME, LIMIT, WEB, INVITE_DATE, RESERVE_DATE
	FROM Seminar.Schedule a
	WHERE ID = @ID
END
