USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[WEB_PERSONAL_DATA]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		PSEDO, c.NAME AS SEMINAR, 
		CONVERT(NVARCHAR(64), b.DATE, 104) + ' â ' + LEFT(CONVERT(NVARCHAR(64), b.TIME, 108), 5) AS DATE,
		a.CONFIRM_STATUS
	FROM 
		Seminar.Personal a
		INNER JOIN Seminar.Schedule b ON a.ID_SCHEDULE = b.ID
		INNER JOIN Seminar.Subject c ON b.ID_SUBJECT = c.ID
	WHERE a.ID = @ID
END
