USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[SCHEDULE_PERSONAL_GET]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID_SCHEDULE, ID_CLIENT, SURNAME, NAME, PATRON, POSITION, PHONE, NOTE
	FROM Seminar.Personal
	WHERE ID = @ID
END
