USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[WEB_MAIL_INVITE_SET]
	@ID		UNIQUEIDENTIFIER,
	@BIN	VARBINARY(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Seminar.Invite(ID_PERSONAL, BIN)
		SELECT @ID, @BIN
END
