USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Seminar].[SCHEDULE_PERSONAL_ARCH]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Seminar.Personal(ID_MASTER, ID_SCHEDULE, ID_CLIENT, PSEDO, EMAIL, SURNAME, NAME, PATRON, POSITION, PHONE, NOTE, ID_STATUS, ADDRESS, MSG_SEND, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_SCHEDULE, ID_CLIENT, PSEDO, EMAIL, SURNAME, NAME, PATRON, POSITION, PHONE, NOTE, ID_STATUS, ADDRESS, MSG_SEND, 2, UPD_DATE, UPD_USER
		FROM Seminar.Personal
		WHERE ID = @ID
END
