USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Seminar].[SUBJECT_SAVE]
	@ID		UNIQUEIDENTIFIER OUTPUT,
	@NAME	NVARCHAR(512),
	@READER	NVARCHAR(1024),
	@NOTE	NVARCHAR(MAX)	
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
		
		INSERT INTO Seminar.Subject(NAME, NOTE, READER)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@NAME, @NOTE, @READER)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
	BEGIN
		UPDATE Seminar.Subject
		SET NAME	=	@NAME,
			NOTE	=	@NOTE,
			READER	=	@READER,
			LAST	=	GETDATE()
		WHERE ID = @ID
	END
END
