USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Study].[LESSON_SAVE]
	@ID			UNIQUEIDENTIFIER,
	@DATE		SMALLDATETIME,
	@TEACHER	NVARCHAR(128),
	@THEME		NVARCHAR(512),
	@NOTE		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		INSERT INTO Study.Lesson(DATE, TEACHER, THEME, NOTE)
			VALUES(@DATE, @TEACHER, @THEME, @NOTE)
	END
	ELSE
	BEGIN
		INSERT INTO Study.Lesson(ID_MASTER, DATE, TEACHER, THEME, NOTE, STATUS, UPD_DATE, UPD_USER)
			SELECT @ID, DATE, TEACHER, THEME, NOTE, 2, UPD_DATE, UPD_USER
			FROM Study.Lesson
			WHERE ID = @ID
			
		UPDATE Study.Lesson
		SET DATE = @DATE,
			TEACHER = @TEACHER,
			THEME = @THEME,
			NOTE = @NOTE,
			UPD_DATE = GETDATE(),
			UPD_USER = ORIGINAL_LOGIN()
		WHERE ID = @ID
	END
END
