USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Study].[LESSON_SELECT]
	@TEACHER	NVARCHAR(128),
	@BEGIN		SMALLDATETIME,
	@END		SMALLDATETIME,
	@TXT		NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		ID, 
		CASE WHEN RN = 1 THEN DATE ELSE NULL END AS DATE_S,
		CASE WHEN RN = 1 THEN TEACHER ELSE NULL END AS TEACHER_S, THEME, NOTE
	FROM
		(
			SELECT ID, DATE, TEACHER, THEME, NOTE, ROW_NUMBER() OVER(PARTITION BY DATE, TEACHER ORDER BY DATE DESC, TEACHER, THEME, NOTE) AS RN
			FROM Study.Lesson
			WHERE STATUS = 1
				AND (DATE >= @BEGIN OR @BEGIN IS NULL)
				AND (DATE <= @END OR @END IS NULL)
				AND (TEACHER = @TEACHER OR @TEACHER IS NULL)
				AND (THEME LIKE @TXT OR NOTE LIKE @TXT OR @TXT IS NULL)
		) AS o_O
	ORDER BY DATE DESC, TEACHER, THEME, NOTE
END
