USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Study].[LESSON_]
	@TEACHER	NVARCHAR(128),
	@BEGIN		SMALLDATETIME,
	@END		SMALLDATETIME,
	@TXT		NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, DATE, TEACHER, THEME, NOTE
	FROM Study.Lesson
	WHERE STATUS = 1
		AND (DATE >= @BEGIN OR @BEGIN IS NULL)
		AND (DATE <= @END OR @END IS NULL)
		AND (TEACHER = @TEACHER OR @TEACHER IS NULL)
		AND (THEME LIKE @TXT OR NOTE LIKE @TXT OR @TXT IS NULL)
	ORDER BY DATE DESC, TEACHER, THEME, NOTE
END
