USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Study].[LESSON_DELETE]
	@ID			UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Study.Lesson(ID_MASTER, DATE, TEACHER, THEME, NOTE, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, DATE, TEACHER, THEME, NOTE, 2, UPD_DATE, UPD_USER
		FROM Study.Lesson
		WHERE ID = @ID
			
	UPDATE Study.Lesson
	SET STATUS = 3,	
		UPD_DATE = GETDATE(),
		UPD_USER = ORIGINAL_LOGIN()
	WHERE ID = @ID	
END
