USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[TEST_AUDIT_ANSWER]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT c.ID, a.ID AS ID_QUESTION, ANS_TEXT AS NAME, c.CORRECT
	FROM 
		Subhost.PersonalTestQuestion a
		--INNER JOIN Common.Question b ON a.ID_QUESTION = b.ID
		INNER JOIN Subhost.TestAnswer c ON c.ID_QUESTION = a.ID_QUESTION
	WHERE ID_TEST = @ID
	ORDER BY NEWID()
END
