USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[FILE_STT_SELECT]
	@SUBHOST	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT USR, DATE, PROCESS
	FROM Subhost.STTFiles
	WHERE ID_SUBHOST = @SUBHOST
	ORDER BY DATE DESC
END
