USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[FEEDBACK_SAVE]
	@EMAIL	NVARCHAR(256),
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Subhost.Feedback(EMAIL, NOTE)
		VALUES(@EMAIL, @NOTE)
		
	EXEC Maintenance.MAIL_SEND @NOTE
END
