USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[IP_USR_FILE]
	@FILE	NVARCHAR(512)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT UF_USR_NAME, UF_USR_DATA
	FROM IP.USRFileView
	WHERE FL_NAME = @FILE
END
