USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[FILE_ALL_XML_SELECT]
	@SH		NVARCHAR(16),
	@USR	NVARCHAR(128) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @USR IS NOT NULL
		EXEC dbo.SUBHOST_EXPORT_DATA @SH, N'ALL', 0
	ELSE
		EXEC dbo.SUBHOST_EXPORT_DATA @SH, N'ALL'
	
	INSERT INTO Subhost.FilesDownload(ID_SUBHOST, USR, FTYPE)
		SELECT SH_ID, @USR, N'ALL'
		FROM dbo.Subhost
		WHERE SH_REG = @SH
			AND @USR IS NOT NULL
END
