USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[USER_INSERT]
	@SH_ID	UNIQUEIDENTIFIER,
	@LGN	NVARCHAR(128),
	@PASS	NVARCHAR(128) =NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SET @PASS = Common.PasswordGenerate(8)

	INSERT INTO Subhost.Users(NAME, PASS, ID_SUBHOST)
		SELECT @LGN, @PASS, @SH_ID
END
