USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[TEST_AUDIT_CHECK]
	@ID		UNIQUEIDENTIFIER OUTPUT,
	@TEST	UNIQUEIDENTIFIER,
	@RESULT	TINYINT,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @ID = ID
	FROM Subhost.CheckTest
	WHERE ID_TEST = @TEST

	IF @ID IS NULL
	BEGIN
		DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)
		
		INSERT INTO Subhost.CheckTest(ID_TEST, RESULT, NOTE)
			OUTPUT inserted.ID INTO @TBL
			VALUES(@TEST, @RESULT, @NOTE)
			
		SELECT @ID = ID FROM @TBL
	END
	ELSE
	BEGIN
		UPDATE Subhost.CheckTest
		SET RESULT	=	@RESULT,
			NOTE	=	@NOTE
		WHERE ID = @ID
		
		DELETE
		FROM Subhost.CheckTestQuestion
		WHERE ID_TEST = @ID
	END
END
