USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[USER_DELETE]
	@SH_ID	UNIQUEIDENTIFIER,
	@ID		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM Subhost.Users
	WHERE ID_SUBHOST = @SH_ID AND ID = @ID
END
