USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[TEST_AUDIT_QUESTION_CHECK]
	@TEST	UNIQUEIDENTIFIER,
	@QST	UNIQUEIDENTIFIER,
	@RES	TINYINT,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Subhost.CheckTestQuestion(ID_TEST, ID_QUESTION, RESULT, NOTE)
		SELECT @TEST, @QST, @RES, @NOTE
END
