USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[PERSONAL_TEST_ANSWER_SAVE]
	@QUEST	UNIQUEIDENTIFIER,
	@ANS	NVARCHAR(MAX),
	@TP		INT
AS
BEGIN
	SET NOCOUNT ON;

	IF @TP = 1
		UPDATE Subhost.PersonalTestQuestion
		SET ANS = @ANS,
			STATUS = 2
		WHERE ID = @QUEST
	ELSE 
	BEGIN
		INSERT INTO Subhost.PersonalTestAnswer(ID_QUESTION, ID_ANSWER)
			SELECT @QUEST, ID
			FROM dbo.TableGUIDFromXML(@ANS)
			
		UPDATE Subhost.PersonalTestQuestion
		SET STATUS = 2
		WHERE ID = @QUEST
	END
END
