USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[FILES_DOWNLOAD_SELECT]
	@SUBHOST	UNIQUEIDENTIFIER,
	@TYPE		NVARCHAR(64)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT USR, DATE
	FROM Subhost.FilesDownload
	WHERE ID_SUBHOST = @SUBHOST
		AND FTYPE = @TYPE
	ORDER BY DATE DESC
END
