USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[TEST_GENERATE]
	@SUBHOST	UNIQUEIDENTIFIER,
	@LGN		NVARCHAR(128),
	@TEST		UNIQUEIDENTIFIER,
	@ID			UNIQUEIDENTIFIER OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)
	
	INSERT INTO Subhost.PersonalTest(ID_SUBHOST, ID_TEST, PERSONAL)
		OUTPUT inserted.ID INTO @TBL
		VALUES(@SUBHOST, @TEST, @LGN)
		
	SELECT @ID = ID FROM @TBL
	
	INSERT INTO Subhost.PersonalTestQuestion(ID_TEST, ID_QUESTION, ORD)
		SELECT @ID, ID, ROW_NUMBER() OVER(ORDER BY NEWID())
		FROM Subhost.TestQuestion
		WHERE ID_TEST = @TEST
END
