USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Subhost].[USR_SELECT]
	@SH_ID	UNIQUEIDENTIFIER,
	@USR	NVARCHAR(128) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC USR.USR_SUBHOST_SELECT @SH_ID
	
	INSERT INTO Subhost.FilesDownload(ID_SUBHOST, USR, FTYPE)
		SELECT @SH_ID, @USR, N'USR'		
		WHERE @USR IS NOT NULL
END
