USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[TEST_FINISH]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Subhost.PersonalTest
	SET FINISH = GETDATE()
	WHERE ID = @ID
	
	EXEC Subhost.TEST_CHECK @ID
END
