USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[FILE_DBF_XML_SELECT]
	@SH		NVARCHAR(16),
	@USR	NVARCHAR(128) = NULL
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	IF @SH = 'Í1'
		EXEC [PC275-SQL\DELTA].DBF_NAH.dbo.FINANCING_TO_CLIENT_SELECT
	ELSE
		SELECT '<root/>' AS DATA
	
	INSERT INTO Subhost.FilesDownload(ID_SUBHOST, USR, FTYPE)
		SELECT SH_ID, @USR, N'DBF'
		FROM dbo.Subhost
		WHERE SH_REG = @SH
			AND @USR IS NOT NULL
END
