USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Subhost].[TEST_AUDIT_DETAIL]
	@ID	UNIQUEIDENTIFIER	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT START, PERSONAL, b.NAME, c.NOTE, c.RESULT, QST_SUCCESS AS SUCCESS_VALUE
	FROM 
		Subhost.PersonalTest a
		INNER JOIN Subhost.Test b ON a.ID_TEST = b.ID
		LEFT OUTER JOIN Subhost.CheckTest c ON c.ID_TEST = a.ID 
	WHERE a.ID = @ID
END
