USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Task].[USER_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT Name AS US_NAME
	FROM sys.database_principals
	WHERE TYPE IN ('S', 'U')
		AND name NOT IN ('dbo', 'guest', 'INFORMATION_SCHEMA', 'sys')
	ORDER BY name
END
