USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Task].[TASK_WORK]
	@ID		UNIQUEIDENTIFIER,
	@NOTE	NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Task.TaskWork(ID_TASK, NOTE)
		VALUES(@ID, @NOTE)
		
	UPDATE Task.Tasks
	SET ID_STATUS = (SELECT ID FROM Task.TaskStatus WHERE PSEDO = N'WORK')
	WHERE ID = @ID
END
