USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Task].[TASK_WORK_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DATE AS [Дата], AUTHOR AS [Написал], NOTE AS [Описание]
	FROM Task.TaskWork
	WHERE ID_TASK = @ID
	ORDER BY DATE DESC
END
