USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Tender].[TENDER_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 		
		ID_LAW, CLIENT, CONTRACT_START, CONTRACT_FINISH, ACT_START, ACT_FINISH, TENDER_START, TENDER_FINISH,
		SURNAME, NAME, PATRON, POSITION, PHONE, EMAIL, CALL_DATE, INFO_DATE, ID_STATUS, MANAGER, MANAGER_DATE, ID_MANAGER,
		MANAGER_NOTE, LET_DATE, LET_NUM
		INTO #tmp
	FROM Tender.Tender
	WHERE ID = @ID	
	
	SELECT *
	FROM #tmp
	
	DROP TABLE #tmp
END
