USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Tender].[TENDER_WARNING]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		ClientID,
		ClientFullName,
		CALL_DATE
	FROM 
		Tender.Tender a
		INNER JOIN dbo.ClientTable b ON a.ID_CLIENT = b.ClientID
	WHERE a.STATUS = 1
		AND dbo.DateOf(CALL_DATE) = dbo.Dateof(GETDATE())
	ORDER BY CALL_DATE
END
