USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Tender].[CALL_FILTER]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SELECT a.ID, ClientID, DATE, SUBJECT, a.SURNAME + ' ' + a.NAME + ' ' + a.PATRON AS FIO, NOTE
	FROM 
		Tender.Call a
		INNER JOIN Tender.Tender b ON a.ID_TENDER = b.ID
		INNER JOIN dbo.ClientTable c ON c.ClientID = b.ID_CLIENT
	WHERE a.STATUS = 1 
		AND (a.DATE >= @BEGIN OR @BEGIN IS NULL)
		AND (a.DATE <= @END OR @END IS NULL)
	ORDER BY DATE DESC
END
