USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE Tender.PLACEMENT_FILTER_COLOR_IGN
	@ID_TENDER	UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @IGN	BIT
	SELECT @IGN = COLOR_IGN 
	FROM Tender.Placement 
	WHERE ID_TENDER = @ID_TENDER
	
	SET @IGN = ISNULL(@IGN, 0)
	
	IF @IGN = 0
		SET @IGN = 1
	ELSE
		SET @IGN = 0
	
	UPDATE Tender.Placement
	SET COLOR_IGN = @IGN
	WHERE ID_TENDER = @ID_TENDER
END
