USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Tender].[CALL_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DATE, SUBJECT, SURNAME, NAME, PATRON, PHONE, NOTE
	FROM Tender.Call
	WHERE ID = @ID	
END
