USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Tender].[OFFER_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 
		DATE, ID_VENDOR, ID_TAX, 
		ACTUAL, ACTUAL_START, ACTUAL_FINISH, ACTUAL_DATE, ACTUAL_TYPES, ACTUAL_COEF,
		EXCHANGE, EXCHANGE_TYPES, EXCHANGE_COEF,
		DELIVERY, DELIVERY_TYPES, DELIVERY_COEF,
		SUPPORT, SUPPORT_START, SUPPORT_FINISH, SUPPORT_TYPES, SUPPORT_COEF,
		QUERY_DATE
	FROM Tender.Offer
	WHERE ID = @ID
END
