USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Tender].[OFFER_DETAIL_SAVE]
	@OFFER		UNIQUEIDENTIFIER,
	@ID_CLIENT	INT,
	@CLIENT		NVARCHAR(256),
	@ADDRESS	NVARCHAR(2048),
	@SYS		INT,
	@SYS_OLD	INT,
	@DISTR		NVARCHAR(64),
	@NET		INT,
	@NET_OLD	INT,
	@DBASE		MONEY,
	@D			MONEY,
	@EBASE		MONEY,
	@E			MONEY,
	@ABASE		MONEY,
	@A			MONEY,
	@SBASE		MONEY,
	@S			MONEY,
	@STOTAL		MONEY,
	@MON_CNT	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Tender.OfferDetail(ID_OFFER, ID_CLIENT, CLIENT, ADDRESS, ID_SYSTEM, ID_OLD_SYSTEM, DISTR, ID_NET, ID_OLD_NET, DELIVERY_BASE, DELIVERY, EXCHANGE_BASE, EXCHANGE, ACTUAL_BASE, ACTUAL, SUPPORT_BASE, SUPPORT, SUPPORT_TOTAL, MON_CNT)
		VALUES(@OFFER, @ID_CLIENT, @CLIENT, @ADDRESS, @SYS,	@SYS_OLD, @DISTR, @NET, @NET_OLD, @DBASE, @D, @EBASE, @E, @ABASE, @A, @SBASE, @S, @STOTAL, @MON_CNT)
END
