USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Tender].[OFFER_ARCH]
	@ID				UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE
		@DebugError		VarChar(512),
		@DebugContext	Xml,
		@Params			Xml;

	EXEC [Debug].[Execution@Start]
		@Proc_Id		= @@ProcId,
		@Params			= @Params,
		@DebugContext	= @DebugContext OUT

	BEGIN TRY

		DECLARE @NEWID	UNIQUEIDENTIFIER

		DECLARE @TBL TABLE(ID UNIQUEIDENTIFIER)

		INSERT INTO Tender.Offer(
					ID_MASTER, ID_TENDER, DATE, ID_VENDOR, ID_TAX,
					ACTUAL, ACTUAL_START, ACTUAL_FINISH, ACTUAL_DATE, ACTUAL_TYPES, ACTUAL_COEF,
					EXCHANGE, EXCHANGE_TYPES, EXCHANGE_COEF, DELIVERY, DELIVERY_TYPES, DELIVERY_COEF,
					SUPPORT, SUPPORT_START, SUPPORT_FINISH, SUPPORT_TYPES, SUPPORT_COEF,
					QUERY_DATE, TPL, STATUS, UPD_DATE, UPD_USER)
			OUTPUT inserted.ID INTO @TBL
			SELECT
					@ID, ID_TENDER, DATE, ID_VENDOR, ID_TAX,
					ACTUAL, ACTUAL_START, ACTUAL_FINISH, ACTUAL_DATE, ACTUAL_TYPES, ACTUAL_COEF,
					EXCHANGE, EXCHANGE_TYPES, EXCHANGE_COEF, DELIVERY, DELIVERY_TYPES, DELIVERY_COEF,
					SUPPORT, SUPPORT_START, SUPPORT_FINISH, SUPPORT_TYPES, SUPPORT_COEF,
					QUERY_DATE, TPL, 2, UPD_DATE, UPD_USER
			FROM Tender.Offer
			WHERE ID = @ID

		SELECT @NEWID = ID FROM @TBL

		UPDATE  Tender.OfferDetail
		SET ID_OFFER = @NEWID
		WHERE ID_OFFER = @ID

		EXEC [Debug].[Execution@Finish] @DebugContext = @DebugContext, @Error = NULL;
	END TRY
	BEGIN CATCH
		SET @DebugError = Error_Message();

		EXEC [Debug].[Execution@Finish] @DebugContext = @DebugContext, @Error = @DebugError;

		EXEC [Maintenance].[ReRaise Error];
	END CATCH
END
GRANT EXECUTE ON [Tender].[OFFER_ARCH] TO rl_tender_u;
GO