USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Training].[TRAINING_SCHEDULE_INSERT]
	@SUBJECT	UNIQUEIDENTIFIER,
	@DATE		SMALLDATETIME,
	@LIMIT		SMALLINT,
	@ID			UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO Training.TrainingSchedule(TSC_ID_TS, TSC_DATE, TSC_LIMIT)
		OUTPUT INSERTED.TSC_ID INTO @TBL
		VALUES(@SUBJECT, @DATE, @LIMIT)

	SELECT @ID = ID 
	FROM @TBL
END