USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Training].[TRAINING_SCHEDULE_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TSC_DATE, TSC_ID_TS, TSC_LIMIT
	FROM Training.TrainingSchedule
	WHERE TSC_ID = @ID
END