USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Training].[TRAINING_SUBJECT_INSERT]	
	@NAME	VARCHAR(100),
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TBL TABLE (ID UNIQUEIDENTIFIER)

	INSERT INTO Training.TrainingSubject(TS_NAME)
		OUTPUT INSERTED.TS_ID INTO @TBL
		VALUES(@NAME)

	SELECT @ID = ID FROM @TBL
END