USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Training].[TRAINING_SUBJECT_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE	Training.TrainingSubject
	SET		TS_NAME	=	@NAME,
			TS_LAST	=	GETDATE()
	WHERE	TS_ID	=	@ID
END