USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Training].[TRAINING_SUBJECT_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TS_ID, TS_NAME
	FROM Training.TrainingSubject
	WHERE @FILTER IS NULL
		OR TS_NAME LIKE @FILTER
	ORDER BY TS_LAST DESC, TS_NAME
END