USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[PROCESS_JOURNAL]
	@DATE	DATETIME,
	@BEGIN	DATETIME,
	@END	DATETIME,
	@RES	TINYINT,
	@TXT	NVARCHAR(MAX),
	@FILE	VARCHAR(50),
	@COMP	VARCHAR(50) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	IF (SELECT Maintenance.GlobalUSRJournal()) = '1'
	BEGIN
		IF @DATE IS NOT NULL
		INSERT INTO USR.ProcessJournal(PR_DATE, PR_BEGIN, PR_END, PR_RES, PR_TEXT, PR_FILE, PR_COMPLECT)
			VALUES(@DATE, @BEGIN, @END, @RES, @TXT, @FILE, @COMP)
	END
END