USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[COMPLECT_JOURNAL_SELECT]
	@UD_COMPLECT	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @COMPLECT	VARCHAR(50)
	
	SELECT @COMPLECT = UD_COMPLECT
	FROM USR.USRData
	WHERE UD_ID = @UD_COMPLECT

	SELECT PR_DATE, PR_TEXT, PR_USER, dbo.TimeMilliSecToStr(DATEDIFF(MILLISECOND, PR_BEGIN, PR_END)) AS PR_TIME
	FROM USR.ProcessJournal
	WHERE PR_COMPLECT = @COMPLECT
	ORDER BY PR_DATE DESC
END