USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[OS_FAMILY_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OF_ID, OF_NAME
	FROM USR.OSFamily
	WHERE @FILTER IS NULL
		OR OF_NAME LIKE @FILTER
	ORDER BY OF_NAME
END