USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[PROCESSOR_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PRC_ID, PRC_NAME, PRC_FREQ, PRC_CORE, PF_NAME
	FROM 
		USR.Processor
		LEFT OUTER JOIN USR.ProcessorFamily ON PF_ID = PRC_ID_FAMILY
	WHERE @FILTER IS NULL
		OR PRC_NAME LIKE @FILTER
	ORDER BY PRC_NAME
END