USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[OS_UPDATE]
	@ID		INT,
	@NAME	VARCHAR(100),
	@MIN	SMALLINT,
	@MAJ	SMALLINT,
	@BUILD	SMALLINT,
	@PLATFORM	TINYINT,
	@EDITION	VARCHAR(100),
	@CAPACITY	VARCHAR(50),
	@LANG		VARCHAR(50),
	@COMPATIBILITY	VARCHAR(100),
	@FAMILY	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE USR.OS
	SET	OS_NAME = @NAME, 
		OS_MIN = @MIN, 
		OS_MAJ = @MAJ, 
		OS_BUILD = @BUILD, 
		OS_PLATFORM = @PLATFORM, 
		OS_EDITION = @EDITION, 
		OS_CAPACITY = @CAPACITY, 
		OS_LANG = @LANG, 
		OS_COMPATIBILITY = @COMPATIBILITY,
		OS_ID_FAMILY = @FAMILY,
		OS_LAST = GETDATE()
	WHERE OS_ID = @ID
END