USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[PROCESSOR_GET]
	@ID		INT	
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PRC_NAME, PRC_FREQ, PRC_CORE, PRC_ID_FAMILY, PRC_FREQ_S
	FROM USR.Processor
	WHERE PRC_ID = @ID
END