USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[OS_FAMILY_INSERT]
	@NAME	VARCHAR(100),
	@ID		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO USR.OSFamily(OF_NAME)
		VALUES(@NAME)

	SELECT @ID = SCOPE_IDENTITY()
END