USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[USR_COMPLECT_ACTIVE]
	@UD_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE USR.USRData
	SET UD_ACTIVE = 
			CASE UD_ACTIVE 
				WHEN 1 THEN 0 
				WHEN 0 THEN 1 
				ELSE NULL
			END
	WHERE UD_ID = @UD_ID
END