USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[INET_CONTROL_SET]
	@UD_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	IF NOT EXISTS
		(
			SELECT *
			FROM USR.InetControl
			WHERE IC_ID_COMPLECT = @UD_ID
				AND IC_RDATE IS NULL
		)
		INSERT INTO USR.InetControl(IC_ID_COMPLECT) VALUES(@UD_ID)
END