USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[PROCESSOR_FAMILY_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PF_ID, PF_NAME 
	FROM USR.ProcessorFamily
	WHERE @FILTER IS NULL
		OR PF_NAME LIKE @FILTER
	ORDER BY PF_NAME
END