USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[PROCESSOR_FAMILY_UPDATE]
	@ID		INT,
	@NAME	VARCHAR(150)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE USR.ProcessorFamily
	SET PF_NAME = @NAME,
		PF_LAST = GETDATE()
	WHERE PF_ID = @ID
END