USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[OS_SELECT]
	@FILTER	VARCHAR(100) = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OS_ID, OS_NAME, OS_BUILD, OS_EDITION, OS_CAPACITY
	FROM USR.OS
	WHERE @FILTER IS NULL
		OR OS_NAME LIKE @FILTER
	ORDER BY OS_NAME
END