USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[INET_CONTROL_UNSET]
	@UD_ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE USR.InetControl
	SET IC_RDATE = GETDATE(),
		IC_RUSER = ORIGINAL_LOGIN()
	WHERE IC_ID_COMPLECT = @UD_ID AND IC_RDATE IS NULL
END