USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[USR_FILE_SAVE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT F.UF_NAME, D.UF_DATA
	FROM USR.USRFile F
	INNER JOIN USR.USRFileData D ON F.UF_ID = D.UF_ID
	WHERE F.UF_ID = @ID
END
