USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[OS_GET]
	@ID		INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT OS_NAME, OS_MIN, OS_MAJ, OS_BUILD, OS_PLATFORM, OS_EDITION, OS_CAPACITY, OS_LANG, OS_COMPATIBILITY, OS_ID_FAMILY
	FROM USR.OS
	WHERE OS_ID = @ID
END