USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [USR].[USR_FILE_HASH_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @Files TABLE
	(
		UF_ID	INT	PRIMARY KEY CLUSTERED,
		UF_NAME	NVARCHAR(256)
	);

	
	INSERT INTO @Files
	SELECT TOP 1000
		UF_ID, UF_NAME
	FROM USR.USRFile
	WHERE UF_HASH IS NULL;

	SELECT F.UF_ID, F.UF_NAME, D.UF_DATA
	FROM @Files F
	INNER JOIN USR.USRFileData D ON F.UF_ID = D.UF_ID
	OPTION (RECOMPILE);
END

