USE [ClientDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [USR].[USR_SUBHOST_DB_SELECT]
	@DB	NVARCHAR(512) = NULL
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT REPLICATE('0', 5 - LEN(CONVERT(VARCHAR(20), RNUM))) + CONVERT(VARCHAR(20), RNUM) AS RN, RNUM, UF_NAME, UF_CREATE, UF_DATA
	FROM
		(
			SELECT ROW_NUMBER() OVER(PARTITION BY UF_NAME ORDER BY UF_DATE) AS RNUM, UF_NAME, UF_CREATE, UF_DATA
			FROM 
				(
					SELECT UF_NAME, UF_CREATE, UF_DATA, UF_DATE
					FROM
						[PC275-SQL\GAMMA].ClientArtDB.USR.USRFile a
						INNER JOIN [PC275-SQL\GAMMA].ClientArtDB.USR.USRData ON UD_ID = UF_ID_COMPLECT
					WHERE UF_CREATE >= DATEADD(MONTH, -3, GETDATE())
						AND NOT EXISTS
							(
								SELECT *
								FROM USR.USRFile z
								WHERE z.UF_DATA = a.UF_DATA
									AND z.UF_DATE = a.UF_DATE
							)
							
					UNION ALL
					
					SELECT UF_NAME, UF_CREATE, UF_DATA, UF_DATE
					FROM
						[PC275-SQL\GAMMA].ClientNahDB.USR.USRFile a
						INNER JOIN [PC275-SQL\GAMMA].ClientNahDB.USR.USRData ON UD_ID = UF_ID_COMPLECT
					WHERE UF_CREATE >= DATEADD(MONTH, -3, GETDATE())
						AND NOT EXISTS
							(
								SELECT *
								FROM USR.USRFile z
								WHERE z.UF_DATA = a.UF_DATA
									AND z.UF_DATE = a.UF_DATE
							)
							
					UNION ALL
					
					SELECT UF_NAME, UF_CREATE, UF_DATA, UF_DATE
					FROM
						[PC275-SQL\GAMMA].ClientSlavDB.USR.USRFile a
						INNER JOIN [PC275-SQL\GAMMA].ClientSlavDB.USR.USRData ON UD_ID = UF_ID_COMPLECT
					WHERE UF_CREATE >= DATEADD(MONTH, -3, GETDATE())
						AND NOT EXISTS
							(
								SELECT *
								FROM USR.USRFile z
								WHERE z.UF_DATA = a.UF_DATA
									AND z.UF_DATE = a.UF_DATE
							)
							
					UNION ALL
					
					SELECT UF_NAME, UF_CREATE, UF_DATA, UF_DATE
					FROM
						[PC275-SQL\GAMMA].ClientUSSDB.USR.USRFile a
						INNER JOIN [PC275-SQL\GAMMA].ClientUSSDB.USR.USRData ON UD_ID = UF_ID_COMPLECT
					WHERE UF_CREATE >= DATEADD(MONTH, -3, GETDATE())
						AND NOT EXISTS
							(
								SELECT *
								FROM USR.USRFile z
								WHERE z.UF_DATA = a.UF_DATA
									AND z.UF_DATE = a.UF_DATE
							)
				) AS o_O
		) AS o_O
	ORDER BY RNUM
END