USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[SERVICE_TYPE_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ServiceTypeName, ServiceTypeID
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ServiceTypeTable
	ORDER BY ServiceTypeName
END
GO
GRANT EXECUTE ON [Client].[SERVICE_TYPE_SELECT] TO rl_common;
GO