USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[MANAGER_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ManagerID, ManagerName, ManagerFullName
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ManagerTable
	ORDER BY ManagerName
END
GRANT EXECUTE ON [Client].[MANAGER_SELECT] TO rl_common;
GO