USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[STATUS_SELECT]
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ServiceStatusID, ServiceStatusName, ServiceStatusIndex
	FROM [PC275-SQL\ALPHA].ClientDB.dbo.ServiceStatusTable
	ORDER BY ServiceStatusIndex
END
GO
GRANT EXECUTE ON [Client].[STATUS_SELECT] TO rl_common;
GO