USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CSV_METADATA]
	@TYPE	NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;	

	IF @TYPE = N'SERVER'
	BEGIN
		SELECT 0 AS INDX, N'NUM' AS FLD
		UNION ALL
		SELECT 1 AS INDX, N'DATE' AS FLD
		UNION ALL
		SELECT 2 AS INDX, N'TIME' AS FLD
		UNION ALL
		SELECT 3 AS INDX, N'HOSTCNT' AS FLD
		UNION ALL
		SELECT 4 AS INDX, N'QUERY' AS FLD
		UNION ALL
		SELECT 5 AS INDX, N'SESSION' AS FLD
		UNION ALL
		SELECT 6 AS INDX, N'TRAFIN' AS FLD
		UNION ALL
		SELECT 7 AS INDX, N'TRAFOUT' AS FLD
	END
	ELSE IF @TYPE = N'CLIENT'
	BEGIN
		SELECT 0 AS INDX, N'NUM' AS FLD
		UNION ALL
		SELECT 1 AS INDX, N'SYS' AS FLD
		UNION ALL
		SELECT 2 AS INDX, N'DISTR' AS FLD
		UNION ALL
		SELECT 3 AS INDX, N'COMP' AS FLD
		UNION ALL
		SELECT 4 AS INDX, N'IP' AS FLD
		UNION ALL
		SELECT 5 AS INDX, N'SESSION' AS FLD
		UNION ALL
		SELECT 6 AS INDX, N'START' AS FLD
		UNION ALL
		SELECT 7 AS INDX, N'QST_TIME' AS FLD
		UNION ALL
		SELECT 8 AS INDX, N'QST_SIZE' AS FLD
		UNION ALL
		SELECT 9 AS INDX, N'ANS_TIME' AS FLD
		UNION ALL
		SELECT 10 AS INDX, N'ANS_SIZE' AS FLD
		UNION ALL
		SELECT 11 AS INDX, N'CACHE_TIME' AS FLD
		UNION ALL
		SELECT 12 AS INDX, N'CACHE_SIZE' AS FLD
		UNION ALL
		SELECT 13 AS INDX, N'DOWNLOAD_TIME' AS FLD
		UNION ALL
		SELECT 14 AS INDX, N'UPDATE_TIME' AS FLD
		UNION ALL
		SELECT 15 AS INDX, N'REPORT_TIME' AS FLD
		UNION ALL
		SELECT 16 AS INDX, N'END' AS FLD
		UNION ALL
		SELECT 17 AS INDX, N'REDOWNLOAD' AS FLD
		UNION ALL
		SELECT 18 AS INDX, N'LOG_PATH' AS FLD
		UNION ALL
		SELECT 19 AS INDX, N'LOG_FILE' AS FLD
		UNION ALL
		SELECT 20 AS INDX, N'LOG_RESULT' AS FLD
		UNION ALL
		SELECT 21 AS INDX, N'LOG_LETTER' AS FLD
		UNION ALL
		SELECT 22 AS INDX, N'USR' AS FLD
		UNION ALL
		SELECT 23 AS INDX, N'CODE_CLIENT' AS FLD
		UNION ALL
		SELECT 24 AS INDX, N'CODE_SERVER' AS FLD
		UNION ALL
		SELECT 25 AS INDX, N'IP_MODE' AS FLD
		UNION ALL
		SELECT 26 AS INDX, N'RES_VERSION' AS FLD
		UNION ALL
		SELECT 27 AS INDX, N'DOWNLOAD_SPEED' AS FLD
		UNION ALL
		SELECT 28 AS INDX, N'STT_SEND' AS FLD
		UNION ALL
		SELECT 29 AS INDX, N'STT_RESULT' AS FLD
		UNION ALL
		SELECT 30 AS INDX, N'INET_EXT' AS FLD		
	END
END
