USE [IPLogs]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[FILES_LOG_SELECT]	
	@BEGIN		DATETIME,
	@END		DATETIME
AS
BEGIN
	SET NOCOUNT ON;
	
	SELECT
		FL_ID, FL_NAME, 
		CONVERT(DECIMAL(24, 8), CONVERT(DECIMAL(24, 8), FL_SIZE) / 1024) AS FL_SIZE, 
		FL_DATE
	FROM dbo.Files
	WHERE FL_TYPE = 1 
		AND (FL_DATE >= @BEGIN OR @BEGIN IS NULL)
		AND (FL_DATE <= @END OR @END IS NULL)	
	ORDER BY FL_DATE DESC
END