USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SERVER_PROPERTY_GET]
	@SERVER	INT,
	@NAME	VARCHAR(50),
	@VALUE	NVARCHAR(512) OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	IF @NAME = 'SERVER_PATH'
		SELECT @VALUE = SRV_PATH
		FROM dbo.Servers
		WHERE SRV_ID = @SERVER
END
GRANT EXECUTE ON [dbo].[SERVER_PROPERTY_GET] TO rl_common;
GO