USE [IPLogs]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [dbo].[CLEAR_DATA]
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM dbo.ServerStatDetail
	DELETE FROM dbo.ClientStatDetail
	DELETE FROM dbo.LogFiles
	DELETE FROM dbo.USRFiles	

	DELETE FROM dbo.ServerStat
	DELETE FROM dbo.ClientStat
	
	DELETE FROM dbo.Files
	

	DBCC CHECKIDENT (ServerStatDetail, RESEED, 1)
	DBCC CHECKIDENT (ClientStatDetail, RESEED, 1)
	DBCC CHECKIDENT (LogFiles, RESEED, 1)
	DBCC CHECKIDENT (USRFiles, RESEED, 1)
	DBCC CHECKIDENT (ServerStat, RESEED, 1)
	DBCC CHECKIDENT (ClientStat, RESEED, 1)
	DBCC CHECKIDENT (Files, RESEED, 1)
END
