USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[LOG_FILE_OPEN]
	@FILENAME	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		FL_NAME, FL_SIZE, FL_DATE,
		LF_TEXT
	FROM
		dbo.Files INNER JOIN
		dbo.LogFiles ON LF_ID_FILE = FL_ID
	WHERE FL_NAME = @FILENAME
END
GRANT EXECUTE ON [dbo].[LOG_FILE_OPEN] TO rl_client_stat;
GO