USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[IP_FILES_REFRESH]
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @cmd NVARCHAR(500)

	SELECT @cmd = ST_VALUE
	FROM dbo.Settings
	WHERE ST_NAME = 'COPY_BAT_PATH'

	EXEC xp_cmdshell @cmd
END
GO
GRANT EXECUTE ON [dbo].[IP_FILES_REFRESH] TO rl_ip_refresh;
GO