USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INET_LOG_FILE_OPEN]
	@FILENAME	NVARCHAR(256)
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		FL_NAME, FL_SIZE, FL_DATE,
		INET_LOG_DATA AS LF_TEXT
	FROM
		dbo.Files INNER JOIN
		dbo.USRFiles ON UF_ID_FILE = FL_ID INNER JOIN
		dbo.ConsErr ON UF_ID = ID_USR
	WHERE FL_NAME = @FILENAME
END
GRANT EXECUTE ON [dbo].[INET_LOG_FILE_OPEN] TO rl_client_stat;
GO