USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE FUNCTION [Common].[DateOf]
(
	@DT	DATETIME
)
RETURNS DATETIME
WITH SCHEMABINDING
AS
BEGIN
	RETURN CONVERT(DATETIME, CONVERT(VARCHAR(20), @DT, 112), 112)
END