USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[RoleID]', 'FN') IS NULL EXEC('CREATE FUNCTION [Security].[RoleID] () RETURNS Int AS BEGIN RETURN NULL END')
GO
CREATE FUNCTION [Security].[RoleID]
(
	@RL_ROLE VARCHAR(128)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID UNIQUEIDENTIFIER

	SELECT @ID = RL_ID
	FROM Security.Roles
	WHERE RL_ROLE = @RL_ROLE

	RETURN @ID
END
GO
