USE [SaleDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Client].[OIS_INFO_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *, (SELECT NAME FROM Client.Company z WHERE STATUS = 1 AND z.ID = a.ID_COMPANY) AS CO_NAME
	FROM Client.OISInfo a
	WHERE ID = @ID
END
