USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_WARNING_WARNING]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @CUR SMALLDATETIME

		SET @CUR = Common.DateOf(GETDATE())

		SELECT a.ID, b.ID AS ID_COMPANY, b.NAME, a.DATE, a.NOTE
		FROM
			Client.CompanyWarning a
			INNER JOIN Client.Company b ON a.ID_COMPANY = b.ID
		WHERE a.STATUS = 1
			AND NOTIFY_USER = ORIGINAL_LOGIN()
			AND DATE <= @CUR
			AND END_DATE IS NULL
		ORDER BY a.DATE DESC, b.NAME


		SELECT @RC = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Client].[COMPANY_WARNING_WARNING] TO public;
GO