USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Client].[COMPANY_NUMBER_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Client].[COMPANY_NUMBER_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [Client].[COMPANY_NUMBER_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SELECT NUMBER
	FROM Client.Company
	WHERE ID = @ID
END

GO
GRANT EXECUTE ON [Client].[COMPANY_NUMBER_SELECT] TO rl_company_number;
GRANT EXECUTE ON [Client].[COMPANY_NUMBER_SELECT] TO rl_company_r;
GO
