USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[COMPANY_DELIVERY_SELECT]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, FIO, POS, EMAIL, DATE, PLAN_DATE, OFFER, CASE STATE WHEN 1 THEN 'Подписан' WHEN 2 THEN 'Снят с подписки' ELSE '???' END AS STATE_STR, PERSONAL
	FROM Client.CompanyDelivery
	WHERE ID_COMPANY = @ID
	ORDER BY STATE
END
