USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[CALL_DATE_CHANGE]
	@ID		UNIQUEIDENTIFIER,
	@DATE	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY		
		IF @DATE IS NULL
			DELETE 
			FROM Client.CallDate
			WHERE ID_COMPANY = @ID
		ELSE
		BEGIN
			UPDATE Client.CallDate
			SET DATE = @DATE
			WHERE ID_COMPANY = @ID
			
			IF @@ROWCOUNT = 0
				INSERT INTO Client.CallDate(ID_COMPANY, DATE)
					VALUES(@ID, @DATE)
		END
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
