USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[COMPANY_ARCHIVE]
	@ID				UNIQUEIDENTIFIER,
	@POTENTIAL		UNIQUEIDENTIFIER,
	@NEXT_MON		UNIQUEIDENTIFIER,
	@AVAILABILITY	UNIQUEIDENTIFIER,
	@CHARACTER		UNIQUEIDENTIFIER = NULL,
	@PAY_CAT		UNIQUEIDENTIFIER = NULL
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		INSERT INTO Client.CompanyArchive(ID_COMPANY, ID_POTENTIAL, ID_NEXT_MON, ID_AVAILABILITY, ID_CHARACTER, ID_PAY_CAT)
			SELECT @ID, @POTENTIAL, @NEXT_MON, @AVAILABILITY, @CHARACTER, @PAY_CAT
			WHERE NOT EXISTS
				(
					SELECT *
					FROM Client.CompanyArchive
					WHERE ID_COMPANY = @ID
						AND STATUS = 1
				)
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END