USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_FILES_LOAD]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT FILE_NAME, FILE_DATA
	FROM Client.CompanyFiles
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [Client].[COMPANY_FILES_LOAD] TO rl_company_files_r;
GO