USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_ARCHIVE_SELECT]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@NAME	NVARCHAR(256),
	@PER	UNIQUEIDENTIFIER,
	@RC		INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		IF @END IS NOT NULL
			SET @END = DATEADD(DAY, 1, @END)

		SELECT
			a.ID, b.ID AS CO_ID, b.NUMBER AS CO_NUM, b.NAME, a.BDATE, a.UPD_USER,
			CONVERT(BIT,
				CASE
					WHEN m.ID IS NULL THEN 0
					ELSE 1
				END
			) AS CONTROL
		FROM
			Client.CompanyArchive a
			INNER JOIN Client.Company b ON a.ID_COMPANY = b.ID
			LEFT OUTER JOIN (SELECT DISTINCT ID, ID_COMPANY FROM Client.CompanyControlView WITH(NOEXPAND)) AS m ON m.ID_COMPANY = a.ID
			LEFT OUTER JOIN Personal.OfficePersonal c ON c.[LOGIN] = a.UPD_USER
		WHERE a.STATUS = 1
			AND b.STATUS = 1
			AND (b.NAME LIKE @NAME OR CONVERT(NVARCHAR(32), NUMBER) LIKE @NAME OR @NAME IS NULL)
			AND (a.BDATE >= @BEGIN OR @BEGIN IS NULL)
			AND (a.BDATE < @END OR @END IS NULL)
			AND (@PER IS NULL OR c.ID = @PER)
		ORDER BY b.NAME

		SELECT @RC = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Client].[COMPANY_ARCHIVE_SELECT] TO rl_archive_apply;
GO