USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[COMPANY_DEPO_NUMBER_INSERT]
	@COMPANY_NUMBER	INT,
	@DEPO_NUMBER	INT,
	@STATUS			INT
AS
BEGIN
	SET NOCOUNT ON;

    UPDATE 
		Client.DepoNumbers
	SET
		COMPANY_NUMBER = @COMPANY_NUMBER,
		STATUS = @STATUS
	WHERE 
		DEPO_NUM = @DEPO_NUMBER
END
