USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[COMPANY_NUMBER_GET]
	@NUM	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @NUM = ISNULL(MAX(NUMBER) + 1, 1)
	FROM Client.Company
	WHERE STATUS IN (1, 3)
END