USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Client].[DEPO_NUMBER_NEW_GET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [Client].[DEPO_NUMBER_NEW_GET]  AS SELECT 1')
GO
ALTER PROCEDURE [Client].[DEPO_NUMBER_NEW_GET]
AS
BEGIN
	SELECT MIN(DEPO_NUM) AS DEPO_NUM
	FROM Client.DepoNumbers
	WHERE	STATUS = 1 AND
			DEPO_NUM > 6229 -- ВОТ ЭТО НАДО БУДЕТ УБРАТЬ, КОГДА ВСЕХ ДО 6000 ДОБАВЯТ
END

GO
GRANT EXECUTE ON [Client].[DEPO_NUMBER_NEW_GET] TO rl_depo_info_r;
GO
