USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_REPORT_DETAIL]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME,
	@LGN	NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		SELECT b.ID, b.NUMBER, b.NAME, Common.DateOf(a.BDATE) AS DT
		FROM
			Client.CompanyCreateView a
			INNER JOIN Client.Company b ON a.ID = b.ID
		WHERE a.BDATE >= @BEGIN
			AND a.BDATE < @END
			AND a.UPD_USER = @LGN
		ORDER BY b.NAME
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Client].[COMPANY_REPORT_DETAIL] TO rl_company_report;
GO