USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[OIS_INFO_DELETE]
	@ID				UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Client.OISInfo
	WHERE ID = @ID
END
GRANT EXECUTE ON [Client].[OIS_INFO_DELETE] TO rl_client_ois_d;
GO