USE [SaleDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Client].[COMPANY_REPORT_MASTER]
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY	
		SET @END = DATEADD(DAY, 1, @END)
		
		SELECT a.UPD_USER, b.SHORT, a.CNT
		FROM
			(
				SELECT UPD_USER, COUNT(*) AS CNT
				FROM Client.CompanyCreateView
				WHERE BDATE >= @BEGIN AND BDATE < @END
				GROUP BY UPD_USER
			) AS a
			LEFT OUTER JOIN Personal.OfficePersonal b ON a.UPD_USER = b.LOGIN
		ORDER BY b.SHORT
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
