USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_DELIVERY_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	SELECT FIO, POS, EMAIL, DATE, PLAN_DATE, OFFER, STATE
	FROM Client.CompanyDelivery
	WHERE ID = @ID
END
GRANT EXECUTE ON [Client].[COMPANY_DELIVERY_GET] TO rl_delivery_r;
GO