USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[WORK_STATE_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(512),
	@SALE	BIT,
	@PHONE	BIT,
	@ARCH	BIT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		UPDATE	Client.WorkState
		SET		NAME	=	@NAME,
				SALE_AUTO	=	@SALE,
				PHONE_AUTO	=	@PHONE,
				ARCHIVE_AUTO	=	@ARCH,
				LAST	=	GETDATE()
		WHERE	ID		=	@ID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GRANT EXECUTE ON [Client].[WORK_STATE_UPDATE] TO rl_work_state_w;
GO