USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_DELIVERY_PERSONAL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT PERSONAL
	FROM Client.CompanyDelivery
	ORDER BY PERSONAL
END
GO
GRANT EXECUTE ON [Client].[COMPANY_DELIVERY_PERSONAL] TO rl_delivery_filter;
GO