USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Client].[COMPANY_DELIVERY_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Client.CompanyDelivery
	WHERE ID = @ID
END
GRANT EXECUTE ON [Client].[COMPANY_DELIVERY_DELETE] TO rl_delivery_d;
GO