USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Client].[COMPANY_ID_SELECT]
	@LIST	NVARCHAR(MAX),
	@RC		INT	=	NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;	

	BEGIN TRY		
		SELECT a.ID, NUMBER, SHORT, NAME
		FROM 
			Common.TableGUIDFromXML(@LIST) a
			INNER JOIN Client.Company b ON a.ID = b.ID
		ORDER BY SHORT, NAME

		SELECT @RC = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END