USE [SaleDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Client].[COMPANY_ARCHIVE_WARNING]
	@RC	INT = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @CURDATE SMALLDATETIME
				
		SELECT b.ID, b.NAME, b.NUMBER
		FROM 
			Client.CompanyArchiveView a WITH(NOEXPAND)
			INNER JOIN Client.Company b ON a.ID_COMPANY = b.ID
			INNER JOIN Client.CompanyWriteList() d ON d.ID = b.ID
		WHERE b.STATUS = 1 			
		ORDER BY b.NAME
				
		SELECT @RC = @@ROWCOUNT
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
