USE [SaleDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Common].[SETTINGS_LOAD]
	@ID_USER		UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;	

	BEGIN TRY
		IF EXISTS
			(
				SELECT * 
				FROM Common.Settings 
				WHERE ID_USER = @ID_USER
			)
			SELECT	DEFAULT_RUS, SEARCH_EXT, MULTY_SEARCH, WARNING_TIME, FONT_SIZE, OFFER_PATH,
					(SELECT VALUE FROM Common.GlobalSettings WHERE NAME = N'AUTH') AS AUTH
			FROM	Common.Settings
			WHERE	ID_USER		=	@ID_USER
		ELSE
			SELECT	DEFAULT_RUS, SEARCH_EXT, MULTY_SEARCH, WARNING_TIME, FONT_SIZE, OFFER_PATH,
					(SELECT VALUE FROM Common.GlobalSettings WHERE NAME = N'AUTH') AS AUTH
			FROM	Common.Settings
			WHERE	ID_USER IS NULL
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END