USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[ODD_DIN_FILTER]
	@DISTR		INT				=	NULL,
	@SYS		NVARCHAR(10)	=	NULL,
	@ACTIVE		BIT				=	NULL
AS
SELECT	SystemShortName,
		DistrNumber,
		Complect,
		RegisterDate,
		DS_INDEX
FROM [PC275-SQL\ALPHA].[ClientDB].[Reg].[RegNodeSearchView]
WHERE	SST_SHORT='ндд' AND 
		NT_SHORT='нбо' AND
		((CAST(DistrNumber AS NVARCHAR) LIKE '%'+CAST(@DISTR AS NVARCHAR)+'%')OR (@DISTR IS NULL)) AND
		((SystemShortName LIKE '%'+@SYS+'%')OR(@SYS IS NULL)) AND
		((DS_INDEX=@ACTIVE)OR(@ACTIVE IS NULL))
ORDER BY DS_INDEX, SystemShortName