USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Meeting].[ASSIGNED_MEETING_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		SELECT 
			a.ID_COMPANY, ID_OFFICE, ID_ASSIGNER, ID_PERSONAL, COMPANY_PERSONAL, EXPECTED_DATE, a.NOTE,
			ID_AREA, ID_STREET, HOME, ROOM, b.NOTE AS ADDR_NOTE, INCOMING, SPECIFY,
			(
				SELECT '{' + CONVERT(NVARCHAR(64), z.ID_PERSONAL) + '}' AS '@id'
				FROM Meeting.AssignedMeetingPersonal z
				WHERE z.ID_MEETING = a.ID
				FOR XML PATH('item'), ROOT('root')
			) AS PERSONAL_LIST,
			c.DATE AS NEXT_DATE
		FROM 
			Meeting.AssignedMeeting a
			INNER JOIN Meeting.MeetingAddress b ON a.ID = b.ID_MEETING
			LEFT OUTER JOIN Client.CallDate c ON c.ID_COMPANY = a.ID_COMPANY
		WHERE a.ID = @ID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END