USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Memo].[SERVICE_SELECT]
	@FILTER	NVARCHAR(256),
	@RC		INT	= NULL OUTPUT
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC [PC275-SQL\ALPHA].ClientDB.Memo.SERVICE_SELECT
END
GRANT EXECUTE ON [Memo].[SERVICE_SELECT] TO rl_client_memo_ref;
GO