USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Personal].[PERSONAL_ID]
	@ID		UNIQUEIDENTIFIER = NULL OUTPUT,
	@NAME	NVARCHAR(128) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;	

	BEGIN TRY
		SELECT @ID = ID, @NAME = SHORT
		FROM Personal.OfficePersonal		
		WHERE UPPER(LOGIN) = UPPER(ORIGINAL_LOGIN())
			AND END_DATE IS NULL
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END