USE [SaleDB]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE PROCEDURE [Price].[OTHER_SERVICE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		SELECT a.ID, a.NAME, b.PRICE
		FROM 
			Price.OtherService a
			LEFT OUTER JOIN 
				(
					SELECT b.ID_SERVICE, b.PRICE
					FROM
						Price.OtherServicePrice b 
						INNER JOIN Common.Month c ON b.ID_PERIOD = c.ID AND c.DATE <= GETDATE() AND DATEADD(MONTH, 1, c.DATE) > GETDATE()
				) AS b ON a.ID = b.ID_SERVICE
		ORDER BY a.ORD
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT 
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
