USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[COMMERCIAL_OPERATION_UPDATE]
	@ID		UNIQUEIDENTIFIER,
	@NAME	NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Price.CommercialOperation
	SET NAME		=	@NAME,		
		LAST		=	GETDATE()
	WHERE ID = @ID
END