USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Price].[ACTION_LAST]
	@LAST	DATETIME = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT @LAST = MAX(LAST)
	FROM Price.Action
END
GRANT EXECUTE ON [Price].[ACTION_LAST] TO rl_offer_r;
GO