USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [Price].[ACTION_SELECT]
	@FILTER VARCHAR(100) = NULL OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NAME, DELIVERY, SUPPORT, DELIVERY_FIXED
	FROM Price.Action
	WHERE @FILTER IS NULL
		OR NAME LIKE @FILTER
	ORDER BY NAME
END
