USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Price].[COMMERCIAL_OFFER_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Price.CommercialOffer
	SET STATUS = 3
	WHERE ID = @ID
END
GRANT EXECUTE ON [Price].[COMMERCIAL_OFFER_DELETE] TO rl_offer_w;
GO