USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Sale].[COMPANY_SALE_DISTR_GET]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		SELECT b.ID AS SYS_ID, b.SHORT AS SYS_SHORT, c.ID AS NT_ID, c.SHORT AS NT_SHORT, CNT
		FROM
			Sale.SaleDistr a
			INNER JOIN System.Systems b ON b.ID = a.ID_SYSTEM
			INNER JOIN System.Net c ON c.ID = a.ID_NET
		WHERE a.ID_SALE = @ID
		ORDER BY ORD
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GO
GRANT EXECUTE ON [Sale].[COMPANY_SALE_DISTR_GET] TO rl_sale_r;
GO