USE [SaleDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Security].[ROLE_GROUP_UPDATE]
	@ID			UNIQUEIDENTIFIER,
	@NAME		NVARCHAR(256),
	@CAPTION	NVARCHAR(256),
	@NOTE		NVARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @OLD_NAME	NVARCHAR(128)

		SELECT @OLD_NAME = NAME
		FROM Security.RoleGroup
		WHERE ID = @ID

		IF (ISNULL(@OLD_NAME, N'') = N'') AND ISNULL(@NAME, N'') <> N''
		BEGIN
			EXEC ('CREATE ROLE [' + @NAME + ']')
		END
		ELSE IF (ISNULL(@OLD_NAME, N'') <> N'') AND ISNULL(@NAME, N'') = N''
		BEGIN
			EXEC ('DROP ROLE [' + @NAME + ']')
		END
		ELSE IF (ISNULL(@OLD_NAME, N'') <> N'') AND (ISNULL(@NAME, N'') <> N'') AND (@OLD_NAME <> @NAME)
		BEGIN
			EXEC ('ALTER ROLE [' + @OLD_NAME + '] WITH NAME = [' + @NAME + ']')
		END

		UPDATE Security.RoleGroup
		SET NAME	= @NAME,
			CAPTION	= @CAPTION,
			NOTE	= @NOTE,
			LAST	= GETDATE()
		WHERE ID = @ID
	END TRY
	BEGIN CATCH
		DECLARE	@SEV	INT
		DECLARE	@STATE	INT
		DECLARE	@NUM	INT
		DECLARE	@PROC	NVARCHAR(128)
		DECLARE	@MSG	NVARCHAR(2048)

		SELECT
			@SEV	=	ERROR_SEVERITY(),
			@STATE	=	ERROR_STATE(),
			@NUM	=	ERROR_NUMBER(),
			@PROC	=	ERROR_PROCEDURE(),
			@MSG	=	ERROR_MESSAGE()

		EXEC Security.ERROR_RAISE @SEV, @STATE, @NUM, @PROC, @MSG
	END CATCH
END
GRANT EXECUTE ON [Security].[ROLE_GROUP_UPDATE] TO rl_role_group_w;
GO