USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[TableIDFromXML]', 'TF') IS NULL EXEC('CREATE FUNCTION [dbo].[TableIDFromXML] () RETURNS @output TABLE(Id Int) AS BEGIN RETURN END')
GO
CREATE OR ALTER FUNCTION [dbo].[TableIDFromXML]
	(
		@SOURCE NVARCHAR(MAX)
	)
RETURNS @TBL TABLE
	(
		ID INT
	)
AS
BEGIN
	DECLARE @XML XML

	SET @XML = CAST(@SOURCE AS XML)

	INSERT INTO @TBL(ID)
		SELECT c.value('(.)', 'INT')
		FROM @xml.nodes('/LIST/ITEM') AS a(c)

	RETURN
END
GO
