USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[MonthDates]', 'TF') IS NULL EXEC('CREATE FUNCTION [dbo].[MonthDates] () RETURNS @output TABLE(Id Int) AS BEGIN RETURN END')
GO
ALTER FUNCTION [dbo].[MonthDates]
(
	@BEGIN	SMALLDATETIME,
	@END	SMALLDATETIME
)
RETURNS @MONTH TABLE
		(
			MID		INT IDENTITY(1, 1),
			MBEGIN	SMALLDATETIME,
			MEND	SMALLDATETIME
		)
AS
BEGIN
	DECLARE @TBEGIN SMALLDATETIME
	DECLARE @TEND SMALLDATETIME

	IF @BEGIN > @END
		RETURN
	ELSE
	BEGIN
		SET @TBEGIN = @BEGIN
		SET @TEND = DATEADD(MONTH, 1 , DATEADD(DAY, 1 - DAY(@BEGIN), @BEGIN)) - 1

		IF @TEND >= @END
			SET @TEND = @END

		INSERT INTO @MONTH(MBEGIN, MEND) VALUES (@TBEGIN, @TEND)

		SET @TBEGIN = DATEADD(DAY, 1, @TEND)

		WHILE @TEND < @END
		BEGIN
			SET @TBEGIN = DATEADD(DAY, 1 - DAY(@TBEGIN), @TBEGIN)
			SET @TEND = DATEADD(MONTH, 1 , DATEADD(DAY, 1 - DAY(@TBEGIN), @TBEGIN)) - 1

			IF @TEND >= @END
				SET @TEND = @END

			INSERT INTO @MONTH(MBEGIN, MEND) VALUES (@TBEGIN, @TEND)

			SET @TBEGIN = DATEADD(DAY, 1, @TEND)
		END
	END

	RETURN
END
GO
