USE [DocumentClaim]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Security].[RoleCaptionView]', 'V ') IS NULL EXEC('CREATE VIEW [Security].[RoleCaptionView]  AS SELECT 1')
GO
ALTER VIEW [Security].[RoleCaptionView]
AS
	WITH CTE AS
	(
		SELECT ID, ID_MASTER, NAME, CONVERT(NVARCHAR(MAX), CAPTION) AS CAPTION
		FROM Security.Roles
		--WHERE NAME <> '' AND NAME IS NOT NULL

		UNION ALL

		SELECT b.ID, b.ID_MASTER, a.NAME, CONVERT(NVARCHAR(MAX), b.CAPTION + '\' + a.CAPTION)
		FROM
			CTE a
			INNER JOIN Security.Roles b ON a.ID_MASTER = b.ID
		--WHERE b.NAME = '' OR b.NAME IS NULL
	)
	SELECT ID, NAME, CAPTION
	FROM CTE
	WHERE NAME <> '' AND NAME IS NOT NULL AND ID_MASTER IS NULL

GO
