USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRICE_TYPE_SYSTEM_TRY_DELETE]
	@PTS_ID	INT
AS
BEGIN
	SET NOCOUNT ON

	DECLARE @res INT
	DECLARE @txt VARCHAR(MAX)

	SET @res = 0
	SET @txt = ''


	SELECT @res AS RES, @txt AS TXT
END

GO
GRANT EXECUTE ON [dbo].[PRICE_TYPE_SYSTEM_TRY_DELETE] TO rl_price_type_system_d;
GO