USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



/*
Автор:			Денисов Алексей
Дата:			2 July 2009
Описание:
*/

ALTER PROCEDURE [dbo].[FINANCING_ADDRESS_TYPE_SELECT]
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT FAT_ID, FAT_DOC, FAT_NOTE, AT_NAME, FAT_TEXT
		FROM	dbo.FinancingAddressTypeTable	A		LEFT OUTER JOIN
				dbo.AddressTypeTable			B	ON	A.FAT_ID_ADDR_TYPE=B.AT_ID
	WHERE FAT_ACTIVE = ISNULL(@active, FAT_ACTIVE)
	ORDER BY AT_NAME

	SET NOCOUNT OFF
END







GO
GRANT EXECUTE ON [dbo].[FINANCING_ADDRESS_TYPE_SELECT] TO rl_financing_address_type_r;
GO