USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[DISTR_CHECK_DISTR]
	@SYS_ID	SMALLINT,
	@DISTR	INT,
	@COMP	TINYINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DIS_ID
	FROM dbo.DistrTable
	WHERE DIS_ID_SYSTEM = @SYS_ID
		AND DIS_NUM = @DISTR
		AND DIS_COMP_NUM = @COMP
END
GO
GRANT EXECUTE ON [dbo].[DISTR_CHECK_DISTR] TO rl_distr_w;
GO