USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Автор:		  Денисов Алексей
Описание:
*/

ALTER PROCEDURE [dbo].[PRICE_TYPE_SELECT]
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT PT_ID, PT_NAME, PG_NAME
	FROM
		dbo.PriceTypeTable LEFT OUTER JOIN
		dbo.PriceGroupTable ON PG_ID = PT_ID_GROUP
	WHERE PT_ACTIVE = ISNULL(@active, PT_ACTIVE)
	ORDER BY PT_NAME

	SET NOCOUNT OFF
END

GO
GRANT EXECUTE ON [dbo].[PRICE_TYPE_SELECT] TO rl_price_type_r;
GO