USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ORGANIZATION_1C_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ORG_ID, ORG_PSEDO
	FROM dbo.OrganizationTable
	WHERE ORG_PSEDO <> '' AND ORG_PSEDO <> 'КонсультантПрим'
END
GO
GRANT EXECUTE ON [dbo].[ORGANIZATION_1C_SELECT] TO rl_organization_r;
GO