USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_DELETE]
	@STW_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.SystemTypeWeightTable
	WHERE STW_ID = @STW_ID
END

GO
GRANT EXECUTE ON [dbo].[SYSTEM_TYPE_WEIGHT_DELETE] TO rl_system_type_weight_d;
GO