USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[REG_PROTOCOL_USER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT RPR_USER
	FROM dbo.RegProtocol
	ORDER BY RPR_USER
END

GO
GRANT EXECUTE ON [dbo].[REG_PROTOCOL_USER] TO rl_reg_protocol_r;
GO