USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[FILTER_PROTOCOL_OPER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT OPER, TP, CONVERT(BIT, 1) AS CHECKED
	FROM dbo.FinancingProtocol
	ORDER BY TP, OPER
END

GO
GRANT EXECUTE ON [dbo].[FILTER_PROTOCOL_OPER] TO rl_financing_protocol_r;
GO