USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[REG_WEIGHT_REPORT_RESTORE]
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM dbo.REG_WEIGHT_REPORT_SELECT(@PR_ID)
END

GO
GRANT EXECUTE ON [dbo].[REG_WEIGHT_REPORT_RESTORE] TO rl_reg_node_report_r;
GRANT EXECUTE ON [dbo].[REG_WEIGHT_REPORT_RESTORE] TO rl_reg_report_r;
GO