USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INCOME_TYPE_GET]
	@id SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT IT_ID, IT_NAME, IT_ACTIVE
	FROM dbo.IncomeTypeTable
	WHERE IT_ID = @id
END

GO
GRANT EXECUTE ON [dbo].[INCOME_TYPE_GET] TO rl_income_type_r;
GO