USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INVOICE_BOOK_RECALC]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	EXEC dbo.BOOK_SALE_PROCESS @ID
	EXEC dbo.BOOK_PURCHASE_PROCESS @ID
END
GO
GRANT EXECUTE ON [dbo].[INVOICE_BOOK_RECALC] TO rl_book_buy_p;
GRANT EXECUTE ON [dbo].[INVOICE_BOOK_RECALC] TO rl_book_sale_p;
GO