USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Автор:		  Денисов Алексей
Описание:
*/

ALTER PROCEDURE [dbo].[CLIENT_PERSONAL_DELETE]
	@personalid INT
AS
BEGIN
	SET NOCOUNT ON

	DELETE FROM dbo.ClientPersonalTable WHERE PER_ID = @personalid

	SET NOCOUNT OFF
END
GO
GRANT EXECUTE ON [dbo].[CLIENT_PERSONAL_DELETE] TO rl_client_d;
GRANT EXECUTE ON [dbo].[CLIENT_PERSONAL_DELETE] TO rl_client_personal_d;
GO