USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLIENT_FINANCING_GET]
	@ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT *
	FROM dbo.ClientFinancing
	WHERE ID_CLIENT = @ID
END

GO
GRANT EXECUTE ON [dbo].[CLIENT_FINANCING_GET] TO rl_client_fin_r;
GO