USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[QUARTER_SELECT]
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT QR_ID, QR_NAME, QR_BEGIN, QR_END
	FROM dbo.Quarter
	WHERE QR_ACTIVE = ISNULL(@active, QR_ACTIVE)
	ORDER BY QR_BEGIN DESC

	SET NOCOUNT OFF
END

GO
GRANT EXECUTE ON [dbo].[QUARTER_SELECT] TO rl_quarter_r;
GO