USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SYSTEM_NET_COEF_DELETE]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.SystemNetCoef
	WHERE SNCC_ID = @ID
END

GO
GRANT EXECUTE ON [dbo].[SYSTEM_NET_COEF_DELETE] TO rl_system_net_w;
GO