USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRICE_SELECT_FROM_PRICECOUNT]
	@IsDepo	Bit
WITH EXECUTE AS OWNER
AS
BEGIN
	SET NOCOUNT ON;

	EXEC [PC275-SQL\GAMMA].[BuhDB].[dbo].[PRICE_EXPORT_SELECT] @IsDepo;
END
GO
GRANT EXECUTE ON [dbo].[PRICE_SELECT_FROM_PRICECOUNT] TO rl_price_list_w;
GRANT EXECUTE ON [dbo].[PRICE_SELECT_FROM_PRICECOUNT] TO rl_price_w;
GO