USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Автор:
Дата создания:  
Описание:
*/

ALTER PROCEDURE [dbo].[CONSIGNMENT_UNSIGN_REPORT]
	@consdate SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		CL_ID, CL_PSEDO, COUR_NAME, CSG_DATE, PR_DATE
	FROM
		dbo.ClientCourView INNER JOIN
		dbo.ConsignmentPeriodView ON CSG_ID_CLIENT = CL_ID INNER JOIN
		dbo.PeriodTable ON PR_ID = CSG_ID_PERIOD
	WHERE CSG_SIGN IS NULL
		AND CSG_DATE <= @consdate
	ORDER BY COUR_NAME, CL_PSEDO, CL_ID, CSG_DATE
END

GO
GRANT EXECUTE ON [dbo].[CONSIGNMENT_UNSIGN_REPORT] TO rl_consignment_w;
GO