USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLIENT_CHECK_CODE]
	@CODE INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT CL_ID
	FROM dbo.ClientTable
	WHERE CL_NUM = @CODE
END
GO
GRANT EXECUTE ON [dbo].[CLIENT_CHECK_CODE] TO rl_client_w;
GO