USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CLIENT_FACT_BILL_DELETE]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.BillFactDetailTable
	WHERE BFD_ID_BFM = @ID

	DELETE
	FROM dbo.BillFactMasterTable
	WHERE BFM_ID = @ID
END

GO
GRANT EXECUTE ON [dbo].[CLIENT_FACT_BILL_DELETE] TO rl_bill_d;
GO