USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


/*
Автор:		  Денисов Алексей
Описание:
*/

ALTER PROCEDURE [dbo].[SYSTEM_GET]
	@id INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT
			SYS_ID, SYS_PREFIX, SYS_SHORT_NAME, SYS_NAME,
			SYS_REG_NAME, SYS_REPORT, SO_ID, SO_NAME, SYS_ORDER,
			HST_NAME, HST_ID, SYS_REPORT, SYS_ACTIVE, SYS_1C_CODE, SYS_1C_CODE2, SYS_COEF, SYS_IB, SYS_CALC
	FROM
		dbo.SystemTable a LEFT OUTER JOIN
		dbo.HostTable b ON a.SYS_ID_HOST = b.HST_ID LEFT OUTER JOIN
		dbo.SaleObjectTable c ON a.SYS_ID_SO = c.SO_ID
	WHERE SYS_ID = @id

	SET NOCOUNT OFF
END
GO
GRANT EXECUTE ON [dbo].[SYSTEM_GET] TO rl_system_d;
GRANT EXECUTE ON [dbo].[SYSTEM_GET] TO rl_system_r;
GRANT EXECUTE ON [dbo].[SYSTEM_GET] TO rl_system_w;
GO