USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[FILTER_PROTOCOL_USER]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT USR_NAME, CONVERT(BIT, 1) AS CHECKED
	FROM dbo.FinancingProtocol
	ORDER BY USR_NAME
END

GO
GRANT EXECUTE ON [dbo].[FILTER_PROTOCOL_USER] TO rl_financing_protocol_r;
GO