USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SUBHOST_KBU_EDIT]
	@SK_ID	INT,
	@SH_ID	SMALLINT,
	@SYS_ID	SMALLINT,
	@PR_ID	SMALLINT,
	@KBU	DECIMAL(8, 4),
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.SubhostKBUTable
	SET SK_ID_HOST = @SH_ID,
		SK_ID_SYSTEM = @SYS_ID,
		SK_ID_PERIOD = @PR_ID,
		SK_KBU = @KBU,
		SK_ACTIVE = @ACTIVE
	WHERE SK_ID = @SK_ID
END

GO
GRANT EXECUTE ON [dbo].[SUBHOST_KBU_EDIT] TO rl_subhost_kbu_w;
GO