USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[REG_PROTOCOL_OPERATION]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT RPR_OPER
	FROM dbo.RegProtocol
	ORDER BY RPR_OPER
END

GO
GRANT EXECUTE ON [dbo].[REG_PROTOCOL_OPERATION] TO rl_reg_protocol_r;
GO