USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[REG_PROTOCOL_COMP]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT RPR_COMPUTER
	FROM dbo.RegProtocol
	ORDER BY RPR_COMPUTER
END

GO
GRANT EXECUTE ON [dbo].[REG_PROTOCOL_COMP] TO rl_reg_protocol_r;
GO