USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PROVISION_SAVE]
	@ID		INT,
	@CLIENT	INT,
	@DATE	SMALLDATETIME,
	@PRICE	MONEY,
	@NUM	INT,
	@ORG	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
		INSERT INTO dbo.Provision(ID_CLIENT, DATE, PRICE, PAY_NUM, ID_ORG)
			VALUES(@CLIENT, @DATE, @PRICE, @NUM, @ORG)
	ELSE
		UPDATE dbo.Provision
		SET	DATE	=	@DATE,
			PRICE	=	@PRICE,
			PAY_NUM	=	@NUM,
			ID_ORG	=	@ORG
		WHERE ID = @ID
END

GO
GRANT EXECUTE ON [dbo].[PROVISION_SAVE] TO rl_income_w;
GO