USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_GET]
	@STW_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT STW_WEIGHT, STW_ACTIVE, SYS_ID, SYS_SHORT_NAME, SST_ID, SST_CAPTION
	FROM
		dbo.SystemTypeWeightTable INNER JOIN
		dbo.SystemTable ON STW_ID_SYSTEM = SYS_ID INNER JOIN
		dbo.SystemTypeTable ON STW_ID_TYPE = SST_ID
	WHERE STW_ID = @STW_ID
END

GO
GRANT EXECUTE ON [dbo].[SYSTEM_TYPE_WEIGHT_GET] TO rl_system_type_weight_r;
GO