USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ORGANIZATION_CALC_DELETE]
	@id SMALLINT
AS
BEGIN
	SET NOCOUNT ON

	DELETE
	FROM dbo.OrganizationCalc
	WHERE ORGC_ID = @id

	SET NOCOUNT OFF
END

GO
GRANT EXECUTE ON [dbo].[ORGANIZATION_CALC_DELETE] TO rl_organization_calc_d;
GO