USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SYSTEM_TYPE_WEIGHT_TRY_DELETE]
	@STW_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @res INT
	DECLARE @txt VARCHAR(MAX)

	SET @res = 0
	SET @txt = ''


	SELECT @res AS RES, @txt AS TXT
END

GO
GRANT EXECUTE ON [dbo].[SYSTEM_TYPE_WEIGHT_TRY_DELETE] TO rl_system_type_weight_d;
GO