USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INCOME_TYPE_EDIT]
	@id SMALLINT,
	@name VARCHAR(50),
	@active BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.IncomeTypeTable
	SET IT_NAME = @NAME,
		IT_ACTIVE = @active
	WHERE IT_ID = @id
END

GO
GRANT EXECUTE ON [dbo].[INCOME_TYPE_EDIT] TO rl_income_type_w;
GO