USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRICE_TYPE_SYSTEM_DELETE]
	@PTS_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.PriceTypeSystemTable
	WHERE PTS_ID = @PTS_ID
END

GO
GRANT EXECUTE ON [dbo].[PRICE_TYPE_SYSTEM_DELETE] TO rl_price_type_system_d;
GO