USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INVOICE_SELECT]
	@ACTIVE BIT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		INS_ID, CL_PSEDO, INS_NUM, INS_DATE, INT_NAME,
		(
			SELECT SUM(INR_SALL)
			FROM dbo.InvoiceRowTable
			WHERE INR_ID_INVOICE = INS_ID
		) AS INS_SALL
	FROM
		dbo.InvoiceSaleTable a
		INNER JOIN dbo.InvoiceTypeTable ON INT_ID = INS_ID_TYPE
		INNER JOIN dbo.ClientTable ON CL_ID = INS_ID_CLIENT
	WHERE INS_DATE >= DATEADD(YEAR, -2, GETDATE())
	ORDER BY INS_DATE DESC, INS_NUM DESC
END

GO
GRANT EXECUTE ON [dbo].[INVOICE_SELECT] TO rl_book_sale_p;
GO