USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PRICE_SYSTEM_TYPE_DELETE]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM	dbo.PriceSystemType
	WHERE PST_ID = @ID
END

GO
GRANT EXECUTE ON [dbo].[PRICE_SYSTEM_TYPE_DELETE] TO rl_price_system_type_d;
GO