USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[NET_TYPE_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NT_ID, NT_SHORT
	FROM dbo.NetType
	--WHERE SN_ACTIVE = ISNULL(@active, SN_ACTIVE)
	ORDER BY NT_NET, NT_TECH
END

GO
GRANT EXECUTE ON [dbo].[NET_TYPE_SELECT] TO rl_system_net_r;
GO