USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ORGANIZATION_DEFAULT_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT TOP 1 ORG_ID, ORG_PSEDO
	FROM dbo.OrganizationTable
END
GO
GRANT EXECUTE ON [dbo].[ORGANIZATION_DEFAULT_SELECT] TO rl_client_fin_r;
GO