USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PERIOD_SEARCH]
	@DT	SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PR_ID, PR_NAME
	FROM dbo.PeriodTable
	WHERE @DT BETWEEN PR_DATE AND PR_END_DATE
END

GO
GRANT EXECUTE ON [dbo].[PERIOD_SEARCH] TO rl_all_r;
GO