USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[QUARTER_GET]
	@id SMALLINT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT QR_ID, QR_NAME, QR_BEGIN, QR_END, QR_ACTIVE
	FROM dbo.Quarter
	WHERE QR_ID = @id
END

GO
GRANT EXECUTE ON [dbo].[QUARTER_GET] TO rl_quarter_r;
GO