USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INCOME_TYPE_DELETE]
	@id SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM dbo.IncomeTypeTable
	WHERE IT_ID = @id
END

GO
GRANT EXECUTE ON [dbo].[INCOME_TYPE_DELETE] TO rl_income_type_d;
GO