USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Автор:		  Денисов Алексей
Описание:
*/

ALTER PROCEDURE [dbo].[ACTION_TYPE_SELECT]
	@active BIT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT ACTT_ID, ACTT_NAME
	FROM dbo.ActionType
	WHERE ACTT_ACTIVE = ISNULL(@active, ACTT_ACTIVE)
	ORDER BY ACTT_NAME

	SET NOCOUNT OFF
END

GO
GRANT EXECUTE ON [dbo].[ACTION_TYPE_SELECT] TO rl_action_type_r;
GO