USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Автор:
Дата создания:  
Описание:
*/

ALTER PROCEDURE [dbo].[ACT_UNSIGN_REPORT]
	@actdate SMALLDATETIME
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		CL_ID, CL_PSEDO, COUR_NAME, ACT_DATE, PR_DATE
	FROM
		dbo.ClientCourView INNER JOIN
		dbo.ActPeriodView ON ACT_ID_CLIENT = CL_ID INNER JOIN
		dbo.PeriodTable ON PR_ID = ACT_ID_PERIOD
	WHERE ACT_SIGN IS NULL
		AND ACT_DATE <= @actdate
	ORDER BY COUR_NAME, CL_PSEDO, CL_ID, ACT_DATE
END

GO
GRANT EXECUTE ON [dbo].[ACT_UNSIGN_REPORT] TO rl_act_r;
GO