USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*
Автор:
Дата создания:  
Описание:
*/
ALTER PROCEDURE [dbo].[BILL_FACT_ALL_GET]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT BFM_DATE, COUNT(*) AS BFM_COUNT, BFM_ID_PERIOD, BILL_DATE
	FROM dbo.BillFactMasterTable
	GROUP BY BFM_DATE, BFM_ID_PERIOD, BILL_DATE
	ORDER BY BFM_DATE DESC
END
GO
GRANT EXECUTE ON [dbo].[BILL_FACT_ALL_GET] TO rl_bill_p;
GO