USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ACT_1C_DATE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT DISTINCT DATE
	FROM dbo.Act1C
	WHERE TOTAL = 1
	ORDER BY DATE DESC
END

GO
GRANT EXECUTE ON [dbo].[ACT_1C_DATE_SELECT] TO rl_report_act_r;
GO