USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[FINANCING_PROTOCOL_ADD]
	@TP		VARCHAR(64),
	@OPER	VARCHAR(256),
	@TXT	VARCHAR(MAX),
	@CLIENT	INT,
	@DOC	INT
AS
BEGIN
	SET NOCOUNT ON;

	SET @TXT = ISNULL(@TXT, '')

	INSERT INTO dbo.FinancingProtocol(OPER, TP, TXT, ID_CLIENT, ID_DOCUMENT)
		VALUES(@OPER, @TP, @TXT, @CLIENT, @DOC)
END
GO
GRANT EXECUTE ON [dbo].[FINANCING_PROTOCOL_ADD] TO public;
GO