USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Price].[PRICE_TYPE_NEW_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT PT_ID, PT_SHORT, PT_GROUP
	FROM Price.PriceType
	--WHERE SN_ACTIVE = ISNULL(@active, SN_ACTIVE)
	ORDER BY PT_ORDER
END
GO
GRANT EXECUTE ON [Price].[PRICE_TYPE_NEW_SELECT] TO rl_price_type_r;
GRANT EXECUTE ON [Price].[PRICE_TYPE_NEW_SELECT] TO rl_price_w;
GO