USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Price].[SYSTEM_TYPE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SST_ID, SST_CAPTION
	FROM dbo.SystemTypeTable
	ORDER BY SST_ORDER
END

GO
GRANT EXECUTE ON [Price].[SYSTEM_TYPE_SELECT] TO rl_price_w;
GO