USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Price].[PRICE_DEPEND_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, ID_OLD_PRICE, ID_NEW_PRICE, ID_OLD_SYS_TYPE, ID_NEW_SYS_TYPE, ID_OLD_NET, ID_NEW_NET, COEF
	FROM Price.PriceDepend
END

GO
GRANT EXECUTE ON [Price].[PRICE_DEPEND_SELECT] TO rl_price_w;
GO