USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Ric].[WEIGHT_CORRECT_SAVE]
	@PR_ID	SMALLINT,
	@VALUE	DECIMAL(10, 4)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @QR_ID	SMALLINT

	SET @QR_ID = dbo.PeriodQuarter(@PR_ID)

	UPDATE Ric.WeightCorrection
	SET WC_VALUE = @VALUE
	WHERE WC_ID_QUARTER = @QR_ID

	IF @@ROWCOUNT = 0
		INSERT INTO Ric.WeightCorrection(WC_ID_QUARTER, WC_VALUE)
			SELECT @QR_ID, @VALUE
END

GO
GRANT EXECUTE ON [Ric].[WEIGHT_CORRECT_SAVE] TO rl_ric_kbu;
GO