USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Ric].[WIEGHT_CORRECTION_SET]
	@DATE	SMALLDATETIME,
	@VALUE	DECIMAL(8, 4)
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @PERIOD SMALLINT

	SELECT @PERIOD = PR_ID
	FROM dbo.PeriodTable
	WHERE PR_DATE = @DATE

	UPDATE Ric.WeightCorrectionMonth
	SET WC_VALUE = @VALUE
	WHERE WC_ID_PERIOD = @PERIOD

	IF @@ROWCOUNT = 0
		INSERT INTO Ric.WeightCorrectionMonth(WC_ID_PERIOD, WC_VALUE)
			VALUES(@PERIOD, @VALUE)
END

GO
GRANT EXECUTE ON [Ric].[WIEGHT_CORRECTION_SET] TO rl_ric_kbu;
GO