USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Ric].[CALC_COEF_SELECT]
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	IF EXISTS
		(
			SELECT *
			FROM Ric.CalcCoef
			WHERE CC_ID_PERIOD = @PR_ID
		)
		SELECT CC_PRICE, CC_INCREASE_DISC, CC_PREPAY_RATE, CC_PREPAY, CC_PREPAY_DISC
		FROM Ric.CalcCoef
		WHERE CC_ID_PERIOD = @PR_ID
	ELSE
		SELECT TOP 1 CC_PRICE, CC_INCREASE_DISC, CC_PREPAY_RATE, CC_PREPAY, CC_PREPAY_DISC
		FROM Ric.CalcCoef
		WHERE CC_ID_PERIOD = dbo.PeriodDelta(@PR_ID, -1)
END

GO
GRANT EXECUTE ON [Ric].[CALC_COEF_SELECT] TO rl_ric_kbu;
GO