USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Ric].[DEPTH_COEF_SAVE]
	@QR_ID	SMALLINT,
	@VALUE	DECIMAL(10, 4)
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Ric.DepthCoef
	SET DC_VALUE = @VALUE
	WHERE DC_ID_QUARTER = @QR_ID

	IF @@ROWCOUNT = 0
		INSERT INTO Ric.DepthCoef(DC_ID_QUARTER, DC_VALUE)
			SELECT @QR_ID, @VALUE
END

GO
GRANT EXECUTE ON [Ric].[DEPTH_COEF_SAVE] TO rl_ric_kbu;
GO