USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Ric].[KBU_LIST_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT RK_ID_QUARTER, QR_NAME, RK_KBU, RK_STOCK, RK_TOTAL
	FROM
		Ric.KBU
		INNER JOIN dbo.Quarter ON QR_ID = RK_ID_QUARTER
	ORDER BY QR_BEGIN DESC
END

GO
GRANT EXECUTE ON [Ric].[KBU_LIST_SELECT] TO rl_ric_kbu;
GO