USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Salary].[SERVICE_DETAIL_DELETE]
	@ID	UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	DELETE FROM Salary.ServiceDetail WHERE ID = @ID
END

GO
GRANT EXECUTE ON [Salary].[SERVICE_DETAIL_DELETE] TO rl_courier_pay;
GO