USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[REG_NODE_SUBHOST_DELETE]
	@RNS_ID BIGINT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.RegNodeSubhostTable
	WHERE RNS_ID = @RNS_ID
END

GO
GRANT EXECUTE ON [Subhost].[REG_NODE_SUBHOST_DELETE] TO rl_subhost_calc;
GO