USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_ADD]
	@SPG_NAME	VARCHAR(50),
	@SPG_ORDER	SMALLINT,
	@ACTIVE	BIT,
	@return	BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Subhost.SubhostProductGroup(SPG_NAME, SPG_ORDER, SPG_ACTIVE)
		VALUES(@SPG_NAME, @SPG_ORDER, @ACTIVE)

	IF @RETURN = 1
		SELECT SCOPE_IDENTITY() AS NEW_IDEN
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_GROUP_ADD] TO rl_subhost_product_group_w;
GO