USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_CALC_DATES_GET]
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

    SELECT SCD_DATE
	FROM Subhost.SubhostCalcDates
	WHERE SCD_ID_PERIOD = @PR_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_CALC_DATES_GET] TO rl_subhost_calc;
GO