USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_GET]
	@SPG_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SPG_ID, SPG_NAME, SPG_ORDER, SPG_ACTIVE
	FROM Subhost.SubhostProductGroup
	WHERE SPG_ID = @SPG_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_GROUP_GET] TO rl_subhost_product_group_r;
GO