USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_KBU_DELETE]
	@SK_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostKBUTable
	WHERE SK_ID = @SK_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_KBU_DELETE] TO rl_subhost_kbu_d;
GO