USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_DELETE]
	@SP_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostProduct
	WHERE SP_ID = @SP_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_DELETE] TO rl_subhost_product_d;
GO