USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_LESSON_POSITION_DELETE]
	@LP_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.LessonPosition
	WHERE LP_ID = @LP_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_LESSON_POSITION_DELETE] TO rl_subhost_lesson_position_d;
GO