USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_EDIT]
	@SPG_ID	INT,
	@SPG_NAME	VARCHAR(50),
	@SPG_ORDER SMALLINT,
	@ACTIVE	BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE Subhost.SubhostProductGroup
	SET SPG_NAME = @SPG_NAME,
		SPG_ORDER = @SPG_ORDER,
		SPG_ACTIVE = @ACTIVE
	WHERE SPG_ID = @SPG_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_GROUP_EDIT] TO rl_subhost_product_group_w;
GO