USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_DELIVERY_CALC_DEFAULT_GET]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		1 AS DIS_COMP
END
GO
GRANT EXECUTE ON [Subhost].[SUBHOST_DELIVERY_CALC_DEFAULT_GET] TO rl_subhost_calc;
GO