USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_TAX_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		a.TX_NAME AS CTX_NAME, a.TX_PERCENT AS CTX_PERCENT,
		b.TX_NAME AS PTX_NAME, b.TX_PERCENT AS PTX_PERCENT
	FROM dbo.TaxTable a, dbo.TaxTable b
	WHERE a.TX_ID = 1 AND b.TX_ID = 2
END
GO
GRANT EXECUTE ON [Subhost].[SUBHOST_TAX_SELECT] TO rl_subhost_calc;
GO