USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_TRY_DELETE]
	@SP_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @res INT
	DECLARE @txt VARCHAR(MAX)

	SET @res = 0
	SET @txt = ''


	SELECT @res AS RES, @txt AS TXT
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_TRY_DELETE] TO rl_subhost_product_d;
GO