USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_GROUP_DELETE]
	@SPG_ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM Subhost.SubhostProductGroup
	WHERE SPG_ID = @SPG_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_GROUP_DELETE] TO rl_subhost_product_group_d;
GO