USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_SUPPORT_PRICE_TYPE_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		PT_ID, PT_NAME, PT_COEF, PTS_ID_ST
	FROM
		dbo.PriceGroupTable
		INNER JOIN dbo.PriceTypeTable ON PT_ID_GROUP = PG_ID
		INNER JOIN dbo.PriceTypeSystemTable ON PTS_ID_PT = PT_ID
	WHERE PG_ID IN (5, 7)
	ORDER BY PT_ORDER
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_SUPPORT_PRICE_TYPE_SELECT] TO rl_subhost_calc;
GO