USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PRODUCT_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SP_ID, SPG_NAME, SP_NAME, UN_NAME, SP_COEF, SP_ACTIVE
	FROM
		Subhost.SubhostProduct INNER JOIN
		Subhost.SubhostProductGroup ON SP_ID_GROUP = SPG_ID INNER JOIN
		dbo.UnitTable ON UN_ID = SP_ID_UNIT
	WHERE SP_ACTIVE = ISNULL(@ACTIVE, SP_ACTIVE)
	ORDER BY SPG_NAME, SP_NAME
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PRODUCT_SELECT] TO rl_subhost_product_r;
GO