USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_LESSON_ADD]
	@LS_NAME	VARCHAR(50),
	@LS_ORDER	SMALLINT,
	@ACTIVE	BIT,
	@return	BIT = 1
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO Subhost.Lesson(LS_NAME, LS_ORDER, LS_ACTIVE)
		VALUES(@LS_NAME, @LS_ORDER, @ACTIVE)

	IF @RETURN = 1
		SELECT SCOPE_IDENTITY() AS NEW_IDEN
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_LESSON_ADD] TO rl_subhost_lesson_w;
GO