USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_LESSON_PRICE_SELECT]
	@PR_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SLP_ID, LS_ID, LS_NAME, SLP_PRICE
	FROM
		Subhost.SubhostLessonPrice INNER JOIN
		Subhost.Lesson ON LS_ID = SLP_ID_LESSON
	WHERE SLP_ID_PERIOD = @PR_ID
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_LESSON_PRICE_SELECT] TO rl_subhost_calc;
GO