USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_PAY_SELECT]
	@SH_ID	SMALLINT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		SHP_ID, SHP_ID_SUBHOST AS SH_ID, SHP_DATE, SHP_SUM, SHP_COMMENT,
		ORG_ID, ORG_PSEDO, PR_ID, PR_DATE
	FROM
		Subhost.SubhostPay INNER JOIN
		Subhost.SubhostPayDetail ON SPD_ID_PAY = SHP_ID INNER JOIN
		dbo.OrganizationTable ON ORG_ID = SHP_ID_ORG INNER JOIN
		dbo.PeriodTable ON PR_ID = SPD_ID_PERIOD
	WHERE SHP_ID_SUBHOST = @SH_ID
	ORDER BY SHP_DATE DESC
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_PAY_SELECT] TO rl_subhost_calc;
GO