USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [Subhost].[SUBHOST_LESSON_SELECT]
	@ACTIVE BIT = NULL
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LS_ID, LS_NAME, LS_ACTIVE
	FROM Subhost.Lesson
	WHERE LS_ACTIVE = ISNULL(@ACTIVE, LS_ACTIVE)
	ORDER BY LS_ORDER
END

GO
GRANT EXECUTE ON [Subhost].[SUBHOST_LESSON_SELECT] TO rl_subhost_lesson_r;
GO