USE [DBF_NAH]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[ActIXView]
WITH SCHEMABINDING
AS
	SELECT ACT_ID_CLIENT, AD_ID_PERIOD, AD_ID_DISTR, PR_DATE, SUM(AD_TOTAL_PRICE) AS AD_TOTAL_PRICE, COUNT_BIG(*) AS AD_CNT
	FROM dbo.ActDistrTable
	INNER JOIN dbo.ActTable ON AD_ID_ACT = ACT_ID
	INNER JOIN dbo.PeriodTable ON PR_ID = AD_ID_PERIOD
	GROUP BY ACT_ID_CLIENT, AD_ID_PERIOD, AD_ID_DISTR, PR_DATE
GO
CREATE UNIQUE CLUSTERED INDEX [UC_dbo.ActIXView(ACT_ID_CLIENT,AD_ID_DISTR,AD_ID_PERIOD)] ON [dbo].[ActIXView] ([ACT_ID_CLIENT] ASC, [AD_ID_DISTR] ASC, [AD_ID_PERIOD] ASC);
CREATE UNIQUE NONCLUSTERED INDEX [UC_dbo.ActIXView(ACT_ID_CLIENT,AD_ID_DISTR,PR_DATE)] ON [dbo].[ActIXView] ([ACT_ID_CLIENT] ASC, [AD_ID_DISTR] ASC, [PR_DATE] DESC);
GO
