USE [BuhDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[ACT_ADDITIONAL_PRINT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[ACT_ADDITIONAL_PRINT]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[ACT_ADDITIONAL_PRINT]
	@ACT INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT SystemName, SystemSet, SystemPrice, TaxPrice, SystemPrice + TaxPrice AS TotalPrice
	FROM ActSystemsTable WITH(NOLOCK) 
	WHERE ActID = @ACT AND (SystemName LIKE '%Yubikey%' OR SystemName LIKE '%флэш%')
	ORDER BY SystemOrder
END
GO
GRANT EXECUTE ON [dbo].[ACT_ADDITIONAL_PRINT] TO DBCount;
GO
