USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[NamedSetItemsSelect]', 'IF') IS NULL EXEC('CREATE FUNCTION [dbo].[NamedSetItemsSelect] () RETURNS TABLE AS RETURN (SELECT [NULL] = NULL)')
GO
CREATE OR ALTER FUNCTION [dbo].[NamedSetItemsSelect]
(
	@REF_NAME	NVARCHAR(128),
	@SET_NAME	NVARCHAR(128)
)
RETURNS TABLE
AS
RETURN
(
	SELECT SetItem
	FROM dbo.NamedSetsItems
	WHERE SetId = (SELECT TOP (1) SetId FROM dbo.NamedSets WHERE RefName = @REF_NAME AND SetName = @SET_NAME)
)GO
