USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [Reg].[Complect@Periodic]
(
	@Complect	VarChar(100),
	@Date		DateTime
)
RETURNS TABLE
AS
RETURN
(
	SELECT D.ID_HOST, H.ID_SYSTEM, D.DISTR, D.COMP, H.ID_NET, H.ID_STATUS, H.DATE
	FROM
	(
		SELECT DISTINCT ID_DISTR
		FROM Reg.RegHistory H
		WHERE H.COMPLECT = @Complect
	) AS CD
	INNER JOIN Reg.RegDistr As D ON CD.ID_DISTR = D.ID
	CROSS APPLY
	(
		SELECT TOP (1) ID_SYSTEM, ID_NET, ID_STATUS, COMPLECT, DATE
		FROM Reg.RegHistory			H
		INNER JOIN Din.SystemType	T ON H.ID_TYPE = T.SST_ID
		WHERE	H.ID_DISTR = CD.ID_DISTR
			AND H.DATE <= @Date
		ORDER BY H.DATE DESC
	)  AS H
	WHERE H.COMPLECT = @Complect
)GO
