USE [ClientDB]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [Reg].[ComplectStatusGet]
(
	@STATUS	UNIQUEIDENTIFIER,
	@DT		DATETIME
)
RETURNS TABLE
AS
RETURN
(
	SELECT COMPLECT, ID_HOST, ID_SYSTEM, DISTR, COMP, ID_NET
	FROM 
		Reg.RegDistr a
		INNER JOIN Reg.RegHistory b ON b.ID_DISTR = a.ID
		INNER JOIN Din.SystemType ON ID_TYPE = SST_ID				
	WHERE b.ID_STATUS = @STATUS
		AND SST_COMPLECT = 1
		AND b.DATE = 
			(
				SELECT MAX(DATE)
				FROM Reg.RegHistory c
				WHERE c.ID_DISTR = b.ID_DISTR
					AND c.DATE <= @DT
			)
)