USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[SCAN_DOCUMENT_DELETE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[SCAN_DOCUMENT_DELETE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[SCAN_DOCUMENT_DELETE]
	@ID			INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @NEWID INT

	INSERT INTO dbo.ScanDocument(ID_MASTER, ID_CATEGORY, ID_DIRECTION, ID_COMPANY, ID_USER, ID_FORM, NAME, DATE, DOC_NUM, DOC_DATE, STATUS, UPD_DATE, UPD_USER)
		SELECT @ID, ID_CATEGORY, ID_DIRECTION, ID_COMPANY, ID_USER, ID_FORM, NAME, DATE, DOC_NUM, DOC_DATE, 2, UPD_DATE, UPD_USER
		FROM dbo.ScanDocument
		WHERE ID = @ID

	SELECT @NEWID = SCOPE_IDENTITY()

	INSERT INTO dbo.ScanPages(ID_DOCUMENT, NUM, NAME, EXT, DATA)
		SELECT @NEWID, NUM, NAME, EXT, DATA
		FROM dbo.ScanPages
		WHERE ID_DOCUMENT = @ID

	UPDATE dbo.ScanDocument
	SET STATUS			=	3,
		UPD_DATE		=	GETDATE(),
		UPD_USER		=	ORIGINAL_LOGIN()
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[SCAN_DOCUMENT_DELETE] TO rl_admin;
GO
