USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[USER_PERMISSION_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[USER_PERMISSION_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[USER_PERMISSION_SELECT]
	@CATEGORY	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		ID, SHORT,
		ISNULL((
			SELECT R
			FROM dbo.CategoryUsers z
			WHERE z.ID_USER = a.ID
				AND z.ID_CATEGORY = @CATEGORY
		), 0) AS R,
		ISNULL((
			SELECT W
			FROM dbo.CategoryUsers z
			WHERE z.ID_USER = a.ID
				AND z.ID_CATEGORY = @CATEGORY
		), 0) AS W
	FROM
		dbo.Users a
	ORDER BY SHORT
END
GO
GRANT EXECUTE ON [dbo].[USER_PERMISSION_SELECT] TO rl_admin;
GO
