USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[SCAN_PAGES_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[SCAN_PAGES_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[SCAN_PAGES_SELECT]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID, NUM, NAME, EXT, DATA
	FROM dbo.ScanPages
	WHERE ID_DOCUMENT = @ID
	ORDER BY NUM
END
GO
GRANT EXECUTE ON [dbo].[SCAN_PAGES_SELECT] TO rl_reader;
GRANT EXECUTE ON [dbo].[SCAN_PAGES_SELECT] TO rl_user;
GO
