USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[USER_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[USER_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[USER_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 2 AS TP, ID, SHORT, LGN
	FROM dbo.Users

	UNION ALL

	SELECT 1 AS TP, NULL, '[нет]', NULL

	ORDER BY SHORT
END
GO
GRANT EXECUTE ON [dbo].[USER_SELECT] TO rl_reader;
GRANT EXECUTE ON [dbo].[USER_SELECT] TO rl_user;
GO
