USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[USER_GET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[USER_GET]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[USER_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT LGN, SHORT
	FROM dbo.Users
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[USER_GET] TO rl_admin;
GO
