USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DIRECTION_DELETE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[DIRECTION_DELETE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[DIRECTION_DELETE]
	@ID		INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.Direction
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[DIRECTION_DELETE] TO rl_admin;
GO
