USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[DIRECTION_SELECT]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[DIRECTION_SELECT]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[DIRECTION_SELECT]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 2 AS TP, ID, NAME
	FROM dbo.Direction

	UNION ALL

	SELECT 1 AS TP, NULL, '[нет]'

	ORDER BY NAME
END
GO
GRANT EXECUTE ON [dbo].[DIRECTION_SELECT] TO rl_reader;
GRANT EXECUTE ON [dbo].[DIRECTION_SELECT] TO rl_user;
GO
