USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[SCAN_PAGES_SAVE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[SCAN_PAGES_SAVE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[SCAN_PAGES_SAVE]
	@DOCUMENT	INT,
	@NUM		INT,
	@NAME		NVARCHAR(128),
	@EXT		NVARCHAR(16),
	@DATA		VARBINARY(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.ScanPages(ID_DOCUMENT, NUM, NAME, EXT, DATA)
		VALUES(@DOCUMENT, @NUM, @NAME, @EXT, @DATA)
END
GO
GRANT EXECUTE ON [dbo].[SCAN_PAGES_SAVE] TO rl_admin;
GO
