USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[USER_DATA]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[USER_DATA]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[USER_DATA]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		(SELECT ID FROM dbo.Users WHERE LGN = ORIGINAL_LOGIN()) AS ID_USER,
		CASE
			WHEN IS_MEMBER('rl_admin') = 1 THEN 'rl_admin'
			WHEN IS_MEMBER('rl_user') = 1 THEN 'rl_user'
			WHEN IS_MEMBER('rl_reader') = 1 THEN 'rl_reader'
			WHEN IS_SRVROLEMEMBER('sysadmin') = 1 THEN 'rl_admin'
			ELSE ''
		END AS ROLE_NAME
END
GO
GRANT EXECUTE ON [dbo].[USER_DATA] TO public;
GO
