USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[USER_PERMISSION_SAVE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[USER_PERMISSION_SAVE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[USER_PERMISSION_SAVE]
	@CATEGORY	INT,
	@USER		INT,
	@R			BIT,
	@W			BIT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE dbo.CategoryUsers
	SET R	=	@R,
		W	=	@W
	WHERE ID_CATEGORY = @CATEGORY
		AND ID_USER = @USER

	IF @@ROWCOUNT = 0
		INSERT INTO dbo.CategoryUsers(ID_CATEGORY, ID_USER, R, W)
			VALUES(@CATEGORY, @USER, @R, @W)
END
GO
GRANT EXECUTE ON [dbo].[USER_PERMISSION_SAVE] TO rl_admin;
GO
