USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[SCAN_DOCUMENT_GET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[SCAN_DOCUMENT_GET]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[SCAN_DOCUMENT_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT ID_CATEGORY, ID_COMPANY, ID_DIRECTION, ID_FORM, NAME, DATE, DOC_NUM, DOC_DATE
	FROM dbo.ScanDocument
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[SCAN_DOCUMENT_GET] TO rl_admin;
GO
