USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[CATEGORY_DELETE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[CATEGORY_DELETE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[CATEGORY_DELETE]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	DELETE
	FROM dbo.Category
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[CATEGORY_DELETE] TO rl_admin;
GO
