USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[FORM_SAVE]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[FORM_SAVE]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[FORM_SAVE]
	@ID		INT OUTPUT,
	@NAME	NVARCHAR(128)
AS
BEGIN
	SET NOCOUNT ON;

	IF @ID IS NULL
	BEGIN
		INSERT INTO dbo.Form(NAME)
			VALUES(@NAME)

		SET @ID = SCOPE_IDENTITY()
	END
	ELSE
		UPDATE dbo.Form
		SET	NAME	=	@NAME,
			LAST	=	GETDATE()
		WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[FORM_SAVE] TO rl_admin;
GO
