USE [ScanDoc]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[dbo].[COMPANY_GET]', 'P ') IS NULL EXEC('CREATE PROCEDURE [dbo].[COMPANY_GET]  AS SELECT 1')
GO
ALTER PROCEDURE [dbo].[COMPANY_GET]
	@ID	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT NAME
	FROM dbo.Company
	WHERE ID = @ID
END
GO
GRANT EXECUTE ON [dbo].[COMPANY_GET] TO rl_admin;
GO
