USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[BookPriceDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Book].[BookPriceDeleted]  AS SELECT 1')
GO
ALTER VIEW [Book].[BookPriceDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		BP_ID_MASTER, BP_ID,
		HLF_ID, HLF_ID_MASTER, HLF_NAME,
		BP_PRICE,
		BP_DATE, BP_END
	FROM
		Book.BookPriceAll a
	WHERE BP_REF = 3GO
