USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[CompetitionActive]', 'V ') IS NULL EXEC('CREATE VIEW [Book].[CompetitionActive]  AS SELECT 1')
GO
ALTER VIEW [Book].[CompetitionActive]
--WITH SCHEMABINDING
AS
	SELECT
		CP_ID_MASTER, CP_ID,
		HLF_ID, HLF_ID_MASTER, HLF_NAME,
		CP_NAME, CP_COUNT, CP_BONUS,
		CP_DATE, CP_END
	FROM
		Book.CompetitionAll
	WHERE CP_REF = 1GO
