USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Book].[BookBonusDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Book].[BookBonusDeleted]  AS SELECT 1')
GO
ALTER VIEW [Book].[BookBonusDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		BB_ID_MASTER, BB_ID,
		PT_ID, PT_ID_MASTER, PT_NAME,
		BB_PERCENT,
		BB_DATE, BB_END
	FROM
		Book.BookBonusAll a
	WHERE BB_REF = 3GO
