USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Claim].[ClaimFullView]
--WITH SCHEMABINDING
AS
	SELECT
		CLM_ID, CLM_DATE, CLM_NUM,
		US_ID, US_ID_MASTER, US_NAME,
		CLD_ID,
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_NAME,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT, SYS_ORDER,
		DT_ID, DT_ID_MASTER, DT_SHORT, 
		NT_ID, NT_ID_MASTER, NT_SHORT,
		TT_ID, TT_ID_MASTER, TT_SHORT,
		CLD_COUNT, CLD_COMMENT
	FROM
		Claim.ClaimMasterView INNER JOIN
		Claim.ClaimDetailView ON CLM_ID = CLD_ID_CLAIMGO
