USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Clients].[VendorDeleted] 
--WITH SCHEMABINDING
AS
	SELECT 
		VD_ID_MASTER, VD_ID, VD_NAME, VD_DATE, VD_END
	FROM 
		Clients.VendorAll a
	WHERE VD_REF = 3