USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[PeriodDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Common].[PeriodDeleted]  AS SELECT 1')
GO
ALTER VIEW [Common].[PeriodDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		PR_ID_MASTER, PR_ID, PR_NAME,
		PR_BEGIN_DATE, PR_END_DATE,
		PR_DATE, PR_END
	FROM
		Common.PeriodAll a
	WHERE PR_REF = 3GO
