USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Common].[HalfActive]', 'V ') IS NULL EXEC('CREATE VIEW [Common].[HalfActive]  AS SELECT 1')
GO
ALTER VIEW [Common].[HalfActive]
--WITH SCHEMABINDING
AS
	SELECT
		HLF_ID_MASTER, HLF_ID, HLF_NAME,
		HLF_BEGIN_DATE, HLF_END_DATE,
		HLF_DATE, HLF_END
	FROM
		Common.HalfAll
	WHERE HLF_REF = 1GO
