USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DistrTypeDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[DistrTypeDeleted]  AS SELECT 1')
GO
ALTER VIEW [Distr].[DistrTypeDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		DT_ID_MASTER, DT_ID, DT_NAME,
		DT_SHORT, DT_REG, DT_DATE, DT_END
	FROM
		Distr.DistrTypeAll a
	WHERE DT_REF = 3GO
