USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[NetTypeLast]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[NetTypeLast]  AS SELECT 1')
GO

ALTER VIEW [Distr].[NetTypeLast]
--WITH SCHEMABINDING
AS
	SELECT
		NT_ID_MASTER, NT_ID, NT_NAME, NT_SHORT,
		NT_FULL, NT_COEF, NT_DATE, NT_END
	FROM
		Distr.NetTypeAll a
	WHERE NT_REF IN (1, 3)
GO
