USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Distr].[DistrActive]
--WITH SCHEMABINDING
AS
	SELECT 
		HST_ID, HST_ID_MASTER, HST_NAME,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		DS_ID, DS_NUM, DS_COMP,
		NT_ID, NT_ID_MASTER, NT_NAME,
		DT_ID, DT_ID_MASTER, DT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		SYS_SHORT + ' ' + CONVERT(VARCHAR(10), DS_NUM) +
		CASE DS_COMP
			WHEN 1 THEN ''
			ELSE '/' + CONVERT(VARCHAR(10), DS_COMP)
		END + ' ' +
		RTRIM(RTRIM(DT_SHORT + ' ' + NT_SHORT) + ' ' + TT_SHORT)
		AS DH_STR,
		DH_ID, DH_DATE, DH_END, SYS_ORDER
	FROM
		Distr.DistrStore												INNER JOIN
		Distr.DistrHistory		ON	DS_ID			=	DH_ID_DISTR		INNER JOIN
		Distr.HostDetail		ON	HST_ID_MASTER	=	DS_ID_HOST		INNER JOIN
		Distr.SystemDetail		ON	SYS_ID_MASTER	=	DH_ID_SYSTEM	INNER JOIN
		Distr.NetTypeDetail		ON	NT_ID_MASTER	=	DH_ID_NET		INNER JOIN
		Distr.DistrTypeDetail	ON	DT_ID_MASTER	=	DH_ID_TYPE		INNER JOIN
		Distr.TechTypeDetail	ON	TT_ID_MASTER	=	DH_ID_TECH
	WHERE DH_REF = 1 AND HST_REF = 1 AND SYS_REF = 1
		AND NT_REF = 1 AND DT_REF = 1 AND TT_REF = 1
		