USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Distr].[DistrAll]
--WITH SCHEMABINDING
AS
	SELECT 
		DS_ID, DS_NUM, DS_COMP,
		HST_ID, HST_ID_MASTER, HST_NAME,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		NT_ID, NT_ID_MASTER, NT_NAME,
		DT_ID, DT_ID_MASTER, DT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		DH_ID, DH_DATE, DH_END,
		SYS_SHORT + ' ' + CONVERT(VARCHAR(10), DS_NUM) + 
		CASE DS_COMP
			WHEN 1 THEN ''
			ELSE '/' + CONVERT(VARCHAR(10), DS_COMP)
		END + ' ' +
		RTRIM(RTRIM(DT_SHORT + ' ' + NT_SHORT) + ' ' + TT_SHORT)			
		AS DH_STR, DH_REF, SYS_ORDER
	FROM 
		Distr.DistrStore INNER JOIN
		Distr.DistrHistory ON DS_ID = DH_ID_DISTR INNER JOIN
		Distr.HostLast ON HST_ID_MASTER = DS_ID_HOST INNER JOIN
		Distr.SystemLast ON SYS_ID_MASTER = DH_ID_SYSTEM INNER JOIN
		Distr.NetTypeLast ON NT_ID_MASTER = DH_ID_NET INNER JOIN
		Distr.DistrTypeLast ON DT_ID_MASTER = DH_ID_TYPE INNER JOIN
		Distr.TechTypeLast ON TT_ID_MASTER = DH_ID_TECH