USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[DistrDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[DistrDeleted]  AS SELECT 1')
GO
ALTER VIEW [Distr].[DistrDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		DS_ID, DS_NUM, DS_COMP,
		HST_ID, HST_ID_MASTER, HST_NAME,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT,
		NT_ID, NT_ID_MASTER, NT_NAME,
		DT_ID, DT_ID_MASTER, DT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME,
		DH_ID, DH_DATE, DH_END, DH_STR, SYS_ORDER
	FROM
		Distr.DistrAll
	WHERE DH_REF = 3
		GO
