USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[TechTypeDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[TechTypeDeleted]  AS SELECT 1')
GO
ALTER VIEW [Distr].[TechTypeDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		TT_ID_MASTER, TT_ID, TT_NAME, TT_SHORT,
		TT_REG, TT_COEF, TT_DATE, TT_END
	FROM
		Distr.TechTypeAll a
	WHERE TT_REF = 3GO
