USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[TechTypeLast]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[TechTypeLast]  AS SELECT 1')
GO

ALTER VIEW [Distr].[TechTypeLast]
--WITH SCHEMABINDING
AS
	SELECT
		TT_ID_MASTER, TT_ID, TT_NAME, TT_SHORT,
		TT_REG, TT_COEF, TT_DATE, TT_END
	FROM
		Distr.TechTypeAll a
	WHERE TT_REF IN (1, 3)
GO
