USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Distr].[WeightAll]', 'V ') IS NULL EXEC('CREATE VIEW [Distr].[WeightAll]  AS SELECT 1')
GO
ALTER VIEW [Distr].[WeightAll]
--WITH SCHEMABINDING
AS
	SELECT
		WG_ID_MASTER, WG_ID, WG_ID_SYSTEM, WG_NAME,
		WG_VALUE, WG_DATE, WG_END, WG_REF
	FROM
		Distr.WeightDetailGO
