USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE VIEW [Income].[IncomePersonalView]
WITH SCHEMABINDING
AS 
	SELECT 
		IP_ID, IP_ID_INCOME AS ID_ID, 
		PER_ID, PER_ID_MASTER, PER_NAME,
		IP_PERCENT, IP_PERCENT2, PER_ID_TYPE, PER_ID_DEP
	FROM
		Income.IncomePersonal INNER JOIN
		Personal.PersonalDetail ON PER_ID_MASTER = IP_ID_PERSONAL
	WHERE PER_REF IN (1, 3)
		