USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Income].[BookResult]', 'V ') IS NULL EXEC('CREATE VIEW [Income].[BookResult]  AS SELECT 1')
GO
ALTER VIEW [Income].[BookResult]
--WITH SCHEMABINDING
AS
	SELECT
		IB_ID_HALF, IB_ID_PERSONAL, COUNT(IB_COUNT) AS IB_COUNT
	FROM
		Income.IncomeBook
	WHERE IB_FULL_PAY IS NOT NULL
	GROUP BY IB_ID_HALF, IB_ID_PERSONAL

	GO
