USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Income].[IncomeDetailFullView]
--WITH SCHEMABINDING
AS
	SELECT
		ID_ID, IN_ID, ID_COUNT,
		ID_DEL_SUM, ID_DEL_SUM_NDS, ID_DEL_PRICE, ID_DEL_PRICE_NDS, ID_DEL_DISCOUNT,
		ID_ACTION, ID_RESTORE, ID_EXCHANGE, ID_FULL_DATE, ID_CALC,
		c.PR_ID AS PR_FIRST_ID, c.PR_ID_MASTER AS PR_FIRST_ID_MASTER, c.PR_NAME AS PR_FIRST_NAME, ID_MON_CNT,
		d.PR_ID AS PR_FULL_ID, d.PR_ID_MASTER AS PR_FULL_ID_MASTER, d.PR_NAME AS PR_FULL_NAME,
		ID_SUP_PRICE, ID_SUP_PRICE_NDS, ID_SUP_DISCOUNT,
		ID_SUP_MONTH, ID_SUP_MONTH_NDS, ID_PREPAY,
		ID_SUP_CONTRACT, ID_SUP_DATE, ID_MON_STR, ID_SALARY, ID_SALARY_NDS,
		ID_LOCK, ID_COMMENT, ID_REPAY, ID_NOTE,
		SYS_ID, SYS_ID_MASTER, SYS_SHORT, SYS_ORDER, ID_MAIN, ID_COLOR,
		CASE 
			WHEN EXISTS(
				SELECT *
				FROM Distr.WeightActive
				WHERE WG_ID_SYSTEM = SYS_ID_MASTER
			) THEN CAST(1 AS BIT)
			ELSE CAST(0 AS BIT)
		END AS SYS_MAIN,
		DT_ID, DT_ID_MASTER, DT_NAME, DT_SHORT,
		NT_ID, NT_ID_MASTER, NT_NAME,
		TT_ID, TT_ID_MASTER, TT_NAME, TT_SHORT,
		NT_NEW_NAME,
		CASE
			WHEN EXISTS	(
					/*
					SELECT d.IN_ID
					FROM
						Income.Incomes d INNER JOIN
						Income.IncomeDetailView e ON d.IN_ID = e.IN_ID
					WHERE d.IN_ID_INCOME = a.IN_ID
						AND a.SYS_ID_MASTER = e.SYS_ID_MASTER
						AND a.DT_ID_MASTER = e.DT_ID_MASTER
						AND a.NT_ID_MASTER = e.NT_ID_MASTER
						AND a.TT_ID_MASTER = e.TT_ID_MASTER
					*/
					SELECT d.IN_ID
					FROM
						Income.Incomes d INNER JOIN
						Income.IncomeDetail e ON d.IN_ID = e.ID_ID_INCOME
					WHERE d.IN_ID_INCOME = a.IN_ID
						AND a.SYS_ID_MASTER = e.ID_ID_SYSTEM
						AND a.DT_ID_MASTER = e.ID_ID_TYPE
						AND a.NT_ID_MASTER = e.ID_ID_NET
						AND a.TT_ID_MASTER = e.ID_ID_TECH
				) OR EXISTS
				(
					SELECT f.IN_ID
					FROM Income.Incomes f
					WHERE f.IN_ID = a.IN_ID
						AND f.IN_ID_INCOME IS NULL
				) THEN CAST(0 AS BIT)
				ELSE CAST(1 AS BIT)
		END AS ID_REPAYED,
		ID_INSTALL
	FROM
		Income.IncomeDetailView a LEFT OUTER JOIN
		Common.PeriodLast c ON a.ID_ID_FIRST_MON = c.PR_ID_MASTER LEFT OUTER JOIN
		Common.PeriodLast d ON a.ID_ID_FULL_PAY = d.PR_ID_MASTER
		GO
