USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Income].[IncomeMasterView]
WITH SCHEMABINDING
AS
	SELECT
		IN_ID, IN_DATE, IN_PAY, IN_ID_INCOME,
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_ID, VD_ID_MASTER, VD_NAME
	FROM
		Income.Incomes INNER JOIN
		Clients.ClientDetail ON CL_ID_MASTER = IN_ID_CLIENT INNER JOIN
		Clients.VendorDetail ON VD_ID_MASTER = IN_ID_VENDOR
	WHERE CL_REF IN (1, 3) AND VD_REF IN (1, 3)

GO
CREATE UNIQUE CLUSTERED INDEX [IX_CLUST] ON [Income].[IncomeMasterView] ([IN_ID] ASC);
GO
