USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Install].[InstallDetailFullView]', 'V ') IS NULL EXEC('CREATE VIEW [Install].[InstallDetailFullView]  AS SELECT 1')
GO


ALTER VIEW [Install].[InstallDetailFullView]
--WITH SCHEMABINDING
AS
SELECT
		IND_ID, INS_ID, IND_LOCK,
		IND_BOX_DATE, IND_ACT_DATE,
		IND_ACT_RETURN,
		D.SYS_ID, D.SYS_ID_MASTER, D.SYS_SHORT,
		D.DT_ID, D.DT_ID_MASTER, D.DT_NAME, D.DT_SHORT,
		D.NT_ID, D.NT_ID_MASTER, D.NT_NAME,
		D.TT_ID, D.TT_ID_MASTER, D.TT_NAME,	D.TT_SHORT,
		IND_DISTR,
		P.PER_ID, P.PER_ID_MASTER, P.PER_NAME,
		IN_ID, ID_ID, IN_DATE, ID_FULL_DATE, ID_COMMENT, ID_LOCK,
		IND_CONTRACT, IND_INSTALL_DATE,
		CLM_ID, CLM_DATE, ID_RESTORE, ID_EXCHANGE, IND_CLAIM,
		NT_NEW_NAME,
		IA_ID_MASTER, IA_ID, IA_NAME, IA_NORM, IND_ACT_SIGN, IND_ACT_MAIL, IND_ACT_NOTE,
		IND_TO_NUM, IND_LIMIT, IND_ARCHIVE,
		D.IND_ID_ACT_PERSONAL, PA.PER_NAME AS IND_ACT_PERSONAL
	FROM Install.InstallDetailView AS D WITH(NOEXPAND)
	LEFT JOIN Personal.PersonalLast AS P ON D.IND_ID_PERSONAL = P.PER_ID_MASTER
	LEFT JOIN Personal.PersonalLast AS PA ON D.IND_ID_ACT_PERSONAL = PA.PER_ID_MASTER
	LEFT JOIN Income.IncomeDetail AS ID ON ID_ID = IND_ID_INCOME
	LEFT JOIN Income.Incomes AS I ON ID_ID_INCOME = IN_ID
	LEFT JOIN Claim.Claims AS C ON CLM_ID = IND_ID_CLAIM
	LEFT JOIN Install.InstallActLast AS IA ON IND_ID_ACT = IA_ID_MASTER
GO
