USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Install].[InstallCommentsView]
--WITH SCHEMABINDING
AS
	SELECT
		INS_DATE, CL_NAME, VD_NAME,
		SYS_SHORT, DT_NAME, NT_NAME, TT_NAME, IND_ID_DISTR,
		IC_DATE, IC_USER, IC_TEXT
	FROM
		Install.Install INNER JOIN
		Install.InstallDetail ON IND_ID_INSTALL = INS_ID INNER JOIN
		Install.InstallComments ON IC_ID_IND = IND_ID INNER JOIN
		Clients.ClientLast ON CL_ID = INS_ID_CLIENT INNER JOIN
		Clients.VendorLast ON VD_ID = INS_ID_VENDOR INNER JOIN
		Distr.SystemLast ON SYS_ID_MASTER = IND_ID_SYSTEM INNER JOIN
		Distr.DistrTypeLast ON DT_ID_MASTER = IND_ID_TYPE INNER JOIN
		Distr.NetTypeLast ON NT_ID_MASTER = IND_ID_NET INNER JOIN
		Distr.TechTypeLast ON TT_ID_MASTER = IND_ID_TECH GO
