USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [Install].[InstallDetailFullView]
--WITH SCHEMABINDING
AS
SELECT
		IND_ID, INS_ID, IND_LOCK,
		IND_BOX_DATE, IND_ACT_DATE,
		IND_ACT_RETURN,
		a.SYS_ID, a.SYS_ID_MASTER, a.SYS_SHORT,
		a.DT_ID, a.DT_ID_MASTER, a.DT_NAME, a.DT_SHORT,
		a.NT_ID, a.NT_ID_MASTER, a.NT_NAME,
		a.TT_ID, a.TT_ID_MASTER, a.TT_NAME,	a.TT_SHORT,
		IND_DISTR,
		PER_ID, PER_ID_MASTER, PER_NAME,
		IN_ID, ID_ID, IN_DATE, ID_FULL_DATE, ID_COMMENT, ID_LOCK,
		IND_CONTRACT, IND_INSTALL_DATE,
		CLM_ID, CLM_DATE, ID_RESTORE, ID_EXCHANGE, IND_CLAIM,
		NT_NEW_NAME,
		IA_ID_MASTER, IA_ID, IA_NAME, IA_NORM, IND_ACT_SIGN, IND_ACT_MAIL, IND_ACT_NOTE,
		IND_TO_NUM, IND_LIMIT, IND_ARCHIVE
	FROM
		Install.InstallDetailView a WITH(NOEXPAND) LEFT OUTER JOIN
		Personal.PersonalLast ON IND_ID_PERSONAL = PER_ID_MASTER LEFT OUTER JOIN
		Income.IncomeDetail ON ID_ID = IND_ID_INCOME LEFT OUTER JOIN
		Income.Incomes ON ID_ID_INCOME = IN_ID LEFT OUTER JOIN
		Claim.Claims ON CLM_ID = IND_ID_CLAIM LEFT OUTER JOIN
		Install.InstallActLast ON IND_ID_ACT = IA_ID_MASTER
