USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE VIEW [Install].[InstallMasterView]
WITH SCHEMABINDING
AS 
	SELECT 
		INS_ID, INS_DATE, 
		CL_ID, CL_ID_MASTER, CL_NAME,
		VD_ID, VD_ID_MASTER, VD_NAME
	FROM
		Install.Install INNER JOIN
		Clients.ClientDetail ON CL_ID_MASTER = INS_ID_CLIENT INNER JOIN
		Clients.VendorDetail ON VD_ID_MASTER = INS_ID_VENDOR
	WHERE CL_REF IN (1, 3) AND VD_REF IN (1, 3)
		