USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [Salary].[PersonalSalarySummaryView]
--WITH SCHEMABINDING
AS
	SELECT 
		PER_ID_MASTER AS PER_ID,
		PER_NAME, PS_DATE, PS_ID, PS_ID_PERIOD, PS_ID_VENDOR, PS_LOCK,
		CAST(ROUND((
			SELECT SUM(PSD_TOTAL)
			FROM Salary.PersonalSalaryDetail
			WHERE PSD_ID_MASTER = PS_ID
		), 0) AS MONEY) AS PS_SALE,
		PS_SALARY,
		--0 AS PS_VISIT,
		--0 AS PS_BONUS,
		CAST(ROUND((
			SELECT CP_BONUS
			FROM Book.CompetitionLast
			WHERE CP_ID_MASTER = PS_ID_COMPETITION
		), 0) AS MONEY) AS PS_COMPETITION,
		CAST(ROUND((
			SELECT SUM(PSB_TOTAL)
			FROM Salary.PersonalSalaryBook
			WHERE PSB_ID_MASTER = PS_ID
		), 0) AS MONEY) AS PS_BOOK,
		--SUM(PSB_TOTAL) AS PS_BOOK,
		CAST(ROUND((
			SELECT SUM(PSB_DELIVERY)
			FROM Salary.PersonalSalaryBook
			WHERE PSB_ID_MASTER = PS_ID
		), 0) AS MONEY) AS PS_DELIVERY,
		--SUM(PSB_DELIVERY) AS PS_DELIVERY,
		--SUM(PSD_TOTAL) AS PS_SALE,
		PS_CORRECT,
		PS_COMMENT, PS_PAYED, PS_DEBT


	FROM
		Personal.PersonalLast	INNER JOIN
		Salary.PersonalSalary	ON	PER_ID_MASTER	=	PS_ID_PERSONAL

		