USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('[Salary].[BonusConditionDeleted]', 'V ') IS NULL EXEC('CREATE VIEW [Salary].[BonusConditionDeleted]  AS SELECT 1')
GO
ALTER VIEW [Salary].[BonusConditionDeleted]
--WITH SCHEMABINDING
AS
	SELECT
		BC_ID, BC_ID_MASTER,
		BC_PREPAY, BC_MON_COUNT, BC_ACTION, BC_EXCHANGE,
		BC_DT_SUP_CON, BC_RESTORE_MAIN, BC_RESTORE_ADD,
		BC_SUP_PRICE, BC_RES_PRICE, BC_PERCENT,
		BC_ORDER, BC_DATE, BC_END
	FROM
		Salary.BonusConditionAll a
	WHERE BC_REF = 3GO
