USE [FirstInstall]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [Security].[UserAll] 
--WITH SCHEMABINDING
AS
	SELECT 
		US_ID_MASTER, US_ID, US_NAME, 
		US_LOGIN, US_NOTE, US_DATE, US_END, US_REF
	FROM 
		Security.UserDetail