USE [FirstInstall]
	GO
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO
	CREATE VIEW [Security].[UserRoleView] 
--WITH SCHEMABINDING
AS
	SELECT 
		RL_ID, RL_ROLE, US_ID_MASTER, US_NAME, US_LOGIN,
		Security.UserRoleStatus(US_LOGIN, RL_ID) AS UR_STATUS
	FROM 
		Security.Roles CROSS JOIN
		Security.UserLast
	WHERE US_REF = 1