USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[ServerStatView]
WITH SCHEMABINDING
AS
	SELECT 
		SSD_MONTH,
		SSD_DAY,
		FL_ID_SERVER,
		SUM(SSD_TRAFIN) AS SSD_TRAFIN,
		SUM(SSD_TRAFOUT) AS SSD_TRAFOUT,
		COUNT_BIG(*) AS CNT
	FROM 
		dbo.ServerStatDetail
		INNER JOIN dbo.ServerStat ON SS_ID = SSD_ID_SD
		INNER JOIN dbo.Files ON FL_ID = SS_ID_FILE
	GROUP BY SSD_MONTH, SSD_DAY, FL_ID_SERVER
