USE [IPLogs]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[ServerStatView]
WITH SCHEMABINDING
AS
	SELECT
		SSD_MONTH,
		SSD_DAY,
		FL_ID_SERVER,
		SUM(SSD_TRAFIN) AS SSD_TRAFIN,
		SUM(SSD_TRAFOUT) AS SSD_TRAFOUT,
		COUNT_BIG(*) AS CNT
	FROM
		dbo.ServerStatDetail
		INNER JOIN dbo.ServerStat ON SS_ID = SSD_ID_SD
		INNER JOIN dbo.Files ON FL_ID = SS_ID_FILE
	GROUP BY SSD_MONTH, SSD_DAY, FL_ID_SERVER

GO
CREATE UNIQUE CLUSTERED INDEX [UC_dbo.ServerStatView(SSD_DAY,FL_ID_SERVER)] ON [dbo].[ServerStatView] ([SSD_DAY] ASC, [FL_ID_SERVER] ASC);
CREATE NONCLUSTERED INDEX [IX_dbo.ServerStatView(SSD_MONTH,FL_ID_SERVER)+(SSD_TRAFIN,SSD_TRAFOUT)] ON [dbo].[ServerStatView] ([SSD_MONTH] ASC, [FL_ID_SERVER] ASC) INCLUDE ([SSD_TRAFIN], [SSD_TRAFOUT]);
GO
